### ISSUE TITLE
Create pending payments & expand payments table

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1000]
Creating a new issue based on the discussion in #999

We should start creating pending payments before sending the user to the gateway, then update the payment record after payment is received. We should also consider adding more data to our payments table, like:

- Discount code used
- Name of the payment gateway (we currently save like "Credit Card One Time" rather than "stripe")
- Whether or not it's for a free trial (should we create an initial $0 payment record for that?)
- Subscription ID (we save the name now, but IMO the ID would be better)

## To do:

- [x] Expand payments table to include:
  - Discount code used
  - Discounted amount
  - Proration credits
  - Fees
  - Subtotal (actual price of the subscription level)
  - Change `payment_type` to be the actual name of the gateway.
  - Change `subscription` to be the subscription ID number instead of the name.
- [x] Back-fill `subscription_level_id` column via magic getter
- [x] Create pending payment before going to gateway.
- [x] Remove these from `rcp_process_registration()` : 
  - Setting pending subscription level/key.
  - Setting expiration date.
  - Role updates/removal.
  - Increasing discount code usage and adding to profile.
- [x] Update all gateways to not insert new payments, and instead change the existing payment to `complete`.
- [x] Trigger action when a payment record is completed and insert all removed code here.
- [x] Remove discount code stuff from `rcp_remove_subscription_data_on_failure()` as that should no longer be necessary.
- [x] Maintain and test for backwards compatibility so as not to break custom gateways.

## Gateway Testing

**Stripe**

- [x] Regular, non-recurring payment.
- [x] Manually renew non-recurring payment and check that there's no proration and expiration date is extended from current expiration date.
- [x] Recurring subscription signup.
- [x] Renewal payment from recurring subscription.
- [x] Free trial (double check trial expiration date is correct and `$0` payment is completed).
- [x] Failed payment when upgrading. Make sure old subscription level/role/etc. remains active and the user doesn't get any new settings from upgraded level.

**PayPal Express**

- [x] Regular payment
- [x] Recurring payment both with and without signup fees
- [x] Free trial

**PayPal Standard**

- [x] Regular payment.
- [x] Recurring signup both with and without signup fees.
- [x] Renewal payment from recurring subscription.
- [x] Free trial (double check trial expiration date is correct and `$0` payment is completed).

**PayPal Pro**

- [x] Regular payment
- [x] Free trial (double check trial expiration date is correct and `$0` payment is completed).
- [ ] Renewal payment from recurring subscription.
- [x] Failed payment correctly gets marked as `failed` 

**Authorize.net**

- [x] Regular, non-recurring payment.
- [x] Recurring subscription signup.
- [x] Renewal payment from recurring subscription.
- [x] Free trial (double check trial expiration date is correct and `$0` payment is completed).

**Braintree**

- [x] Regular, non-recurring payment.
- [x] Recurring subscription signup.
- [x] Recurring subscription with signup fee.
- [ ] Renewal payment from recurring subscription.
- [x] Free trial (double check trial expiration date is correct and `$0` payment is completed).

**2Checkout**

- [x] Regular, non-recurring payment.
- [x] Recurring subscription signup.
- [ ] Renewal payment from recurring subscription.

**Misc**

- [x] Register for free subscription. Ensure expiration date is set to `none` and status is `free`.
- [x] Register with 100% off recurring discount. Ensure expiration date is set to `none`.
- [x] Register for old style free trial (free plan with fixed duration). Make sure expiration date is correct and status is `active`.

**Comment by mindctrl** [comment]
Yes! We need better payment data. All of these have come up numerous times.

**Comment by nosegraze** [comment]
Updated the issue with a more extensive to-do list.

**Comment by nosegraze** [comment]
WIP PR: #1127

Don't look too close because there's still a ton I haven't done. :P But let me know if you have any comments on the general approach. If I need to change something fundamental I want to do it before I go any further.

**Comment by pippinsplugins** [comment]
General approach is looking good to me!

**Comment by mindctrl** [comment]
Once this is in, we can do https://github.com/restrictcontentpro/restrict-content-pro/issues/798.

**Comment by nosegraze** [comment]
Ran some successful Stripe tests today:

- [x] Non-recurring
- [x] Non-recurring renewal (check that expiration is extended from current expiration date)
- [x] Non-recurring with discount 
- [x] Non-recurring upgrade with proration 
- [x] Recurring
- [x] Free trial
- [x] Recurring with recurring discount 
- [x] Recurring with one-time discount
- [x] Recurring with proration
- [x] Recurring with signup fee
- [ ] Failed trial payment (make sure user isn't still trialling)
- [ ] Failed discount payment (make sure discount code usage wasn't incremented)

**Comment by nosegraze** [comment]
Note: several of our add-ons (like EDD Member Downloads and a few others) and AffiliateWP will be affected by this update unless we do some funky changes to the `rcp_insert_payment` action. Those plugins assume that `rcp_insert_payment` is a completed payment, but with this update it will pretty much only run when a _pending_ payment is created.

**Comment by mindctrl** [comment]
Maybe we should introduce a new action, `rcp_insert_payment_{$status}`, like we did with `rcp_set_status`. Either way we'll need to update the other add-ons I think.

**Comment by nosegraze** [comment]
This update does introduce an action for `rcp_update_payment_status_complete`, which would handle all payments transitioning from pending => complete. That's the new one add-ons would want to use. But things could get a bit screwed up if someone updates RCP but not AffiliateWP, for example. It could result in some invalid referrals for payments that were never completed.

**Comment by mindctrl** [comment]
From a back compat perspective, we could run `rcp_insert_payment` only on complete. That would break anything people do where they insert payments and do actions on failed/pending/whatever custom thing they're doing. That's probably the lesser of the evils I guess. Hmm...

**Comment by nosegraze** [comment]
Yeah we could only run it in `RCP_Payments::insert()` if the status is complete. Then we could also run it in `RCP_Payment::update()` if the status is being _updated_ to complete. That way the action always gets triggered when a payment is completed.

TBH I don't really like it because I feel like it changes the core meaning of the action. It becomes a "completed payment" action rather than an "inserted payment into the DB" action. But it would work in terms of full backwards compatibility.

**Comment by pippinsplugins** [comment]
>>>Yeah we could only run it in RCP_Payments::insert() if the status is complete. Then we could also run it in RCP_Payment::update() if the status is being updated to complete. That way the action always gets triggered when a payment is completed.

I think this is the best option from a BC perspective. `rcp_insert_payment` has been around for a really long time so it's impossible to say how many people may be depending on it.

**Comment by nosegraze** [comment]
This is ready for an initial test. The only gateway I've actually focused on so far is Stripe, so that's where testing should start, but with any luck the others should still be backwards compatible. I ran a quick test with PayPal Standard and it seemed to work. It correctly updated the pending payment instead of inserting a new one.

If Stripe testing goes well and you guys are happy with the code, I'll update the other gateways next.

**Comment by pippinsplugins** [comment]
@nosegraze Starting to test this. Just noticed we need to add `Pending` to the status drop down on the edit/create payment screen.

**Comment by nosegraze** [comment]
Thanks - will do. I think I added it to the Edit screen but not the Create screen. I'll get that added.

**Comment by pippinsplugins** [comment]
@nosegraze I'm getting a PHP notice.

PHP Notice: Undefined property: stdClass::$gateway in /Users/pippin/Sites/edd/wp-content/plugins/restrict-content-pro/includes/gateways/gateway-functions.php on line 287

That happened during registration I believe.

Beyond that, it appeared to work!

**Comment by pippinsplugins** [comment]
Looks like the subscription level is not shown properly on the edit payment screen:
<img width="665" alt="screen shot 2017-05-01 at 11 06 40 am" src="https://cloud.githubusercontent.com/assets/1034109/25585068/6f103ee0-2e5e-11e7-8288-a2657b379f11.png">

**Comment by nosegraze** [comment]
@pippinsplugins  Did you create the new DB column for `gateway` ? I don't have that set up to auto create yet. That's the only way I can think of that PHP notice happening.

Can you also show me the DB data for that payment? It's displaying okay on my end!

**Comment by mindctrl** [comment]
This might be me, but I find the new `RCP_Payment` class to be confusing. It's part object, part utility. It has update and delete methods, but no get method... because presumably you access the public properties to "get" the payment. But that means it's mostly mutable, which is inherently less predictable.

There's also no insert method, which makes sense since this is sort of a query/utility class, but you can now update and delete a payment via this class and via the `RCP_Payments` class.
 From a usability standpoint, you find yourself using two classes to interact with the payments table.

Also the classes both have hardcoded dependencies referencing each other. `RCP_Payments::insert` calls `RCP_Payment` to update the payment details but I think those could be updated with `RCP_Payments::update` since `RCP_Payment::update` ends up using `RCP_Payments::update` anyway.

Am I wrong in thinking we don't need RCP_Payment at all to do this?

**Comment by pippinsplugins** [comment]
I don't think `RCP_Payment` is _needed_ for this but I do think it's a great object to have, though we could round it out more and make it more consistent.

**Comment by mindctrl** [comment]
I agree that it's a good abstraction to have.

I'd prefer we implement an interface in `RCP_Payment`, and I'd prefer that all its other object dependencies (such as `RCP_Payments`) get injected in the constructor. I want to move towards most new classes we introduce containing instances of objects they need to use.

With that in mind I think `RCP_Payments` itself should implement an interface too, so we can inject any object that implements that interface. This frees both us and other developers up to customize/overhaul it as we/they see fit without worry about implementation details.

Since this is likely to be a "first class citizen" in RCP as time goes on, I'd prefer to not introduce the class right now and spend time over the next couple cycles defining how exactly it'll be used and what exactly it should do.

**Comment by pippinsplugins** [comment]
@nosegraze would removing the class from this PR be too catastrophic? If so, I think we need to introduce both at the same time. If the new pending payments can be easily decoupled from the RCP_Payment class, then let's do that and introduce it at a later time.

**Comment by nosegraze** [comment]
I can take a more thorough look later, but off the top of my head the one thing that's actively used in that class is the magic `__get()` to backfill the new `subscription_level_id` column.

Other than that, we don't really _need_ it, though I do think it's useful.

**Comment by pippinsplugins** [comment]
>>>is the magic __get() to backfill the new subscription_level_id column.

Ah, that's a really good point. That makes me inclined to fully fill out `RCP_Payment` and ship them both together.

**Comment by mindctrl** [comment]
If the only need at the moment is the magic getter for `subscription_level_id`, I vote we put the magic getter in `RCP_Payments` and limit it to that specific use case. This gives us time to fully consider what RCP_Payment should be.

**Comment by nosegraze** [comment]
`RCP_Payment` class moved to https://github.com/restrictcontentpro/restrict-content-pro/issues/1235

**Comment by nosegraze** [comment]
Removed the `RCP_Payment` class in https://github.com/restrictcontentpro/restrict-content-pro/commit/fa263f41f77456dcb1aa4e50f244eecc2195c53b though I haven't yet done any testing to make sure I haven't mucked something up.

**Comment by pippinsplugins** [comment]
I'll work on testing this more tomorrow!

**Comment by nosegraze** [comment]
Awesome, thanks! Here's a list of tests I did a few weeks ago: https://github.com/restrictcontentpro/restrict-content-pro/issues/1000#issuecomment-291176101 It'll probably be useful to re-run those. I've made a lot of changes since then.

**Comment by mindctrl** [comment]
I'll give this a test today.

**Comment by mindctrl** [comment]
I'm getting the gateway notice Pippin was before

```
Undefined property: stdClass::$gateway in /app/public/wp-content/plugins/restrict-content-pro/includes/gateways/gateway-functions.php on line 287
```

Getting it viewing the payments page. Looks like we still need to add the new columns when updating.

**Comment by nosegraze** [comment]
Yes I haven't added an upgrade routine to do that yet.

**Comment by mindctrl** [comment]
Stream of thought here...

I found the "Edit" subscription level link on the payment details screen to be confusing.

![image](https://cloud.githubusercontent.com/assets/1254870/26503943/adcea778-4210-11e7-9dcf-ece33dba480e.png)

I thought it was going to let me change the level the payment was for (which I thought would be weird), but it takes you to the sub level edit screen. 

An "Edit" link next to the sub level on a payment edit screen implies to me that you want to edit the value on the payment itself.

I think it would be clearer to link the sub level name itself to the sub level edit screen. That makes it more clear what it's for, I think.

Something like this:
![image](https://cloud.githubusercontent.com/assets/1254870/26504217/a6e4b9f6-4211-11e7-8b7e-65d4c78233f8.png)

**Comment by nosegraze** [comment]
I like that 👍

**Comment by mindctrl** [comment]
Pending payments do not show in the `[subscription_details]` payments list. I think it probably should, in case of webhook issues or whatever, so that the member doesn't get a bad feeling or wonder if it didn't go through and then end up trying to buy again.

**Comment by nosegraze** [comment]
I think @pippinsplugins said not to because they were confusing people when they were left pending in EDD.

**Comment by mindctrl** [comment]
Hmm I think the confusion in EDD was store owners seeing pending payments in the admin, due to not completing PayPal purchases, not customers seeing pending payments on the front end. @pippinsplugins thoughts?

**Comment by pippinsplugins** [comment]
Let's show them.

**Comment by mindctrl** [comment]
Stripe renewal payments are coming in and they don't look quite right. The payments list table is showing the level ID instead of the name, and when you view the payment details page it's missing from there.

![image](https://cloud.githubusercontent.com/assets/1254870/26589545/4c87fce4-4526-11e7-81dc-a539c50ce34f.png)

![image](https://cloud.githubusercontent.com/assets/1254870/26589616/7a74f044-4526-11e7-8b16-24effd4d6922.png)

**Comment by mindctrl** [comment]
The payment object from the screenshots above.

```
stdClass Object
(
    [id] => 1552
    [subscription] => 38
    [date] => 2017-05-30 02:38:46
    [amount] => 5
    [user_id] => 426
    [payment_type] => Credit Card
    [subscription_key] => 39f875e71d0741e4f79720402e8f543d
    [transaction_id] => ch_1APBUg2zbkexLKRKSEjVZLV4
    [status] => complete
    [subscription_level_id] => 0
    [subtotal] => 0
    [credits] => 0
    [fees] => 0
    [discount_amount] => 0
    [discount_code] => 
    [gateway] => stripe
)
```

**Comment by pippinsplugins** [comment]
@mindctrl could you dig in and track that down?

**Comment by mindctrl** [comment]
In `RCP_Payment::insert()`, there are two new actions:

`rcp_update_payment_status` and `rcp_update_payment_status_' . $args['status']`

The comment says: `This is here to spoof a status change when a payment is first inserted.`

What was the reason for that? I don't remember.

The action names don't match the method name/context. "update" inside a method called `insert()` feels wrong, and they run inside the `update()` method.

**Comment by nosegraze** [comment]
I did that so one action could be used, primarily when executing code on
completed payments. That way one action could be used whether the payment
was immediately added with a `complete` status (meaning it may not ever be
updated) or updated later to change the status to `complete`.

**Comment by mindctrl** [comment]
Thanks!

I think since this is new and we'll soon be introducing `RCP_Payment`, I'd like to remove the new actions here until we see how this all shakes out.

**Comment by nosegraze** [comment]
I'm fine with whatever changes you want to make. Eventually I'd like to
have one action that people can use in both scenarios but I'm fine with
postponing that if you prefer. I'd just like to keep it on our radar.

**Comment by mindctrl** [comment]
A note for Braintree before I forget it.

This is currently breaking the separate payment we do when there's a signup fee or discount on auto-renewing payments. It's charging the wrong amount, and logging the payment in RCP with that wrong amount.

**Comment by mindctrl** [comment]
Oops, thought I posted this Friday but ignore my previous comment about Braintree. I was mistaken.

**Comment by mindctrl** [comment]
When using the manual payment gateway, marking a pending payment as complete results in the payment losing its `subscription` and `subscription_key`.

**Comment by mindctrl** [comment]
We need a new `Failed` filter in the payments list now.

![image](https://user-images.githubusercontent.com/1254870/26894290-f4273062-4b8b-11e7-82cb-f4092776e84a.png)

**Comment by mindctrl** [comment]
Updated
![image](https://user-images.githubusercontent.com/1254870/26895319-415f21a2-4b8f-11e7-8814-57cf77e6c6b5.png)

**Comment by mindctrl** [comment]
Getting two payment entries with PayPal Express on a non-recurring purchase. One pending, one completed.

![image](https://user-images.githubusercontent.com/1254870/26930263-d80fa1a8-4c2a-11e7-8ca3-4199d59e6e06.png)

**Comment by mindctrl** [comment]
For recurring with PP Express, I'm not getting any IPN from PayPal so I'm stuck with a pending payment and an active member.

**Comment by nosegraze** [comment]
Looks like it's because the `Subscription` field is blank on the `Complete` payment so [this line](https://github.com/restrictcontentpro/restrict-content-pro/blob/issue/1000/includes/class-rcp-payments.php#L105) is failing.

**Comment by nosegraze** [comment]
Changing this line to `$rcp_payments->update()` instead of `insert()` should fix it: https://github.com/restrictcontentpro/restrict-content-pro/blob/issue/1000/includes/gateways/class-rcp-payment-gateway-paypal-express.php#L342-L353

**Comment by mindctrl** [comment]
Some more thoughts on the action hooks in this PR.

The name of the new `rcp_update_payment_status` actions implies the status was changed, and the comment says as much, but that's not how the code is written. The code only checks that a status was passed in the arguments array, not that it's different and being changed. I think we should consider more accurate names if they're going to run on every successful insert/update regardless of status change.

One other thing with those is we're querying the payment and returning it along with the actions. That could certainly be handy, but it's not always required to have the full object and if you want it you can always query it. My concern here is we lock ourselves into the payment object structure with this action passing the full object. This ties our hands for any updates we make to the payment class and the new `RCP_Payment` object may need to consider this. It encourages developers to have to think about implementation details instead of working with methods that get those properties for them. (Minor side note before I forget, the phpdoc is wrong for the `$payment` structure. It's an object, not an array). Also worth noting that other actions in this class do not pass back the full payment object.

Back to the `rcp_insert_payment` action discussion. For back compat reasons, we decided to only run it when a payment is inserted with the `complete` status. But we're still breaking back compat that way. The action has always been run as long as a payment was inserted, regardless of status, for 4+ years now. I'm concerned what we might break.

**Comment by nosegraze** [comment]
Regarding your final point (I'll look at the earlier stuff in a bit), while that is true, every single add-on that I've seen using that action assumes that `rcp_insert_payment` is inserting a completed payment. I've never actually seen us check the status when using that action. Examples:

https://github.com/restrictcontentpro/rcp-edd-member-downloads/blob/master/rcp-edd-member-downloads.php#L208-L223
https://github.com/restrictcontentpro/rcp-wp-job-manager/blob/master/rcp-wp-job-manager.php#L222-L232

Those are just two examples but there are more. Really those snippets should be checking to make sure the status was `complete` when the payment was added, but they don't. They just assume it's complete since everything in RCP core adds payments as complete. The only way to do otherwise (I think) is to manually add a payment with a different status.

**Comment by mindctrl** [comment]
We definitely need to update those extensions to check the status. I think we just took it for granted since we knew we only inserted them with `complete` status in RCP.

I wondering about custom gateways we don't know about and any other custom development built on top of RCP.

**Comment by mindctrl** [comment]
re: passing full payment object in those actions. After thinking about it a little more, I vote we do not do that. While it's handy and the payment object is already full of `public` properties since it's just a `stdClass` object, it doesn't _help us_ to further encourage that paradigm. It's a small (temporary) gain to pass it and a potentially annoying one to deal with going forward. As we move towards `RCP_Payment` it'll be nice having people deal with payments via methods and not public properties.

**Comment by nosegraze** [comment]
AffiliateWP uses the action in the same way for marking referrals as completed.

I think we'll see a lot more potential issues if we have `rcp_insert_payment` run on _all_ payment insertions because of the huge amount of official add-ons that need updating. We should update them anyway for better practice moving forward, but I'm hesitant to make a huge change that will cause many unexpected results if people don't update the add-ons. And since we've done it that way in our own code, we've left an example of how it should be done (even if it's wrong) so I wouldn't be surprised if third party plugins followed our example and not bothering to check.

Either way we're introducing potential breakage, and I guess I see running `rcp_insert_payment` on `complete` only as the lesser of the two evils.

---

I'm fine with not passing the full payment object into `rcp_update_payment_status` and just sticking with the payment ID.

---

I'm also open to any alternative names you have in mind for the action. `rcp_set_payment_status` ?

**Comment by nosegraze** [comment]
Putting this here so I don't forget to investigate later...

I'm getting "Payment Received" emails when testing with a declining card in Stripe. Payment is entered as "Failed" but I'm getting the payment received email and my account is being activated.

**Comment by pippinsplugins** [comment]
What about introducing a new `rcp_create_payment` (or similar) action that runs along side `rcp_insert_payment`? To ensure we don't break compatibility, we could make `rcp_insert_payment` only run when the status is complete (it could also run when changing from pending to complete). We could also then add a deprecated notice that lets developers know they need to move to the new action.

This allows us to create a more sane structure while maintaining backwards compatibility with custom builds that do not get updated.

**Comment by nosegraze** [comment]
That works for me.

**Comment by nosegraze** [comment]
[This comment about failed payments](https://github.com/restrictcontentpro/restrict-content-pro/issues/1000#issuecomment-307449806) should be fixed by https://github.com/restrictcontentpro/restrict-content-pro/issues/1277.

**Comment by mindctrl** [comment]
Something I think we need to address in this now instead of later is the table structure for payments not being tied to subscription levels. In this PR we've extended the table to include `subscription_level_id`, which further ties us to payments being only for subscriptions.

Per [this comment](https://github.com/restrictcontentpro/restrict-content-pro/issues/1235#issuecomment-301514770) I think we should go ahead and store a `type` and `object_id` now instead of `subscription_level_id`.

**Comment by nosegraze** [comment]
I'm on board with that.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by nosegraze** [comment]
Want me to make that change @mindctrl or are you doing it?

**Comment by mindctrl** [comment]
@nosegraze was there a particular reason for the update logic inside `RCP_Payments::insert()`? I'd rather the method remain purely an insert method unless there's a need for it. If there's a pending payment for a user, we should be able to know that outside the payment class and do the update with the `update()` method instead.

**Comment by nosegraze** [comment]
That's backwards compatibility for third party gateways that may not have been updated to work with our new flow (so they'll be inserting payments in their gateway class instead of updating an existing one from pending to complete). That block hopes to catch that behaviour so we don't wind up with two payments for one purchase.

**Comment by mindctrl** [comment]
Ah yes, that's right. Derp. When I read the back compat comment my head went to internal back compat, not external.

On another note, I'm still having PayPal sandbox issues. Have you been able to test various scenarios with Standard/Pro/Express?

**Comment by mindctrl** [comment]
Hmm I'm thinking the new `type` column should be renamed to `item_type` or something more descriptive. `type` is too generic. Thoughts?

**Comment by pippinsplugins** [comment]
I don't love "item". How about "object"?

**Comment by mindctrl** [comment]
Ooh I like that. `object_type` makes sense.

**Comment by nosegraze** [comment]
I'm happy with `object_type`. :)

RE PayPal: I haven't done thorough testing with those but I can dig into it later today or tomorrow. I did a basic test with PayPal Standard before I updated it to see what the backwards compatibility would be like with a third party gateway and it performed well. Then I did a basic payment after I updated it, but not with more complicated scenarios. So I'll do a more thorough test.

**Comment by nosegraze** [comment]
Tests:

**PayPal Express**

- [x] Regular payment
- [x] Recurring payment both with and without signup fees
- [ ] Free trial

**PayPal Standard**

- [ ] Regular payment
- [ ] Recurring payment both with and without signup fees
- [ ] Free trial

**PayPal Pro**

- [ ] Regular payment
- [ ] Free trial

**Comment by nosegraze** [comment]
Just a note to myself for later: I'm seeing some Authorize.net issues that need to be addressed.

**Comment by nosegraze** [comment]
PayPal isn't working for me this morning so I haven't been able to test PayPal Standard/Pro yet.. _sigh_

Regarding Authorize.net, the problem I've found is that currently we activate the account straight away in `process_signup()`. But at that point we don't have a transaction number for the payment, since payment technically hasn't been taken, so we don't create a payment record. We just know that the subscription was set up. (See https://github.com/restrictcontentpro/restrict-content-pro/issues/1236)

Then, in `process_webhooks()`, we finally record the payment when it comes in, but my understanding is that Authorize.net takes payments in batches like once per day or something... so the webhook could come in _hours_ later.

Our current pending payment flow kind of relies on the account not being activated until payment is completed. That would mean we remove the account activation from `process_signup()` and the account won't be activated until payment comes in, which could be hours later. I imagine this will make for some upset/confused customers.

But if we leave it how it is now where the account is activated immediately in `process_signup()` and payment isn't completed until later, I'm pretty sure that could result in an incorrect expiration date being calculated (potentially giving non-auto renew customers double time).

Any ideas on how best to approach this? Maybe we do need to rely on the `rcp_pending_expiration_date` meta here or something.

**Comment by pippinsplugins** [comment]
We can force Authorize to authorize the transaction. See how we did it in EDD Recurring: https://github.com/easydigitaldownloads/edd-recurring/issues/682

That's not quite the same as actually processing the transaction but at least that way we know it's going to work. Then we just need to prevent duplicating the expiration date processing.

**Comment by nosegraze** [comment]
Okay I set up Authorize.net to use a pending expiration date, which I think should solve the problem: https://github.com/restrictcontentpro/restrict-content-pro/commit/dea0b795d4fd838d7051a1528091ce6988f30b45 `RCP_Member::calculate_expiration()` will use the pending expiration date if it exists instead of calculating it anew. I did a quick test by registering, then manually switching the payment from `pending` to `complete`, which triggers all the complete registration stuff and is essentially the same as the silent post coming in. It seemed to work okay.

We do have a separate issue for authorizing the transaction in Authorize.net - currently slated for `2.9.5`: https://github.com/restrictcontentpro/restrict-content-pro/issues/1236

**Comment by mindctrl** [comment]
Looking at the code comments in that block you moved.

![image](https://user-images.githubusercontent.com/1254870/27489333-2686ba9a-5808-11e7-8a32-29c92a1808c0.png)

Note what the comment says and how it's before the part that sets the expiration date. Is that going to be an issue?

**Comment by nosegraze** [comment]
Arrrgghh. You're right lol. That's why moving it felt wrong. I moved it because `calculate_expiration()` also uses the subscription ID so that actually needs to be set.

**Comment by nosegraze** [comment]
Still haven't been able to test PayPal due to broken sandbox _sigh_.

I've been trying to re-review the code without testing just purely theoretically. I think there's one small tweak that PayPal Pro needs that I want to confirm when I am able to actually get a proper test in.

**Comment by nosegraze** [comment]
Updated the first post in the issue with a gateway testing checklist. Feel free to add/update as you see fit and check anything off that you get tested.

**Comment by mindctrl** [comment]
Just a note that some change here has broken Braintree since last time I tested it. 

Webhooks for new signups die here:

```
		if ( ! $subscription_id = $member->get_subscription_id() ) {
			die( 'no subscription ID for member' );
		}
```

**Comment by nosegraze** [comment]
@mindctrl Was that with auto renew turned on? I think regular auto renew (no trial, no signup fees, no proration) is the only case where the payment isn't completed in `process_signup()`.

**Comment by mindctrl** [comment]
@nosegraze yes I was testing an auto renew. I didn't do more thorough testing because I was working with someone else at the time, so just wanted to log it here before I forgot.

Looking at the commit where you adjusted the renew logic in Braintree, note that the DateTime object in the subscription object is different based on the type of event they send. Sometimes it's stored in `nextBillingDate`, sometimes `firstBillingDate`, and sometimes `paidThroughDate`. I _think_ that's going to break things, but will have to test it.

**Comment by nosegraze** [comment]
Noted. I'm doing a bunch of testing right now and making a bunch of tweaks.

**Comment by nosegraze** [comment]
Added `$0` payments for all free subscription levels and 100% off recurring discounts.

**Comment by mindctrl** [comment]
I have this running on 2 sites now and I'm watching for any issues. Would love to get this merged later this week. I think the Braintree changes earlier will need to be reverted or adjusted. https://github.com/restrictcontentpro/restrict-content-pro/issues/1000#issuecomment-313398518

They're a pain in the ass to test because they don't allow short subscription periods.

**Comment by pippinsplugins** [comment]
❤️

**Comment by nosegraze** [comment]
The last major thing I need to test is free trials with PayPal Pro.
Planning on looking at that tomorrow.

**Comment by mindctrl** [comment]
I'm tired of thinking about this PR. Merged!

**Comment by pippinsplugins** [comment]
Yes!
