### ISSUE TITLE
Empty post meta values being saved

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1005]
When saving a post, it's possible that `rcp_show_excerpt` and `rcp_hide_from_feed` get saved to post meta with empty values. We should delete them from post meta instead.

**Comment by nosegraze** [comment]
PR: #1006

**Comment by mindctrl** [comment]
I just noticed `_is_paid` gets set empty too.

**Comment by nosegraze** [comment]
Derp. How did I miss that one. :P Updated PR.
