### ISSUE TITLE
[rcp_group_members_list] fails in mobile view

### ISSUE THREAD

**Issue by meadows19** [restrictcontentpro/restrict-content-pro#1010]
Normal view:

<img width="307" alt="normal" src="https://cloud.githubusercontent.com/assets/21014471/23172332/7ce2dede-f866-11e6-99a3-ec84f09bf9c9.png">

Mobile view:

<img width="250" alt="mobile" src="https://cloud.githubusercontent.com/assets/21014471/23172340/812a49be-f866-11e6-88b9-7817cd4727ac.png">

**Comment by nosegraze** [comment]
This will actually need to be updated in the Group Accounts add-on, I believe.

**Comment by nosegraze** [comment]
New issue in group accounts: https://github.com/restrictcontentpro/rcp-group-accounts/issues/120

We'll get it sorted there. Thanks @meadows19 !
