### ISSUE TITLE
Auto renew not checked on by default

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1014]
Isn't it supposed to be?

Also now it's not possible to change whether it's checked on or off by default (as we've [been showing here](https://github.com/restrictcontentpro/library/blob/master/registration-form/unchecked-autorenew-checkbox.php)) because it's now done in JavaScript:

```js
// Set up defaults
$('#rcp_auto_renew_wrap input').prop('checked', false);
$('#rcp_auto_renew_wrap').show();
```

Maybe we should actually look up whether it's checked or not initially and then use that for the default.

**Comment by pippinsplugins** [comment]
I think we should make it an option whether to be checked by default or not. We've had a lot of tickets from people that wanted to change it one way or the other.

**Comment by nosegraze** [comment]
PR: #1018
