### ISSUE TITLE
rcp_get_post_ids_assigned_to_restricted_terms() incorrectly includes unrestricted content

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1017]
Similar to #978 and #1005, we're saving `access_level` to `None` when saving a term with no restrictions.

This is causing an issue in `rcp_get_post_ids_assigned_to_restricted_terms()` because the query there just checks for `rcp_restricted_meta`.

We should not store a 'None' value to indicate a term is unrestricted, as that is the default state. We also need to adjust the query in `rcp_get_post_ids_assigned_to_restricted_terms()` to check for the `None` value for back compat.

**Comment by nosegraze** [comment]
Are you sure `None` is still being saved? I think it *used* to be but was changed at some point.

In `rcp_save_term_meta()` : 

```php
if( ! empty( $fields['access_level'] ) ) {

	if( 'None' == $fields['access_level'] ) {
		unset( $fields['access_level'] );
	}

}
```

**Comment by mindctrl** [comment]
Hmm it may be legacy terms I'm seeing it on.

**Comment by mindctrl** [comment]
Yep, that was definitely legacy terms, so just need to address `rcp_get_post_ids_assigned_to_restricted_terms()`.

**Comment by mindctrl** [comment]
PR submitted.

We talked in Slack about batching the deletion of legacy term meta in a future update. While writing this PR, it occurred to me that since we're already querying the metadata and looping through it to possibly ignore, we could go ahead and delete the legacy data while we're in here. That would clean it up pretty quickly. I think that should be ok, but curious what @pippinsplugins and @nosegraze think.

To test this against a site with legacy metadata in the terms, you can:
- check out an old version of RCP (not sure how far back that goes), create some terms without restrictions and let it save the old metadata we don't want.
- or on the latest version, manually create some `rcp_restricted_meta` entries in the termmeta table, with the following values: `a:0:{}`, or `a:1:{s:12:"access_level";s:4:"None";}`.

I don't know of any other legacy term meta issues, so I think this covers them. If you know of any others let's add them.

**Comment by pippinsplugins** [comment]
I like this approach because it cleans up along the way in the background.

:+1: from me.

**Comment by nosegraze** [comment]
Love it!

**Comment by nosegraze** [comment]
Did a little before and after test and it works perfectly!
