### ISSUE TITLE
Ensure PayPal integration is not passing invalid data

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1019]
Per PayPal, as of March 29, 2017 if certain data is passed to them during transactions, the transactions will not be processed and an error will show.

> Most integrations are already working with the new PayPal checkout automatically. However, there are some integrations with problems that cause the user experience to fall back to the old PayPal checkout.

> If your PayPal button redirects to the old experience (left image), your button is passing incorrect data to PayPal.
> If your PayPal button redirects to the new experience (right image), your button is passing correct data to PayPal.

> As of March 29, 2017, redirecting to the old PayPal checkout experience will no longer process the transaction, and customers will receive an error message...

Reference: https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ2067&expand=true&locale=en_US

We need to ensure we're current with that before the time comes.

**Comment by nosegraze** [comment]
For what it's worth, I did an unrelated test payment with PayPal today and got the new UI.

**Comment by mindctrl** [comment]
@nosegraze do you see the new style on both non-recurring and recurring?

**Comment by mindctrl** [comment]
I see the new style on one-time payments, but I see the old style on subscriptions. I don't see why, at least after a quick look at their doc and the info we're sending.

**Comment by mindctrl** [comment]
Here are some things I quickly tested to see if they made any difference:

- setting `page_style` to `paypal` (the default, instead of empty string). did not fix.
- not sending `page_style` at all. did not fix.
- not sending `no_shipping`, `shipping`, `no_note`, `tax`, `a1`, `p1`, and `t1`. did not fix.

**Comment by mindctrl** [comment]
Example of our default request for a subscription:

```
https://www.sandbox.paypal.com/cgi-bin/webscr/
?business=xxx
&email=xxx
&item_number=074957efeed83b23e2264567a77dcd50
&item_name=Basic
&no_shipping=1
&shipping=0
&no_note=1
&currency_code=USD
&charset=UTF-8
&custom=783
&rm=2
&return=http%3A%2F%2Frcp-dev.dev%2Fregister%2Fwelcome%2F
&cancel_return=http%3A%2F%2Frcp-dev.dev
&notify_url=http%3A%2F%2Frcp-dev.dev%2Findex.php%3Flistener%3DIPN
&cbt=RCP+Dev
&tax=0
&page_style=
&bn=EasyDigitalDownloads_SP
&cmd=_xclick-subscriptions
&src=1
&sra=1
&a3=10
&a1=10
&p3=1
&p1=1
&t3=M
&t1=M
```

**Comment by nosegraze** [comment]
Yeah I'm seeing the old style for recurring. But given how different the interfaces are anyway, I'm not actually sure what the new style looks like for recurring anywya. Are we definitely supposed to be seeing the new style for recurring subscriptions?

**Comment by mindctrl** [comment]
Since they don't mention recurring, I assume they mean any transaction type should see the new interface, but with PayPal it's anybody's guess.

**Comment by mindctrl** [comment]
Deprecated variables: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#deprecated-variables

I see `no_note` and `page_style` in the deprecated list, though I'm pretty sure I tested by not sending them at all. Will have to double check.

**Comment by nosegraze** [comment]
Found this topic: https://www.paypal-community.com/t5/PayPal-HTML-Buttons/Update-your-PayPal-buttons-before-29th-March-2017/m-p/1175385/highlight/true#M286

> the subscription flow doesn't have an updated interface yet, and it's not part of the March 29th button ugprade.

**Comment by mindctrl** [comment]
Nice find. Silly PayPal inconsistencies.
