### ISSUE TITLE
Improve Stripe Checkout + reCAPTCHA UX

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1037]
If someone doesn't check the reCAPTCHA during registration while using Stripe Checkout, the process is really quite confusing.

- Don't check reCAPTCHA.
- Click "Register".
- Stripe Checkout modal pops up.
- Enter card details.
- You get the green tick indicating that payment was made.
- Page refreshes.
- Get error message saying, _"Please verify that you are not a robot"_

Because of the green tick, it looks like payment was made (it wasn't) and people might be hesitant about trying again.

The guy who reported this said he added this code to fix the problem on his site:

```php
function mr_rcp_validate_user_fields_on_register( $posted ) {
    if ( rcp_get_subscription_id() ) {
        return;
    }

    if( empty( $posted['g-recaptcha-response'] ) ) {
        rcp_errors()->add( 'invalid_recaptcha', __( 'Are you a robot?', 'rcp' ), 'register' );
    }
}
add_action( 'rcp_form_errors', 'mr_rcp_validate_user_fields_on_register', 10 );
```

**Comment by pippinsplugins** [comment]
I don't see how that fix addresses it . .  . All it changes is adding a check for the subscription ID. Wouldn't that make it _never_ run the check?

**Comment by nosegraze** [comment]
It would never run for logged in users, I guess. But I think we show the CAPTCHA for all users, right? So we wouldn't really want that check there at all.

We'd also need to make sure CAPTCHA is actually activated.

**Comment by pippinsplugins** [comment]
It makes sense to not show reCaptcha to logged in users, but I suspect that would cause a _huge_ support burden as most admins enable it and then go look to see it on the form.

**Comment by mindctrl** [comment]
If there's a callback in reCaptcha we can use when someone successfully completes the thingy, we could use it to enable the Submit button. That would let us disable it until we know it's completed.

**Comment by pippinsplugins** [comment]
I bet there is a callback. Good idea!

**Comment by mindctrl** [comment]
Related: there's an invisible version now. https://developers.google.com/recaptcha/docs/invisible

**Comment by mindctrl** [comment]
It looks like we can use `grecaptcha.getResponse();` to determine if the reCAPTCHA thingy was filled out properly. If returns nothing if it hasn't been filled out, and it returns a response with a string of characters if it has been filled out properly.

https://developers.google.com/recaptcha/docs/invisible#js_api

**Comment by mindctrl** [comment]
Related: the reCAPTCHA javascript loads from Google's site even when it's not enabled in the RCP settings. Unless there's a reason for that we should only load it when enabled.

**Comment by nosegraze** [comment]
Very nice! Works well!

**Comment by pippinsplugins** [comment]
Excellent!
