### ISSUE TITLE
Content restricted to 'any' level is accessible to pending members

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1041]
Content restricted to `any` subscription level is visible to pending members. That's because of this: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.7.3/includes/class-rcp-member.php#L1093

We check for `! is_expired()`, which pending is not. I think we should check for `in_array( rcp_get_status(), array( 'active', 'free', 'cancelled' ) );` instead.

**Comment by nosegraze** [comment]
We should do both IMO.

Without checking for `! is_expired()`, a cancelled but expired member still has access.

**Comment by mindctrl** [comment]
Sigh. We should be marking cancelled members as expired after their expiration date is reached... unless there's a good reason not to that I can't think of right now.

**Comment by nosegraze** [comment]
I would be fine with that. It's caused quite a bit of confusion in several other issues lately like https://github.com/restrictcontentpro/restrict-content-pro/pull/1013

**Comment by pippinsplugins** [comment]
The only "good" reason I know of for not marking them as expired is simply that we never have. That's not a very good reason though.

I think we should change it so cancelled members get marked as expired.

**Comment by pippinsplugins** [comment]
Shouldn't this be `in_array( rcp_get_status(), array( 'active', 'free', 'cancelled' ) ) && ! $member->is_expired()`?

**Comment by mindctrl** [comment]
Updated PR

**Comment by pippinsplugins** [comment]
Pr looks right to me now.

**Comment by nosegraze** [comment]
Tested with:

- Cancelled, but expired member. (no access)
- Cancelled, but not expired member. (access)
- Pending, but not expired member. (no access)
- Expired member. (no access)
- Active member. (access)
- Free member. (access)

👍
