### ISSUE TITLE
Username validation fails on multisite when using uppercase characters

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1047]
More like a bad, unexpected user experience than a _bug_, but whatevs.

- Someone enters "Ashley" as their username.
- `sanitize_user()` sends it back as "ashley" (on multisite).
- Since the two don't match, they get an _"Invalid Username"_ error.

One customer had a lot of people running into this issue and it was very unclear as to why the username was invalid.

I don't think usernames are actually case sensitive while logging in, so in `rcp_validate_username()` we could change this:

```php
$sanitized = sanitize_user( $username, false );
$valid = ( $sanitized == $username );
```

to this:

```php
$sanitized = sanitize_user( $username, false );
$valid = ( strtolower( $sanitized ) == strtolower( $username ) );
```

In the end it would actually get saved as the lowercase version, but the user should still be able to login with uppercase characters if they want.

**Comment by pippinsplugins** [comment]
Let's get this in right after 2.8. We've run into this consistently on the EDD site.

**Comment by nosegraze** [comment]
PR: #1075
