### ISSUE TITLE
Currency chosen should dynamically change the currency position select menu

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#105]
Choosing a currency that uses a symbol other than "$" should dynamically update the "Currency Position" select list to use the appropriate symbol, if applicable.

I'm assuming the simplest (best?) way to do this is to store an array of possible "before/after" text, and use js to swap out them out if the selected currency matches one of the before/after pairs. Hopefully that makes some sense.

By the way, I realize this is a tiny, tiny enhancement that impacts the user for all of probably five seconds, so I won't feel bad at all if this is lower than low on the priority list :smile:.

![2014-08-07 at 11 06 pm](https://cloud.githubusercontent.com/assets/796639/3853032/fbb1c5e2-1eb9-11e4-9efb-5f00a2018564.png)

**Comment by pippinsplugins** [comment]
PR is working perfectly for me!

**Comment by tnorthcutt** [comment]
@pippinsplugins Awesome. Don't merge just yet; one more improvement coming 😄
