### ISSUE TITLE
Posts restricted by term not included in rcp_is_restricted_content()

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1051]
I suggest we include posts with term restrictions in `rcp_is_restricted_content()`, then we can create another function for like `rcp_has_post_restrictions()` that only looks at post-level restrictions.

**Comment by mindctrl** [comment]
Good idea. For `rcp_is_restricted_content()` I think we can just merge the arrays from `rcp_get_restricted_post_ids()` and `rcp_get_post_ids_assigned_to_restricted_terms()`, which are cached, and check if the post ID is in the array.

**Comment by nosegraze** [comment]
PR: #1102
