### ISSUE TITLE
Return early in RCP_Member::can_access() under certain conditions

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1052]
We currently check the user's status and/or expiration date in multiple places.

[here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1116)
[here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1135)
[here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1163)
[here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1215)
[here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1221)
[here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1259)
[and here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1265)

This has recently led to quite a few patches when we don't check quite the right thing in every single place. It would be nice to just totally bail out early if the account is obviously expired or doesn't have the right status.

I'd suggest three early return points:

1. If the user is an admin (always get access).
2. If the post is totally unrestricted (always get access).
3. If the current user is expired or doesn't have the right status (no access).

Example:

```php
// Admins always get access.
if( user_can( $this->ID, 'manage_options' ) ) {
	return apply_filters( 'rcp_member_can_access', true, $this->ID, $post_id, $this );
}

// If the post is unrestricted, everyone gets access. (this would work after issue #1051)
if( ! rcp_is_restricted_content( $post_id ) ) {
	return apply_filters( 'rcp_member_can_access', true, $this->ID, $post_id, $this );
}

/*
 * From this point on we assume the post has some kind of restrictions added.
 */

// If the user is not logged in or doesn't have an active account, they don't get access.
if( ! is_user_logged_in() || $this->is_expired() || ! in_array( $this->get_status(), array( 'active', 'free', 'cancelled' ) ) ) {
	return apply_filters( 'rcp_member_can_access', false, $this->ID, $post_id, $this );
}

// ... rest of method follows
```

I believe this would also fix some issues people have now where they mark an account as expired expecting to revoke their access, but they actually still have access to some content because their expiration date is still in the future.

But mostly I think this would be nice to simplify our code and stop repeating the checks so often.

**Comment by mindctrl** [comment]
Related, I'd love to see a method for getting "active" users that are `active`, `free`, or `cancelled` but not expired yet.

Ideally `is_active()` would cover that, but that's technically a breaking change since `free` has been kept separate.

**Comment by nosegraze** [comment]
Yeah I totally agree about that. Ideally I'd like `is_active()` to do that and then have `is_paid()` to cover paid ones instead. But yeah, breaking change.. bleh.

**Comment by mindctrl** [comment]
To your original point, I like the suggestion of returning early where possible to avoid running code unnecessarily and to avoid running into those edge cases where we break `can_access()` due to simply overlooking a case further down the method.

**Comment by nosegraze** [comment]
PR: #1110

I'd like to get this into `2.8.3` because I just got a report that a cancelled but expired member still retains access to content restricted to a subscription level via term. This update would fix that.

**Comment by mindctrl** [comment]
👍 I'm ready to tear that whole method apart and bring some sanity to our lives. I'm tired of issues with that method.

**Comment by mindctrl** [comment]
Unit tests failed with this PR

**Comment by mindctrl** [comment]
Haven't tested this yet, but would love to get a new test that covers "cancelled but expired member still retains access to content restricted to a subscription level via term".
