### ISSUE TITLE
Member edit allows viewing invalid member ID

### ISSUE THREAD

**Issue by cklosowski** [restrictcontentpro/restrict-content-pro#1053]
If you visit the Member edit page with an invalid member ID, you get some odd results that are unexpected.

For instance it brings up a full member edit form, but has an expiration date of `1970-01-01` and the payment history just pulls the last payments it finds for any member record:

![screen shot 2017-03-03 at 9 50 58 pm](https://cloud.githubusercontent.com/assets/1390124/23576187/8ad0f290-005b-11e7-8afc-e113601b1adb.png)

![screen shot 2017-03-03 at 9 51 07 pm](https://cloud.githubusercontent.com/assets/1390124/23576188/8e26ac32-005b-11e7-98d5-6a9cf8718d72.png)

To replicate, just use the following Admin URL:
`wp-admin/admin.php?page=rcp-members&edit_member=999999999`

**Comment by nosegraze** [comment]
PR: #1077
