### ISSUE TITLE
Subscription level price doesn't update on register-single.php when discounts are applied

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1054]
In the _register-single.php_ template we have a second instance of the subscription level price at the bottom of the page. This price isn't updated when applying a discount code.

![rcp-level-price](https://cloud.githubusercontent.com/assets/6324272/23588410/2cdfae46-01b5-11e7-9f4c-fd2a81443390.png)

But since we already display the full information in the above table, I think it would be better to remove it all together. We do use this information when creating a Stripe token and maybe in other places:

```php
class="rcp_level" rel="<?php echo esc_attr( $level->price ); ?>"
```

(the class and rel value)

But we could easily integrate that elsewhere.

**Comment by pippinsplugins** [comment]
Let's remove it. It's left over from before we had the detailed pricing displayed.

**Comment by nosegraze** [comment]
PR: #1076

**Comment by pippinsplugins** [comment]
This needs to be tested with Stripe and Stripe checkout.
