### ISSUE TITLE
Large empty white space on Edit Member payment table

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1055]
It's only noticeable on larger screens, but there's a huge empty white area on the right side of the table.

![rcp-payments-table](https://cloud.githubusercontent.com/assets/6324272/23611952/48aba708-0271-11e7-87d4-b7a2066450dc.png)

This is because we have inline CSS setting the display type to `block` when it should be `table`. We should just remove this completely:

```
style="display: block; width: 100%;"
```

The 100% width is already covered in our admin stylesheet anyway.

**Comment by mindctrl** [comment]
This PR is causing the payments table to run outside the right of the browser, which makes the browser show a horizontal scrollbar to view the full table.

**Comment by mindctrl** [comment]
I'm using Chrome on a 13" screen.

**Comment by nosegraze** [comment]
Shucks. Will look into a better responsive table solution.

**Comment by nosegraze** [comment]
Updated the PR, which I believe fixes your problem @mindctrl .

But while we're here, maybe we should update the mobile view as well. It's a bit crap.

**Comment by mindctrl** [comment]
Yep, that fixes what I saw. Also agree that it would be nice to fix up the mobile view like we did in some of the other tables.

**Comment by nosegraze** [comment]
![rcp-responsive-payments](https://cloud.githubusercontent.com/assets/6324272/23861761/f81486a6-0802-11e7-9869-c909c3e87dc7.png)

...aaaalmost got it, but need some help on something.

From core's `common.js` : 

```js
// Toggle list table rows on small screens
$( 'tbody' ).on( 'click', '.toggle-row', function() {
	$( this ).closest( 'tr' ).toggleClass( 'is-expanded' );
});
```

However, when I click on the payments table button, the click action is triggering twice, so it adds `is-expanded` then immediately removes it again. Can't quite figure out what I've mucked up lol. You guys see anything?

**Comment by pippinsplugins** [comment]
Could we make the amount the primary column?

**Comment by mindctrl** [comment]
IIRC, setting a column as primary that isn't the first column in the table didn't work right back when we were updating the member, payment, and discount screens.

**Comment by nosegraze** [comment]
Yeah I just tested it and it was a huge mess. We could make it work if we duplicate some of the info and use media queries to show/hide.

**Comment by mindctrl** [comment]
@nosegraze if you move the `rcp_payment_details` table outside of the `<tr>` it expands properly, but it breaks the visuals on desktop.

**Comment by nosegraze** [comment]
Hmm two options:

1. We can move the payments table outside of the main table completely. (Directly before `<p class="submit">`)
2. We rename some stuff and add our own JavaScript for the trigger.

**Comment by mindctrl** [comment]
I vote for option 1. I'd rather it all work with the existing core stuff if possible.

**Comment by nosegraze** [comment]
Me too. The only visual difference (I think) is that the payments table will now be _after_ the `rcp_edit_member_after` hook instead of before. Things will be ordered slightly differently for anyone using that hook. But I don't think that's a big deal. In fact I actually kind of prefer it.

**Comment by mindctrl** [comment]
Looks good to me. I'm also fine with the payments being after the hook.

**Comment by mindctrl** [comment]
For reference, there's a ticket on Trac for the issue you see when the primary column is the first column in the table: https://core.trac.wordpress.org/ticket/33308
