### ISSUE TITLE
Upgrades improperly given both proration and full expiration date extension

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1056]
When a non-recurring member upgrades early, a proration credit is given and the expiration date is extended a full period from the current expiration date instead of current date. This results in the person getting free time on their subscription.

Related: #812

**Comment by nosegraze** [comment]
PR: #1098

**Comment by mindctrl** [comment]
If a non-recurring member renews the same subscription early, the remaining time is lost because the expiration date is calculated from today and not their existing date.

**Comment by mindctrl** [comment]
Oh I think we fixed that already.

**Comment by mindctrl** [comment]
We disabled proration in #812 when renewing same sub, but the expiration date is being calculated from now instead of existing expiration date.

**Comment by nosegraze** [comment]
We fixed it for renewing the same sub, this one is specifically for upgrades.
