### ISSUE TITLE
PayPal Express: if initial payment fails, user still has access to content

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1060]
It looks like this flow is happening:

- User signs up for recurring payment.
- `recurring_payment_profile_created` IPN gets triggered and account is activated.
- Initial payment actually fails, triggering `recurring_payment_profile_cancel` IPN.
- RCP status is set to `cancelled`, but the account expiration date is still set in the future so they still retain access until the end of the cycle.

In the profile cancelled IPN, `initial_payment_status` comes back as `Failed` so that's something we could look for.

**Comment by pippinsplugins** [comment]
I didn't know there was a `initial_payment_status` field. Cool.

**Comment by nosegraze** [comment]
PR: #1074

**Comment by mindctrl** [comment]
This looks good to me, but I can't test it right now. My sandbox is tripping again.

**Comment by mindctrl** [comment]
The PR looks good, but I still can't get my sandbox working right to test. @nosegraze if you've confirmed this works, feel free to merge.

**Comment by nosegraze** [comment]
Yep it works well. I turned on negative testing and made a purchase of `131.22` to trigger this response: `Transaction Declined (API Error Code 13122)`.

**Comment by mindctrl** [comment]
Woot!
