### ISSUE TITLE
Auto Renew checkbox remains visible when selecting levels with 'unlimited' duration

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#1085]
The auto renew checkbox remains visible on the join/renew form when the user selects a membership level with an 'unlimited' duration.

**Comment by pippinsplugins** [comment]
@nosegraze could you look at this?

**Comment by nosegraze** [comment]
@thomasfw Is this also a free subscription? I'm seeing the problem with an unlimited free subscription, but not an unlimited paid one.

**Comment by thomasfw** [comment]
@nosegraze yep free and unlimited

**Comment by nosegraze** [comment]
@thomasfw Thanks, I'll look into it! :)

**Comment by nosegraze** [comment]
PR: #1088
