### ISSUE TITLE
Add a more reliable hook that gets triggered when the user plan gets changed

### ISSUE THREAD

**Issue by lordspace** [restrictcontentpro/restrict-content-pro#1086]
Can you please add a more reliable hook that gets triggered when the plan gets changed and not just on rcp_set_status?  ... because I can change the user plan from the Admin area.

https://youtu.be/tiDGuAX7zUQ

**Comment by nosegraze** [comment]
We do have two hooks for this already:

`rcp_member_pre_set_subscription_id` - fired right before the level is changed
`rcp_member_post_set_subscription_id` - fired right after the level is changed

Here's an example of how we used those hooks recently: https://github.com/restrictcontentpro/restrict-content-pro/pull/1082/files

**Comment by lordspace** [comment]
Nice! That will do. My code gets triggered now.
Thanks Ashley.
