### ISSUE TITLE
Add support for Paypal Micropayments / Digital Products Payment Processing

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1089]
Link: https://www.paypal.com/us/webapps/mpp/digital-products

Request: https://secure.helpscout.net/conversation/333238455/55108/?folderId=1100052

**Comment by nosegraze** [comment]
Is this the same as this: https://developer.paypal.com/docs/classic/products/digital-goods/ ?

If so:

> Note: Express Checkout Digital Goods is no longer available for new integrations. This feature remains available for merchant accounts that already have Express Checkout Digital Goods enabled.

**Comment by mindctrl** [comment]
I think that's the same. Even if it isn't, I say we don't add any new PayPal anything that we don't have to. It's an abomination. Closing this out. Reopen if you disagree.
