### ISSUE TITLE
Improve member notes during initial signup

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1093]
When a member first subscribes, the first note says:
`Member's status changed from  to pending`

Since the member doesn't have an initial status, the note doesn't read properly. I think we should update that so the first note reads well.

**Comment by nosegraze** [comment]
This is more related to #1030 I suppose, but interesting behaviour here with a free subscription. This is a brand new account registering for the first time.

```
March 13, 2017 17:49:35 - Forever Free subscription started.

March 13, 2017 17:49:35 - Member's status set to pending

March 13, 2017 17:49:35 - Member's expiration changed from  to none

March 13, 2017 17:49:35 - Forever Free subscription renewed.

March 13, 2017 17:49:39 - Member's status changed from pending to free
```

Main one of interest is `Forever Free subscription renewed.`

**Comment by nosegraze** [comment]
Also while we're here, maybe we should update this too:

```
Member's expiration changed from  to none
```
