### ISSUE TITLE
Check subscription ID before cancelling membership via Stripe webhook

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1095]
It would be excellent if we could match the subscription ID before cancelling here:

```php
// Cancelled / failed subscription
if( $event->type == 'customer.subscription.deleted' ) {

	if( ! $member->just_upgraded() ) {

		$member->cancel();

		die( 'member cancelled successfully' );

	}

}
```

I've only had this happen once, but I ran into an issue while cancelling then immediately paying again:

- Cancel subscription.
- Manually adjust expiration date to be in the past.
- Register for new plan.
- Webhook triggers activating new plan.
- Slightly delayed webhook triggers cancelling the previous plan.
- Status ended up stuck at `cancelled`.

Again, I only had it happen once and it was probably just bad luck that the cancelled webhook was delayed, but would still be nice to fix just in case!

**Comment by nosegraze** [comment]
PR: #1130

**Comment by pippinsplugins** [comment]
PR looks good to me.
