### ISSUE TITLE
Stripe customer balance should be removed if payment fails

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1097]
When using signup fees:

If a member tries to subscribe and the customer credit card is attached to the Stripe customer object, but the actual charge fails, the customer balance is not adjusted.

If the customer tries again, a second balance is added to their Stripe customer object. This makes it possible for the customer to be charged more than intended.

If the initial payment fails, we should remove the amount we added from the customer balance so that any additional attempts work as expected.

Stripe has a test card number that tests this scenario. It is: `4000000000000341`

**Comment by nosegraze** [comment]
Works perfectly! Merged.
