### ISSUE TITLE
Split up process-data.php

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1101]
I hate this file so much. I hate trying to find anything in there. I'd love to see it divided up into different files. Anything related to processing member data would go in `includes/admin/members/`, and anything for discounts in `includes/admin/discounts/`, etc.

**Comment by pippinsplugins** [comment]
It's only my least favorite file in the plugin!

**Comment by nosegraze** [comment]
PR: #1140

**Comment by pippinsplugins** [comment]
@nosegraze ready for full testing?

**Comment by nosegraze** [comment]
Yep I believe so!

**Comment by pippinsplugins** [comment]
Left a few change notes on the PR but otherwise this appears to all be working perfectly!

**Comment by nosegraze** [comment]
Updated. :)

**Comment by pippinsplugins** [comment]
@nosegraze Deleting a payment doesn't work anymore.

**Comment by nosegraze** [comment]
Thanks @pippinsplugins . Should be fixed now!

**Comment by pippinsplugins** [comment]
Yep, works now! I'm going to merge this!
