### ISSUE TITLE
Amounts missing trailing zeroes on payment edit screen

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1105]
When editing a payment, the trailing zeroes are stripped on the display. When you try to submit the edit, an error is shown due to the format not being correct.

![image](https://cloud.githubusercontent.com/assets/1254870/24007157/2615f448-0a44-11e7-9ac3-035aaad9b234.png)

That's because we have a pattern attribute on the amount field that requires a decimal and trailing zeroes, but we don't display it that way when rendering the field.

We store the amounts in the DB without the trailing zeroes, so I think we should adjust the regex pattern to allow non-decimal numbers.

**Comment by nosegraze** [comment]
PR: #1134

**Comment by pippinsplugins** [comment]
PR looks good.
