### ISSUE TITLE
Free trials not working (again) in PayPal Express

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1107]
We somehow lost this PR in the `2.8` update: https://github.com/restrictcontentpro/restrict-content-pro/pull/991

**Comment by nosegraze** [comment]
PR: #1108

**Comment by nosegraze** [comment]
This may need some tweaking. I've been running a few tests with a customer and I think the `PROFILESTARTDATE` may need an adjustment. Right now it's set to when the trial ends, but it looks like this is happening:

- Create subscription level with 2 day free trial and 1 month subscription.
- Signup.
- After two days (end of free trial) a $0 "payment" is taken and "next payment due" is set for 2 days after that.
- First real payment isn't taken until a total of _four days_ after initial signup.

So perhaps the `PROFILESTARTDATE` needs to be set to the current day?

**Comment by pippinsplugins** [comment]
https://github.com/easydigitaldownloads/edd-recurring/issues/675

**Comment by nosegraze** [comment]
New PR: #1144

**Comment by pippinsplugins** [comment]
This looks correct to me.
