### ISSUE TITLE
Allow login redirect URL to be filled by a query arg

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1147]
I got a request from someone who wanted to link to their login page but add a query arg so the user would be redirected back to the previous page after login.

Sounds like a nice idea, though we should update the redirect to use `wp_safe_redirect()`.

**Comment by pippinsplugins** [comment]
This would bring us in line with what WP core allows. :+1:

**Comment by nosegraze** [comment]
Um, so apparently this is already a thing. https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/member-forms.php#L27-L35

I swear I looked for it and couldn't find it before lol.

I made two super small changes anyway: #1185

**Comment by mindctrl** [comment]
This PR makes it so redirects to another domain after login no longer work, which would break any redirects on multisite with domain mapping.

**Comment by nosegraze** [comment]
The main reason I added it is because it might be a bit iffy to allow external redirects when it can be filled via query arg. The same customer who wanted this feature was concerned about that.

**Comment by mindctrl** [comment]
Since we do a nonce check, I don't think anyone can stuff a scammy URL in the POST data and it still work, but I'm ok with merging this if you and @pippinsplugins are ok with the possible multisite implications.

**Comment by pippinsplugins** [comment]
Let's stick with `wp_safe_redirect()` for now. If it becomes an issue we can either document how to go to external domains or change it back.
