### ISSUE TITLE
RCP cancels wrong paypal subscription (cancels new one instead of the old one)

### ISSUE THREAD

**Issue by lordspace** [restrictcontentpro/restrict-content-pro#1151]
I've reported this in an email but want to have it here so it doesn't get lost.
Ticket #56677

**Comment by lordspace** [comment]
Also cancellation link doesn't work.
There was a problem cancelling the subscription, please contact customer support. Error: Invalid profile status for cancel action; profile should be active or suspended

**Comment by pippinsplugins** [comment]
@lordspace we'll continue this via the support ticket. If we confirm it is indeed a bug in the code, we'll re-open this.

**Comment by lordspace** [comment]
Ok. Sounds good.
