### ISSUE TITLE
rcp_register_form_submission handler is bound multiple times

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1154]
The Stripe Checkout modal loads twice. You can't really see it because one launches right over the other. It doesn't seem to affect anything, but it happens due to the handler being registered multiple times because we load the fields method multiple times.

**Comment by mindctrl** [comment]
PR submitted.

In the other gateways, we set a variable when processing and bail. We could fix those up to use this method instead.

**Comment by mindctrl** [comment]
Updated the title and PR to address other gateways.

**Comment by mindctrl** [comment]
For historical reference, this was an issue prior to this handler being introduced when we were binding to click instead.

**Comment by mindctrl** [comment]
We also have similar issues in register.js where we reference variables to avoid running code multiple times due to the multiple bind issues, but those should be addressed in another issue.

**Comment by nosegraze** [comment]
Tested:

- [x] Stripe Checkout
- [x] 2Checkout
- [x] Braintree
- [x] Stripe

👍
