### ISSUE TITLE
%amount% template tag incorrect in activation email when using Stripe (recurring)

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1159]
The activation email gets sent when the status is updated to 'active', but we don't insert the payment on Stripe recurring until _after_ we updated the status. So the `%amount%`' template tag ends up being either empty (first time purchases) or showing the _previous_ payment amount rather than the most recent one.

I think #1000 would fix this, since it would create the payment before going to the gateway.

Note: This isn't an issue with non-recurring Stripe payments.

**Comment by mindctrl** [comment]
#1127 has been merged.

**Comment by mindctrl** [comment]
Accidentally closed. Reopened for testing.
