### ISSUE TITLE
Membership incorrectly cancelled when upgrading from recurring to non-recurring in Stripe

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1160]
I stumbled into this and only pieced together what probably happened later. I haven't had a chance to confirm, but I think this is what happened:

- Start with an active, recurring account (has a `merchant_subscription_id` from Stripe filled out).
- Upgrade to a non-recurring membership. This process doesn't delete the `merchant_subscription_id`.
- Previous membership is cancelled during the upgrade.
- Webhook comes back with cancellation event, and as of #1095 we removed the `just_upgraded()` check before cancelling -- we only check this:
```
if( $payment_event->id == $member->get_merchant_subscription_id() ) {
```

It's coming back as `true` since the `merchant_subscription_id` wasn't deleted, even though the new membership doesn't have a recurring subscription.

**Comment by pippinsplugins** [comment]
Seems like we could just delete the ID during upgrade to resolve this.

**Comment by nosegraze** [comment]
PR: #1163
