### ISSUE TITLE
Input fields are too small

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1165]
The price input fields on the subscription level add/edit screen are not wide enough. Prices like 19.99 get cut off in the display. Same for discount amount fields. There may be other fields. Time to fix this annoyance.

![image](https://cloud.githubusercontent.com/assets/1254870/24916706/e17b7e1a-1ea8-11e7-96de-ff1d60bc06d1.png)

**Comment by nosegraze** [comment]
While we're doing this, we should also get rid of the inline CSS on that field and move it to the stylesheet.

**Comment by nosegraze** [comment]
PR: #1171

![rcp-price-field](https://cloud.githubusercontent.com/assets/6324272/25005426/dd920b76-2050-11e7-836e-638127e4ba92.jpg)

**Comment by mindctrl** [comment]
Woot!
