### ISSUE TITLE
Row actions on payment list table are out of order

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1173]
When viewing the payment list in the admin, the actions aren't ordered sensibly.

The first two actions are `View Member` and `Edit User`, both of which are secondary actions unrelated to payments. I'd even argue that `Edit User` can go away, in deference to the `Edit User Account` link on the `View Member` screen. I think it's highly unlikely that people need to edit the user account frequently while viewing payments.

![image](https://cloud.githubusercontent.com/assets/1254870/25006737/11c4c174-202c-11e7-9596-f758959e17ea.png)

Current actions:
`ID: 1067 | View Member | Edit User | View Invoice | Edit | Delete`

Proposed actions:
`Edit | Invoice | Delete | Member | ID: 1067`

**Comment by nosegraze** [comment]
Yess this has been bugging me!

Related: My first instinct is always to click on the primary bolded link in order to edit an item in a table like this. That's how it is with subscription levels, members, discount codes, and basically everything else in WordPress. But in this table, clicking on the primary link (the username) shows all payments by that user. It catches me out every time.

**Comment by mindctrl** [comment]
Yep, me too! I was going to member that here but couldn't think of a way to handle that functionality. But how about this?

Make the bold link go to the payment view/edit screen, and use these actions below instead:
`View Invoice | Delete | Member | Member Payments | ID: 1067`

or something along those lines... I really want the bold link to work like all other list tables.

**Comment by nosegraze** [comment]
Yep I like that! I might actually suggest keeping `Edit` in there as well just for clarity. That's also consistent with how we do it in other areas (and how WP core does it). So you can click on the bolded item, or hover over and click `Edit`.

**Comment by mindctrl** [comment]
👍 
`Edit | Invoice | Delete | Member | Member Payments | ID: 1067`

**Comment by pippinsplugins** [comment]
Love it.

**Comment by nosegraze** [comment]
PR: #1176

![rcp-payment-actions](https://cloud.githubusercontent.com/assets/6324272/25042425/d96a1b1e-210f-11e7-94fc-497f198ba7e7.png)

I also made the delete button red in both the payments and discount tables.

**Comment by pippinsplugins** [comment]
That's a great improvement.

**Comment by nosegraze** [comment]
Merged!
