### ISSUE TITLE
Filter in rcp_currency_filter() never runs

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1189]
In the `switch()`, once the case is matched it returns, and never passes through the filter. From the looks of it in `git blame`, it's always been this way and the filter has never worked.

Since it's been 5+ years without a working filter, I'm inclined to just remove the filter entirely and maybe introduce a new function with a better name in the future that has a filter.

**Comment by mindctrl** [comment]
We do have a ticket right now where someone wants to change Australian $ to show `AU$` for clarity, so we could keep the filter and make it work.

**Comment by mindctrl** [comment]
As far as I know, that's one person... otherwise we'd have tickets about this before.

**Comment by nosegraze** [comment]
> so we could keep the filter and make it work.

Let's do that since we have a request for it right now. We even [use it in our documentation](http://docs.restrictcontentpro.com/article/1698-registering-currency-codes) though at least in those circumstances it should work (with a whole new currency rather than editing an existing one).

**Comment by pippinsplugins** [comment]
I vote we fix the filter so it works.

**Comment by nosegraze** [comment]
PR: #1194
