### ISSUE TITLE
Stripe Checkout modal shows price when signing up for trial via [register_form_stripe]

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1191]
![rcp-stripe-checkout-trial](https://cloud.githubusercontent.com/assets/6324272/25181404/5b2f0a68-2509-11e7-99fe-86c4ff6a3652.png)

This is when signing up for a free trial. The $20 is a bit misleading. I remember we addressed this already in the normal `[register_form]` shortcode, so it just says `Start Trial` or `Register`.

**Comment by nosegraze** [comment]
PR: #1192

**Comment by pippinsplugins** [comment]
Works perfectly.
