### ISSUE TITLE
Submit button disabled if reCaptcha is checked on but no keys are filled out

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1197]
Really this is a user error, but maybe we should account for it just in case.

We pass this into the JavaScript:

```php
'recaptcha_enabled'  => isset( $rcp_options['enable_recaptcha'] ) ? true : false
```

Then the JS does this:

```js
if ( '1' === rcp_script_options.recaptcha_enabled ) {
	jQuery('#rcp_registration_form #rcp_submit').prop('disabled', true);
}
```

If reCaptcha is checked on but no keys are entered, the reCaptcha doesn't actually get displayed on the registration form, but the submit button gets disabled anyway.

**Comment by mindctrl** [comment]
I've seen this twice already. People are amazing. Enable it but don't enter the keys.

**Comment by nosegraze** [comment]
PR: #1198
