### ISSUE TITLE
Fully-discounted auto-renewing subscriptions expire unintentionally

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1205]
When the one-time discounts setting is disabled and a 100% discount code is applied to an auto-renewing subscription, the member ends up expiring at the end of the term. Members should be set to never expire under these conditions.

**Comment by nosegraze** [comment]
PR: #1210

**Comment by pippinsplugins** [comment]
Looks good, merged.
