### ISSUE TITLE
Move to standard wp_signon() method of login

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1217]
We use a custom implementation, which has the disadvantage of not running some actions and filters that the WP core login does inside of `wp_signon()`. Because of this we do manual checks for plugins like Limit Login Attempts, which I don't think would be necessary if we switch.

Also I think using the core method would just generally be safer and more compatible all around.

`wp_signon()` returns a `WP_Error` object in all instances of failure (missing username, pass, wrong info, etc), and we can use that as a failure indicator to reduce some of the error checking we have in place and still use our own error messaging.

**Comment by nosegraze** [comment]
PR: #1609

The error checking may be a bit funky, but I think it was necessary for backwards compatibility. We need to do an error check before `wp_signon()` in case third party plugins have added their own checks. If there's an error via that `rcp_login_form_errors` hook, we shouldn't even attempt the login at all. But then we need to check for errors again after `wp_signon()` in case that process failed.
