### ISSUE TITLE
After user registration automatically lands into the members area without verifying email.

### ISSUE THREAD

**Issue by dinakaranAppViewX** [restrictcontentpro/restrict-content-pro#1218]
Hi,

In my membership website, when submit the registration form, it automatically lands into the members area before verifying the email. But my requirement is user should lands on the verify email page saying "please verify your email address". And the user checks their email and click the link to verify the email and then lands into login page. Then only user can access the members area. 

Please suggest me how can I fix this?

**Comment by nosegraze** [comment]
I see you submitted a support ticket - great. :) I'm closing this while we help you there. We don't handle support on GitHub.
