### ISSUE TITLE
Media Library not working if RCP active

### ISSUE THREAD

**Issue by nagygabor** [restrictcontentpro/restrict-content-pro#1219]
Hi!

If I activate RCP Media Library doesnt work any more, it is loading indefinetly.
![rcp_bug](https://cloud.githubusercontent.com/assets/11510539/25579347/652f1dec-2e77-11e7-8948-3b5aeb6892e3.png)

If I turn RCP off, it will work again.

I think it is some javascript problem:(

Version 2.8.5

please advise!
thanks

**Comment by nosegraze** [comment]
Hi @nagygabor ,

Can you please submit a support ticket here: https://restrictcontentpro.com/support/ ?

GitHub is just where we track the plugin's development. We don't do support here. But we'll be happy to help you via the above form. :)
