### ISSUE TITLE
"Hide from RSS feeds" meta box option does nothing

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1220]
RSS feed content is already restricted via `rcp_filter_restricted_content()`.

Since it doesn't do what it was originally intended to do, perhaps we should just remove the option completely.

Alternatively we could make it fully remove the post from the RSS feed, but the `Hide Restricted Posts` option already does that too.

**Comment by pippinsplugins** [comment]
>>>Since it doesn't do what it was originally intended to do, perhaps we should just remove the option completely.

I think we should remove it. While I know it was originally kept separate, that behavior really doesn't make sense except perhaps in 1% or less of standard use cases.

**Comment by nosegraze** [comment]
PR: #1226

We may want to delete the old meta data.
