### ISSUE TITLE
Eliminate duplicate queries on discounts admin page

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1222]
When viewing the discount codes page in the admin, the queries that get the discount details/status run twice for each code.

![image](https://cloud.githubusercontent.com/assets/1254870/25585755/25c8fbd0-2e6a-11e7-8d36-0ca54efa09fd.png)

This is because we're calling `rcp_get_discount_status()` twice on the codes. We should run it once and store the result for reference.

**Comment by mindctrl** [comment]
Line numbers above are coming from `issue/847` branch, but the same thing happens on current release. We can patch this up after 2.9.

**Comment by nosegraze** [comment]
I'm not even sure why we're using `rcp_get_discount_status()` at all since we can just do `$code->status`. It's right there. :P

**Comment by mindctrl** [comment]
PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/1353
