### ISSUE TITLE
z-index issue on username search results causes text overlap

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1234]
![rcp-username-search](https://cloud.githubusercontent.com/assets/6324272/25957632/b30d0e06-3666-11e7-8b2e-bac6364a9e32.png)

Giving `#rcp_user_search_results` a higher `z-index` fixes it.

**Comment by nosegraze** [comment]
PR: #1355

**Comment by mindctrl** [comment]
Works great, will merge when tests finish.
