### ISSUE TITLE
Authorize.net: authorize cards before creating subscriptions

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1236]
Authorize.net doesn't actually authorize cards when we hand over the card details. It happens later in the day. This could result in someone getting access to restricted content after providing a card that ultimately gets declined.

See: https://github.com/easydigitaldownloads/edd-recurring/issues/682

**Comment by mindctrl** [comment]
We have a report of this happening.

**Comment by mindctrl** [comment]
In the above case, when the member's payment failed ~24 hours after registration, the member status remained as active.

**Comment by nosegraze** [comment]
I have a PR open for updating the Authorize.net SDK and will tackle this as soon as that's merged.

**Comment by mindctrl** [comment]
@nosegraze I'm going to test that PR sometime tomorrow so we can move forward with all these little Authnet quirks.

**Comment by nosegraze** [comment]
PR: #1494

This authorizes cards, and I also added kind of a catchall to the webhook in case the very first payment fails.

Took me a while to figure out that you have to use `Transaction Amount Triggers (legacy)` for testing here: http://developer.authorize.net/hello_world/testing_guide/?searchid=1485175934365 The zip code things weren't working for me at all...

So to get a declined response code from a card, set the amount to `$70.02`.

**Comment by mindctrl** [comment]
Authnet is a bit confusing.

I'm looking at transactions I did yesterday before this while testing #1367 , and the transaction says `Captured/Pending Settlement`.  The details show `Transaction Type: | Authorization w/ Auto Capture`

Today, I did one with this and the status is `Authorized/Pending Settlement`. The details on this one just show: `Transaction Type: | Authorization Only`

While looking at [authnet's docs about transaction types](https://support.authorize.net/authkb/index?page=content&id=A510), I see the description for each of those types.

#### AUTH_CAPTURE (Authorize and Capture)

> This is the default transaction type. When using AIM, if the x_type field is not sent to us, the type will default to AUTH_CAPTURE. Simple Checkout uses AUTH_CAPTURE only. The Virtual Terminal defaults to AUTH_CAPTURE unless you select a different transaction type.

> With an AUTH_CAPTURE transaction, the process is completely automatic. The transaction is submitted to your processor for authorization and, if approved, is placed in your Unsettled Transactions with the status Captured Pending Settlement. The transaction will settle at your next batch. Settlement occurs every 24 hours, within 24 hours of your Transaction Cut-off Time.

#### AUTH_ONLY (Authorization Only)

> When an AUTH_ONLY transaction is submitted to Authorize.Net, we send the transaction to your processor for authorization. If approved, the transaction is placed in your Unsettled Transactions with a status of Authorized/Pending Capture. The authorization places the funds on hold with the customer's bank. When the transaction is captured, the funds transfer process will occur. This can be useful in situations where you need to make a sale, but won't be able to ship merchandise for several days. You can authorize the transaction to ensure funds availability, then capture the transaction to obtain the funds upon shipment. AUTH_ONLY transactions are only kept in your Unsettled Transactions for 30 days. If an AUTH_ONLY transaction is not captured for settlement within 30 days, the transaction status will change to Expired, and the funds will not be transferred. To capture a transaction, you can manually log into your Authorize.Net interface and go to your Unsettled Transactions. From there, you can use the Group Capture filter toward to the top of your screen to capture multiple transactions at once, or click the individual Transaction ID of the transaction you would like to capture, and the next screen will provide a Capture button. From a website or billing application, you can submit the x_Type variable, with a value of PRIOR_AUTH_CAPTURE or CAPTURE_ONLY to capture the transaction.

Does that mean if we use `authOnlyTransaction` that we'll have to manually initiate a capture? Or will they do it automatically since it's tied to a subscription? Also worth noting that the original one from yesterday shows that it's tied to a subscription, whereas the one I did today doesn't.

**Comment by nosegraze** [comment]
In this case, the authorization is never actually charged. It's just made to see if a charge will go through later.  So it's basically:

- Authorize credit card for amount.
- If authorization fails (card declined, card invalid, etc.) then the subscription is not created.
- If authorization is successful, subscription is created.
- A few hours later, the subscription processes the _actual_ charge (new transaction, I think).
- After 30 days the initial authorization that wasn't used expires.

Just looking at the source code, this is how EDD Recurring handles it too.

The other option would be to do an actual one-time transaction for the first payment in a subscription (auth and capture). Then set up the subscription but delay the start date by a full period like you would a free trial. So the first payment is a one-time transaction and the subscription doesn't actually kick in until the next full payment.

**Comment by mindctrl** [comment]
I think what we have here is ok, but their UI is a little confusing and I'm just wanting to be sure. It's also unfortunate that we have to wait ~24 hours to see if certain things happen as expected. I'm going to watch this transaction to see what happens tomorrow.
