### ISSUE TITLE
Don't show proration message if proration can't be added

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1241]
Example scenario:

- There's only _one_ active subscription level on the site, so upgrades and downgrades aren't an option.
- The customer is logged in and already has that subscription level and wants to manually renew.
- Proration won't be given to them for a renewal, but the proration message shows up anyway.

**Comment by nosegraze** [comment]
PR: #1423

**Comment by mindctrl** [comment]
Do you foresee this `$exclude_current` being used anywhere else? If not, I think we can achieve the same result, without adjusting these function signatures, by doing a `continue` in the `foreach` loop in `rcp_add_prorate_message()` if `$subscription_level->id == rcp_get_subscription_id()`.

**Comment by nosegraze** [comment]
I feel like I remember doing what you suggested at first, then changing it to this... But I can't remember my reason... So let's do it your way lol.
