### ISSUE TITLE
PayPal Express CANCELURL set to registration page when that may not be the page that was used

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1244]
This can be confusing if the signup actually occurred on a different page containing the `[register_form id="1"]` shortcode but isn't assigned as the registration page in the settings.

In the PayPal Standard gateway, `cancel_return` is just set to `home_url()`

**Comment by pippinsplugins** [comment]
We could set it to the originating page, if detected, then fallback to the home URL or the default registration page.

**Comment by nosegraze** [comment]
PR: #1553
