### ISSUE TITLE
Subscription ID numbers in the admin list are hard to see

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1251]
When hovering over a subscription level to see its ID, it's hard to see the number due to poor contrast.

![image](https://cloud.githubusercontent.com/assets/1254870/26376525/ca4e1056-3fda-11e7-92f3-5ade7adfd990.png)

We should make it easy to see, something like how the Member ID looks.

![image](https://cloud.githubusercontent.com/assets/1254870/26376588/11fb9a2c-3fdb-11e7-96d0-ca2d2f61d0f9.png)

**Comment by nosegraze** [comment]
PR: #1409

I updated subscription levels, discount codes, and payments to make everything consistent:

1. Delete buttons now all use the `.trash` class from core and inherit the red styling from there. (Subscription levels were randomly using a different shade of red.)
2. ID numbers have all been moved to be at the end of row actions.
3. ID numbers all use the same CSS class to have that darker grey colour.

**Comment by mindctrl** [comment]
This looks great with one small issue.

![image](https://user-images.githubusercontent.com/1254870/30117618-bd32bd2e-92ee-11e7-8c86-62994471548c.png)

On the discount code page, I'm seeing a lot of the ID numbers wrapping.

**Comment by nosegraze** [comment]
I tweaked some CSS which should prevent the "ID" and number from getting separated. This at least makes it more readable. We can't avoid the wrapping completely, as it will depend on screen sizes and available column space.

**Comment by mindctrl** [comment]
That didn't make a difference here, even at a width greater than 1500px.

It looks like this is the reason: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.1/includes/css/admin-styles.css#L270-L272

```
.rcp-discounts-name-col {
	width: 190px;
}
```
Removing that entirely seems to help, though it may have some other consequences. I wonder if we need any of the fixed widths there?

**Comment by nosegraze** [comment]
I just tried removing the fixed widths and it forces subscription level and payment actions onto two lines. Discounts and members are fine though.

**Comment by mindctrl** [comment]
@nosegraze ok, I'm good with this for now unless you feel like tweaking this more.

**Comment by nosegraze** [comment]
I can't really reproduce the discount code page issue so I can't think of any other tweaks I'd make.
