### ISSUE TITLE
Remove Email IPN Report feature

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1252]
```php
if( isset( $rcp_options['email_ipn_reports'] ) ) {
	wp_mail( get_bloginfo('admin_email'), __( 'IPN report', 'rcp' ), $listener->getTextReport() );
}
```

`$listener` is undefined.

**Comment by pippinsplugins** [comment]
Let's remove the IPN report entirely. It's a super old feature that really isn't needed, especially as #1103 is added.

**Comment by mindctrl** [comment]
I have seen some customers using it, though I have no idea why they'd want to. I wouldn't mind removing it. If we get some push back on it, we could add it back.

**Comment by nosegraze** [comment]
I've seen quite a few people using it in support, but I am fine with removing it to see if the new debug tool will be sufficient for them. PayPal should store the information in the IPN history anyway so it's not totally inaccessible.

**Comment by pippinsplugins** [comment]
By using the debug class we make the debug / testing method consistent with all gateways. Right now it's this weird feature that is only available for PayPal.

**Comment by nosegraze** [comment]
PR: #1567
