### ISSUE TITLE
Improve access control checks for content filtering

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1253]
We run access checks in `rcp_post_classes()`, `rcp_filter_restricted_content()`, and `rcp_hide_comments()`. These duplicate checks shouldn't be needed, and they cause some filters to run multiple times.

**Comment by mindctrl** [comment]
PR submitted. I ended up with a gnarly merge conflict due to my own stupidity, so this needs more eyeballing than normal from @nosegraze to make sure I didn't bulldoze anything.

**Comment by mindctrl** [comment]
Hmm I may redo this to branch straight off `release/2.9`.

**Comment by nosegraze** [comment]
Haven't looked at the whole thing yet, but at quick glance it looks like the post class behaviour has been changed a bit.

In `master` it works like this:

- Class `rcp-is-restricted` is _always_ added if the post has restrictions (whether the user can access or not).
- Class `rcp-no-access` is added if the post has restrictions and the user cannot access.
- Class `rcp-can-access` is added if the post has restrictions and the user can access.

In the PR:

- Class `rcp-is-restricted` seems to only get added if the user doesn't have access.
- Class `rcp-no-access` works the same as in `master`.
- Class `rcp-can-access` is added to all posts the user has access to, even if they don't have restrictions at all.

So some `rcp_is_restricted_content()` checks are needed.

**Comment by mindctrl** [comment]
I'm going to redo this after lunch, so I'd hold off looking at it.

I knew `rcp-can-access` was different, and was intentional as I wanted to avoid running yet another `rcp_is_restricted_content()` call outside of `can_access()` and ultimately probably doesn't matter (but maybe it does). But I missed the `rcp-is-restricted` bit.

I _really_ hate our access checks right now. This may be better handled when we deal with caching restrictions, but I'll look at it later today. Also I think I duplicated issue #1250 here.
