### ISSUE TITLE
Members can renew/upgrade their current active subscription multiple times

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#1256]
I have a member who's just renewed their membership twice in one day, in quick succession. So they've been charged the full subscription price twice.

If a user has an active subscription, they should be prevented from renewing/upgrading to that subscription level again, at least when it's on the same day (could look at the last_renewed meta?). If they've just renewed or upgraded, the form could throw out an error when it's submitted - "Looks like you already have an active *** subscription. Please try again another time.".

Currently, a member can go renew/upgrade the same subscription over and over again and they will keep getting charged for it.

**Comment by mindctrl** [comment]
@thomasfw did it create more than one subscription or just extend the expiration date of the existing subscription?

**Comment by pippinsplugins** [comment]
I could be wrong but I believe we used to prevent people from re-purchasing the same level already on their account if their subscription was active. This turned out to cause more issues than it prevented so we removed it.

**Comment by nosegraze** [comment]
Somewhat related: we have a closed issue in `2.9` that fixed an expiration date calculation problem with manual renewals: https://github.com/restrictcontentpro/restrict-content-pro/issues/1208

Once that fix is in place and the expiration date is properly extended another full period, I don't think being allowed to renew multiple times is a problem. People will actually get the extra time they're paying for.

**Comment by thomasfw** [comment]
Thanks, looks like #1208 resolves this :)
