### ISSUE TITLE
Improve text on subscription cancellation notice

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1260]
When cancelling a subscription on the `[subscription_details]` page, the message says:

`Your profile has been successfully cancelled.`.

I think _profile_ is the wrong user-facing word to use here.

I think it would be better to use `subscription`, or even better `Your <subscription name here> subscription has been cancelled.`, which will make it ready when we implement multiple subscriptions.

**Comment by nosegraze** [comment]
PR: #1403
