### ISSUE TITLE
Downgrading from paid to free doesn't cancel paid subscription

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1263]
Customer reported a variation of this and I replicated it.

Tested in Stripe.

Changing from a paid sub to a free sub does not cancel the paid subscription.

Related: #442

**Comment by nosegraze** [comment]
Maybe we should remove the subscription cancellations from the gateway classes and just have it once in `rcp_add_user_to_subscription()`. Try cancelling the existing subscription before adding the new one.

**Comment by nosegraze** [comment]
PR: #1454
