### ISSUE TITLE
Consider explicitly stating Stripe API version support

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#1268]
As you probably know, Stripe [updates their API rather frequently](https://stripe.com/docs/upgrades), but active Stripe accounts are locked to an API version, and must be manually upgraded to the latest API version.

This can create some uncertainty for users of RCP & Stripe, as we (developers) generally encourage folks to upgrade `$thing` whenever possible – but RCP doesn't explicitly state the latest version of the Stripe API it's compatible with anywhere, as far as I can tell.

I'm sure in most cases, RCP will remain compatible with whatever the latest Stripe API version is, since most of their updates don't break backcompat. However, it only takes one time for a user of RCP to upgrade their Stripe API version, break something, and lose confidence.

Furthermore, when upgrading your Stripe API version, you're shown this message:

> Upgrading your API version may break your implementation. Be sure to read the list of changes made since your version.

I propose that we add some information to RCP to indicate what the most recent version of the Stripe API it has been tested against is. The easy place would be in the readme. A more sophisticated approach might be to add some information to the Stripe section of the Payments tab on RCP's settings page. This could include an account's current version (assuming Stripe's API exposes that), as well as information about the latest supported version.

**Comment by nosegraze** [comment]
I like this idea. I've gotten a few support tickets where people were hesitant to update their API version. We could also just include a note somewhere in the Stripe docs.

**Comment by pippinsplugins** [comment]
I'd rather we update documentation, otherwise we could be fully compatible with the latest version but RCP hasn't been updated in a while so the version shown in RCP is incorrect.

**Comment by nosegraze** [comment]
Added to the documentation here: http://docs.restrictcontentpro.com/article/1549-stripe#api-version :)

**Comment by tnorthcutt** [comment]
🎉 thanks for doing that!
