### ISSUE TITLE
Login redirect doesn't respect the redirect_to parameter

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1269]
With login redirect **disabled**, if you're logged out and try to access a URL like this:

`http://rcp-dev.dev/wp-admin/admin.php?page=rcp-member-levels&edit_subscription=103`

you get redirected to:

`http://rcp-dev.dev/wp-login.php?redirect_to=http%3A%2F%2Frcp-dev.dev%2Fwp-admin%2Fadmin.php%3Fpage%3Drcp-member-levels%26edit_subscription%3D103&reauth=1`

and when you log in, you're directed to the page you originally requested.

When login redirect is **enabled**, you get redirected to whatever page you have saved in the settings, but you lose the `redirect_to` value and do not get redirected to the page you originally requested.

**Comment by pippinsplugins** [comment]
@mindctrl I'd like to see this fixed sooner than later so bumping it up to 2.9.1.

**Comment by nosegraze** [comment]
PR: #1271

**Comment by mindctrl** [comment]
Works great. Will merge when tests finish.

**Comment by mindctrl** [comment]
HHVM tests are failing because they're no longer supported. We can ignore those. I've already removed HHVM from the `release/2.9` branch.

**Comment by mindctrl** [comment]
Merged!

**Comment by pippinsplugins** [comment]
Woot!

**Comment by pippinsplugins** [comment]
Looks like we need to look at both `redirect_to` and `redirect`. This is the URL that I'm getting when clicking on a payment ID from inside Help Scout on the EDD site:

https://easydigitaldownloads.com/your-account/?redirect=https%3A%2F%2Feasydigitaldownloads.com%2Fwp-admin%2Fedit.php%3Fpost_type%3Ddownload%26page%3Dedd-payment-history%26view%3Dview-order-details%26id%3D1081934

`redirect` is actually coming from RCP itself, here: 

```php
/**
 * Redirects users to the custom login page when access wp-login.php
 *
 * @return void
 */
function rcp_redirect_from_wp_login() {
	global $rcp_options;

	if( isset( $rcp_options['hijack_login_url'] ) && isset( $rcp_options['login_redirect'] ) ) {

		if ( ! empty( $_GET['redirect_to'] ) ) {
			$login_url = add_query_arg( 'redirect', urlencode( $_GET['redirect_to'] ), get_permalink( $rcp_options['login_redirect'] ) );
		} else {
			$login_url = get_permalink( $rcp_options['login_redirect'] );
		}

		wp_redirect( esc_url_raw( $login_url ) ); exit;
	}
}
add_action( 'login_form_login', 'rcp_redirect_from_wp_login' );
```

**Comment by nosegraze** [comment]
Closing this, as it ended up being an EDD bug.
