### ISSUE TITLE
"All" role restriction incorrectly being run through user_can()

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1274]
We run through `user_can()` here:

```php
if ( $ret && ! empty( $user_level ) && 'All' != $user_level ) {
    if ( ! user_can( $this->ID, strtolower( $user_level ) ) ) {
        $ret = false;
    }
}
```

So we're checking `All`, but in https://github.com/restrictcontentpro/restrict-content-pro/issues/158 it was switched to lowercase `all` so it's not matching. Just needs another `strtolower()` around `$user_level`.

**Comment by nosegraze** [comment]
PR: #1275

**Comment by pippinsplugins** [comment]
PR looks good.
