### ISSUE TITLE
Need to save customer in Stripe before attempting charge

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1277]
Caused by https://github.com/restrictcontentpro/restrict-content-pro/pull/1195 . We need to run `$customer->save()` to save the new card details before attempting a charge.

**Comment by nosegraze** [comment]
PR: #1278

**Comment by nosegraze** [comment]
To test the problem (before/after PR):

1. You want to register with an existing customer that already has a Stripe profile.
2. Delete any saved cards from the customer.
3. Submit RCP registration.
4. Before the change in this PR you'll get an error `Cannot charge a customer that has no active card`

**Comment by pippinsplugins** [comment]
PR looks good to me.

**Comment by mindctrl** [comment]
Not sure if it's an API version difference or I was doing it wrong, but I wasn't able to replicate the bug. But this PR makes sense and works fine. Merged.
