### ISSUE TITLE
Update Authorize.net to use webhooks instead of Silent Post URL

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1280]
It looks like webhooks are replacing Silent Post.

Per their [documentation](https://support.authorize.net/authkb/index?page=content&id=A609):

> Important Note: While Silent Post is a supported service, we strongly recommend that you use Webhooks to receive transaction updates and other event notifications from the Authorize.Net Payment Gateway. Visit http://developer.authorize.net/api/reference/features/webhooks.html for more information on Webhooks

On the [webhook docs](http://developer.authorize.net/api/reference/features/webhooks.html) page:

> Note: Webhooks notifications replace the Silent Post method of receiving notifications.

At the moment I'm not clear on whether or not they send webhooks in sandbox mode, but if so that would be great since they do not send Silent Posts for sandbox transactions.

**Comment by nosegraze** [comment]
Got a request for this.

**Comment by nosegraze** [comment]
Closing this to handle it in the new add-on: https://github.com/restrictcontentpro/rcp-authorize-net/issues/3
