### ISSUE TITLE
Rest API Commenting issue

### ISSUE THREAD

**Issue by mrbobbybryant** [restrictcontentpro/restrict-content-pro#1281]
I have a site which uses the REST API to allow people to make comments. I've made the required changes in the admin, to allow "member" users to post comments. However, `rcp_post_password_required_rest_api` seems to put a blanket password restriction on all posts. This results in comments posted by members without the `edit_post` capability to fail.

Unregistering this hook does fix the problem, but that results in all the protected posts showing up in the REST API.

**Comment by mrbobbybryant** [comment]
For now I have added the following code to my repo.
```
function radiate_rcp_post_password_required_rest_api( $required, $post ) {
	if( DEFINED( 'REST_REQUEST' ) &&
        REST_REQUEST && rcp_is_restricted_content( $post->ID ) &&
        ! rcp_user_can_access( wp_get_current_user(), $post->ID ) ) {
		$required = true;
	}

	return $required;

}

remove_filter( 'post_password_required', 'rcp_post_password_required_rest_api' );
add_filter( 'radiate_rcp_post_password_required_rest_api', 'rcp_post_password_required_rest_api', 10, 2 );```

It will need testing, but this could be a potential solution.

**Comment by mindctrl** [comment]
This was introduced in #1046 per recommendations from a member of the WP REST API team. In hindsight this seems like a less than ideal way of dealing with it. We should explore a better option.

I've seen another customer experience an issue where fetching content via the REST API (using a search/filtering plugin) resulted in WP thinking the content required a password - which resulted in all the excerpts saying the post was password protected when it wasn't.

**Comment by mindctrl** [comment]
@mrbobbybryant with regards to your solution there, I don't think it will work.

`rcp_user_can_access` takes the user ID as the first parameter. You're passing the full user object. 

But more importantly I don't think `wp_get_current_user()` will work with all the authentication methods available.

**Comment by mindctrl** [comment]
Confirmed that this is causing issues with FacetWP, which fetches results via the WP REST API. It causes the excerpts/content in the search results to say `There is no excerpt because this is a protected post`.

**Comment by nosegraze** [comment]
The logic behind using this was that it was recommended we do something to cause the REST API to return a proper unauthorized response (rather than a few of the other hacky methods we talked about) and that handled removing comments automatically. Annoyingly, they don't actually have a filter to allow you to control that so you have to use a core method like password protection to actually throw the error.

I'm definitely open to alternatives or modifications, just offering that explanation. :)

**Comment by markjaquith** [comment]
@mrbobbybryant's code wouldn't work as written, but it seemed like the right idea.

Here's a working snippet:

```php
add_action( 'init', function() {
  remove_filter( 'post_password_required', 'rcp_post_password_required_rest_api' );

  add_filter( 'rcp_post_password_required_rest_api', function( $required, $post ) {
    if (
      defined( 'REST_REQUEST' ) &&
      REST_REQUEST &&
      rcp_is_restricted_content( $post->ID ) &&
      ! rcp_user_can_access( wp_get_current_user(), $post->ID )
    ) {
      $required = true;
    }

  return $required;
  }, 10, 2 );
});
```
