### ISSUE TITLE
Composer/Installers version incompatible with Bedrock

### ISSUE THREAD

**Issue by fourstacks** [restrictcontentpro/restrict-content-pro#1284]
I'm trying to install RCP via composer in a Bedrock project.  The version of composer/installers in composer.json is set at 1.0.6 and the version included with bedrock is at 1.2.0 so composer throws a compatibility error.  Proposing a PR to fix this

**Comment by tnorthcutt** [comment]
Closing this as the related PR is also closed: https://github.com/restrictcontentpro/restrict-content-pro/pull/1285
