### ISSUE TITLE
Improve error messaging when adding/updating subscription levels fails

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1288]
Right now it just show a generic message. It might be good to set some errors with `rcp_errors()`, or just simply `wp_die()` with a message, so we can give people some details about why it fails.

**Comment by nosegraze** [comment]
PR: #1608

**Comment by mindctrl** [comment]
Works great. We'll need to announce this change to developers in our 3.0 release notes or somewhere. Changing the return type from `false` to `WP_Error` could break some things.
