### ISSUE TITLE
Improve payment display on Member edit page

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1291]
When editing a member, the last 20 payments for that member are shown at the bottom. But, there's nothing to indicate it's limited to 20, so it's a bit confusing.

I propose we add some text that says something like "Most recent payments" or something along those lines, along with a link that takes you to the Payments page with search results listing all payments for that member.

Something like this, maybe better looking:

![image](https://user-images.githubusercontent.com/1254870/27348659-d6085d40-55c2-11e7-9aea-b23e4d61961c.png)

**Comment by nosegraze** [comment]
Yes! I've been thinking this too.

**Comment by nosegraze** [comment]
I'm going to do this in #1003

**Comment by mindctrl** [comment]
Closing this in favor of #1003
