### ISSUE TITLE
Account actions: display the action links in one line

### ISSUE THREAD

**Issue by ramiy** [restrictcontentpro/restrict-content-pro#1294]
**Current:**

> ![actions-1](https://user-images.githubusercontent.com/576623/27559375-039b7660-5ac9-11e7-8db7-1e9b780e529a.png)

**New:**

> ![actions-2](https://user-images.githubusercontent.com/576623/27559380-0c4adb70-5ac9-11e7-8e1c-4d9d8bad6eb5.png)

Currently the "actions" col has two actions with a line break (BR) between them. I suggest to display them in one line separated with by "|" char between them.

**Comment by mindctrl** [comment]
That does look better, but links separated by a `|`, or another character, probably won't look great on mobile.

![image](https://user-images.githubusercontent.com/1254870/27562336-254d91e6-5a9a-11e7-80b2-d24612ccac42.png)

With varying screen widths, font sizes, and link text lengths (translations, different link types, the filters on the links, etc), it's likely a lot of little edge cases show up where it doesn't look attractive.

I'd recommend just customizing the template to do it.

**Comment by ramiy** [comment]
Can we change the separator with a filter? It's simpler to use a short filter than changing the entire template.

**Comment by nosegraze** [comment]
You could use the `rcp_subscription_details_actions` filter and do a `str_replace()` to change `<br/>` into ` | `.
