### ISSUE TITLE
Incorrect expiration calculation when upgrading with 0 proration credits, no auto renew

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1300]
This is when auto renew is disabled.

When a user is upgrading _with_ proration credits, the new expiration date is calculated from today. This is fine.

When a user is upgrading _without_ proration credits (due to proration being disabled or the first purchase being with a 100% off discount), the expiration date is extended from the existing one.

Am I correct in thinking that an upgrade/downgrade expiration date should always be calculated from the current day, regardless of proration credits? The only time an expiration date should be extended from the existing one is during a renewal.

As it is currently, you could do the following (assuming proration is disabled):

- Signup for $10/year plan, expiration date is June 30, 2018.
- Immediately upgrade to $50/year plan, expiration date is extended to June 30, 2019.
- You've now gotten the more expensive plan for two years but only paid $60 for it.

**Comment by pippinsplugins** [comment]
I don't think proration should affect the expiration calculation in any way.,

**Comment by nosegraze** [comment]
This is no longer an issue. I think it got fixed via a similar issue in `2.9` or shortly after.
