### ISSUE TITLE
Add usage tracking

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1304]
We've talked about this in our meetings. This will be useful for determining which add-ons are the most commonly used.

See https://github.com/AffiliateWP/AffiliateWP/issues/1498

**Comment by nosegraze** [comment]
What RCP data do we want to collect? (Other than the standard stuff like PHP version, active plugins, etc.)

I'm thinking:

- Auto renew setting.
- Currency.
- Enabled gateways.
- Number of members.
- Number of subscription levels.

What else?

**Comment by pippinsplugins** [comment]
Here's what AFFWP tracks:
```php
	/**
	 * Retrieves site data (plugin versions, integrations, etc) to be sent along with the license check.
	 *
	 * @since 1.9
	 * @access public
	 *
	 * @return array
	 */
	public function get_site_data() {

		$data = array();

		$theme_data = wp_get_theme();
		$theme      = $theme_data->Name . ' ' . $theme_data->Version;

		$data['php_version']  = phpversion();
		$data['affwp_version']  = AFFILIATEWP_VERSION;
		$data['wp_version']   = get_bloginfo( 'version' );
		$data['server']       = isset( $_SERVER['SERVER_SOFTWARE'] ) ? $_SERVER['SERVER_SOFTWARE'] : '';
		$data['install_date'] = get_post_field( 'post_date', affwp_get_affiliate_area_page_id() );
		$data['multisite']    = is_multisite();
		$data['url']          = home_url();
		$data['theme']        = $theme;

		// Retrieve current plugin information
		if( ! function_exists( 'get_plugins' ) ) {
			include ABSPATH . '/wp-admin/includes/plugin.php';
		}

		$plugins        = array_keys( get_plugins() );
		$active_plugins = get_option( 'active_plugins', array() );

		foreach ( $plugins as $key => $plugin ) {
			if ( in_array( $plugin, $active_plugins ) ) {
				// Remove active plugins from list so we can show active and inactive separately
				unset( $plugins[ $key ] );
			}
		}

		$data['active_plugins']   = $active_plugins;
		$data['inactive_plugins'] = $plugins;
		$data['locale']           = get_locale();
		$data['integrations']     = affiliate_wp()->integrations->get_enabled_integrations();
		$data['affiliates']       = affiliate_wp()->affiliates->count( array( 'number' => -1 ) );
		$data['creatives']        = affiliate_wp()->creatives->count( array( 'number' => -1 ) );
		$data['payouts']          = affiliate_wp()->affiliates->payouts->count( array( 'number' => -1 ) );
		$data['referrals']        = affiliate_wp()->referrals->count( array( 'number' => -1 ) );
		$data['consumers']        = affiliate_wp()->REST->consumers->count( array( 'number' => -1 ) );
		$data['visits']           = affiliate_wp()->visits->count( array( 'number' => -1 ) );
		$data['referral_rate']    = $this->get( 'referral_rate' );
		$data['rate_type']        = $this->get( 'referral_rate_type' );

		return $data;
	}
```

That is sent along in the `check_license` request here: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/settings/class-settings.php#L1397

**Comment by mindctrl** [comment]
Definitely want the PHP and WP version info. Very curious how many of our customers are still on old 5.3 stuff.

**Comment by nosegraze** [comment]
Started here: #1322

**Comment by pippinsplugins** [comment]
What about including payment counts? Not dollar numbers, just the raw records count?

**Comment by nosegraze** [comment]
👍 All payments or just complete ones?

**Comment by pippinsplugins** [comment]
All.

**Comment by nosegraze** [comment]
As I noted in Slack, the gateway graphs aren't accurate due to the serialized data and `LIKE` queries, but otherwise this and the plugin is working well for me. (Pushed one minor fix to the plugin though.) I tested with two tracking requests from one site and verified that the site info updates correctly, logs get recorded, graphs get updated, etc.

**Comment by pippinsplugins** [comment]
@nosegraze I think I missed the slack comment. Why does the serialized array make gateway count inaccurate?

**Comment by nosegraze** [comment]
Actually, the gateways are comma-separated - not serialized, but the problem is still the same. So many of the gateway names contain the same words so the `LIKE` matches aren't exact and may return partials.

Example:

Checking for `Stripe` usage returns both `Stripe` and `Stripe Checkout`.
Checking for `PayPal` usage returns `PayPal` and `PayPal Express`.

So in my test site I had `Stripe` and `PayPal` (standard) checked on for gateways, but the graph is showing that I have `1` count for Stripe, Stripe Checkout, PayPal, and PayPal Express.

We could consider storing them slightly differently in our tracking plugin than they are in RCP. So changing `PayPal` to `PayPal Standard` and `Stripe` to `Stripe Standard`.

**Comment by pippinsplugins** [comment]
Let's go ahead and store them in separate columns then. We'll just need to remember to update our tracking DB anytime we introduce new gateways (rarely).

**Comment by pippinsplugins** [comment]
Server-side of this is now activated on restrictcontentpro.com
