### ISSUE TITLE
PayPal Express: error in confirm template when get_checkout_details() returns WP_Error

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1305]
`RCP_Payment_Gateway_PayPal_Express::get_checkout_details()` can return a `WP_Error` object or possibly even `false`, but in the `paypal-express-confirm.php` template we always assume it's an array. This can result in:

```
PHP Fatal error: Uncaught Error: Cannot use object of type WP_Error as array
```

**Comment by pippinsplugins** [comment]
I'm seeing this in the EDD PayPal Express gateway too.

**Comment by pippinsplugins** [comment]
Apparently moving wp_remote_get() to wp_remote_post() fixes this.

**Comment by nosegraze** [comment]
Let's update it then. I don't know if this is a permanent change on PayPal's end but the problem has been there long enough that it's starting to annoy customers (understandably).

**Comment by nosegraze** [comment]
PR: #1316
