### ISSUE TITLE
Add "Mark As Deleted" To Pending Members Bulk Actions

### ISSUE THREAD

**Issue by braddalton** [restrictcontentpro/restrict-content-pro#1306]
This will help bulk remove spam registrations so they don't get listed with legitimate expired and cancelled users.

**Comment by mindctrl** [comment]
@braddalton I think "Mark as Spam" could imply the system learns from the action, like email clients do when you mark an email as spam. We have a reCaptcha option for helping with spam registrations. Have you considered using that?

**Comment by pippinsplugins** [comment]
I agree with @mindctrl's assessment. If we provide a mark as spam option, it also needs to have a "spam learning" system, which is far beyond the scope of Restrict Content Pro.

**Comment by braddalton** [comment]
@mindctrl Yes but it can make new registrations harder sometimes which is why i deactivated it. Now i need to delete Pending spam registrations rather than mark them as Expired or Cancelled because the they remain users and remain listed as expired or cancelled even though they've never been active. I just want to completely bulk delete them from pending.

**Comment by nosegraze** [comment]
Sounds like a job for https://github.com/restrictcontentpro/restrict-content-pro/issues/1177

**Comment by mindctrl** [comment]
Agreed on #1177. Closing this one in favor of that. Thanks @braddalton
