### ISSUE TITLE
Remove Alipay support from Stripe Checkout

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1310]
It looks like they're removing support for it in Checkout. See https://github.com/easydigitaldownloads/edd-stripe/issues/241.

More info:
Appears to be supported in Sources.

https://stripe.com/blog/stripe-alipay
> Update: We’ve updated our Alipay integration on Stripe. Alipay is now available on our [Sources platform,](https://stripe.com/docs/sources) see our announcement [here](https://stripe.com/blog/hong-kong).

**Comment by mindctrl** [comment]
From Stripe support:

>We have removed Alipay from Stripe Checkout in favor of integrating one unified API using sources, which is a single integration path using any supported method. You can read more about this through the Stripe blog:

> https://stripe.com/blog

> As this payment method is now available to all Stripe users, Alipay can be easily activated through the Payments tab in your Dashboard settings:

> https://dashboard.stripe.com/account/payments/settings

> You'll then need to click `Activate` next to the payment method and fill out the associated form, including all required details. After you've submitted this form, the payment method will move from pending to live within 24 hours. Once live, you'll be free to begin live processing. That said, should the payment method remains in ""pending"" state more than 24 hours, please let us know. To get started on your integration, feel free to look though our documentation:

> https://stripe.com/docs/sources/alipay

**Comment by nosegraze** [comment]
PR: #1465

We will also need to remove Alipay references from the documentation and website.
