### ISSUE TITLE
Add links to Edit/View RCP pages in settings

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1312]
![rcp-edit-view-page](https://user-images.githubusercontent.com/6324272/28117736-859fd176-6706-11e7-81f8-d178d7d6882c.png)

I saw another plugin doing this and it was useful. :)

**Comment by pippinsplugins** [comment]
Yes please!

**Comment by nosegraze** [comment]
PR: #1401
