### ISSUE TITLE
Braintree isn't a valid case for rcp_can_member_cancel returning true by default.

### ISSUE THREAD

**Issue by VesterDe** [restrictcontentpro/restrict-content-pro#1313]
[The function](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.3/includes/member-functions.php#L1223) checks if the gateway is Stripe, Paypal or 2Checkout and generates the cancellation link if so (or rather, returns true, which causes it to happen).

Why isn't `rcp_is_braintree_subscriber` used as well for the check? I'm solving this by hooking into the filter, but I didn't know about it and spent quite a bit of time before I realised what the problem was.

I'd like to know for instance if there's some arguable reason to not display the link for Braintree by default which I'm not aware of and may cause problems for my use case in the future.

If not, I can make a pull request and include it.

Thank you.

**Comment by mindctrl** [comment]
@VesterDe this has been updated in newer version of RCP. You linked to version 2.6.3. The latest is 2.8.6. Updating to the latest should work just fine with Braintree.

**Comment by VesterDe** [comment]
Oh, I have absolutely no idea how I managed that...

Sorry for that.

And thanks.
