### ISSUE TITLE
Authorize.net: membership doesn't renew after free trial

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1315]
In the webhook, we only renew the membership if:

```php
if ( intval( $_POST['x_subscription_paynum'] ) > 1 )
```

But when a free trial expires and the first payment comes in, that would be the first payment. So we should instead be doing something like:

```php
if ( intval( $_POST['x_subscription_paynum'] ) > 1 || $member->is_trialing() )
```

**Comment by mindctrl** [comment]
Will this still be an issue after #1000, since we'll be creating $0 payments?

**Comment by mindctrl** [comment]
Oh my bad. I couldn't see the code you posted.

![image](https://user-images.githubusercontent.com/1254870/28427735-3345588e-6d45-11e7-8c03-10c3e47bf73a.png)

Just saw the code in email though and see that the count is coming from the webhook data and not RCP.

**Comment by pippinsplugins** [comment]
Seems like we should go ahead and include this in 2.9. It's a very minor change with significant side effects.

**Comment by nosegraze** [comment]
PR: #1318

**Comment by nosegraze** [comment]
I sent this patch to the customer who reported it and she just confirmed it fixed the problem. :)

**Comment by pippinsplugins** [comment]
Thanks, merged!
