### ISSUE TITLE
Stripe Checkout args are inconsistent on [register_form] and [register_form_stripe]

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1317]
For example, in `[register_form_stripe]` we set an image:

```php
if ( empty( $data['data-image'] ) && $image = get_site_icon_url() ) {
	$data['data-image'] = $image;
}
```

We don't do that in `[register_form]`. I think we should try to make them pretty much the same between the two options.

**Comment by nosegraze** [comment]
PR: #1471 Added the image.

The other inconsistency is that in `[register_form_stripe]` the `name` parameter uses the name of the site. But in `[register_form]` we use the name of the selected subscription level. Anyone see a reason we shouldn't update `[register_form_stripe]` to use the name of the subscription level as well?

**Comment by mindctrl** [comment]
@nosegraze left a comment on PR.

re: `name` parameter, I agree with you that they should be the same.
