### ISSUE TITLE
Shortcode login_form is not using class attribute in rcp_login_form_fields nor login.php

### ISSUE THREAD

**Issue by luke-au** [restrictcontentpro/restrict-content-pro#1319]
The shortcode `login_form` accepts the attribute **class** however when passed to the `rcp_login_form_fields` function it does not get used nor in the **login.php** template file.

- Shortcode [login_form](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/shortcodes.php#L354).
- Function [rcp_login_form_fields](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/member-forms.php#L11).
- Template [login.php](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/templates/login.php#21).

**Comment by nosegraze** [comment]
PR: #1427
