### ISSUE TITLE
rcp_user_can_access fails on 404 because post ID is 0

### ISSUE THREAD

**Issue by luke-au** [restrictcontentpro/restrict-content-pro#1324]
If I'm not mistaken I think the function `rcp_user_can_access( )` falls over on a 404 result because the `$post->ID` is 0 also when a query used within a template like a header which is also shown on a 404 result if that calls the `rcp_user_can_access( )` function using a `$post_id` of 0 is defaults back to `$post->ID` of the current post which is 0 on a 404 result.

**Comment by nosegraze** [comment]
Hi @luke-au :)

Can you just clarify for me how you're reproducing this? Are you inserting the function yourself in a template somewhere or is this being caused with a default RCP setup?

**Comment by luke-au** [comment]
Hi @nosegraze 

The function was inserted in a theme template. 
I injected members menu items into the header menu with a filter querying if the pages still existed based on their slug and then getting the post ID from the object, and then finally checking if that current user can access the page but I hadn't realised an error when checking the response to the page query so it was ultimately sending `rcp_user_can_access( get_current_user_id(), 0 )` however on non-404 pages that was falling back to that page's post ID whereas on the 404 page which has no post ID falling back to 0 again caused the error to appear. 

I thought maybe it might be worth considering adding another fallback on the `rcp_user_can_access` function if that second step failed or just detect 404 pages.

**Comment by nosegraze** [comment]
Just to clarify, here's what I see as the main problem:

If someone uses `rcp_user_can_access()` (no parameters) on a page like a 404 that doesn't have a global `$post` set, then we get this error:

```
PHP Notice:  Trying to get property of non-object in C:\wamp\www\rcp\wp-content\plugins\restrict-content-pro\includes\member-functions.php on line 427
```

So that being said, I'm happy adding an extra check somewhere in here:

```php
if( empty( $post_id ) ) {
	global $post;
        // We should check to make sure $post is an object.
	$post_id = $post->ID;
}
```

I guess we should probably default to a `true` response if we can't obtain a post ID.

**Comment by nosegraze** [comment]
PR: #1408
