### ISSUE TITLE
Stripe: Renewal payment failed email sent during registration when card is declined

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1325]
To reproduce:

1. Register for a new subscription via Stripe.
1. Use `4100000000000019` for test card that gets declined.
1. Make sure recurring is _off_.
1. You'll get a `wp_die()` screen with an error.
1. You will receive the renewal payment failed email.

We send the email on the `charge.failed` webhook but the example [here](https://stripe.com/docs/recipes/sending-emails-for-failed-payments) uses `invoice.payment_failed`. Not sure if that would fix the problem but it's worth a look.

**Comment by pippinsplugins** [comment]
Pretty sure we need to use `invoice.payment_failed` and only send the email when the invoice is tied to a subscription.

**Comment by nosegraze** [comment]
PR: #1410
