### ISSUE TITLE
Remove current status from renewal log to avoid 'expired' status change

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1330]
In `RCP_Member::get_status()` we check the user's expiration and update the status to `expired` if necessary:

```php
// double check that the status and expiration match. Update if needed
if( $status == 'active' && $this->is_expired() ) {

	rcp_log( sprintf( 'Expiring member %d via get_status() method. Expiration Date: %s; Subscription Level: %s', $this->ID, $this->get_expiration_date(), $this->get_subscription_name() ) );

	$status = 'expired';
	$this->set_status( $status );

}
```

I'd kind of like to introduce a new parameter to `get_status()` that allows you to bypass this behaviour.

A customer sent me this member notes log:

```
August 1, 2017 02:02:21 - Member's status changed from active to expired
August 1, 2017 02:02:21 - Member's expiration changed from 2017-07-31 23:59:59 to 2017-08-31 23:59:59
August 1, 2017 02:02:21 - Member's status changed from expired to active
```

Check the timestamps. This happened during a renewal. The status went to expired, then back to active all in the same second. This is in the `2.9` beta. I'm pretty sure this happened because `RCP_Member::renew()` has this line which gets the user's status:

```php
rcp_log( sprintf( 'Starting membership renewal for user #%d. Subscription ID: %d; Current Expiration Date: %s; Current Status: %s', $this->ID, $this->get_subscription_id(), $this->get_expiration_date(), $this->get_status() ) );
```

I _think_ that's what triggered the expiry in this case. That would be a perfect scenario where we want to get the user's status but not actually update it to expired because we're about to renew the account anyway.

---

I'd love to squeeze this into `2.9` because the above scenario is actually caused by the `2.9` update.

**Comment by mindctrl** [comment]
Ideally `get_status()` wouldn't do anything but what its name says it does. It's already a code smell to have it doing a status change, but since it's been there for quite some time and is a great fallback for when crons fail or haven't run yet, it should probably stay. Adding additional complexity to `get_status()` feels wrong though.

What if we simply don't show the status in that "Starting membership" log entry?

**Comment by nosegraze** [comment]
To add to what you said, another small annoyance about having the update in there at all is that in the cron we allow for like a 1-2 day grace period before marking people as expired. But this function ignores that grace period, which is a little inconsistent.

I am fine with removing the status in the log entry.

**Comment by mindctrl** [comment]
Ah yeah, good point on the difference there.

👍 to removing the status from that log entry. If it turns out to be an issue in other areas, we can always take a look at it then.

**Comment by pippinsplugins** [comment]
:+1: from me.

**Comment by nosegraze** [comment]
Sneaking this into `2.9` :P 

PR: #1336
