### ISSUE TITLE
Authorize.net transaction IDs linked to wrong gateway

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1331]
This may be fixed in 2.9 already, but just in case I'm logging it for 2.9.1.

It seems that somewhere along the way, transaction IDs for Authorize.net are missing the `anet_` prefix. Because of this, the transaction IDs are linked to 2checkout.com instead of authorize.net.

Ticket: https://secure.helpscout.net/conversation/409956448/64429/?folderId=841781

**Comment by nosegraze** [comment]
PR: #1373
