### ISSUE TITLE
PayPal IPN overrides payment transaction ID

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1332]
As discussed in our meeting, the `subscr_signup` IPN doesn't have a transaction ID, which can result in the ID being deleted from the payment.

**Comment by nosegraze** [comment]
Also need to mark members as recurring.

**Comment by nosegraze** [comment]
PR: #1334

**Comment by pippinsplugins** [comment]
PR looks good.
