### ISSUE TITLE
Add body classes to registered pages

### ISSUE THREAD

**Issue by cklosowski** [restrictcontentpro/restrict-content-pro#1342]
When applicable, a body class being added to the pages that are registered in the settings would make theming easier.

**Comment by pippinsplugins** [comment]
Related #587

**Comment by pippinsplugins** [comment]
See potential concerns on https://github.com/restrictcontentpro/restrict-content-pro/issues/587#issuecomment-265165566

**Comment by mindctrl** [comment]
I think this will be fine since it's not doing any restriction checks, though I'm not sure we need a filter in there since body_class is already filterable anyway. Anyone doing custom stuff can filter that already.

**Comment by mindctrl** [comment]
I updated this, and performance isn't an issue since it only checks the settings and the current page being shown. But now that I'm thinking about it, we haven't had any other requests for it. This could be a snippet in the library instead and we could always add it officially if we do get requests. Thoughts @nosegraze @pippinsplugins ?

**Comment by nosegraze** [comment]
I'm fine with either way.

Most people probably won't need this, but at the same time it's a super simple thing to add so I don't see any harm in us adding it anyway.

**Comment by mindctrl** [comment]
I agree that most people won't need it, since they're not asking for it. Most people probably target the classes in the markup output by the shortcodes. I vote we don't add it, since we usually don't add things most people don't need.

**Comment by mindctrl** [comment]
Added to library: https://github.com/restrictcontentpro/library/commit/8b0da38b18b8ce23924fd9466401d70ddae5dcf6
