### ISSUE TITLE
No default value for "Members of Subscription Levels" radios

### ISSUE THREAD

**Issue by cklosowski** [restrictcontentpro/restrict-content-pro#1346]
When first enabling Content Restriction for a page and choosing `Members of Subscription Level(s)`, the radio buttons that load have no default value, so if they are saved without choosing one, a PHP Notice is thrown:
![No default selected](https://cl.ly/0H462c1O020F/Image%202017-08-13%20at%209.00.08%20AM.public.png)

![PHP Notices](https://cl.ly/0M1Z3y3t3S2X/Screen%20Shot%202017-08-13%20at%209.04.35%20AM.png)

This only happens on the first save attempt, subsequent saves of the same page does not give the error.

**Comment by nosegraze** [comment]
PR: #1429
