### ISSUE TITLE
Some email template tags not working

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1360]
When signing up for an auto-renewing subscription, some of the email template tags do not work. So far, the ones I'm aware of are:
- `%subscription_name%`
- `%subscription_key%`

These are missing in the active subscription email to both admin and member. In the payment received email, the `%subscription_key%` is still blank.

---
Also, when signing up for a sub that doesn't renew, both `%subscription_name%` and `%subscription_key%` are empty in the payment received email, but not the active sub email.

---
When upgrading from non-recurring to recurring, the active sub email to member and admin have the old subscription name and key. The payment received key has the correct info.

**Comment by mindctrl** [comment]
This apparently affects the `%expiration%` tag too.

**Comment by nosegraze** [comment]
For the payment received email, I believe we just need to increase the priority in the hook so that it fires _after_ the subscription is activated.

**Comment by mindctrl** [comment]
@nosegraze see any issues with this workaround for now? Didn't open a PR yet.

**Comment by nosegraze** [comment]
Changing the priority should be all we need to fix the "payment received" email. I don't see any problems with that.

For the activation email we'll need to do what we discussed in Slack and fully complete the payment in the process signup method in the gateway instead of the webhook.

**Comment by flowdee** [comment]
Would be happy to see the fix soon too 👍

**Comment by nosegraze** [comment]
PR: #1383
