### ISSUE TITLE
Incorrect "subscription renewed" note on new signup

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1365]
From here: https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/member-functions.php#L1500-L1503

**Comment by mindctrl** [comment]
Let's see if we can get this in 2.9.1 to keep the support requests down.

We have one report of it here: https://secure.helpscout.net/conversation/415796367/65010/?folderId=841776

**Comment by nosegraze** [comment]
As noted in Slack, this is connected to https://github.com/restrictcontentpro/restrict-content-pro/issues/1360

It happens in Stripe because we manually set up subscription status and level ID to avoid a few second delay in account activation, but then it gets set again when the payment gets completed.

**Comment by nosegraze** [comment]
This PR should fix it: #1383
