### ISSUE TITLE
Update Authorize.net SDK

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1367]
It looks like we're on an ancient version of the Authnet PHP SDK. The methods we're using are deprecated in their documentation.

We should update it before doing #1239, #1366, #1236, etc.

**Comment by nosegraze** [comment]
Note that the latest version of their SDK requires PHP `5.6+`.

**Comment by mindctrl** [comment]
Right now all the sites we have data on using Authorize.net are running PHP 5.6 and higher.

I wonder how far back we'd have to go to support older versions...

**Comment by nosegraze** [comment]
What are your thoughts on this @pippinsplugins ?

**Comment by mindctrl** [comment]
Not many people are using Authorize.net on 2.9.x. All our data still shows `5.6+`. I think unless we have a very good reason to use deprecated software for payments we should upgrade.

**Comment by mindctrl** [comment]
Having said that, auth.net usage is so low I think we should dedicate as little time as possible to it until that changes.

**Comment by nosegraze** [comment]
Usage may be low but I do think the problems we have with it right now are pretty significant.

**Comment by mindctrl** [comment]
I agree. I'm not saying don't fix those. I think we should fix those and let it sit without further dev.

I'm not happy about using deprecated software on a new gateway. How long has it been deprecated? What's their history of deprecating things in the API based on this? We don't know. I'd hate for them to deprecate this stuff and kill payments on customer sites. The safest thing is to update the SDK and use the latest code, but if you two disagree with that that's fine by me.

**Comment by nosegraze** [comment]
I'm fine updating the SDK, I just wanted to make sure Pippin was on board with it too before doing it.

**Comment by pippinsplugins** [comment]
Let's update the SDK.

**Comment by nosegraze** [comment]
PR: #1418

**Comment by mindctrl** [comment]
Updated PR to remove the bash scripts and unit tests we don't use.

I did some tests of recurring and non-recurring purchases, cancelling subscriptions, and updating billing card. All seems to work as expected.

I'm still waiting for a silent post to come in to ensure those are working as expected. Right now my payments are still pending and the payment_type and transaction_id are still empty.

**Comment by nosegraze** [comment]
The silent post doesn't work in sandbox. You have to use Postman. Here's a list of data that they send: http://www.johnconde.net/blog/all-about-authorize-nets-silent-post/

**Comment by nosegraze** [comment]
Yeah it's a pain. I wonder if webhooks work in sandbox...

**Comment by mindctrl** [comment]
Merged!
