### ISSUE TITLE
PayPal Express: auto renew members not being marked as recurring

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1368]
PR incoming.

**Comment by nosegraze** [comment]
PR: #1369

**Comment by nosegraze** [comment]
This also fixes a problem where `RCP_Member::renew()` was being run on initial signup. It didn't have any repercussions because the correct expiration date was passed to it, but there was no reason for it to be running, so that's been fixed too.

**Comment by pippinsplugins** [comment]
PR looks good to me.

**Comment by mindctrl** [comment]
Looks like it will work, but my sandbox is hosed again so I can't test it.

**Comment by mindctrl** [comment]
@nosegraze if you're happy with this and have confirmed it with testing, we can merge it.

**Comment by nosegraze** [comment]
I tested this when I first made the PR and it worked well. Went to test it again today just to double check but now my sandbox is on the fritz too lol.

**Comment by nosegraze** [comment]
Was able to test this again today and it worked well. Merged.
