### ISSUE TITLE
Allow restricting content within custom taxonomies

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#137]
It would be pretty cool if you could somehow get the RCP custom fields that are on category edit screens on custom taxonomy edit screens as well (and of course restrict access to content in those taxonomies accordingly).

Of course this would mean a pretty significant refactoring of [`/includes/admin/categories.php`](https://github.com/pippinsplugins/Restrict-Content-Pro/blob/master/includes/admin/categories.php) and [`/includes/content-filters.php`](https://github.com/pippinsplugins/Restrict-Content-Pro/blob/master/includes/content-filters.php) to generalize that code.

Just wanted to drop this in here now as I'm thinking about it, for future reference.

**Comment by pippinsplugins** [comment]
I'd love to get this added.

**Comment by pippinsplugins** [comment]
This could be easily done now with taxonomy meta in WP 4.4

**Comment by tnorthcutt** [comment]
Thinking through this now, I'm wondering: would it be better to have the settings for this on each individual taxonomy term screen, or on an RCP settings page? The advantage to the former is of course visibility as you're editing that taxonomy term, but the advantage to the latter is that all (well, more of) your restriction settings are centralized and visible in one place.

Just food for thought :smile:

**Comment by pippinsplugins** [comment]
I've considered that. I think for now, adding them to the term page like categories makes most sense.

**Comment by tnorthcutt** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@tannerm #355 gets us most of the way there but we still need to enable the additional UI options on  custom taxonomies. For example, they don't show here:
![screen shot 2016-02-15 at 9 33 41 am](https://cloud.githubusercontent.com/assets/1034109/13052927/5e4e5bfc-d3c7-11e5-844d-eed3e49a63de.png)

**Comment by pippinsplugins** [comment]
I really like how you set it up to get rid of the old category meta incrementally :)

**Comment by tannerm** [comment]
Thanks!

**Comment by pippinsplugins** [comment]
We'll need to make this support our WooCommerce integration.

@tannerm Could you look at that?

**Comment by tannerm** [comment]
Just pushed up a fix.

**Comment by pippinsplugins** [comment]
@tannerm This Works really well for the category / shop views. We will also need to restrict viewing of the single product page. Right now if you have a single product that is in a restricted category, you can still view it via the direct URL. Take a look at the `hide_template()` method in the WooCommerce integration to see how we did this for individual product restrictions: https://github.com/restrictcontentpro/restrict-content-pro/blob/release/2.5/includes/integrations/class-rcp-woocommerce.php#L305

**Comment by pippinsplugins** [comment]
Actually it looks like it should be working . . . not quite sure why it's not. Are you able to access the single product page for a product that is in a restricted category when logged into an account that does not have necessary access levels (or are logged out)?

**Comment by mindctrl** [comment]
@tannerm currently admins are restricted from viewing content restricted at the taxonomy level. (Happens on built-in WP taxonomies too).

**Comment by tannerm** [comment]
@pippinsplugins @mindctrl  Just removed restrictions for admins and authors in #387

**Comment by pippinsplugins** [comment]
Perfect.
