### ISSUE TITLE
Allow us to pass empty message in [restrict] shortcode to prevent non-member output

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#1379]
It would be useful to be able to prevent the "you do not have access to this content" message from appearing in some cases when using the [restrict] shortcode in post content, like when we're just displaying a simple message to members.

If we pass an empty `message` to the shortcode we still get the default message. Could this be updated so that an empty `message` param == no message / html output for non-members?

```html
[restrict paid="true" message=""]
A message for site members. Non-members will be none the wiser..
[/restrict]
```

**Comment by mindctrl** [comment]
@thomasfw I can see that being useful. We'll take a look at it.

In the meantime, you should be able to use this hack to do what you want:

```
add_filter( 'shortcode_atts_restrict', function( $out, $pairs, $atts ) {
	if ( isset( $atts['message'] ) && '' === $atts['message'] ) {
		$out['message'] = 'fake';
	}
	return $out;
}, 10, 3 );

add_filter( 'rcp_restricted_message', function( $msg ) {
	if ( 'fake' === $msg ) {
		$msg = '';
	}
	return $msg;
});
```

**Comment by nosegraze** [comment]
There was another customer who wanted to do this and I just advised her to enter `[restrict message="&nbsp;"]` (in the text/HTML editor).

**Comment by nosegraze** [comment]
PR: #1431

This allows for an empty space to be passed in like so: `[restrict message=" "]`
