### ISSUE TITLE
Missing action 'rcp_edit_member'

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1381]
This action should be triggered when editing a member in the admin panel, but it seems to have gotten removed somehow.

```php
do_action( 'rcp_edit_member', $user_id );
```

**Comment by mindctrl** [comment]
It was lost here: https://github.com/restrictcontentpro/restrict-content-pro/pull/1140

While we're here let's double check to make sure we're not missing any others.

**Comment by luke-au** [comment]
Any chance of a quick fix? 
I've been re-writing my custom fields for days trying to work out what I'd done since the last update. 😢

**Comment by nosegraze** [comment]
PR: #1386

I did a search for `do_action` in the old `process-data.php` file and this was the only result, so I think we're good.

Sorry for the inconvenience @luke-au !
