### ISSUE TITLE
Trailing zeroes removed from amount in emails

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1384]
For example: `$12.50` becomes `$12.5` in the email.

**Comment by nosegraze** [comment]
The problem here is that it ends up being stored as `12.5` due to `RCP_Registration::get_total()` running `floatval()` on the final value. This turns `12.50` into `12.5`.

Maybe what we need is some kind of currency format function that handles this and https://github.com/restrictcontentpro/restrict-content-pro/issues/1385

**Comment by mindctrl** [comment]
/me grumbles about storing currency as floats. Tons of articles online about why it's a bad idea.

We could run the emailed amount through `number_format()`, but there may be other consequences of doing that I'm not thinking about...

**Comment by mindctrl** [comment]
or maybe `number_format_i18n()`

**Comment by nosegraze** [comment]
Whatever we do here I think we should also do the same in the registration template and invoice for consistency. Amounts should display exactly the same in all areas.

It looks like we are currently using `number_format()` in a few places, but not quite all.

**Comment by chrisvanpatten** [comment]
Was just going to comment with that ;-)

Something worth noting with `number_format_i18n` though is that it doesn't seem to work well in situations where your site locale is different from your selected currency.

**Comment by nosegraze** [comment]
How about this: #1474 ?

The filter would allow for further customization.

**Comment by mindctrl** [comment]
Unit tests failed due to a forced `.00` on the discount amount.

On the filter, I prefer we never add filters to new code until it has been proven after being live for a while, and preferably after numerous people have asked for it. `number_format_i18n` and `rcp_currency_filter` both have filters, and our prorate message even runs the amount through a filter. Our filters have filters!

**Comment by nosegraze** [comment]
Good point. The filter on `number_format_i18n()` should be enough anyone who wants to change the format.

I updated the PR and just reverted the change on `format_discount()`.

**Comment by mindctrl** [comment]
One thing I noticed here, and this maybe isn't an issue but worth mentioning in case it spurs a thought... 

I switched currencies from USD to JPY to see how it affects things since JPY is a zero decimal currency. Existing amounts with decimals get rounded everywhere they're shown. Probably not an issue on real sites that start out with zero decimals but worth a mention.

This also works fine with a new custom currency I registered with 4 decimals.

**Comment by nosegraze** [comment]
Hm I suspect that would be fine if they wouldn't be using decimals anyway. I don't know enough about it to say if there are any circumstances where they possibly could.

**Comment by mindctrl** [comment]
Any downside to just running `$price` through `number_format_i18n()` in `rcp_currency_filter()`?

That `test_format_discount()` test would fail, but I think that test should be set up to expect a fully formatted discount amount, and it would help standardize all the number formatting throughout.

Oh you know, just realized `rcp_format_amount()` probably shouldn't add a currency symbol. We have similar functions in EDD and AffWP and those don't add it. I can see the value in a formatting function separate from the currency symbol.

**Comment by nosegraze** [comment]
I don't really mind. I just thought it would be easier/cleaner to just run `rcp_format_amount( $amount )` everywhere rather than:

```php
rcp_currency_filter( rcp_format_amount( $amount ) );
```
or
```php
rcp_currency_filter( number_format_i18n( $amount, rcp_currency_decimal_filter() ) );
```
But maybe one of those is better to maintain consistency across products.

**Comment by mindctrl** [comment]
If we format the price inside `rcp_currency_filter` we can leave many of these changes out. Is there a use case for needing an unformatted amount with the currency symbol?

**Comment by nosegraze** [comment]
I don't think so.

**Comment by mindctrl** [comment]
I can't think of one either. I think we can keep `rcp_format_amount()`, but remove the currency sign from its output so that it just formats amounts, and then we can use `rcp_format_amount()` inside `rcp_currency_filter` to get a fully formatted amount with currency symbol.

**Comment by nosegraze** [comment]
Updated PR.

**Comment by mindctrl** [comment]
This looks good now. One thing I noticed, part of which we can touch in another issue right after this, is if you pass `rcp_format_amount()` a value with a comma already in it, you get the following notice:

`PHP Notice:  A non well formed numeric value encountered in /app/public/wp-includes/functions.php on line 219`

This will then result in the amount coming out the other side wrong. For example, `1,000.00` becomes `1.00`.

This is only problematic in cases where a comma got into the amount. One place where that can happen is manually adding a payment in the admin. Our regex pattern allows the entry of `1,000.00`, and it should not allow the comma there, because then it gets into the DB with the comma and causes the issue every place it passes through `rcp_format_amount()`.

For now in this PR, I think we should consider doing a `str_replace` on the amount to strip commas before passing it through `number_format_i18n()` in `rcp_format_amount()`.

For the other part, I'll open a new issue so we can prevent the entry of commas in amounts when adding payments manually. I don't think we have any other place in the code where we allow it.

**Comment by mindctrl** [comment]
Hmm re: comma comment. Some currencies use that as a decimal point. We need to double check that before stripping them out.

**Comment by mindctrl** [comment]
Bumping this to 2.9.6. It looks like we're going to need to do a little more in `rcp_format_amount()`.

In EDD and AffWP, they do a search/replace on the amount based on the decimal and thousands separator settings. We don't have those settings, and we can certainly introduce them at some point if needed, but I think we can get the info from the `$wp_locale` object in the near term.

I'll update this PR and we can do more testing for 2.9.6.

**Comment by mindctrl** [comment]
Updated PR. Copy/pasta from EDD's function, just changed where the separator data comes from. Needs testing.

**Comment by nosegraze** [comment]
Works well. 👍 Couldn't break it.
