### ISSUE TITLE
Incorrect expiration date/status when renewing membership via manual gateway

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1397]
A few problems that are all related:

1. If a user renews a subscription early with the manual gateway, their status is set to `Pending` until payment is confirmed. This means they lose access to content they should already have.
2. Because their status is `Pending`, the expiration date is incorrectly calculated during a renewal. It actually gets calculated twice: once inside the gateway itself (this one is accurate) then again after the payment status is updated to `Complete`. This second one is inaccurate because it uses today as the base timestamp instead of extending the expiration date. But really we shouldn't be doing two calculations anyway - we should just do it when the payment status is updated and get that one fixed.
3. The expiration date is incorrectly extended when upgrading, instead of being recalculated based on today.

**Comment by nosegraze** [comment]
PR: #1398

Also sending this to the user who reported it so they can confirm I've fixed all the problem areas.

**Comment by mindctrl** [comment]
Just noticed something. When editing a pending member to mark them as active, their subscription level is incorrect since it's not set. It defaults to the first one in the list. This would result in someone receiving the wrong subscription level on update unless you notice it and also change the subscription level.

**Comment by nosegraze** [comment]
Well with this new flow with pending payments really you should be updating the pending payment to change the status to `Complete`, then that will update the member's status, subscription level, and expiration automatically. There shouldn't be a need to edit the member at all.

**Comment by mindctrl** [comment]
Agreed, but since we don't block people from using the flow they used before pending payments were introduced, we should probably update the member edit screen to use the pending subscription level if the member status is pending. I'll open a separate issue for that.
