### ISSUE TITLE
Incorrect subscription level selected in dropdown on pending members

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1407]
re: #1397 

Old flow before pending payments were introduced:
For example, manual payments. Admins would edit the member and change the status from pending to active. The payment was already set to complete prior to 2.9.

Now when editing a pending member, their subscription level in the dropdown is incorrect since it's not set. It defaults to the first one in the list. This would result in someone receiving the wrong subscription level on update unless you notice it and also change the subscription level.

We should probably update this dropdown to show the pending level if the member is pending. I considered that we could show a notice instructing the admin to edit the payment as complete, however there are other valid use cases for editing a member before their payment is finalized, such as adding notes, etc.

**Comment by nosegraze** [comment]
PR: #1421
