### ISSUE TITLE
Get all groups names

### ISSUE THREAD

**Issue by wollsale** [restrictcontentpro/restrict-content-pro#1424]
Hi, 

I did not found any rcpga repo so I post this question down here:

I was wondering how could I display all the existing groups names on a page (in order to allow existing users or users trying to register to select a group from a list of all existing groups)?

For now I'm going through `rcp_get_members()` function but I don't think it's the best way to achieve this:

```
<?php $members = rcp_get_members(); ?>
<?php foreach ($members as $key => $member) {
	$id = $member->ID;
        print_r(rcpga_group_accounts()->members->get_group_name($id));
} ?>
```

Thanks in advance,

AW.

**Comment by mindctrl** [comment]
Hi @wollsale, we use Github for development tracking only. Please go ahead and open a support ticket here: https://restrictcontentpro.com/support/

**Comment by wollsale** [comment]
Well noted, thanks!
