### ISSUE TITLE
Incorrect tooltip for email verification

### ISSUE THREAD

**Issue by m-e-h** [restrictcontentpro/restrict-content-pro#1425]
This isn't right, is it?
![tooltiphuh](https://user-images.githubusercontent.com/3585901/30458571-283e716c-997a-11e7-89fb-fb7681c036ec.png)

Something may have gone awry here https://github.com/restrictcontentpro/restrict-content-pro/commit/dbe581bfa5fcba885dbe851e671fc8747e3e1fab

**Comment by nosegraze** [comment]
That's meant to clarify what the _"On for free subscription levels"_ option will apply towards.

**Comment by m-e-h** [comment]
Ohhh. That makes sense now. I read it over and over but could not make sense of it. 
What I didn't do was look to see what the options were. Sorry bout that.

**Comment by chrisvanpatten** [comment]
It's a bit longer, and would require a translation update, but can I suggest an alternative?

> If 'On for free subscription levels' is selected, subscriptions with a price of "0" in the level settings will require email verification. Registrations that are free after applying a discount code will bypass verification.

For reference, the current text:

> A free subscription level is one with a 0 price in the level settings. It does not include registrations that have been made free with a discount code.

**Comment by nosegraze** [comment]
Thanks for the suggestion @chrisvanpatten ! :)

PR: #1428
