### ISSUE TITLE
PayPal incorrectly storing payment amounts with a thousands separator

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1433]
If a subscription's price is `1000`, that amount gets sent to PayPal the correct way as `1000`. Then PayPal's IPN sends back the amount still formatted as `1000` or `1000.00`.

Before inserting the payment in RCP, the amount is passed through `number_format()` here: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.3/includes/gateways/class-rcp-payment-gateway-paypal.php#L287

This causes the number to come out the other side as `1,000.00`, which then gets saved in the payment table.

This results in a few issues:

1) When viewing the payments page in the admin, you get the following PHP notice: 
`PHP Notice:  A non well formed numeric value encountered in wp-content/plugins/restrict-content-pro/includes/admin/payments/payments-page.php on line 187`

2) When viewing an invoice, the amount show as `1.00` along with the following notice: `PHP Notice:  A non well formed numeric value encountered in wp-content/plugins/restrict-content-pro/templates/invoice.php on line 275`

Since we don't store amounts in the database with commas anywhere else, we should update the usage of `number_format()` in the PayPal gateway to not use the thousands separator.

**Comment by mindctrl** [comment]
Looks like it also happens in Express. Updated title.

**Comment by nosegraze** [comment]
Merged #1434
