### ISSUE TITLE
Improve rcp_has_post_restrictions() meta key value check

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1435]
`rcp_has_post_restrictions()` should compare `All` as `all` after running the value through `strtolower`, since it was stored as `All` and then at some point was changed to `all`.

`if ( ! empty( $rcp_user_level ) && 'All' !== $rcp_user_level ) {`
should be:
`if ( ! empty( $rcp_user_level ) && 'all' !== strtolower( $rcp_user_level ) ) {`

It technically works now because `_is_paid` still gets set when saving a post with `All` roles, but we should fix it up anyway.

**Comment by nosegraze** [comment]
PR: #1459
