### ISSUE TITLE
Allow admins to manually verify "pending verification" accounts

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1440]
Two different customers have had problems with users being unable to verify their accounts via email and wanted to be able to approve those accounts manually. Seems like a good idea. We could add a link for that in the actions in the members table.

**Comment by mindctrl** [comment]
👍  to having an admin option to verify manually.

Did they say what problems their members are having doing it themselves?

**Comment by nosegraze** [comment]
One customer's problem was because her site URL in WordPress was set to `mysite.com` but then she actually had it set up so the homepage (`mysite.com`) was using LeadPages -- not WordPress. But because of her configuration, WordPress assumed that the homepage would be part of the WordPress site... it was weird. But it caused problems because we run the verification on the homepage, but when people clicked the link, they were taken to LeadPages instead.

The second customer didn't elaborate on what the problem was.

**Comment by nosegraze** [comment]
PR: #1472
