### ISSUE TITLE
%amount% tag incorrect when using same RCP_Emails instance for multiple emails (reminders)

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1441]
This happens when expiration/renewal reminders get send out, and when more than one email is being sent at a time.

This is because the `payment_id` property is set in `RCP_Emails::send()` like so:

```php
if ( empty( $this->payment_id ) ) {

	global $rcp_payments_db;

	$payment = $rcp_payments_db->get_payments( array(
		'user_id' => $this->member_id,
		'order'   => 'DESC',
		'number'  => 1
	) );

	$payment = reset( $payment );

	$this->payment_id = ! empty( $payment ) && is_object( $payment ) ? $payment->id : 0;

}
```

When the first email gets sent, `$this->payment_id` is empty, so it gets correctly queried to get the latest payment. But when the second email is sent to the second user, `$this->payment_id` is already set (to the previous user's payment) so the `if` statement never runs. This results in the second email using the `%amount%` from the first member.

**Comment by mindctrl** [comment]
`RCP_Emails::send()` should only send the email, and do nothing with payment queries unless there's a reason I'm not seeing.

**Comment by nosegraze** [comment]
PR: #1445

I just deleted the code completely. It's not needed because the template tags that use the `$payment_id` all include their own queries. Example: https://github.com/restrictcontentpro/restrict-content-pro/blob/issue/1441/includes/email-functions.php#L700-L715
