### ISSUE TITLE
Swap order of Publishable Key and Secret Key in settings

### ISSUE THREAD

**Issue by amdrew** [restrictcontentpro/restrict-content-pro#1443]
For consistency with Stripe's settings it would be nice to have the Publishable Key first, followed by the Secret Key.

<img width="1107" alt="screenshot 2017-09-22 12 29 36" src="https://user-images.githubusercontent.com/52581/30724420-c9bc3f7a-9f91-11e7-9b7f-9bb84090bd7c.png">

<img width="590" alt="screenshot 2017-09-22 12 29 56" src="https://user-images.githubusercontent.com/52581/30724421-c9cf28e2-9f91-11e7-8c6b-91ad4b222a4a.png">

**Comment by tnorthcutt** [comment]
A nice bit of UI polish might be to also add placeholder text, along the lines of `sk_test_xxxxxxxx`, `pk_test_xxxxxxxx`, etc.

**Comment by nosegraze** [comment]
PR: #1508
