### ISSUE TITLE
Getting non existent payment ID via get_payment() returns non-empty object

### ISSUE THREAD

**Issue by brandomeniconi** [restrictcontentpro/restrict-content-pro#1444]
If I execute this code (from `rcp_generate_invoice` function ):

```php
$payment_id = 99999; //non existent payment ID
$payments_db  = new RCP_Payments;
$payment  = $payments_db->get_payment( $payment_id );

if( ! $payment ) {
   wp_die( __( 'This payment record does not exist', 'rcp' ) );
}

var_dump($payment);
```
I receive the following warning:

`Warning: Creating default object from empty value in plugins/restrict-content-pro/includes/class-rcp-payments.php on line 313 `

and the var dump prints:

`object(stdClass)#12258 (1) { ["status"]=> string(8) "complete" } `

**Comment by nosegraze** [comment]
PR: #1458
