### ISSUE TITLE
Docs for rcp_add_user_to_subscription()

### ISSUE THREAD

**Issue by m-e-h** [restrictcontentpro/restrict-content-pro#1453]
Sorry for adding to this repo's issue feed but wasn't sure where best to report this. 
Pretty sure `'subscription_level'` is mistakenly being shown for the $args rather than `'subscription_id'`.
http://docs.restrictcontentpro.com/article/1912-rcp-add-user-to-subscription

Made for a pretty long day here :smirk:

**Comment by mindctrl** [comment]
@m-e-h you are correct. Sorry about that! I've updated the docs to correctly show `subscription_id`.
