### ISSUE TITLE
rcp_is_post_taxonomy_restricted() unavailable for ajax requests

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1466]
`rcp_is_post_taxonomy_restricted()` is loaded in `content-filters.php`, which is not loaded in the `is_admin()` context, which means it's not available for ajax requests.

This causes issues in WooCommerce on the `woocommerce_add_to_cart` hook.

We should probably move that function to another file, like `misc-functions.php`.

**Comment by nosegraze** [comment]
PR: #1468
