### ISSUE TITLE
Invoice notes: use wpautop() instead of hard-coding <p> tag

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1467]
The display in `invoice.php` looks like this:

```
<?php if( ! empty( $rcp_options['invoice_notes'] ) ) : ?>
	<article>
		<p><?php echo $rcp_options['invoice_notes']; ?></p>
	</article>
<?php endif; ?>
```

We should change that to:

```
<?php if( ! empty( $rcp_options['invoice_notes'] ) ) : ?>
	<article>
		<?php echo wpautop( $rcp_options['invoice_notes'] ); ?>
	</article>
<?php endif; ?>
```

to allow people to use multiple paragraphs inside the notes box. Perhaps we should also consider changing the plain textarea for notes into a visual editor.

**Comment by nosegraze** [comment]
PR: #1473

**Comment by mindctrl** [comment]
Looks great. Pushed a small update to run it through `wp_kses_post()`. We can merge when tests finish.
