### ISSUE TITLE
User Role column in Members outputs role slug rather than role name using rcp_get_user_role

### ISSUE THREAD

**Issue by luke-au** [restrictcontentpro/restrict-content-pro#1476]
The "User Role" column in Members outputs the role slug rather than role name using `rcp_get_user_role`. A custom role "**example-role**" would display rather than it's nice name "**Example Role**". 
Should that **$user_role** return **$name** instead of **$role** within the foreach loop?

```php
foreach ( $wp_roles->role_names as $role => $name ) {
	if ( array_key_exists( $role, $capabilities ) ) {
		$user_role = $name; // $user_role = $role;
	}
}
```
https://github.com/restrictcontentpro/restrict-content-pro/blob/7d90a8565bfbf65690158870b5e45cb8b00de0cd/includes/member-functions.php#L728-L758

**Comment by mindctrl** [comment]
@luke-au thanks for the feedback! I agree that it should use the nice name over the slug, and that would make it match other areas of the admin where we reference roles.

**Comment by nosegraze** [comment]
PR: #1599

**Comment by pippinsplugins** [comment]
I think we should leave this function as is and then introduce a new `rcp_get_user_role_name()` helper. Having a helper for getting the role's slug is useful and changing it could have unexpected consequences.

**Comment by nosegraze** [comment]
That works for me!
