### ISSUE TITLE
Network activated database table names missing prefix

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1478]
```php
$prefix = is_plugin_active_for_network( plugin_basename( RCP_PLUGIN_FILE ) ) ? '' : $wpdb->prefix;
```
This results in:

Network activated: `rcp_payments`
Normal site: `wp_rcp_payments`

The network activated one is missing the `wp_` (or whatever) prefix.

Instead of setting the prefix to an empty string, it should be `$wpdb->base_prefix`. In multisite, `prefix` would contain `wp_85_` with the blog ID but `base_prefix` would only contain `wp_`.

**Comment by mindctrl** [comment]
The missing prefix has been a thing for 5+ years. Introduced here: https://github.com/restrictcontentpro/restrict-content-pro/commit/0ac50ab1c802faeb6879235b5e375180ae8e270c

I don't know if this is something we should fix at this point.

**Comment by pippinsplugins** [comment]
I agree with @mindctrl.

There are not any negative side effects of the missing base prefix are there?

**Comment by nosegraze** [comment]
I'm fine with leaving it as is. I can't think of any side effects.
