### ISSUE TITLE
RCP_Payments::get_payment_by() doesn't work with strings

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1479]
```php
$payment = $wpdb->get_row( "SELECT * FROM {$this->db_name} WHERE {$field} = {$value}" );
```

When trying to get a payment by transaction ID this results in:

```
PHP message: WordPress database error Unknown column 'ch_1B9FGMEzPYrMeqUy6art4EEB' in 'where clause' for query SELECT * FROM rcp_payments WHERE transaction_id = ch_1B9FGMEzPYrMeqUy6art4EEB 
```
We should be using `$wpdb->prepare()` here.

**Comment by nosegraze** [comment]
Also this needs to be fixed to account for the payment not being found:

```php
if( empty( $payment->status ) ) {
	$payment->status = 'complete';
}
```

We had another issue about this recently. I think we had the same code in another method.

**Comment by nosegraze** [comment]
PR: #1480

**Comment by mindctrl** [comment]
Merged. Looks like this probably caused issues with 2Checkout processing `REFUND_ISSUED` webhooks.
