### ISSUE TITLE
Add filter for Stripe Checkout "Submit Payment" button text (or change value)

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1482]
The normal register button has a filter:

```php
'register' => apply_filters ( 'rcp_registration_register_button', __( 'Register', 'rcp' ) ),
```

But Stripe Checkout uses its own special value instead when that gateway is selected and it does not have a filter:

```php
'pay_now' => __( 'Submit Payment', 'rcp' ),
```

I got a request for a filter from a customer because they set up a free trial and didn't feel that `Submit Payment` was quite the right word for the button.

Personally, I'd be inclined to ditch the `pay_now` value and just use the `register` value for all gateways. I'm not really sure Stripe Checkout needs to switch the text on the button to something else at all. But if you guys would rather keep it as is, then we could add a filter instead.

**Comment by pippinsplugins** [comment]
The submit button for Stripe Checkout originally had its text changed because the action taken when that button is clicked is different than the action taken when clicking the standard registration button. Once processes the account registration and one simply moves to the next step in the registration process.

While I like the simplicity of having a single value, I don't think it makes sense for Stripe Checkout's initial submit button to say `Register` when the action is really `Okay, take me to the payment screen`.

**Comment by mindctrl** [comment]
Another difference we have is the Stripe Checkout shortcode uses `Join %s`, where `%s` is the subscription name. That one can be overridden with the `data-label` shortcode attribute.

**Comment by nosegraze** [comment]
PR: #1525

I left the Stripe Checkout one as-is for now. I'm indifferent as to whether we leave it or change it. As you said, John, at least it can be changed via the shortcode attribute.

**Comment by mindctrl** [comment]
Technically the text can already be changed using this:

```
add_action( 'wp_footer', function() {
	?>
	<script>
		if( typeof rcp_script_options !== 'undefined' ) {
			rcp_script_options.pay_now = 'Custom Text';
		}
	</script>
	<?php
}, 11 );
```

What I like about that method is we don't have to add another filter, and from a customer perspective the steps required to add custom code are the same. Thoughts?

**Comment by nosegraze** [comment]
I don't really mind either way. It seems to me like a filter would be a little bit easier for some people to grasp and adding one to change text isn't really a big deal, but if you'd rather not add one I don't mind.

**Comment by pippinsplugins** [comment]
I'm fine with a filter and I also like John's approach. If we use a filter, however, I think we should remove `stripe_checkout` from it as it's possible we could use that text in another gateway in the future.

**Comment by mindctrl** [comment]
Let's not add it for now. We can always revisit if pops up a lot.
