### ISSUE TITLE
Wrap discount fields in <span>

### ISSUE THREAD

**Issue by amdrew** [restrictcontentpro/restrict-content-pro#1489]
Just like: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6041, it would be nice to have the discount input and button wrapped in a span by default. This would allow a nicer layout when using flexbox.

Twenty Seventeen:

<img width="553" alt="screenshot 2017-10-12 21 09 25" src="https://user-images.githubusercontent.com/52581/31485808-a652ab4a-af91-11e7-8ee4-02ba2aae8f1a.png">

Themedd:

<img width="740" alt="screenshot 2017-10-12 21 09 07" src="https://user-images.githubusercontent.com/52581/31485797-9e15834e-af91-11e7-835e-6ac4a8dcb593.png">

___

And after:

<img width="752" alt="screenshot 2017-10-12 21 13 40" src="https://user-images.githubusercontent.com/52581/31485967-41b189b2-af92-11e7-908c-5a95b07bdc34.png">

**Comment by amdrew** [comment]
PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/1492

**Comment by mindctrl** [comment]
@amdrew this looks ok, but I'm curious why it's required? The 2012 theme shows the input and button inline.

![image](https://user-images.githubusercontent.com/1254870/31514951-7c2aee3e-af61-11e7-8085-997730e227f3.png)

What's special about flexbox that it requires a span?

**Comment by amdrew** [comment]
@mindctrl Good question, I wasn't clear on the "why". Some themes like to style the fields so they are 100% wide, and take up the full width of the container/wrapper. Plus, it looks nicer to have all fields lined up like this:

<img width="583" alt="screenshot 2017-10-13 11 27 34" src="https://user-images.githubusercontent.com/52581/31522317-af7db4e4-b009-11e7-8e5e-e2b4ae3f08b4.png">

Without the input and button being wrapped in a containing element you cannot achieve the desired layout above without resorting to "guessing" the exact width value of the input field and button. With flexbox, you don't have to set any widths, the input and button will take up all available space, with more CSS rules to further fine-tune the proportions.

If you apply a 100% width on the input field for example (without using flexbox) you get this:

<img width="567" alt="screenshot 2017-10-13 11 27 56" src="https://user-images.githubusercontent.com/52581/31522316-af4ab8c8-b009-11e7-84fa-b85eb2a3ffe8.png">

Sure, you can set a hard-coded value of like 60-70% (what we've done in the past) but it won't align exactly. Also, you'll never know if the text on the button has been modified to be wider or slimmer, which will affect the widths of the elements.

Here's probably a better explanation: https://philipwalton.github.io/solved-by-flexbox/demos/input-add-ons/

> Because of the way input sizing works in CSS, it’s almost impossible to append or prepend another element to it and have the input field behave fluidly and take up the remaining space.

> The only existing way to do this is to either know the exact width of the input, or to use something like display:table-cell, which has its own set of problems, most notably the difficulty with positioning anything absolutely inside of the add-on in certain browsers.

> With Flexbox, all these problems go away, and the code is trivially simple. In addition, you get the input field and the input add-on to be the same height for free.

**Comment by amdrew** [comment]
> What's special about flexbox that it requires a span?

Just to clarify on that, it's not that it needs a `span`, it just requires a wrapping element that only contains the elements you're wanting to position. Since the label is _also_ a sibling of the other two elements, flexbox can't be used to align only the input and button, without the label coming along for the ride. 

A span was chosen since it's bad practice to place a block level element inside another block level element. Had the `p` not been wrapping everything, we could have used a `div` for example.

**Comment by mindctrl** [comment]
Excellent explanation! Thanks for the info. Merged!
