### ISSUE TITLE
Change price to use <th>

### ISSUE THREAD

**Issue by amdrew** [restrictcontentpro/restrict-content-pro#1490]
The final total ($49 in the examples below) is not bolded like the `Total Today` which seems a little off.

Example (Twenty Seventeen):

<img width="590" alt="screenshot 2017-10-12 21 22 11" src="https://user-images.githubusercontent.com/52581/31486453-0a89981a-af94-11e7-8335-2ebcce1b96dd.png">

___

Example (Twenty Sixteen):

<img width="814" alt="screenshot 2017-10-12 21 22 43" src="https://user-images.githubusercontent.com/52581/31486498-26a13990-af94-11e7-8c20-af2d811bafe4.png">

___

If we look a the HTML we can see that the total uses a `td`, whereas the `Total Today` text uses a `th`:

```
<tr class="rcp-total">
    <th>Total Today</th>
    <td data-th="Total Today">$49.00</td>
</tr>
```

___

The other (and related) issue is that some theme's tend to give `th`'s a background color. Since the `Total Today` is a `th`, you get this:

Themedd:

<img width="790" alt="screenshot 2017-10-12 21 23 36" src="https://user-images.githubusercontent.com/52581/31486652-a8b60938-af94-11e7-9f71-7306d924a17e.png">

___

Vendd:

<img width="756" alt="screenshot 2017-10-12 21 23 06" src="https://user-images.githubusercontent.com/52581/31486671-b50020de-af94-11e7-9813-957e418085c9.png">

___

I guess the solution here would be to also make the price use a `th`, as opposed to a `td`. This would fix both issues, since a theme is likely to also "bold" a `th` (just noticed that Themedd doesn't seem to do this but that can be changed).

**Comment by amdrew** [comment]
PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/1491

<img width="723" alt="screenshot 2017-10-12 21 44 17" src="https://user-images.githubusercontent.com/52581/31487371-e3a6b176-af96-11e7-9895-9d4ee67d5efb.png">

<img width="559" alt="screenshot 2017-10-12 21 43 58" src="https://user-images.githubusercontent.com/52581/31487372-e3d91152-af96-11e7-927e-98ceeeb34e6e.png">

<img width="688" alt="screenshot 2017-10-12 21 48 53" src="https://user-images.githubusercontent.com/52581/31487457-2aca03e6-af97-11e7-8231-76f06fd4efd9.png">

<img width="675" alt="screenshot 2017-10-12 21 48 17" src="https://user-images.githubusercontent.com/52581/31487459-2b18f91a-af97-11e7-85f7-1a10eb104ae4.png">

Also tested at mobile resolutions.

**Comment by mindctrl** [comment]
We need to revert this and/or take the change further. On small screens this causes the Total Today to not show up.

Before:
![image](https://user-images.githubusercontent.com/1254870/31503490-cad16b7c-af3d-11e7-8eac-d01f7b57494a.png)

After:
![image](https://user-images.githubusercontent.com/1254870/31503503-d0109374-af3d-11e7-8e38-23b90b839d74.png)

**Comment by mindctrl** [comment]
@amdrew I'm not seeing what your shots show.

**Comment by pippinsplugins** [comment]
Whoops, thanks for catching that!

@mindctrl should just mean that it needs the responsive attributes added.

**Comment by nosegraze** [comment]
From an organizational perspective, I'm wondering if it should be kept as `<td>`. I mean if you think about what's going on, `Total Today` is a header/label, and the value (`$30` or whatever) is not. It doesn't really make sense to make it a header if it's not one.

If you want it bolded or styled differently, perhaps custom CSS should be used instead.

**Comment by amdrew** [comment]
Thinking about it some more I agree with @nosegraze, the price is not a header so should remain as a `td`. I do however still think the price should stand out more, it's the final total after all?

Could we add some CSS inside RCP so it appears bold by default? Something like (not tested):

```
.rcp-total td { font-weight: bold; } 
```
And also make sure the `Total Recurring Per Month` is bolded.

Since Vendd (ping @SDavisMedia) and Themedd have styled `th`'s to have a background color (there are probably more themes also) we'll just need to take that into consideration to support RCP better.

**Comment by mindctrl** [comment]
The relationship between the `th` and `td` changes once it hits the totals sections.
```
		<tr>
			<th><th>
		</tr>
		<tr>
			<td><td>
		</tr>
		<tr>
			<th>
		</tr>
		<tr>
			<td><td>
		</tr>
		<tr> (total today)
			<th><td>
		</tr>
		<tr> (total recurring)
			<th><td>
		</tr>
```

It goes from header over data to header beside data. Would it be good to come up with something that gives a consistent row/header/data structure throughout the table?

**Comment by mindctrl** [comment]
Revert PR here: https://github.com/restrictcontentpro/restrict-content-pro/pull/1498

**Comment by chrisvanpatten** [comment]
From a semantic perspective, I'm pretty sure the table markup is correct right now, but the <th> cells should have "scope" attributes defined.

For a <th> that labels the row, you would use `<th scope="row">Total</th> <td>Value</td>`. For a column header, you'd use `<th scope="col">Amount</th>`.

If a theme tries to style the <th> I think that falls on the theme to correct.

[This document has more](https://www.w3.org/WAI/tutorials/tables/irregular/) on dealing with table headers in an accessible way.

**Comment by mindctrl** [comment]
Thanks @chrisvanpatten! I agree with your assessment. Punting this to 2.9.6 since we're aiming to release 2.9.5 today.

**Comment by nosegraze** [comment]
PR: #1535

I've added the `scope` attribute and also better organized the table to include `<thead>` and `<tfoot>` tags. I didn't add any classes because I believe having the thead and tfoot tags allows everything to now be targeted separately anyway.
