### ISSUE TITLE
Make admin emails filterable

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#1497]
Currently, admin emails are not always filterable. In [`email-functions.php`](https://github.com/restrictcontentpro/restrict-content-pro/blob/724c7c207f2ed022e6daf34edc44a5904268ac49/includes/email-functions.php#L59):

```
$admin_message = isset( $rcp_options['active_email_admin'] ) ? $rcp_options['active_email_admin'] : '';
```

So if an admin message is set, it is not filterable. However, if it is not set, it is now filterable:
```
if( empty( $admin_message ) ) {
    $admin_message = __( 'Hello', 'rcp' ) . "\n\n" . $user_info->display_name . ' (' . $user_info->user_login . ') ' . __( 'is now subscribed to', 'rcp' ) . ' ' . $site_name . ".\n\n" . __( 'Subscription level', 'rcp' ) . ': ' . rcp_get_subscription( $user_id ) . "\n\n";
    $admin_message = apply_filters( 'rcp_before_admin_email_active_thanks', $admin_message, $user_id );
    $admin_message .= __( 'Thank you', 'rcp' );
}
```

I propose adding filters, like so:
```
$admin_message = isset( $rcp_options['active_email_admin'] ) ? $rcp_options['active_email_admin'] : '';
$admin_message = apply_filters( 'rcp_subscription_active_admin_email', $admin_message, $user_id, $status );
```

And the same for the subject, and for each status (`active`, `cancelled`, `expired`, `free`, `trial`).

If this is something that would be merged, give me the thumbs up and I'll PR it ASAP.

_My use case, FWIW: a client wants notification emails to specify whether a registration is for a new user or for a plan change. Currently, I can't see a way to accomplish this, without these filters. Any suggestions for a workaround are of course welcome._

**Comment by nosegraze** [comment]
That sounds fine with me. I believe your proposed changes would make this match how the user notifications work and thus make everything more consistent. 👍
