### ISSUE TITLE
email sent on manual payment is sent to the wordpress admin

### ISSUE THREAD

**Issue by cecilehabran** [restrictcontentpro/restrict-content-pro#1516]
The rcp_email_admin_on_manual_payment function in email-functions.php sends the notification to the wordpress admin, not to the emails set in the rcp options, like the other functions.

A reason for that ?

Is it possible to replace
`$admin_emails[] = get_option( 'admin_email' );`
by
`$admin_emails  = ! empty( $rcp_options['admin_notice_emails'] ) ? $rcp_options['admin_notice_emails'] : get_option('admin_email');`
?

Thanks !

**Comment by nosegraze** [comment]
PR: #1519
