### ISSUE TITLE
_rcp_new_subscription flag not removed for free users

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1522]
```php
function rcp_remove_new_subscription_flag( $status, $user_id ) {

	if( 'active' !== $status ) {
		return;
	}

	delete_user_meta( $user_id, '_rcp_old_subscription_id' );
	delete_user_meta( $user_id, '_rcp_new_subscription' );
}
add_action( 'rcp_set_status', 'rcp_remove_new_subscription_flag', 9999999, 2 );
```

It only gets removed for `active` ones but should be removed for `free` too.

**Comment by nosegraze** [comment]
PR: #1524

**Comment by mindctrl** [comment]
@nosegraze PR looks good. any known issues this causes?

**Comment by nosegraze** [comment]
I just had a minor problem with this and the MailChimp Pro add-on, which uses that flag here https://github.com/restrictcontentpro/rcp-mailchimp-pro/blob/master/includes/class.mailchimp-api.php#L538-L542

I think I signed up for a free level, got the status `free`, then edited my status in the admin panel to `cancelled` and since the flag was never deleted, that MailChimp Pro method exited early. I'm not sure you'd see the problem if everything was done via the registration form since a `free` user wouldn't cancel or expire.
