### ISSUE TITLE
Connection lost when updating a post

### ISSUE THREAD

**Issue by FaramarZHidden** [restrictcontentpro/restrict-content-pro#1528]
hello,
when i want to update a post, wordpress shown below error:

> Connection lost. Saving has been disabled until you’re reconnected. We’re backing up this post in your browser, just in case.

 and server down... 
when rcp deactive problem is solved.. 

anyone see that issues ?
can help me ?

wordpress version 4.8.2
theme twenty*
activate plugins: just restrict content pro 2.9.4

**Comment by mindctrl** [comment]
Hi @FaramarZHidden,

Please open a support ticket at https://restrictcontentpro.com/support/. We use Github for development purposes only.
