### ISSUE TITLE
Admin CSS Styles are targeting non-RCP pages

### ISSUE THREAD

**Issue by cklosowski** [restrictcontentpro/restrict-content-pro#1529]
In EDD https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6088 we added some tabs to one of our admin pages, and all was well until we went to the EDD live site with RCP active, and the tab text size was getting increased to 16px from 14px.

It appears that this CSS file in admin is loading on the Downloads list table:
https://easydigitaldownloads.com/wp-content/plugins/restrict-content-pro/includes/css/admin-styles.min.css?ver=2.9.5

Which is causing fonts to be increased from the `14px` that WordPress core adds to the tab text, to `16px`

Without RCP:
![screen shot 2017-10-19 at 4 18 25 pm](https://user-images.githubusercontent.com/1390124/31798563-44393d68-b4e9-11e7-90cf-0eccf4432a44.png)

With RCP:
![screen shot 2017-10-19 at 4 18 42 pm](https://user-images.githubusercontent.com/1390124/31798571-499c6410-b4e9-11e7-836d-2980cad15b10.png)

**Comment by luke-au** [comment]
It might be worth mentioning here that I don't actually think the tabs setup is correctly on RCP Settings. I never see an active state tab.

> General

![rcp-settings-tabs](https://user-images.githubusercontent.com/23548658/31803810-899f32dc-b5a1-11e7-8b4f-3b81f771cc38.png)


> Payments

![rcp-settings-tabs-payments](https://user-images.githubusercontent.com/23548658/31803936-2d15bdb4-b5a2-11e7-9cf1-d909296dc4c7.png)

**Comment by mindctrl** [comment]
PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/1530

Removed our CSS and let core style it. Also fixed active tab CSS issue.

![image](https://user-images.githubusercontent.com/1254870/31804567-30dd95f4-b528-11e7-8136-d5a47066bde0.png)
