### ISSUE TITLE
Proration incorrect when date format has comma

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1532]
Just ran into a case with a customer where proration credit was incorrectly coming out as `0`. The time remaining was incorrectly coming out as a negative number due to a bad `strtotime()`.

Here's the relevant code:

```php
$exp_date = $member->get_expiration_date(); // This is the formatted date.

// make sure we have a valid date
if ( ! $exp_date = strtotime( $exp_date ) ) {
	return 0;
}

$exp_date_dt = date( 'Y-m-d', $exp_date ) . ' 23:59:59';
```

We get the user's expiration date _formatted_. In this customer's case it was `23 January, 2018` (note the comma).

But `strtotime()` doesn't like commas, so that final variable `$exp_date_dt` ended up being `2017-01-23 23:59:59` . The year got changed to `2017` instead of `2018` which killed the whole thing.

This can easily be fixed by getting the unformatted expiration date instead.

**Comment by nosegraze** [comment]
PR: #1533

**Comment by mindctrl** [comment]
How did the expiration date get into the db with that format?

**Comment by nosegraze** [comment]
It wasn't, but we were doing `$this->get_expiration_date()`. By default the first parameter in that method (`$formatted`) is set to `true` which means the expiration date actually comes back as:

```php
$expiration = get_user_meta( $this->ID, 'rcp_expiration', true );
if( $formatted && 'none' != $expiration ) {
	$expiration = date_i18n( get_option( 'date_format' ), strtotime( $expiration, current_time( 'timestamp' ) ) );
}
```

The PR sets that to `false` so it doesn't run it through the formatting.

**Comment by mindctrl** [comment]
Oh! For some reason my mind went to it being that way in db. Gotcha.
