### ISSUE TITLE
Thousands of transient being saved in database for for rcp_user_logged_in

### ISSUE THREAD

**Issue by jmagnone** [restrictcontentpro/restrict-content-pro#1536]
Seems this transient is not defined with an expiration (the third option of set_transient is not defined). For site with large number of users being logged in, this is causing to have thousands of transient entries in the wp_options table that are not deleted automatically until we execute a delete SQL statement. 

https://github.com/restrictcontentpro/restrict-content-pro/blob/b00889991746cde1d1f12af74987f55012e56e8a/includes/misc-functions.php#L374

The transient is being deleted by logout action, but of course not all the users click the Logout so for those who never logout formally using the logout action, a transient is being saved indefinitely in the database.

**Comment by nosegraze** [comment]
PR: #1564
