### ISSUE TITLE
Reduce path depth for Authorize.net SDK

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1546]
I've seen two tickets on this already.

When WP is installing the RCP update, the following error occurs on some Windows servers:
```
An error occurred while updating Restrict Content Pro: Could not create directory. restrict-content-pro/includes/libraries/anet_php_sdk/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/KeyManagementSchemeType
```

This exceeds the maximum path depth supported in some versions of Windows. Let's see if we can reduce that by renaming some things and/or moving them to another folder.

**Comment by nosegraze** [comment]
We've gotten like 5+ tickets about this now.

**Comment by nosegraze** [comment]
Right now it's in `restrict-content-pro/includes/libraries/anet_php_sdk`. We could move it to `restrict-content-pro/anet/` . That's not much, but then inside the actual folder it uses an autoloader so it's hard to edit anything in there. :/

**Comment by nosegraze** [comment]
PR: #1722

Implemented the above suggestion of moving the existing files to `/anet/`

**Comment by nosegraze** [comment]
Closing this in favour of https://github.com/restrictcontentpro/restrict-content-pro/issues/1829
