### ISSUE TITLE
CSV Export bug when a column contains '-'

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1549]
For example, if you export a payment that has a negative fee, the `esc_field()` method ends up improperly formatting the column.

Here's how it looks in the CSV file (the zero is the field before it, just to give a better picture)
`"0",""-3"`

Note the double `""` before the `-3`.

When you open this CSV in an app like Numbers, the column value is `-3"` instead of `-3`.

**Comment by pippinsplugins** [comment]
Borrowed the logic that we use in the EDD batch export classes and it resolves it for me.
![image](https://user-images.githubusercontent.com/1034109/33442808-aadc4c02-d5bb-11e7-8a5f-0d8477512fc4.png)

**Comment by nosegraze** [comment]
Works well! Merged!
