### ISSUE TITLE
Set sslverify to true in updater code

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1550]
We have `sslverify` set to `false` in the updater code. We can set them to `true`.

**Comment by tnorthcutt** [comment]
@mindctrl is there any reason not to use `true` in all cases? Others I found were fetching RCP addons, license activation, and communicating with PayPal.

According to [this StackExchange answer](https://wordpress.stackexchange.com/a/167947/49), `sslverify` should be set to `true` from WordPress core 3.7 on.

If we decide to change this, we can simply drop setting it to `false`; it defaults to `true`.

**Comment by mindctrl** [comment]
@tnorthcutt I'm not aware of any reasons to keep `false` around. I say we get rid of it. 👍

**Comment by pippinsplugins** [comment]
No reason any more, just a left over.
