### ISSUE TITLE
Status changed to "Pending" when upgrading from free account but not completing payment

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1551]
- Start with an account on a free subscription level. Status is `free`
- Upgrade to a paid level using something like PayPal.
- Exit out of PayPal without completing payment and return to site.
- Status is now `Pending` and the user loses access to content from their free level.

Due to this block in registration:

```php
if( ! $member->is_active() ) {

	// Ensure no pending level details are set
	delete_user_meta( $user_data['id'], 'rcp_pending_subscription_level' );
	delete_user_meta( $user_data['id'], 'rcp_pending_subscription_key' );

	$member->set_status( 'pending' );

} else {

	// Flag the member as having just upgraded
	update_user_meta( $user_data['id'], '_rcp_just_upgraded', current_time( 'timestamp' ) );

}
```

`Free` users are not `Active`, which means the `if` block gets triggered, when really they should get `else` instead.

**Comment by nosegraze** [comment]
PR: #1552

**Comment by mindctrl** [comment]
This looks right, but I'm having issues with PayPal sandbox - of course! Will circle back around to this later.
