### ISSUE TITLE
Free user can't view post restricted to "specific levels" if one is paid

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1569]
Set up post restrictions for `Members of specific subscription levels` and select at least two levels: one free one and one paid. When a user is on the paid plan they can see the content, but when a user is on the free plan they cannot.

See this block: https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L1313-L1318

Basically if one of the levels is paid, then it suddenly becomes a requirement that the user be on a paid level to view the content.

Is there a reason we need that block at all?

**Comment by mindctrl** [comment]
Yeah, that seems... wrong. We should only require paid if 'any paid' is chosen.

**Comment by nosegraze** [comment]
PR: #1576

**Comment by mindctrl** [comment]
Punting to 2.9.8 so we can get more eyeballs on this.
