### ISSUE TITLE
Stripe: member is charged for old overdue subscriptions before they're being cancelled

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1570]
Related to https://github.com/restrictcontentpro/restrict-content-pro/issues/962

When a user has an existing subscription in Stripe that is overdue then signs up for a new subscription or to manually renew, the flow goes like this:

- Register form.
- New card is added to Stripe customer.
- Stripe uses this new card to pay the outstanding invoice. <-- bad
- Old subscription is then cancelled by RCP.
- New subscription is then added and charged.

We've correctly gotten the old subscription cancelled, but the user is still being charged twice initially.

**Comment by mindctrl** [comment]
EDD Recurring had a similar issue, where we had to close unpaid invoices when cancelling. https://github.com/easydigitaldownloads/edd-recurring/issues/850

**Comment by mindctrl** [comment]
Stripe recommends deleting the invoices.

> When a subscription has pending invoice items you’ve created, the customer is still billed for those even after the subscription is canceled. To avoid that final charge, manually delete the invoice items.

https://stripe.com/docs/subscriptions/canceling-pausing

https://stripe.com/docs/api#delete_invoiceitem

**Comment by nosegraze** [comment]
We can certainly delete the invoices too but I don't think that would fix the problem. The core issue is that before we even start the process of cancelling, we add a new card to the customer in Stripe. This then immediately prompts Stripe to pay outstanding invoices. Then we proceed with cancelling subscriptions (at this point they've already now been paid up), and then we create and charge a whole new subscription.

So it seems like what we really need to do is:

- Cancel old subscriptions (and delete invoices).
- Then add new card.
- Then create new subscription.

But we'll also have to consider how this works if the new card they add isn't actually approved, but we've already cancelled their old subscription.

**Comment by mindctrl** [comment]
I think there's a delay between saving the card and when they start paying them. In my tests with EDD Recurring, the closed invoices didn't get paid before being closed.

But I think we should probably just cancel the existing sub and delete the invoices before saving the card. If someone fails during registration and we cancelled their existing sub already, that's on them to redo the registration to have an active sub... I think.

**Comment by nosegraze** [comment]
A customer sent me a screenshot of their event log. It goes like this:

```
x added a new Visa ending in xxx - 2017/11/10 15:27:15
x was charged $9.99 - 2017/11/10 15:27:17
x's subscription to y was canceled - 2017/11/10 15:27:19
x subscribed to the y plan 2017/11/10 15:27:20
```

I edited out a few duplicate entries, but that shows you the exact sequence of events during an RCP registration, all within seconds of each other. Card was added, overdue invoice immediately paid within 2 seconds, then the old subscription was cancelled, then the new one was added.

I have the full screenshot in Slack if you want to take a look.

**Comment by nosegraze** [comment]
Got another report of this. Same exact events.

**Comment by thomasfw** [comment]
Please fix this, it’s been open for months now in one form or another and honestly I don’t get why it’s not more of a priority. If the plugin was free maybe I’d understand the complete lack of urgency, but it’s not. 

I’d argue that when an issue arises that has the potential to effect people’s finances, it should be patched in a matter of days rather than released whenever the next version is penned in for. 

In our case, were not seeing duplicate payments amounting to $10/20, we’re pulling $400 from our members bank accounts rather than the $200 they’ve agreed to.

**Comment by pippinsplugins** [comment]
@thomasfw This _is_ a priority. The problem, however, is that it is exceptionally difficult to fix and we have not so far found a reliable way to fix it that does not have some potentially really bad side effects.

It is still being worked on and will be included in a release as soon as we have a reliable fix for it.

**Comment by nosegraze** [comment]
I'm not sure if we should still cancel the associated invoices because we set `'at_period_end' => false` (whereas EDD Recurring does `'at_period_end' => true`).

**Comment by pippinsplugins** [comment]
@nosegraze to help prevent failed upgrades where the card is declined and the previous subscription cancelled, could we add an authorization request to the card prior to cancelling the old subscriptions? We could then only cancel the subs if the authorization request succeeds.

https://stripe.com/docs/charges#auth-and-capture

**Comment by nosegraze** [comment]
@pippinsplugins The full process of authorize -> cancel subs -> capture would work perfectly for one-off transactions, but for subscriptions am I right in thinking it'd be more like authorize -> cancel subs -> create new sub -> never capture authorization so it expires after 7 days? That's definitely doable but can sometimes be confusing for end users to see the authorized payment in addition to the real payment.

**Comment by pippinsplugins** [comment]
Yeah that's not awesome for subs.

What if we authorized a 0.01 transaction and then cancelled the authorization? That doesn't guarantee a full price charge will go through but it at least makes it less likely for it to fail.

**Comment by mindctrl** [comment]
I'm not sure we should care about if the new sub fails after the old one is cancelled. The member clearly did not want the old subscription. Presumably any errors during registration will be rectified by the member trying again.

What would happen if we close all the invoices for the existing subscription, save the card, create the new subscription, then cancel the existing one only if the new one is successful? It seems like that shouldn't result in a double billing since all the invoices are closed.

**Comment by nosegraze** [comment]
@mindctrl Is this what you had in mind? #1594

I'm fine with either method. In terms of pure code organization I think I prefer the other PR, as everything feels more grouped into one place rather than split between before/after adding the card. But I'm fine with either.

**Comment by mindctrl** [comment]
@nosegraze will review both approaches and test by Monday. Would like to get this live early next week.

**Comment by mindctrl** [comment]
The original #1592 works great and I like that it's grouped together and does not make extra API calls for invoice closing. @nosegraze if you're happy with it, I'll do a little more testing and merge.

**Comment by nosegraze** [comment]
I'm happy with it. The only question is whether or not we want to add the card authorization feature. We could also just open a separate issue to consider that.

**Comment by mindctrl** [comment]
Working great for me. We can open a new issue for card auth if needed.
