### ISSUE TITLE
Original timestamp is lost when editing payments

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1571]
When editing a payment in the admin, the original timestamp is overwritten. Also there's an inconsistency in the display of date/time on payments.

- Payments list page shows both date and time
- Edit page shows date only

When saving a payment, even if you don't touch the date, the timestamp gets lost. The timestamp always gets set to now, whether you change the date field or not. The date is not changed, just the timestamp.

What happens if you do touch the date:
- Set date with picker. Date with no time is inserted into field.
- When saved this way, the date is saved as inserted but the time is set to now.
- When the time is manually input with the date, the time is still set to now. There's currently no way to set/fix the time on a payment in the admin UI.

What happens if you do not touch the date:
- Date is not changed. Time is always set to now.

**Comment by nosegraze** [comment]
PR: #1584
