### ISSUE TITLE
First/last name not saved to customer profile on Braintree

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1577]
The Braintree gateway grabs the first/last from `$this->subscription_data['post_data']['rcp_user_first']`.

[Reference](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.6/includes/gateways/class-rcp-payment-gateway-braintree.php#L129-L130).

This is empty if the user is already logged in, since the fields aren't on the registration form, and if their first registration didn't use Braintree, the newly-created Braintree customer record won't have a first/last name.

We should change that to get the user data from the user object.

**Comment by nosegraze** [comment]
PR: #1583
