### ISSUE TITLE
Get all User Roles for metabox's User Level setting

### ISSUE THREAD

**Issue by cliffordp** [restrictcontentpro/restrict-content-pro#158]
I'm unclear if "User Level" is referring to WordPress' user roles, but I think it is.
If it is, then shouldn't it display all user roles, not just a hard-coded list of the default ones?

References:
- https://github.com/pippinsplugins/Restrict-Content-Pro/blob/master/includes/admin/metabox.php#L56
- http://codex.wordpress.org/Function_Reference/get_editable_roles

**Comment by pippinsplugins** [comment]
It is default user roles. Custom roles aren't supported yet.

**Comment by pippinsplugins** [comment]
Another request https://secure.helpscout.net/conversation/243086775/40810/?folderId=841776

**Comment by mindctrl** [comment]
Started this in `issue/158`, but we need to consider what we'll do inside `includes/content-filters.php`.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by nosegraze** [comment]
Can't we merge this as-is now that we got rid of that big `rcp_user_level_checks()` function in `content-filters.php` ?

**Comment by nosegraze** [comment]
PR: #1156

**Comment by pippinsplugins** [comment]
@nosegraze can you test this with a non-English site to ensure the translated role names work properly.

**Comment by nosegraze** [comment]
@pippinsplugins Still works perfectly! The `value` in the metabox dropdown is actually more like a role ID so that doesn't get translated (the first parameter [here](https://codex.wordpress.org/Function_Reference/add_role)). They call it a name but really it's an ID.

**Comment by pippinsplugins** [comment]
Excellent :+1:
