### ISSUE TITLE
Password reset links do not work with SendGrid click tracking

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1585]
SendGrid click tracking converts `&` to `#038;`, and that breaks the reset links. EDD has experienced [similar issues](http://docs.easydigitaldownloads.com/article/1085-file-download-links-dont-work-with-sendgrid).

We could try URL encoding the query strings to see if that'll work.

**Comment by nosegraze** [comment]
@mindctrl Can you reproduce this?

I have seen this error on a customer's site so I believe that it happened, but I just set up SendGrid myself, enabled link tracking, requested a password reset,and the `&` symbols worked just fine.

**Comment by mindctrl** [comment]
@nosegraze I haven't tried it in a while. I'll give it another try. Are you using HTML or plain email template?

**Comment by nosegraze** [comment]
I'm using HTML.

**Comment by nosegraze** [comment]
Oh wait I got it.

The SendGrid plugin I was using had the content type set to HTML, so it was actually being sent as HTML in the end, but my RCP template was set as plain text. With those settings it worked fine. When I switch the RCP template to HTML it breaks.

**Comment by nosegraze** [comment]
I think this is something funky going on in `make_clickable()`. If you formulate the URL manually it works perfectly fine. If you let `make_clickable()` handle it, that's when it breaks.

**Comment by mindctrl** [comment]
@nosegraze I think that's our best bet.

**Comment by nosegraze** [comment]
PR: #1708

**Comment by pippinsplugins** [comment]
@mindctrl @nosegraze could one of you please carry this over to EDD's `EDD_Emails` class as well as AffiliateWP? Both will have the exact same issue.

**Comment by mindctrl** [comment]
Merged. Opening issues in EDD and AffWP.
