### ISSUE TITLE
How to create a custom gateway

### ISSUE THREAD

**Issue by tahmasebi** [restrictcontentpro/restrict-content-pro#1589]
Hi, 
I want to create a custom gateway, that gateway works like this:

1- redirect user to gateway URL 
2- return to our site and verify payment

sample codes are like this:

redirect to gateway url:

    $api = 'API';
    $amount = 'Amount';
    $redirect = 'Callback';
    $factorNumber = 123;
    $result = send($api,$amount,$redirect,$factorNumber);
    $result = json_decode($result);
    if($result->status) {
	    $go = "https://pay.ir/payment/gateway/$result->transId";
	    header("Location: $go");
    } else {
    	    echo $result->errorMessage;
    }

return and verify payment:

    $api = 'API';
    $transId = $_POST['transId'];
    $result = verify($api,$transId);
    $result = json_decode($result);
    echo $result;

I don't find any clear documentation to create my custom gateway.

I found this [plugin](https://github.com/payir-plugins/wordpress-restrict-content-pro/blob/master/class-restrict-content-pro-payir.php) , but I think it's not in the standard way!

How to implement this gateway? and why I should implement user registration in gateway plugin?!!

Thanks :)

**Comment by mindctrl** [comment]
Hi @tahmasebi, 

You can read about our payment gateway API here: http://docs.restrictcontentpro.com/article/1695-payment-gateway-api

If you need help building it, considering hiring a consultant. We have some recommended ones here: https://restrictcontentpro.com/consultants/
