### ISSUE TITLE
restricting an entire post type not always works

### ISSUE THREAD

**Issue by colomet** [restrictcontentpro/restrict-content-pro#1604]
http://docs.restrictcontentpro.com/article/1906-restricting-an-entire-post-type

Some plugins (CPT oriented) works perfect. Like https://es.wordpress.org/plugins/wp-job-manager/
![captura de pantalla 2017-12-18 a las 12 01 33](https://user-images.githubusercontent.com/3929177/34103050-9c15ff5e-e3eb-11e7-849d-2fe95d451579.png)

But some times. other plugins with CPT, do not offer the same protection option.

Like https://es.wordpress.org/plugins/easy-pricing-tables/ or others
![captura de pantalla 2017-12-18 a las 12 00 55](https://user-images.githubusercontent.com/3929177/34103061-aa2cd658-e3eb-11e7-8a03-dd01aa7adc65.png)
![captura de pantalla 2017-12-18 a las 12 01 08](https://user-images.githubusercontent.com/3929177/34103062-aa4c84e4-e3eb-11e7-98bb-616ff4c66eae.png)

**Comment by nosegraze** [comment]
Hi @colomet ,

We add the "Restrict Access" menu item to all post types with the following parameters:

```php
'public'  => true,
'show_ui' => true
```

If the post type doesn't have those two settings, then RCP doesn't add the menu option.

We have a tutorial here that demonstrates how you can add the restriction and metabox to another post type: http://docs.restrictcontentpro.com/article/1750-rcp-metabox-post-types
