### ISSUE TITLE
Enable PayPal Express In-Context Flow

### ISSUE THREAD

**Issue by brandomeniconi** [restrictcontentpro/restrict-content-pro#1605]
Hi,
our data analytics team has raised this problem: when a user selects the PayPal Express payment method its been redirected to the PayPal website, this causes Google Analytics to track PayPal as a new referral source and it's impossible to determine from which ad campaign the purchase has been genereated.

We have tried many things but the only solution we came so far is to implement the [PayPal Express In-Context Flow](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/) that uses a popup instead of a hard redirect.

Does RCP support this payment flow or there is any quick fix to force PayPal to open in a new tab?

**Comment by mindctrl** [comment]
@brandomeniconi we use GitHub for development tracking only. Please open any support requests at https://restrictcontentpro.com/support.

**Comment by brandomeniconi** [comment]
Ok, just to clarify 😉. I was asking if there is any plan to upgrade to the latest PayPal Express spec, the one that RCP is using now it has been [deprecated](https://developer.paypal.com/docs/classic/express-checkout/ht_ec-singleItemPayment-curl-etc/) since 1 Jan, 2017.
