### ISSUE TITLE
Identify RCP pages in the list table screen

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1617]
Some plugins, like WooCommerce, identify their pages in the Pages > All Pages list view.

Example, note the "Cart Page" and "Checkout Page" hints after the linked title:
![image](https://user-images.githubusercontent.com/1254870/34445610-e55cd9ca-eca2-11e7-9e0f-3440f4fbd81a.png)

I find this a useful hint when logged into customer sites, and think it could be useful for us to do the same.

We can use the `display_post_states` filter to do this.

**Comment by pippinsplugins** [comment]
One small change on the PR please, otherwise this looks and works great!
