### ISSUE TITLE
Support object_id in RCP_Payments::count()

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1620]
It would be helpful to support `object_id` in `RCP_Payments::count()`.

We support `subscription` via the `s` argument, but that's less than ideal since it relies on the name not having been changed to be completely accurate.

Use case: counting all of a user's payments for a specific object_id. For example, filling the `times_billed` column in the new subscription table.

A possible issue with this would be cases where `RCP_Payments::backfill_payment_data()` hasn't run on all the payments for the user. I wouldn't mind doing an upgrade routine for this, which would also be helpful when we improve reports.

**Comment by nosegraze** [comment]
PR: #1721
