### ISSUE TITLE
rcp_stripe_charge_succeeded action is not firing

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#1622]
After updating from 2.8.6 to 2.9.7 some of our custom functionality has broken. As far as I can see the culprit is the `rcp_stripe_charge_succeeded` action no longer firing?

I've tested this for payments initiated by new registrations (both one-off payment and recurring) by adding this hook.

```php
add_action( 'rcp_stripe_charge_succeeded', 'ilts_test_rcp_hook' );
function ilts_test_rcp_hook()
{
    rcp_log( "Hook fired on 'rcp_stripe_charge_succeeded'" );
}
```

I'd expect to see something in the log but there's nothing there. Here's the debug log for a new registration payment:

```
2018-1-06 13:26:28 - Started new registration for subscription #2 via stripe.
2018-1-06 13:26:30 - Started new registration for subscription #2 via stripe.
2018-1-06 13:26:31 - New payment inserted. ID: 645; User ID: 17366; Amount: 190.00; Subscription: Regular Membership; Status: pending
2018-1-06 13:26:31 - Member #17366 status set to pending.
2018-1-06 13:26:31 - Registration for user #17366 sent to gateway. Level ID: 2; Initial Amount: 190.00; Recurring Amount: 190.00; Auto Renew: false
2018-1-06 13:26:33 - Starting to process Stripe webhook.
2018-1-06 13:26:34 - Updating payment #645 with new data: array (
  'payment_type' => 'Credit Card One Time',
  'transaction_id' => 'ch_1BhHgzIQ9UyUhi0xlRD161MZ',
  'status' => 'complete',
)
2018-1-06 13:26:34 - Completing registration for member #17366 via payment #645.
2018-1-06 13:26:34 - Exiting Stripe webhook - no customer attached to event.
2018-1-06 13:26:35 - wp_mail() failure in RCP_Emails class.
2018-1-06 13:26:35 - Active email sent to user #17366.
2018-1-06 13:26:35 - Active email not sent to admin(s) - message is empty.
2018-1-06 13:26:35 - Member #17366 status changed from pending to active.
2018-1-06 13:26:35 - Updating recurring status for member #17366. Previous: false; New: false
2018-1-06 13:26:36 - wp_mail() failure in RCP_Emails class.
2018-1-06 13:26:36 - Payment Received email sent to user #17366.
2018-1-06 13:26:36 - Payment #645 completed for member #17366 via Stripe gateway.
2018-1-06 13:26:36 - Updating recurring status for member #17366. Previous: false; New: false
2018-1-06 13:26:36 - Starting to process Stripe webhook.
2018-1-06 13:26:37 - Starting to process Stripe webhook.
2018-1-06 13:26:37 - Exiting Stripe webhook - no customer attached to event.
2018-1-06 13:26:37 - Processing webhook for member #17366.
2018-1-06 13:26:37 - Processing Stripe charge.succeeded webhook.
2018-1-06 13:26:37 - A duplicate payment was detected for user #17366. Check to make sure both payments weren't recorded. Transaction ID: ch_1BhHgzIQ9UyUhi0xlRD161MZ
2018-1-06 13:26:38 - Starting to process Stripe webhook.
2018-1-06 13:26:38 - Processing webhook for member #17366.
2018-1-06 13:26:43 - Starting to process Stripe webhook.
2018-1-06 13:26:43 - Exiting Stripe webhook - no customer attached to event.
```

Here's the event log for this same member in Stripe:

![screen shot 2018-01-06 at 20 38 55](https://user-images.githubusercontent.com/7723105/34640277-25082018-f322-11e7-8505-6bc9fdade55b.jpg)

The webhook response for the `customer.created` event (evt_1BhHgxIQ9UyUhi0xTAXOTna4) is "no customer attached".

The webhook response for the `customer.updated` event (evt_1BhHgyIQ9UyUhi0ximOHMObO) is
"no customer attached".

The webhook response for the `customer.source.created` event (evt_1BhHgyIQ9UyUhi0xsaRuD6A7) is
"1".

The webhook response for the `charge.succeeded` event (evt_1BhHgzIQ9UyUhi0x8E30F2Zc) is "duplicate payment found".

The webhook response for the `
customer.updated` event (evt_1BhHh2IQ9UyUhi0x7jcFSSU9) is "no customer attached".

From the rcp log it looks like the payment is being recorded before the `charge.succeeded` webhook event is processed (looks like it's being stored in the first event `customer.created`?), so the duplicate payment check returning true prevents the `rcp_stripe_charge_succeeded` and `rcp_stripe_charge_succeeded` hooks from firing when they're supposed to?

---

I also just realised the "Started new registration for subscription 2 via stripe" appears twice at the start of the log, is that supposed to happen?

**Comment by thomasfw** [comment]
Looks like the payment is stored in [process_signup()](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/gateways/class-rcp-payment-gateway-stripe.php#L295), at which point the `rcp_gateway_payment_processed` action is defined, but `rcp_stripe_charge_succeeded` isn't.

**Comment by nosegraze** [comment]
Do you specifically need to use `rcp_stripe_charge_succeeded` rather than `rcp_gateway_payment_processed`?

It looks like `rcp_stripe_charge_succeeded` never fired for one-time payments, though it did used to for recurring ones.

Fixing this would require that we copy the hook into `process_signup()` as well, and I'm just wondering if that would make the action no longer really accurate for what it's representing (the `charge.succeeded` or `invoice.payment_succeeded` webhook coming through).

**Comment by thomasfw** [comment]
We're using a different hook for this now. I think this is probably a non-issue for the reasons you mentioned.

**Comment by nosegraze** [comment]
Thanks for confirming!
