### ISSUE TITLE
Member receiving "cancelled subscription" email when renewing expired membership

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1626]
User notes for affected member:

```
December 13, 2017 05:39:50 - Member's status changed from active to expired

December 19, 2017 09:58:48 - Recurring charge failed in Stripe. Event ID: evt_xxx

January 13, 2018 10:58:50 - Member's status changed from expired to pending

January 13, 2018 10:58:59 - Member's status changed from pending to cancelled

January 13, 2018 10:59:00 - Annual Story Art Education subscription renewed.

January 13, 2018 10:59:00 - Member's expiration changed from 2017-12-10 23:59:59 to 2019-01-13 23:59:59

January 13, 2018 10:59:01 - Member's status changed from cancelled to active
```

It looks like the webhook for the cancellation came in before the new signup was finished processing, so this `if` statement in `process_webhook()` still evaluated to `true` : 

```php
if( $payment_event->id == $member->get_merchant_subscription_id() ) {

	$member->cancel();

	do_action( 'rcp_webhook_cancel', $member, $this );

	die( 'member cancelled successfully' );

}
```

One thing to note is that even checking for `RCP_Member::just_upgraded()` wouldn't fix this, as users don't get flagged as that when they've expired.

We could just let this sit until we finish multiple memberships. How we approach that might just fix this problem on its own.

**Comment by thomasfw** [comment]
Was just about to report this. Please don't just let it sit, first thought is maybe adding a `suppress_email` argument to gateway metadata which can be checked in the webhook listener?

**Comment by mindctrl** [comment]
What if when processing the signup we didn't cancel the subscription if they're buying/renewing the same plan? We'd probably have to delete all the outstanding invoices on that subscription because of the setting in Stripe that allows people to infinitely accumulate unpaid/past due invoices.

**Comment by nosegraze** [comment]
I'm not sure if that would fully solve the problem. It would fix it if they were renewing, but not if they were upgrading to a different plan. I think this problem could still theoretically occur during an upgrade as well.

**Comment by nosegraze** [comment]
PR: #1635

I have no idea if this works because I wasn't able to actually reproduce the problem. I feel like I have seen it once before but I couldn't get it to happen for me this time. But I think theoretically this might work... that meta flag should be set whenever someone goes through the registration form, so the `if` statement has been modified to only run if that flag is not present.

```php
if( $payment_event->id == $member->get_merchant_subscription_id() && ! get_user_meta( $member->ID, '_rcp_new_subscription', true ) ) {

	$member->cancel();

	do_action( 'rcp_webhook_cancel', $member, $this );

	die( 'member cancelled successfully' );

}
```
