### ISSUE TITLE
 Add support for taxes

### ISSUE THREAD

**Issue by brandomeniconi** [restrictcontentpro/restrict-content-pro#1631]
Add support for tax rates that can be added to the final price and showed to the user.  B2B prices in our country usually are shown without taxes (our theme handles the deduction) but managing discounts codes its a nightmare because are applied to the final price (with taxes).

**Comment by mindctrl** [comment]
@brandomeniconi at this time we have no plans to add support for taxes. However, there are a couple third party tax add-ons here: https://restrictcontentpro.com/add-ons/3rd-party/
