### ISSUE TITLE
array_key_exists() error when get_post_type() returns false

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1640]
We've gotten two reports of this error message:

```
Warning: array_key_exists(): The first argument should be either a string or integer in /home/fccc4476/public_html/wp-content/plugins/restrict-content-pro/includes/misc-functions.php on line 801
```

Line 801 is the return line here: https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/misc-functions.php#L799-L802

```php
return array_key_exists( $post_type, $restricted_post_types ) ? $restricted_post_types[ $post_type ] : array();
```

I haven't been able to reproduce this myself, but I suspect `$post_type` is `false` for some reason. `$post_type` comes from using `get_post_type()` elsewhere and passing that value into this function. `get_post_type()` can return `false` on failure.

We could just return an empty array early if `$post_type` is empty.

**Comment by nosegraze** [comment]
PR: #1641

I sent this to one of the customers experiencing the problem. Will update when I hear back to confirm it fixes the problem. He ran into it while running a PHP script outside the scope of WordPress so it's clearly an edge case.

**Comment by mindctrl** [comment]
Looks good. Let's merge when you hear back that it's working.

**Comment by nosegraze** [comment]
Got confirmation from one of the two customers that this fixed the problem.
