### ISSUE TITLE
Links and other tags are stripped from email content

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#1648]
As far as I can tell email text is run through `wp_strip_all_tags`, so our links added to various emails are stripped out. Is there a reason for this?

**Comment by nosegraze** [comment]
They should only be stripped if you have _"No template, plain text only"_ selected.

**Comment by thomasfw** [comment]
Our website is sending lots of transactional emails, not just those from RCP, so we're using a separate plugin to handle HTML email templating. We have "No template, plain text only" turned on for that reason.

Is there some way this can be made compatible?

**Comment by nosegraze** [comment]
I think the best move for you would be to create a custom template that's bare bones and use that instead. See here for instructions: http://docs.restrictcontentpro.com/article/1760-rcp-email-templates

When the "plain text" option is selected, our email headers don't support HTML so that's why we strip out tags.

**Comment by thomasfw** [comment]
Okay, so my **header.php** and **footer.php** email templates will be empty files, and **body.php** will just contain the `{email}` tag?

If I wanted to enforce this custom template am I right in thinking i'd use the `rcp_email_template` filter to make sure the template dropdown in _RCP > Settings > Emails_ is ignored. Something like this?
 
```php
// Add the new template
add_filter( 'rcp_email_templates', 'my_add_rcp_email_template' );
function my_add_rcp_email_template( $templates ) 
{
    $templates['wp-html-mail-compatability'] = 'WP HTML Mail';
    return $templates;
}

// Enforce template
add_filter( 'rcp_email_template', 'my_rcp_enforce_email_template' );
function my_rcp_enforce_email_template( $template ) 
{
    return 'wp-html-mail-compatability';
}
```

**Comment by nosegraze** [comment]
Yes that's right. If you have further questions you can submit a support ticket and we can discuss there: https://restrictcontentpro.com/support/
