### ISSUE TITLE
$wpdb->paymentmeta table name param conflicting with Give

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1656]
See: https://github.com/WordImpress/Give/issues/2710

**Comment by nosegraze** [comment]
PR: #1657

This change will require that we change the `payment_id` column name in the payment meta table to `rcp_payment_id`.

**Comment by mindctrl** [comment]
Just a reminder so we don't forget, we'll need a quick upgrade routine to change the column name on existing installs.

**Comment by mindctrl** [comment]
Known plugins that use payment meta below. Please add to this comment if you find others.

- https://plugins.svn.wordpress.org/rcp-mollie-addon/trunk/inc/gateway/class-rcp-payment-gateway-mollie.php

**Comment by mindctrl** [comment]
For people doing direct queries, we could use the `query` filter to rewrite the column name in the query string, but that feels like a hack. That filter can easily run 100+ times on an index page.

Also, that only fixes half the problem. If someone is doing direct queries and checking for `payment_id` in the results object/array, the `query` filter wouldn't fix the problem. As far as I know there aren't any filters for the return values in `$wpdb` queries.

In any case, we need to announce this change ahead of time and reach out to the plugin authors we know about. They can update any code "on both ends" of the query, if they need to update anything at all.

**Comment by nosegraze** [comment]
It seems annoying and hacky to use the `query` filter when it may not even 100% fix the issue.

Given the low number of users this impacts, we could punt this to `3.0` so it's seen as more of a major change (and it will have a beta for people to test beforehand).

**Comment by mindctrl** [comment]
Agreed. I just changed the milestone and the merge path for the PR.

**Comment by mindctrl** [comment]
Opened a new PR here because the other one was showing tons of unrelated stuff. I just realized I updated the version # wrong in the upgrade routine. Will update that now.
