### ISSUE TITLE
Stripe: Plan object changes in the latest API version

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1658]
Stripe has deprecated `statement_descriptor` and `name` on the plan object. They have moved these to product objects.

https://stripe.com/docs/upgrades#2018-02-05

> Each plan object is now linked to a product object with type=service. The plan object fields statement_descriptor and name attributes have been moved to product objects. Creating a plan now requires passing a product attribute to POST /v1/plans. This may be either an existing product ID or a dictionary of product fields, so that you may continue to create plans without separately creating products.

We'll need to update to account for these changes.

**Comment by nosegraze** [comment]
This change completely breaks registering via RCP if the plan hasn't already been created in Stripe. You get a `wp_die()` with the following error:

```
An error occurred
Status: 400

Message: Received unknown parameter: name
```

**Comment by nosegraze** [comment]
PR: #1660

The docs say the `type` argument is required and should be `service`, but whenever I included it I got this error:

> Received unknown parameter: product[type]

So I don't know what's up with that. But I tested this PR on API version `2017-06-05` and `2018-02-06` and both worked.

**Comment by mindctrl** [comment]
I got the same error with the product type param, while still on the old API version. I have not tested it with the new one.

Something I think is weird is that the product that gets created does not show up under products. You can only access it if you click the product name in the event data for the plan creation request. I don't know if they normally hide service products, or if that's a quirk related to how we're doing this.

**Comment by nosegraze** [comment]
When I'm on the _old_ API version I don't see the product easily. But when I upgrade to the new API version there's a new menu item for it in my dashboard.

**Comment by mindctrl** [comment]
I just updated to the new API and I still get the error with product type enabled. That's so weird.

I see a Products menu item, but the product itself doesn't show up there.

**Comment by mindctrl** [comment]
Yep, I think you're right. I was blinded by the big orange REQUIRED text on the `name` field. Going to test.

**Comment by mindctrl** [comment]
I updated the PR with that and it seems to be working fine. It could use another round of tests though before we ship it.

**Comment by mindctrl** [comment]
I'm also wondering if we should just force set the api version with `\Stripe\Stripe::setApiVersion()` to avoid breaks like this in the future.

**Comment by nosegraze** [comment]
I like that idea. I didn't even know you could do that lol.

I'll give these changes a test tomorrow.

**Comment by mindctrl** [comment]
I tested to confirm that you can set the api version to one newer than the account is set to, which is nice since we can't possibly know the version set in an account. I've seen them dated back years.

I've updated the PR to specify the API version so we don't get caught by this again. We can update it going forward after we've confirmed our integration works with their updates.

I also went ahead and simplified the logic that sets the api key and moved the `setAppInfo` call to `init()`.

**Comment by nosegraze** [comment]
I re-tested this on both API versions `2017-06-05` and `2018-02-06` on my account and it worked fine.

**Comment by mindctrl** [comment]
Renewal payments are working as expected.

The only weird thing I'm seeing is at the top of the customer record in Stripe.

![image](https://user-images.githubusercontent.com/1254870/36050140-4a7778de-0db3-11e8-9b12-d6331a06d9aa.png)

The `Subscribed to` text is missing the plan name, however it's listed in the customer's subscriptions section, and both the plan and product have the name. 

It seems like a UI bug, but I'm going to reach out to Stripe and make sure we're not missing something before we merge this.

**Comment by mindctrl** [comment]
It's a Stripe UI bug.

> This indeed is a UI bug in our Subscriptions Dashboard. Thank you again for letting us know about it! Our developers have been notified of this and will be working to push through a fix. I will let you know as soon as we have resolved this issue!

Merging.
