### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by johnpwooton** [restrictcontentpro/restrict-content-pro#1672]
I've got a client that has their subscription fee set to $1 and their sign-up fee set to $-1 (so that they cancel each other out when the customer registers). They then have their gateway set as Stripe. When the customer signs up, they see a fatal error: 

`Fatal error: Uncaught Error: Class name must be a valid object or a string in wp-content/plugins/restrict-content-pro/includes/gateways/gateway-functions.php:95 `

`Stack trace: 
0 wp-content/plugins/restrict-content-pro/includes/registration-functions.php(307): rcp_send_to_gateway(false, Array) 
1 wp-includes/class-wp-hook.php(298): rcp_process_registration('') 
2 wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) 
3 wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
4 wp-settings.php(448): do_action('init') 
5 wp-config.php(41): require_once('/srv/users/serv...') 
6 wp-load. in wp-content/plugins/restrict-content-pro/includes/gateways/gateway-functions.php on line 95`

I traced it back to a few things: 

/includes/registration-functions.php (lines 53-56)
`// Change gateway to "free" if this subscription doesn't require payment.
if ( $full_discount || empty( $price ) ) {
	$gateway = 'free';
}`

and then in /includes/gateway-functions.php: (lines 95)
`$gateway  = new $gateway['class']( $subscription_data );`

It attempts to set the gateway class from the get_gateways() array in the RCP_Payment_Gateways class, but in our case, the gateway appears to have been set as "free" and there's no "free" option or class within the get_gateways() array. This is what ultimately causes the fatal error.

**Comment by nosegraze** [comment]
Although this error is slightly different, it's related to https://github.com/restrictcontentpro/restrict-content-pro/issues/1023 so I'm going to close this. They're both related to the same fundamental issue, which is that if you have an initial payment of `$0` due to a one-time discount, negative signup fee, or prorated credits, the registration form doesn't work. This is something we're working on!
