### ISSUE TITLE
No [login_form] shortcode on login page unchecks settings option - but I use do_shortcode in PHP

### ISSUE THREAD

**Issue by DeveloperWil** [restrictcontentpro/restrict-content-pro#1674]
It's nice that RCP checks the chosen page in Settings > Misc > Redirect Default Login URL for a [login_form] shortcode.

However, I have a custom login form template in Genesis which uses do_shortcode( '[login_form]');

Luckily I don't need to use the post_content for my template so I can put the shortcode in the editor window.  I don't think it should uncheck the option - maybe a warning yes.

Unless you want to check the post content for the login form don't assume that the lack of shortcode in the content editor means that the login shortcode is not being done in PHP.

**Comment by mindctrl** [comment]
We do this to prevent people from locking themselves out of their sites. If they enable the login redirect option and don't have the shortcode in their page, they would effectively be locked out of their sites. I don't really see a way to not check the `post_content` for the shortcode and still safely apply the redirect setting.
