### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1677]
We're adding support for [Stripe Connect](https://stripe.com/docs/connect).

I'll update this issue later with a list of tasks we must complete.

**Comment by mindctrl** [comment]
Connect has 3 different account types: Standard, Express, and Custom. I'm working my way through all the Connect docs before writing any code, but I think we want Standard.

Table below taken from https://stripe.com/docs/connect/accounts
<table>
    <thead>
    <tr>
      <th>&nbsp;</th>
      <th style="width:24%;">Standard</th>
      <th style="width:22%;">Express</th>
      <th style="width:18%;">Custom</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><strong>Integration effort</strong></td>
      <td>Lowest</td>
      <td>Low</td>
      <td>Typically higher</td>
    </tr>
    <tr>
      <td><strong>Integration method</strong></td>
      <td>OAuth integration</td>
      <td>OAuth integration</td>
      <td>API-only</td>
    </tr>
    <tr>
      <td><strong>Fraud and dispute liability</strong></td>
      <td>User</td>
      <td>Platform</td>
      <td>Platform</td>
    </tr>
    <tr>
      <td><strong>Platform can specify payout timing?</strong></td>
      <td>No</td>
      <td>Yes</td>
      <td>Yes</td>
    </tr>
    <tr>
      <td><strong>Onboarding</strong></td>
      <td>Stripe</td>
      <td>Stripe</td>
      <td>Platform</td>
    </tr>
    <tr>
      <td><strong>Identity information gathering</strong></td>
      <td>Stripe</td>
      <td>Stripe</td>
      <td>Platform</td>
    </tr>
    <tr>
      <td><strong>User can access the Stripe Dashboard?</strong></td>
      <td>Yes, full Stripe Dashboard</td>
      <td>Yes, Express Dashboard</td>
      <td>No</td>
    </tr>
    <tr>
      <td><strong>User support provided by</strong></td>
      <td>Platform and Stripe</td>
      <td>Platform and Stripe</td>
      <td>Platform</td>
    </tr>
    <tr>
      <td><strong>Ideal for users that are</strong></td>
      <td>Experienced online businesses</td>
      <td>Any type</td>
      <td>Any type</td>
    </tr>
    </tbody>
  </table>

**Comment by pippinsplugins** [comment]
I agree, we want Standard based on my understanding of the three types.

**Comment by pippinsplugins** [comment]
Could we adjust this a little bit?
![image](https://user-images.githubusercontent.com/1034109/38122439-99004b54-339a-11e8-840d-beba6e96532e.png)

It's best that all sites get connected via Connect. When not already connected, could we please hide the API key fields and then add some descriptive text to help the user know what's going to happen?

**Comment by pippinsplugins** [comment]
After authorizing Stripe, I was redirected back to my site and shown this:

![image](https://user-images.githubusercontent.com/1034109/38122500-0132380e-339b-11e8-9e5c-f45afed481f1.png)

There's a warning at the bottom of the page and a message that says `Completing your Stripe account setup...`.

**Comment by pippinsplugins** [comment]
Refreshing the screen shows that it did work. The API keys are present.

**Comment by mindctrl** [comment]
Will update to hide the api key fields.

The "Completing" message at the bottom is an artifact of how RCP's settings tabs work. I haven't seen it do that, so it could have been a speed issue with the RCP site response on the credential fetch. I'll see if I can do something different here.

That warning notice I've never seen. My guess is it's unrelated, but will dig into it.

**Comment by mindctrl** [comment]
If we hide/disable the api key fields, we'll need a way to unhide them in the case of someone deauthorizing the RCP app in the Stripe Connect Applications section of their Stripe accounts. Otherwise they won't be able to reconnect their accounts and/or enter their api keys.

Stripe sends a `account.application.deauthorized` webhook event to the host application - in this case restrictcontentpro.com. We would need to listen for those and send a request to the customer site so we can unset the api keys and/or show the Connect button again. I'll be working with this today.

**Comment by mindctrl** [comment]
It looks like the above idea won't work, as Stripe doesn't seem to send enough information to determine which customer deauthorized the application. Seems weird, like I'm missing something...

At any rate, the more I've thought about it, the more I don't like being in the middle of those types of requests. Too many possibilities for failure, or just not working at all in sandbox environments due to inaccessible local domains.

I think a good alternate approach would be to put a little link in the description that allows someone to easily unset the saved (hidden) Stripe keys and then show the Connect button again.

**Comment by nosegraze** [comment]
I'm fine with that link idea.

**Comment by mindctrl** [comment]
Updated PR as per above comments. Can I get another review and some testing?

**Comment by mindctrl** [comment]
Test note: you'll need to hard refresh your browser or clear the cache to get the CSS changes until we version bump.

**Comment by nosegraze** [comment]
Cancelling works well now, but the UX might be a little irksome because it completely removes the whole payments section unless you click _"try again"_. Some people might try clicking the tabs at the top to get back to the payment settings but the payments one won't actually show you the options anymore unless you click _"try again"_. Maybe we should put that error in an admin notice instead?

Connecting works well for me.

**Comment by mindctrl** [comment]
I tried that originally but because of the `#payments` bit in the URL, the browser jumps down the page to the div with that ID and the admin notice isn't visible.

If you load a notice manually inside the `#payments` div, WP core will rip it out and move it to the top.

We could load the settings page without `#payments`, but that loads the General tab and feels disconnected from the process.

Then I thought since this is an exceptional case where we want errors to be very visible we could just not load the full settings page to make sure people go "hmm something isn't right here".

**Comment by mindctrl** [comment]
I updated the PR to move the admin style notice above the settings tabs. I think it's a good compromise between what was there and a full `wp_die()`.

Screenshot:
![image](https://user-images.githubusercontent.com/1254870/38313541-512729c2-37f2-11e8-94fe-90e760f73a87.png)

**Comment by mindctrl** [comment]
I've emailed Stripe again to ask them to look at things and verify it works as required. Will report back when I hear from them.

**Comment by mindctrl** [comment]
Got confirmation from Stripe that all is well! Merged.

**Comment by chrisvanpatten** [comment]
Is there any way to revert back to text fields? Stripe Connect is slightly maddening in dev environments because you can't connect via Connect unless your Stripe account is fully activated.

**Comment by mindctrl** [comment]
@chrisvanpatten glad to hear you got it working. We're considering making an easier way to manage them manually.
