### ISSUE TITLE
Search functionality makes it hard to find members

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#1679]
If I have a member who has `wp_usermeta` values of `Judy` & `Smith` for the keys `first_name` and `last_name`, searching for `judy` or `smith` does not find this member when using the search form on `/wp-admin/admin.php?page=rcp-members`.

But, using the search form on `/wp-admin/users.php` does find the user account for this member.

Related, but a little different: when searching for a member who is expired, it's not immediately obvious that the user has been found, unless the person searching knows to scan the 5 status groups at the top of the page:

![rcpexpiredsearch](https://user-images.githubusercontent.com/796639/36330038-bff6c6f8-132d-11e8-9412-db1fee523137.jpg)

**Comment by mindctrl** [comment]
When we fix the name searching, I'd like to ditch the status filters at the top on search results views. I've seen people confused by this numerous times, and it's annoying to do an extra click to get to the results.

**Comment by tnorthcutt** [comment]
@mindctrl what about defaulting the search results to show all statuses, but still allow filtering? This would depend on https://github.com/restrictcontentpro/restrict-content-pro/issues/1562

**Comment by mindctrl** [comment]
I'm ok with that, just trying to think of a use case where searching for something results in a lot of results that you want to filter by status. Seems like an uncommon use case, but I definitely could be wrong.

**Comment by tnorthcutt** [comment]
Yeah, fair point.

**Comment by chrisvanpatten** [comment]
I think the problem increases as your community grows, and the less narrow your search is.

Another factor to consider: with multiple subscriptions on the roadmap, how will that affect filters? You might have users with subscriptions in multiple statuses.

**Comment by mindctrl** [comment]
That's a good point. We've discussed this internally, but the concept of status being tied to a member is probably going to have to go away. It doesn't really make sense with multiple subscriptions, and in some cases it would be tricky or impossible to "choose" a status to return.

A member is always a member... just a way to designate someone has some kind of membership. The membership status is the thing that matters.

**Comment by chrisvanpatten** [comment]
Yeah, it makes sense that in the future there might be separate "Members" and "Subscriptions" screens, similar to how Stripe handles it.

**Comment by tnorthcutt** [comment]
Turns out core user search also doesn't search on first or last names (🙄), but I did discover why RCP member search isn't as "good": the `LIKE` clauses it uses look like `'searchterm'` whereas a core user search looks like `'%searchterm'%`. So in RCP, searching for `john` wouldn't find a member with the email address `john@gmail.com`, but it would in WP core.

Still sorting out why/where this is different.

**Comment by tnorthcutt** [comment]
In [wp-admin/includes/class-wp-users-list-table.php](https://github.com/WordPress/WordPress/blob/d950c7530735035eb557f91fdde747a8a8e3dda8/wp-admin/includes/class-wp-users-list-table.php#L114-L116), core prepends and appends a `*` to non-empty user searches. We should probably do this too. I'm fixing up a PR for it.
