### ISSUE TITLE
Update login link text in registration templates

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1688]
Based on something a customer wanted to change, I think we should consider changing the text.

Our login text is currently this:

`Log in if you wish to renew an existing subscription.`

The customer wanted to change his to this:

`Log in to renew or upgrade an existing subscription.`

But, "upgrade" isn't always applicable - people may want to downgrade, or simply "change" their subscription. Maybe something like:

`Log in to renew or change an existing subscription.`

**Comment by llity** [comment]
+1

**Comment by tnorthcutt** [comment]
@mindctrl any reason we shouldn't make that text filterable?

**Comment by mindctrl** [comment]
I'm not entirely opposed to a new filter here, but I'd rather just change the text for now and if we get more requests for customizing it, let's add one then.
