### ISSUE TITLE
rcp_is_paid_content() has a missing edge case

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#1690]
Currently, `rcp_is_paid_content()` checks if a value is set for the `is_paid` postmeta key. That postmeta value gets set in `rcp_save_meta_data()`.

However, if a post's restrictions are set to "Members of any subscription level(s)", and all subscription levels are paid, that post [will not have the `is_paid` meta set.](https://github.com/restrictcontentpro/restrict-content-pro/blob/29b189a466ad32509134154159c2e630747b5869/includes/admin/metabox.php#L137-L142).

The fix for this is to check all subscription levels, and if they're all paid, set the meta appropriately.

One problem with this: any time a subscription level is updated, if it's going from free to paid or vice versa, and if doing so means that now all subscription levels are paid, or that they were all paid and now there is a free one, we'd need to loop through _all posts_ and possibly add or remove the `is_paid` meta.

If we introduce an `rcp_is_free_content()` function as I mentioned in https://github.com/restrictcontentpro/restrict-content-pro/issues/914, we'd also need to possibly update the corresponding `is_free` meta as well.

Those seem like pretty expensive operations, so I'm going to hold off for now on doing the refactoring.

@nosegraze @pippinsplugins would love your input on this.

**Comment by tnorthcutt** [comment]
On review, this is somewhat related to [this comment](https://github.com/restrictcontentpro/restrict-content-pro/pull/1576#issuecomment-345651978).

**Comment by mindctrl** [comment]
re: price changes. We recommend people not change them. https://docs.restrictcontentpro.com/article/1563-changing-subscription-level-prices

We don't mention all the details about why we recommend against changing, but this is definitely one we should put in the doc.

**Comment by tnorthcutt** [comment]
@mindctrl ah, right, thanks for that. Should simplify this quite a bit then. We'd still have the situation where if all _were_ paid, but a new (free) one is added, it would impact `is_paid`. Same goes for if there was a free one, but it is then deleted.

But, sounds like in #914 we might move away from free vs. paid messaging anyway, which would make this a non-issue 😁

**Comment by mindctrl** [comment]
I think we all agree that free vs paid messaging needs to go away in #914. Going to close this. Reopen if you disagree.
