### ISSUE TITLE
RCP shortcodes and visual composer?

### ISSUE THREAD

**Issue by kendraschaefer** [restrictcontentpro/restrict-content-pro#1697]
Heya, 

I know you've addressed this issue in the past here: https://github.com/restrictcontentpro/restrict-content-pro/issues/1481

Was wondering if the decision ever got made to resolve this? I'm also having this problem with VC. I want to use RCP shortcodes to restrict content that spans multiple VC rows, but can't seem to do it.

**Comment by mindctrl** [comment]
@kendraschaefer we have not made any further attempts to integrate with VC. At this time it's not on our roadmap.

**Comment by nosegraze** [comment]
Given that this affects all shortcodes and not just `[restrict]` this really sounds like something the folks at VC need to fix.
