### ISSUE TITLE
Member subscription level changes are not always reflected in Stripe

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#1700]
I've spoken with @mindctrl about this before in passing; I'm opening an issue here because it's continuing to happen on one of my client sites.

On this site (which, FWIW, is a multisite install, with RCP activated separately on each site), occasionally a member will change plans but that plan change is not reflected in Stripe. Of course, this is only noticed when the member is charged the amount of their old plan. When they downgraded to a cheaper plan, this causes a significant customer service issue.

I'm not sure what the best way to diagnose & solve this is, but **I'd love suggestions for monitoring/logging I can put in place to help track down the root cause.**

**Comment by pippinsplugins** [comment]
How is the plan getting changed? Is an admin changing it from the member edit screen or is the member going back through registration?

**Comment by tnorthcutt** [comment]
The member is going through the registration flow.

**Comment by nosegraze** [comment]
1. Was the user's old status still "active" when they downgraded?
2. Is the user actually given the new subscription level in RCP after going through the form? And is their status "active"?
3. Can you paste the user's notes?
4. Is there any payment record at all in RCP for the downgrade? What's the status of the payment?

**Comment by tnorthcutt** [comment]
@nosegraze 
1. Yes, still active
2. Yes, they were moved to the new level _in RCP_, and stayed "active"
3. See below
4. The next payment recorded in RCP after downgrading was for the new plan, but the amount was for the old plan. In Stripe, they were not moved to the new plan.

![](https://d.pr/i/ViFJvm+)

**Comment by nosegraze** [comment]
If the user went through the registration form there should at least be a `pending` payment for the downgrade amount. That payment gets created at the very start of the registration process, before any gateway API calls or anything like that. I suspect there's something else at play here and I suggest we continue it via support: https://restrictcontentpro.com/support/

If you have debug mode turned on then please send us the debug log file along with the ID number of this affected user.

If you don't have debug mode turned on, then please turn it on now so we will at least have that information for next time.

**Comment by tnorthcutt** [comment]
@nosegraze Thanks. Debug was turned on for the main site, but not the subsite this occurred on. I've got it turned on now – is it worth opening a ticket right now, or should I wait until this happens again so we'll have log information?

**Comment by nosegraze** [comment]
It might be better to wait until it happens again. I'm not sure if we have enough information right now to definitely be able to solve it. The debug log should hopefully be enough to figure out exactly what happened though!

**Comment by tnorthcutt** [comment]
👍
