### ISSUE TITLE
Protect a URL

### ISSUE THREAD

**Issue by tinyCoder32** [restrictcontentpro/restrict-content-pro#1715]
Hi, is there any chance to protect a URL instead of a page?

For example, BuddyPress members page cannot be protect by Restrict, i think because it doesn't have `the_content()` filter maybe? and it shows the members directory instead.

I appreciate if you lead me to a way to protect a link or the pages that are similar to BuddyPress custom pages.

Thanks :)

**Comment by mindctrl** [comment]
@tinyCoder32 with the filter, you'll likely need to customize the template that displays the members page and do some checks that way. You may find these functions helpful: https://docs.restrictcontentpro.com/category/1514-functions

There's a 3rd party BuddyPress integration here. Feel free to reach out to them about this feature. https://skillfulplugins.com/plugins/restrict-content-pro-buddypress/

We use GitHub for development tracking only. In the future, please open support questions like these via our website here: https://restrictcontentpro.com/support
