### ISSUE TITLE
Members page showing wrong number of members

### ISSUE THREAD

**Issue by tinyCoder32** [restrictcontentpro/restrict-content-pro#1716]
Hello, yesterday I had the members filters showing wrong numbers of users, Active was saying (7) while it was showing only 1 member, also Expired was showing (5) while it has none!

Today, it got back fixed again, is that some kind of a cron job or something? I mean is it normal or taken into consideration? or it is a bug? we where just curious to know about that.

Thanks.

**Comment by mindctrl** [comment]
We use GitHub for development tracking only. In the future, please open support questions like these via our website here: https://restrictcontentpro.com/support
