### ISSUE TITLE
Custom field value is not sent through the Admin notification email

### ISSUE THREAD

**Issue by dinakaranAppViewX** [restrictcontentpro/restrict-content-pro#1717]
Hi Guys,

I cannot sent the custom field checkbox value through the Admin email notifications. But the value's are properly stored in a DB. Is there any way to make this work?

**Comment by nosegraze** [comment]
@dinakaranAppViewX GitHub is used for development tracking only. Please send support queries through this page: https://restrictcontentpro.com/support/

However, for custom fields you will need to create a custom template tag. Please see this tutorial: https://docs.restrictcontentpro.com/article/1761-adding-a-new-email-template-tag
