### ISSUE TITLE
Authorize.net: process one-time charge for first payment in a subscription

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1723]
Right now we authorize the card for the full payment amount. It then takes 30 days for this authorization to expire. We've gotten 2 or 3 tickets about this from customers, because their customers are confused by it and think it's a double charge.

We should consider adding a filter on the authorisation amount so people can change it, or maybe we should change it ourselves to $0.01 by default.

**Comment by mindctrl** [comment]
I don't remember the specific here. Can we not auth and capture at the same time?

**Comment by nosegraze** [comment]
@mindctrl We set up a subscription immediately but the issue is that they don't actually _charge_ those subscriptions immediately. All subscription payments are bulk processed once per day only. So there could be a several hour gap between setting up a new subscription and actually attempting to bill for that subscription. This was how it was previously and it resulted in someone signing up, getting immediate access, then the card was declined hours later. We now authorize the amount first to immediately find out if the card is valid to help us know for sure if a charge will actually go through later. If the authorization is successful, we then setup the subscription.

Another option would be to process a separate one-time transaction now to take the first payment and set up a subscription with a delayed start date (starting during the next period). So if they sign up on March 17th for a 1 month recurring subscription, we'd do a one-time payment today, then set up a recurring subscription that won't actually start until April 17th.

**Comment by mindctrl** [comment]
I like the idea of capturing the one-time charge right away and setting up the sub to start at the end of the first period. I wonder if they have any limitations on how far out start dates can be...

**Comment by nosegraze** [comment]
WIP PR: #1770

I haven't tested this at all yet because Authorize.net's API wasn't working for me. I think I was running into this issue https://github.com/AuthorizeNet/sdk-php/issues/298 . It's been fixed in version `1.9.6` in the SDK so we may need to update that.

**Comment by nosegraze** [comment]
Closing this to handle it in the new add-on: https://github.com/restrictcontentpro/rcp-authorize-net/issues/1
