### ISSUE TITLE
Adjust description/functionality for "Disable WordPress Toolbar" setting

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1729]
Right now it says:

> Check this if you'd like to disable the WordPress toolbar for subscribers. Note: will not disable the toolbar for administrators.

First of all, I don't like the usage of "subscribers". I think that word is confusing and we should start trying to move away from it and use "members" instead.

However, either way the description isn't really accurate for what the option does. The setting disables the toolbar for _non-admins_, regardless of whether they have a membership or not.

This confused one customer who thought the toolbar would only be disabled for the `subscriber` role. He was confused as to why it also disappeared for his users in the `editor` role.

We should do one or both of the following:

1. Consider: should we really disable the toolbar for users who are able to edit/create posts (or in general perform any admin action beyond just editing their profile)?
2. We should reword the description to more accurately describe who is going to lose toolbar access.

**Comment by pippinsplugins** [comment]
I vote for re-wording it to `members` and then only disabling it for users that have subscribed to a membership through RCP. The status of their membership should not matter, I don't think.
