### ISSUE TITLE
Dripped Content Enhancement

### ISSUE THREAD

**Issue by jerrickhakim** [restrictcontentpro/restrict-content-pro#1730]
Ok, so if a user subscription becomes expired due to non payment and dripped content is enabled. 

Then if the user re signs up again the drip content schedule resets and starts again at day 1. I would think for most applications it would be best for the user to resume where they left off. 

Now what if the user's rcp status falls back to pending rather then expired. Would this prevent from this from happening?

**Comment by mindctrl** [comment]
Hi @jerrickhakim,

Thanks for the feedback. For support questions and feature suggestions like this, please send us a support ticket here: https://restrictcontentpro.com/support/

We use Github for development tracking only.
