### ISSUE TITLE
Add support for Alipay again

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1731]
We've had a few requests that I know of to support Alipay.

We used to support it via Stripe Checkout, but they removed it there so we did too. But they do support it in `Sources`.

https://stripe.com/docs/sources/alipay

**Comment by nosegraze** [comment]
We already have a general issue for the sources API: https://github.com/restrictcontentpro/restrict-content-pro/issues/1378

If we're going to do everything at once and just add general "Sources API" support then we can probably close this in favour of the other one.

**Comment by mindctrl** [comment]
Ah yes, closing this.
