### ISSUE TITLE
Remove message in settings that implies API keys are optional for PayPal Standard

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1749]
The message says:

> The PayPal API credentials are required in order to use PayPal Express, PayPal Pro, and to support advanced subscription cancellation options in PayPal Standard.

It basically says API credentials are optional for PayPal Standard. However, if API keys aren't entered then cancellations don't work at all. This is fine for cancelling via the members page, but it proves to be a kind of serious issue during upgrades/downgrades. Users end up getting double billed because the previous subscription never gets cancelled. We've gotten several support tickets about people getting double billed and this ended up being why.

We should just remove that message and make them required.

**Comment by pippinsplugins** [comment]
>>>We should just remove that message and make them required.

I agree.

**Comment by nosegraze** [comment]
PR: #1751
