### ISSUE TITLE
Improve Stripe Checkout modal experience in [register_form_stripe] shortcode

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1753]
When Stripe approves the payment, the modal closes along with the dark overlay. However, in the background things are still being processed and it's not clear that it's happening. If a host is slow or there's some kind of slowness with Stripe communications, people can think things didn't work right. We should improve this experience and keep the overlay until the redirect happens.

**Comment by nosegraze** [comment]
Yes! I've gotten a few comments about this.
