### ISSUE TITLE
Discounts do not apply to signup fees [Stripe]

### ISSUE THREAD

**Issue by messierlaurent** [restrictcontentpro/restrict-content-pro#1780]
I've noticed that discounts do not apply to signup fees with Stripe (didn't try with other payment processors). 

My pricing requires as a setup fee of $39. Then the user will pay $15 monthly.
So in RCP, I did setup the pricing like this: Price: $15 & Signup fee: $24 (so total is $39).

The problem is, when a user is entering a coupon code of $20, the total is $24 for some reason..
(it should give them a total of $19 on signup, $39 - $20 = $19)

That would mean discounts do not apply to signup fees.
Is there an easy way to implement what I want to do? Is this a bug or it's intended?

**Comment by mindctrl** [comment]
As mentioned in the support ticket, this is intentional and at this time we don't have plans to change it. You would need to do some custom development to support this. See the filters in the `RCP_Registration` class.
