### ISSUE TITLE
Plugin integrations don't load

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#1783]
In working on https://github.com/restrictcontentpro/restrict-content-pro/pull/1777, I noticed that our built-in plugin integration loading seems to fail.

For instance, when loading `/wp-admin/admin.php?page=rcp-members`, `RCP_WP_Approve_User::init()` never executes, because `class_exists( 'Obenland_Wp_Approve_User' )` returns false, even if the WP Approve User plugin is active. I tested this on two different local installs.

This is surprising, because loading of integrations is hooked to `plugins_loaded` in `RCP_Integrations::__construct()`.

I'd love a second look at this.

**Comment by luke-au** [comment]
I've been having trouble with the WP Approve User plugin integration too, scratching my head trying to understand what was going wrong.

**Comment by tnorthcutt** [comment]
@luke-au interesting! Is it adding the row actions? Meaning, when you go to the Members page and hover over a row, is the Approve or Unapprove link visible?

**Comment by nosegraze** [comment]
It works fine for me. Do you have `anyone can register` checked on in Settings > General? That's required by WP Approve User and the plugin doesn't load if that's not checked on.

**Comment by mindctrl** [comment]
What @nosegraze said is the answer. WP Approve User returns early if that option isn't enabled.
