### ISSUE TITLE
Member improperly set to cancelled when changing from PayPal to another gateway

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1784]
If you move from PayPal to another gateway, and the PayPal subscription is cancelled, and the IPN comes in late, the member will be marked as cancelled even though they now have a new subscription on another gateway.

This is because `RCP_Payment_Gateway_PayPal::process_webhooks()` does not verify that the customer is still a PayPal subscriber before setting the status to cancelled.

After checking their current payment profile ID against `$posted['subscr_id']`, it does two additional fallback checks against `$posted['custom']` and `$posted['payer_email']` to find a user account.

From there, when it processes the `subscr_cancel` block inside the switch, the `! $member->just_upgraded()` returns true and the member is set to cancelled without seeing if the member is still a PayPal subscriber.

Found when testing https://github.com/restrictcontentpro/restrict-content-pro/issues/1719.

**Comment by nosegraze** [comment]
Presumably we should be able to do the same thing we do for the `subscr_eot` IPN:

```php
if( isset( $posted['subscr_id'] ) && $posted['subscr_id'] == $member->get_payment_profile_id() && 'cancelled' !== $member->get_status() ) {
```

Only cancel the member if the payment profile ID in the IPN matches what's in RCP.

**Comment by mindctrl** [comment]
PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/1785
