### ISSUE TITLE
Users not logged out after changing password

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1789]
I'm not sure if this is an RCP issue because I haven't had a chance to do more thorough testing yet, but I've gotten several reports from customers that users are not logged out after changing their passwords through RCP. We don't do anything on our end to log users out because I think WordPress core is supposed to handle clearing the authentication cookies, but maybe we're breaking something there.

**Comment by tnorthcutt** [comment]
FWIW, when you generate and save a new password in wp-admin on `/wp-admin/profile.php`, you are not logged out. So, we're not really doing anything different than core at the moment.

**Comment by nosegraze** [comment]
Yep - you're right.

In that case we should remove the note about needing to log back in.
