### ISSUE TITLE
An error occurred while updating Restrict Content Pro: Could not create directory. restrict-content-pro/includes/admin/discounts

### ISSUE THREAD

**Issue by hanadullset** [restrictcontentpro/restrict-content-pro#1807]
I'm trying to update the plugin from 2.9.2 to 2.9.11. Unable to do so and I receive this error:

_An error occurred while updating Restrict Content Pro: Could not create directory. restrict-content-pro/includes/admin/discounts_

**Comment by mindctrl** [comment]
Please open a support ticket here: https://restrictcontentpro.com/support/

We use GitHub for development only.
