### ISSUE TITLE
Scripts not loaded in rcp_reset_password_form()

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#1809]
`rcp_reset_password_form()` checks for an option that doesn't exist before it sets the `$rcp_load_scripts` global, so the global isn't set to `true` and the scripts do not load.

Reference: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.9.11/includes/shortcodes.php#L411

**Comment by nosegraze** [comment]
PR: #1810
