### ISSUE TITLE
Syntax error in PHP 5.3

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1812]
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/admin/settings/settings.php#L1833

```php
$data = json_decode( $response['body'], true )['data'];
```

The result of `json_decode()` needs to be put in a variable before trying to access `'[data']`

**Comment by mindctrl** [comment]
I think it's this line? https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/admin/settings/settings.php#L2189

**Comment by mindctrl** [comment]
PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/1813

**Comment by nosegraze** [comment]
Yes you're right - I just linked to the wrong one. :P
