### ISSUE TITLE
PHP 7.2 warning - count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1820]
```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/rcp/wp-content/plugins/restrict-content-pro/includes/admin/tools/system-info.php on line 261
```

I get this error from here:

```php
$muplugins = get_mu_plugins();
if( count( $muplugins > 0 ) ) {
```

when I have no MU plugins active.

**Comment by chrisvanpatten** [comment]
Core [recently implemented](https://core.trac.wordpress.org/ticket/43583) an `is_countable` polyfill which could be used here.

**Comment by nosegraze** [comment]
PR: #1824

I misread it the first time. The issue was simply due to a parenthesis being in the wrong place. :P
