### ISSUE TITLE
Suppress all emails

### ISSUE THREAD

**Issue by chrisvanpatten** [restrictcontentpro/restrict-content-pro#1839]
I'd love a simple programmatic way to make sure RCP never sends an email.

We have a client where we're using the "restrict content" bit of RCP but not the account management/billing/etc (we are SSO'ing and syncing the member status data from a third party service… an increasingly common application, we're finding). This has me mildly paranoid that RCP will send a billing flow email when we don't want it to.

I'd love if there were a  way to just disable these across the board, perhaps something like `if ( defined( 'RCP_DISABLE_EMAILS' ) && RCP_DISABLED_EMAILS ) { return; }` in `RCP_Emails->send()`.

The reasons to do it this way, over disabling in the admin, are

1. Disabling each email in the admin is tedious
2. If new email notifications are added in the future, they don't default to disabled, so you could inadvertently start sending emails without realising it

Another option would be to allow filtering the `to` value on an email and just replace it with an admin email or some fake email. It's possible to do that with the `wp_mail` filter but that assumes that the filter is available… a bit risky because the `wp_mail` function is pluggable.

A third option would be to make this an admin setting but I feel like that's a dangerous option for RCP's non-technical users.

Happy to submit a PR, if this is of interest.

**Comment by nosegraze** [comment]
I really like the idea of a constant to disable all emails. This would be very useful on staging sites where you probably don't want emails to be sent out. We often get issues in support where customers say expiry emails were sent out incorrectly, and it turns out they were being sent from the customer's staging site without them realizing.

**Comment by mindctrl** [comment]
I like this too. Thoughts on also showing an admin notice while this is enabled? That would only be applicable to production sites, but it's a case where forgetting emails are disabled could be a problem.

**Comment by chrisvanpatten** [comment]
@mindctrl I tried that… was trying to get the admin notice to show up only in the email tab in RCP settings, but WordPress tries to be helpful and moves the notice above the tabs so they show up on all settings page tabs.

If that's okay, I can definitely add it!

**Comment by nosegraze** [comment]
I'm fine with either of the above. And whichever one we go with, we can always make changes later depending on feedback if we find out it's too annoying on every page, or not clear enough on just one page.

**Comment by chrisvanpatten** [comment]
Awesome. I think it works best on just the settings page... will update and push that up tomorrow!

**Comment by chrisvanpatten** [comment]
@nosegraze @mindctrl Do you think this notice should be dismissible? (I'd say if it's only on the settings page it probably shouldn't be, but I defer to you!)

**Comment by mindctrl** [comment]
I agree since it’ll only be on the settings page.

**Comment by nosegraze** [comment]
Love it :+1:  Thank you @chrisvanpatten !
