### ISSUE TITLE
Synchronized Renewal Date

### ISSUE THREAD

**Issue by dglogowski** [restrictcontentpro/restrict-content-pro#1845]
I have been searching for an answer to this capability within Restrict Content Pro for some time without success.  So trying here—apologies if not the proper forum.

I am supporting a genealogical society which synchronizes our annual membership period with our operating calendar (1 Jan - 31 Dec).  I can use the Hard Expiration Date add-on to set all the initial registrations/subscriptions to 31 Dec 2018 — full date; including the year.  I have not found a way to set subscription periods to 31 Dec of any year.  For example, if I set the hard expiration date to 31 Dec 2018, a member renews on 15 Dec 2018, then the expiration date is set to  31 Dec 2018; not 31 Dec 2019.  

Is this the intended behavior?  Is there something I am missing?  Is there a configuration or setting I can use to achieve my desired behavior?

Cheers,
Dave

**Comment by nosegraze** [comment]
Hi Dave,

The Hard-set Expiration Date add-on is not designed to be a renewal sync plugin. It doesn't sync the renewal date; it literally sets a hard cut off for when the membership ends. It's not designed to work with renewals at all.

If you'd like to discuss this more please get in touch with us via our support page: https://restrictcontentpro.com/support/
