### ISSUE TITLE
Content excerpt length is set to 50, but then filtered to 100, which is confusing

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#1849]
```php
$the_excerpt = preg_split( '/\b/', $the_excerpt, $length * 2+1 );
```

~~The length is set to `50` words, but then we do `$length * 2+1`, which sets it to `100` words.~~

**Comment by nosegraze** [comment]
Actually my bad - that wasn't the problem. The problem is we set `$excerpt_length = 50;` here:

```php
$excerpt_length = 50;
if ( has_filter( 'rcp_filter_excerpt_length' ) ) {
	$excerpt_length = apply_filters( 'rcp_filter_excerpt_length', $excerpt_length );
}
```

but then later we change it here:

```php
function rcp_excerpt_length( $excerpt_length ) {
	// the number of words to show in the excerpt
	return 100;
}
add_filter( 'rcp_filter_excerpt_length', 'rcp_excerpt_length' );
```

I have no idea why we do that. We should stick to either 50 or 100 and not be filtering it. O_O

**Comment by nosegraze** [comment]
PR: #1853

I removed the function hooked into the filter and set the default to `100` so it doesn't actually change in this update.

**Comment by mindctrl** [comment]
I wonder why change the default WP excerpt length of `55` at all?

Looks good to me. Merging.
