### ISSUE TITLE
It is a pity there is not a centralised system of payment for a wp multisite.

### ISSUE THREAD

**Issue by colomet** [restrictcontentpro/restrict-content-pro#220]
To chose one installation, and handle there the subscriptions for all the blogs.

**Comment by pippinsplugins** [comment]
@colomet it's a feature I've considered.

**Comment by colomet** [comment]
i think is the only feature will make your plugin better than Membership 2 Pro for multisite enviroment.

**Comment by michaelbeil** [comment]
a request here: https://secure.helpscout.net/conversation/187523421/31167/?folderId=841776

**Comment by michaelbeil** [comment]
Would creating a multisite constant that can be defined in wp-config, similar to how AWP shares data between all subsites, be a feasible approach to make this happen?

**Comment by pippinsplugins** [comment]
Yes. I'd like to have a constant.

**Comment by michaelbeil** [comment]
For future use: https://github.com/AffiliateWP/AffiliateWP/search?utf8=%E2%9C%93&q=AFFILIATE_WP_NETWORK_WIDE

**Comment by mindctrl** [comment]
I'm going to see if we can tackle this in 2.7. We're seeing an increase in requests for this.

**Comment by pippinsplugins** [comment]
Closing this in favor of #669
