### ISSUE TITLE
PayPal Express payments log the Profile ID in place of the Transaction ID 

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#229]
Recurring payments received via PayPal Express are logging the subscription `Profile ID` in place of the `Transaction ID`. 

For example, this payment shows the Transaction ID as `I-TYSXMM1AEENF`, when it should be `52W67004UJ358100L`: 
![screen shot 2015-09-10 at 12 36 37 pm](https://cloud.githubusercontent.com/assets/1648631/9795875/ba971574-57b8-11e5-810f-3f7163ccbe35.png)

**Comment by pippinsplugins** [comment]
Whoops!

**Comment by tannerm** [comment]
I've fixed this in #388.
