### ISSUE TITLE
Card Details shortcode always displays empty fields

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#230]
The `[card_details]` short code output always displays empty fields, even after a successful card update. This gives the impression that the card update failed and/or that no card is on file. 

These fields should show the last four of the card on file, along with the expiration and any other relevant details. 

![screen shot 2015-09-10 at 4 17 52 pm](https://cloud.githubusercontent.com/assets/1648631/9801248/88adeb90-57d7-11e5-8d87-2d116b6d99cd.png)

**Comment by pippinsplugins** [comment]
There should be a confirmation message after updating the card. Is CGC using a customized template file?

**Comment by carter2422** [comment]
@pippinsplugins the issue is more that the fields always being empty (regardless of a confirmation message) gives the user the impression that they have no card on file. 

Typically most card update forms will show key info about the card on file, which is really helpful. 

Is this doable?

**Comment by pippinsplugins** [comment]
Ah! Ok I fix that.

**Comment by carter2422** [comment]
:+1:

**Comment by wesburke** [comment]
I am excited to see this. 

We do answer a few support conversations of customers inquiring what card they have on file, or if the update was a success. :+1:

**Comment by carter2422** [comment]
Thoughts on getting this into 2.4.9 or 2.5.0 @pippinsplugins?

**Comment by pippinsplugins** [comment]
Will get it in 2.5

**Comment by pippinsplugins** [comment]
This is ready for testing!

Note: Stripe and Stripe checkout only.

**Comment by pippinsplugins** [comment]
Had a quick discussion about this with @mindctrl and debated whether we should go ahead and structure the data such that it supports multiple payment gateways / subscriptions.

For now I think I'm going to leave it as is, simply because it will be trivial to update / change it later if necessary.

**Comment by pippinsplugins** [comment]
Merged and closing. Re-open if you notice anything.

**Comment by michaelbeil** [comment]
Sounds good.

**Comment by mindctrl** [comment]
Re-opening after a quick chat with @pippinsplugins. Already had this written. Also updated the HTML to avoid duplicate IDs if looping through multiple gateways / subscriptions in the future.

**Comment by pippinsplugins** [comment]
Thanks @mindctrl !
