### ISSUE TITLE
Occasional user goes from expired > active > expired > active while upgrading

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#241]
Occasionally when user signs up they cycle between `active`, `pending`, and `expired` status more than once, causing Expiration emails to be sent out. 

So far this seems to be limited to users whom previously had a subscription and then returned, but I cannot yet verify. 

Here're the notes for a user today:
```
September 28, 2015 04:47:46 - Member's status changed from expired to pending

September 28, 2015 04:47:51 - Member's status changed from active to expired

September 28, 2015 04:47:51 - Member's status changed from pending to active

September 28, 2015 04:47:55 - Member's expiration changed from 2015-06-18 23:59:59 to 2016-09-28 23:59:59

September 28, 2015 04:47:55 - Member's status changed from expired to active
```

**Comment by pippinsplugins** [comment]
Which gateway?

**Comment by carter2422** [comment]
Stripe.

**Comment by pippinsplugins** [comment]
Figured it out! Goes back to same thing as https://github.com/restrictcontentpro/restrict-content-pro/issues/299

**Comment by carter2422** [comment]
Whoop!
