### ISSUE TITLE
Remove fixed widths from labels + more

### ISSUE THREAD

**Issue by sumobi** [restrictcontentpro/restrict-content-pro#251]
We've discussed this before. Just realised I posted on PR. See: https://github.com/pippinsplugins/restrict-content-pro/pull/169#issuecomment-145329385

In summary:

1. Fixed widths on labels should be removed

2. The `Remember` checkbox (let's also rename this to Remember Me) doesn't look good on the 2015 or upcoming 2016 theme

3. Floats on labels should be removed (I see no need for them) 

I think we can fix this by either:

1. letting users know in advance about the changes
2. including the changes prominently in release notes
3. ???

**Comment by pippinsplugins** [comment]
Tagging for 2.4 to try and make it happen.

**Comment by sumobi** [comment]
:+1:  :+1:  :+1:

**Comment by pippinsplugins** [comment]
Before:
![screen shot 2016-06-20 at 2 09 39 pm](https://cloud.githubusercontent.com/assets/1034109/16207005/a7d9df62-36f0-11e6-925e-90faddf1dd09.png)
After:
![screen shot 2016-06-20 at 2 10 06 pm](https://cloud.githubusercontent.com/assets/1034109/16207014/b4f75d32-36f0-11e6-901c-d591409fe043.png)

This worries me.

Do you guys think I'm just being paranoid?

**Comment by mindctrl** [comment]
The new look makes the form feel a good bit longer, and some folks might not like it, but I think it looks more in line with what most forms on the web look like these days. I think I'm ok with this.

**Comment by pippinsplugins** [comment]
Let's leave it in for beta and see if we get any fallout on it.

We should probably also be prepared to do one of the following if a lot of people complain post release:

A. revert
B. have the CSS ready to go to restore the previous widths.

**Comment by michaelbeil** [comment]
Seems as if my comment never went through on this, but I am ok with testing as is and reverting if we get negative feedback.
