### ISSUE TITLE
Subscription price not updated in Stripe when updated in RCP

### ISSUE THREAD

**Issue by Mono-Code** [restrictcontentpro/restrict-content-pro#290]
I don't know if I can call this a feature request or an "un-feature" request but I found out that if you update the price of a subscription (that someone has signed up for already) Stripe doesn't update the price for the subscription on it's end. Although this makes sense, since I don't think you can legally up the price for an existing subscription without the member's consent, it makes all subscriptions going forward to be charged with the amount saved on stripe not what is set on the website (and displayed to the new member). Do you think it would be a good process to "lock" a subscription's price upon creation? Therefore, forcing the manager of the website to create a new subscription (with the updated price) instead.

**Comment by pippinsplugins** [comment]
This is a bug that I need to fix :)

The subscription level should be updated in Stripe but existing subscribers should not be affected.

**Comment by tannerm** [comment]
@pippinsplugins I just created a PR for this ( #378 ). I've reconfigured the plan ID to include plan name, duration unit, duration, and price.

I have also included a fallback to check if the previous plan id is valid. This way we won't unnecessarily create new Stripe plans for websites whose plans are still valid.

**Comment by pippinsplugins** [comment]
@tannerm Looks good at first glance! I'll test it and then let you know of any issues or comments.
