### ISSUE TITLE
Stripe: account for Unpaid subscriptions when re-subscribing

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#302]
If a user tries to re-subscribe via Stripe, and has a previously unpaid subscription (typically due to failed payments) then the new subscription never goes through but RCP reports it as successful to the user. 

There needs to be a way to account for unpaid subscriptions in Stripe.

Note: after signup no error messages are presented, so it appears successful, but the user is never actually activated.

**Comment by carter2422** [comment]
Since most Unpaid subscriptions are due to multiple failed payments, dependent on your Stripe settings, my suggestion would be to simply cancel the unpaid subscription if it exists, and then continue with the new signup like normal. 

![screen shot 2015-12-07 at 10 06 21 am](https://cloud.githubusercontent.com/assets/1648631/11631973/602fd9d4-9cca-11e5-8946-7a86f43bd626.png)

**Comment by pippinsplugins** [comment]
Can you show me all events logged on the customer in Stripe for a member this happened to?

**Comment by pippinsplugins** [comment]
@carter2422 ping

**Comment by carter2422** [comment]
Just now coming back around to this. 

Here are all the events from a user that just ran into this today: 
![screen shot 2016-02-04 at 2 35 44 pm](https://cloud.githubusercontent.com/assets/1648631/12828882/b3e7c8ce-cb4c-11e5-89b3-216ab6ffed2b.png)

**Comment by carter2422** [comment]
That user had a previously, unpaid `Quarterly` plan.
