### ISSUE TITLE
Add-on licensing / updater

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#308]
The add-on updater API needs to be added.

**Comment by mindctrl** [comment]
@pippinsplugins this just needs to be tested to make sure updates and licensing work as expected? anything else to look for?

**Comment by pippinsplugins** [comment]
Not ready. I have to make some changes to it. This version is expecting the plugins to be distributed through pippinsplugins.com. We've moving them to restrictcontentpro.com

**Comment by pippinsplugins** [comment]
Ok this should be ready as soon as the RCP site gets its SSL cert installed later today.

**Comment by pippinsplugins** [comment]
Pretty sure we're done with this now.
