### ISSUE TITLE
Add in hook for failed credit card payment

### ISSUE THREAD

**Issue by jmarx** [restrictcontentpro/restrict-content-pro#310]
When a credit card fails, users are now forced to an ugly wp_die message. I would really like the ability to send users to a custom page instead of the ugly error message.
@pippinsplugins would you consider adding in this hook or giving me some direction as to how to accomplish this without the hook?
I have been trying a million different ways and haven't been able to get it. Would you consider merging this or providing direction on how to redirect users in this situation?
Happy Holidays!
p.s. Forgot to include the pr: https://github.com/jmarx/restrict-content-pro/tree/payment_failed

**Comment by pippinsplugins** [comment]
@jmarx Which gateway?

**Comment by jmarx** [comment]
Stripe. I can code it up for the others too. But stripe is the one we work with.

**Comment by pippinsplugins** [comment]
@jmarx I don't think this is necessary since we already have `do_action( 'rcp_stripe_' . $event->type, $payment_event );`

That will fire on every event type that doesn't already have a handler.

**Comment by jmarx** [comment]
Ok ill mess around with this and let u know how I make out. Didn't see that before.

**Comment by jmarx** [comment]
``
add_action( 'rcp_stripe_charge.failed', 'jeff_charge');
function jeff_charge( $event ) {
    wp_redirect( '/payment_failed' );
    exit;
}
``

**Comment by jmarx** [comment]
```
add_action( 'rcp_stripe_charge.failed', 'jeff_charge');
function jeff_charge( $event ) {
    wp_redirect( '/payment_failed' );
    exit;
}
```

**Comment by pippinsplugins** [comment]
Doing a redirect there won't work as that even fires during the Stripe webhooks, not during any user-initiated event.

**Comment by jmarx** [comment]
Yep. Am I using the wrong hook?
I am desperately trying to avoid sending my users here:
<img width="1144" alt="screen shot 2015-12-31 at 6 13 52 pm" src="https://cloud.githubusercontent.com/assets/223919/12069032/64c2d28e-afea-11e5-83e0-9d5c49139806.png">

**Comment by jmarx** [comment]
The pr I pushed up allows me to do that.

**Comment by jmarx** [comment]
we have a pretty /payment_failed page set up, but not way to get them there :)

**Comment by jmarx** [comment]
I was wondering if there is a way to just make an api call and check if the card is valid or not and use the create_args hook, but I couldn't make that work as there seems to be no such api call available from stripe. That I know of anyways.

**Comment by jmarx** [comment]
So any feedback you could provide to help me accomplish that, would be greatly appreciated.

**Comment by jmarx** [comment]
Or if there is a way to create a hook just to catch any general payment error and be able  to react to it before sending users to wp_die. OK I'll stop spamming this issue. Thanks so much and Happy New Years! :)

**Comment by pippinsplugins** [comment]
@jmarx got it. Can you submit the PR? Looks like you committed to your fork but didn't make the PR.

**Comment by jmarx** [comment]
@pippinsplugins Do you need to grant me access to push a branch? I have been trying and it doesn't work. Unless I am missing something. I apologize that I am a little inexperienced at contributing to projects like these. I thought it was done through forks.

**Comment by jmarx** [comment]
Here is the pr: let me know what you think. https://github.com/restrictcontentpro/restrict-content-pro/pull/315
Or if you have a better idea of how to accomplish what I am trying to do.

**Comment by pippinsplugins** [comment]
They're in.

I modified them slightly though.

**Comment by jmarx** [comment]
Thanks!
