### ISSUE TITLE
htmlspecialchars causing issue with sending html emails

### ISSUE THREAD

**Issue by psorensen** [restrictcontentpro/restrict-content-pro#324]
When adding the html content-type to the headers via [`rcp_email_headers`](https://github.com/restrictcontentpro/restrict-content-pro/blob/ed369f9ab445f54a9e9dc0602ebcdbe523693c45/includes/email-functions.php#L25) filter...

```php
add_filter( 'rcp_email_headers', 'om_rcp_email_headers', 10, 3);

function om_rcp_email_headers( $headers, $user_id, $status ) {
	$headers    .= "Content-Type: text/html; charset=utf-8\r\n";
	return $headers;
}
```
... the html tags in the sent email are still rendered as plain text. I've determined that the issue is local to RCP as other emails not sent through RCP (and with text/html content-type header) include correctly rendered HTML.

Digging deeper, I determined that the culprit is the `htmlspecialchars()` added to the message via the [`rcp_filter_email_tags()`](https://github.com/restrictcontentpro/restrict-content-pro/blob/ed369f9ab445f54a9e9dc0602ebcdbe523693c45/includes/email-functions.php#L189)

Removing the `htmlspecialchars` function solves the issue, and seemingly (preliminary testing) does not affect the function to render the email tags. Is the `htmlspecialchars` necessary?

**Comment by pippinsplugins** [comment]
Aha! That was added to ensure that apostrophes (and other characters) get displayed properly. I can probably modify it so that it runs before the filters.

**Comment by psorensen** [comment]
:+1:
