### ISSUE TITLE
Add refunds tab to RCP reports

### ISSUE THREAD

**Issue by ramiy** [restrictcontentpro/restrict-content-pro#326]
This is a feature request.

Currently the **Reposts** has two tabs: **Earnings** and **Signups**.

I will love to see a new tab showing me all my **Refunds**.

![RCP Refunds Report](http://i.imgur.com/elqx6be.png)

**Comment by pippinsplugins** [comment]
Great idea.

**Comment by ramiy** [comment]
Done!

https://github.com/restrictcontentpro/restrict-content-pro/pull/331

**Comment by pippinsplugins** [comment]
Looking good! We'll get this reviewed for 2.5

**Comment by tannerm** [comment]
@pippinsplugins just tested and this looks good to me!

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Merged manually :)
