### ISSUE TITLE
Applying a discount code should update the price displayed

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#327]
Currently, successfully applying a discount does not update the price displayed, which can be confusing to buyers, even though a "Valid" message is displayed with the discount amount (a friend using RCP has had several customers contact him because they thought a discount code wasn't working).

I suspect there will be some edge cases here, but at the very least we could easily cover the 80% use cases for now.

**Comment by carter2422** [comment]
:+1:

**Comment by pippinsplugins** [comment]
:+1:

**Comment by michaelbeil** [comment]
Definitely!

**Comment by mindctrl** [comment]
Signup fees don't show either. Generalize this issue or open another?

**Comment by pippinsplugins** [comment]
Let's generalize it here.

**Comment by tannerm** [comment]
I've address this issue in the Upgrade Paths ( #195 ) Pull Request: #356.

**Comment by pippinsplugins** [comment]
This is working really, really nicely.

**Comment by tannerm** [comment]
@tnorthcutt @michaelbeil @carter2422 @pippinsplugins I've added this feature and it is ready for testing on PR #356. Would love to have you all test it when you get a chance. Thanks!

**Comment by pippinsplugins** [comment]
@mindctrl I'd love for your eyes on this as well.

**Comment by pippinsplugins** [comment]
@tannerm The `table` element for registration total should have a class of `class="rcp-table"`.

**Comment by carter2422** [comment]
Great! I'll try and test soon.

**Comment by mindctrl** [comment]
Briefly chatted in Slack about discount codes being applied last. See image below for why it may be a good idea to do so - particularly with the new upgrade routines coming.

![image](https://cloud.githubusercontent.com/assets/1254870/13652023/02a6706a-e618-11e5-830c-3ff15bb92e94.png)

**Comment by pippinsplugins** [comment]
@mindctrl Do you just mean showing the discount code as the last item in the list?

**Comment by mindctrl** [comment]
@pippinsplugins Sorry for the confusion. It's tightly coupled with #195.

I meant calculating the discount after proration. Signup fees are being negated due to order of calculations.

Without a proration in effect, discount is calculated on the base sub price and leaves the signup fee intact:
![image](https://cloud.githubusercontent.com/assets/1254870/13855419/c317a006-ec46-11e5-8b58-2ed36486c7b0.png)

With proration, before applying discount:
![image](https://cloud.githubusercontent.com/assets/1254870/13854979/8eadd4c2-ec44-11e5-9ab4-13536ac76928.png)

---

With proration, after applying discount:
![image](https://cloud.githubusercontent.com/assets/1254870/13854982/96968562-ec44-11e5-99df-19e02e31af40.png)

Or maybe another way to look at it is, calculate the proration before everything else?

**Comment by pippinsplugins** [comment]
@mindctrl Try it again now?

**Comment by michaelbeil** [comment]
All seems to work well now when upgrading with a discount with a proration credit.

- Upgraded from a 5 dollar daily subscription to a 30 dollar monthly subscription. 
- Applied a 50% OFF discount code
- $30 - $5 = $25; $25 / 2 = $12.50
- All is good

![screen shot 2016-03-18 at 2 07 28 pm](https://cloud.githubusercontent.com/assets/4752949/13889207/40527ccc-ed13-11e5-85a2-4c1db17f494d.png)

- However, when auto renew is checked, a total recurring of 50% off is set. Perhaps this is expected for all future payments to be 50% off. 

![screen shot 2016-03-18 at 2 07 40 pm](https://cloud.githubusercontent.com/assets/4752949/13889239/762f66b6-ed13-11e5-9803-ecb63a91dd07.png)

- When I add a signup fee of $2, the final calculation is off. Should be [(SUB - PROCRDT) / 2] + SIGNUP. Display shows $13.50, but if I am correct, it should be $14.50.

![screen shot 2016-03-18 at 2 14 08 pm](https://cloud.githubusercontent.com/assets/4752949/13889345/20ea5ef8-ed14-11e5-8617-173bd143f91b.png)

**Comment by pippinsplugins** [comment]
Those amounts look correct to me.

50% off a $30 subscription would be $15 per month since the pro-rations and signups fees only apply to the first payment.

$30 + $2 signup - $5 proration = $27
50% of $27 = $13.5

That all seems correct to me. Yes? No?

**Comment by mindctrl** [comment]
@pippinsplugins are discount codes supposed to discount signup fees?

![image](https://cloud.githubusercontent.com/assets/1254870/13891918/82effd7c-ed2a-11e5-989b-255cf1e6b19c.png)

**Comment by pippinsplugins** [comment]
@mindctrl ugh I don't know. What do you guys  think? Yes? No? Either could be valid.

**Comment by michaelbeil** [comment]
Well, if a site admin is using a signup fee as a guaranteed amount, then my vote would be no. Discount codes should only be valid for the subscription.

**Comment by michaelbeil** [comment]
I wonder if we should display the discount code row below the signup fee and proration credit rows, above the total?

**Comment by mindctrl** [comment]
I tend to think of signup fees as something that covers administrative costs for setting up an account, or something like that. In that case, I vote they should not be discounted. Maybe a filter, or happy to hear other thoughts from others on this issue.

**Comment by pippinsplugins** [comment]
Let's make signup fees not get discounted.

**Comment by michaelbeil** [comment]
Perhaps we can add a `$prorations` variable in `class-rcp-registration.php` and remove a signup fee from a recurring upgrade. 

The discount code also applies to recurring subs, which seems odd.

**Comment by pippinsplugins** [comment]
@mindctrl @michaelbeil try now please:
![screen shot 2016-03-21 at 3 28 48 pm](https://cloud.githubusercontent.com/assets/1034109/13933129/a559e0ca-ef79-11e5-99c5-84e89e0c6b1d.png)

**Comment by michaelbeil** [comment]
That is the exact fix I had locally. Looks good here.

I think we should address discounts on recurring subscriptions as well. Do we want discounts to be used on future payments?

**Comment by pippinsplugins** [comment]
Discounts has always been setup to work on recurring. That will be a future change.

**Comment by michaelbeil** [comment]
Ok, yea. I knew that discounts were already setup that way, but wanted to check into a future change, wherein a member only receives a discount on the first payment.

**Comment by pippinsplugins** [comment]
I want to add an option for it but that's out of scope for this issue / release.

**Comment by michaelbeil** [comment]
Alright. Sounds like a plan. This seems good to go here.

@mindctrl ?

**Comment by mindctrl** [comment]
@michaelbeil does this still discount the signup fee?

**Comment by pippinsplugins** [comment]
No, signup fee is not discounted.

**Comment by michaelbeil** [comment]
No, it is not.

**Comment by mindctrl** [comment]
I see this during upgrades.

![image](https://cloud.githubusercontent.com/assets/1254870/13934683/c2e62a30-ef89-11e5-8ae2-18a1bb18c467.png)

**Comment by pippinsplugins** [comment]
Grrr . . . . This is being a pain :P

**Comment by michaelbeil** [comment]
John and I were having mad fun with this on Friday night. 

Should we add a $proration method to the class?

**Comment by pippinsplugins** [comment]
Maybe. I'll dig in more and see what I can find.

**Comment by pippinsplugins** [comment]
Ready for another test. Should work like this:

1. Grab base price --> $20
2. Subtract proration credits --> $20-$10 === $10
3. Subtract discount codes --> 50% ... $10/2 === $5
4. Add signup fees --> $5 + $1 === $6

**Comment by pippinsplugins** [comment]
Pretty sure we're done with this now.

**Comment by pippinsplugins** [comment]
`Total Recurring Per {period}` should not show on 100% discount codes.
![screen shot 2016-03-28 at 8 46 18 pm](https://cloud.githubusercontent.com/assets/1034109/14095463/302d3e5c-f526-11e5-83c0-d8ac844aa2e9.png)
