### ISSUE TITLE
Validate user input on discount code creation screen

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#328]
When creating a discount code, if you key in the `%` sign in the amount field, you can see an error 400, invalid integer message.

![image](https://cloud.githubusercontent.com/assets/1254870/12589743/47aa420c-c42d-11e5-92a6-f5bb56485f9a.png)

![image](https://cloud.githubusercontent.com/assets/1254870/12589729/3857e480-c42d-11e5-9370-bab00b32e3a5.png)

Customer reported this problem. I replicated locally on one site. Another site allows it through, but shows a double `%% on the list:

![image](https://cloud.githubusercontent.com/assets/1254870/12589795/7e52abdc-c42d-11e5-8283-92910e06e79e.png)

**Comment by michaelbeil** [comment]
We would clarify the description by saying: "The amount of this discount code. Use a number without % or $, such as 15."

Or we could just strip any non integer characters on output.

**Comment by mindctrl** [comment]
Left a note on the PR here: https://github.com/restrictcontentpro/restrict-content-pro/pull/336#issue-129893846

**Comment by pippinsplugins** [comment]
See comments on PR :)
