### ISSUE TITLE
Add system info report to help with tech support

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#330]
Like we have in EDD, it would be nice to have a system info report to help troubleshooting issues. Items that would be useful (feel free to add any I miss):

- Site info (URLs under Settings > General, and whether it's multisite)
- WP config (version, language, permalink structure, memory limit, multisite, etc.)
- RCP settings (gateways, page configs, misc settings)
- Installed plugins, broken down by mu-plugins, active, inactive
- Web server config (apache/nginx, PHP version, PHP config, etc)

Any others?

**Comment by michaelbeil** [comment]
Been on my mind to do this. Big :+1:.

**Comment by pippinsplugins** [comment]
Let's do it.

The run down of items to show looks right to me.

**Comment by mindctrl** [comment]
Pushed the first part of this, copied from EDD and adjusted. Still needs the download part wired in, and another pass through the code before I PR.

**Comment by michaelbeil** [comment]
Good deal @mindctrl.

**Comment by pippinsplugins** [comment]
@mindctrl The RCP Config section will need to use `empty()` or `isset()` when first setting up the variables, otherwise it will throw notices.

**Comment by pippinsplugins** [comment]
Let's add enabled gateways to the report too.

**Comment by mindctrl** [comment]
@pippinsplugins added the `empty()` checks and ditched the unnecessary variables. Gateways report already in there. 

![image](https://cloud.githubusercontent.com/assets/1254870/13267119/94c3d9c2-da49-11e5-894a-a34c4d287def.png)

**Comment by michaelbeil** [comment]
nice work @mindctrl.

**Comment by michaelbeil** [comment]
when you open a PR, i can test this out.

**Comment by mindctrl** [comment]
@m can you pull down branch `issue/330` and give it a whirl?

**Comment by michaelbeil** [comment]
whirling ...

**Comment by pippinsplugins** [comment]
Go ahead and open a PR

**Comment by michaelbeil** [comment]
All seems great here: http://beil.io/dsZ5.

**Comment by pippinsplugins** [comment]
:)

**Comment by mindctrl** [comment]
@pippinsplugins when the global was changed, it broke the CSS. I fixed that, and went ahead and renamed the function to match.

**Comment by michaelbeil** [comment]
I noticed the CSS was wrecked too. All fixed.
