### ISSUE TITLE
Media restriction settings

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#332]
Right now, the restriction settings show on attachment post types, but the settings do not get saved. The `save_post` hook doesn't fire on attachment edits. I think `edit_attachment` is the proper hook.

Even still, if you make that work, RCP doesn't restrict the attachment page properly anyway, depending on implementation. I propose one of the two options:
- Fix the settings and restriction of attachment pages, which would likely involve restricting the attachment page and the direct media files
- Remove the meta box from attachment pages until we can dig into the first 

Thoughts?

**Comment by michaelbeil** [comment]
For reference: 
http://cl.ly/1J150p1e2Q3T 
http://cl.ly/0w1Z3j343T30 
http://cl.ly/40461u1y3J22 
http://cl.ly/3U1V041r2t20

**Comment by ramiy** [comment]
I think this issue is also apply to the regular "[Restrict Content](https://wordpress.org/plugins/restrict-content/)" plugin.

**Comment by pippinsplugins** [comment]
Let's remove it completely.

**Comment by pippinsplugins** [comment]
Thanks @mindctrl !
