### ISSUE TITLE
Reports: Bug when custom range spans from one year to another

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#334]
Customer reported and confirmed locally. If you set up a custom range report that spans from one year to the next, the report doesn't stop at the end date. It continues throughout the rest of the year.

Example: custom range from Dec 2015 - Jan 2016.

![image](https://cloud.githubusercontent.com/assets/1254870/12678855/e6bca3d8-c66e-11e5-9986-9a22bfffd9e2.png)

Instead of stopping at Jan 2016, it shows to the end of 2016.

**Comment by pippinsplugins** [comment]
Will get it fixed.

**Comment by pippinsplugins** [comment]
@mindctrl want to give this a quick test?

**Comment by mindctrl** [comment]
@pippinsplugins looks good
