### ISSUE TITLE
language files dont work

### ISSUE THREAD

**Issue by SQLfix** [restrictcontentpro/restrict-content-pro#340]
i use IR wordpress in old versions when install plugin automtic chnge to my languge [ir]

now update to 2.4.9 and dont work languages
auto use .php template files texts

i change ES language files but dont work . when i change .php files work fine example

<?php echo apply_filters( 'rcp_registration_header_logged_in', __( 'Register New Account', 'rcp' ) ); ?>
change to
<?php echo apply_filters( 'rcp_registration_header_logged_in', __( 'xxxxxxxxx', 'rcp' ) ); ?>

in register page show xxxxxxxxx  but when chnge lnguage file do nothing

**Comment by mindctrl** [comment]
@SQLfix could you open a support ticket [here](http://restrictcontentpro.com/support/) and include your translation files so we can take a look?

**Comment by michaelbeil** [comment]
What version of WordPress are you using?

What does the output show when you are on ES?
