### ISSUE TITLE
WooCommerce products are not being restricted

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#341]
When non-members use a direct link, RCP is not restricting the product page at all. 

Our description says: "Restrict viewing of this product to:"  ... and we're not doing that.

We could filter `the_content` I suppose.

- https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/content-filters.php
- https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/integrations/class-rcp-woocommerce.php#L258

**Comment by pippinsplugins** [comment]
Let's see if we can take care of it.

**Comment by mindctrl** [comment]
We introduced a bug here where products hidden in the catalog get restricted. 

This option:
![image](https://cloud.githubusercontent.com/assets/1254870/14251072/300e66f2-fa4f-11e5-9aca-ab7174ce6e1d.png)

**Comment by pippinsplugins** [comment]
@mindctrl let's please open as a separate issue and milestone.
