### ISSUE TITLE
Better payment history on Member details screen

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#342]
I'd love to see the payment history shown on member details screen improved. It should display in a list table format and provide direct links to the payment details screen for each payment.

**Comment by tannerm** [comment]
@pippinsplugins just pushed this up on #366

**Comment by pippinsplugins** [comment]
@tannerm This is looking really good. I've made a couple of tweaks to it just to add the standard WP list table styles.
![screen shot 2016-02-27 at 2 12 17 pm](https://cloud.githubusercontent.com/assets/1034109/13375086/2b76fac4-dd5c-11e5-8321-9ceeaf2e5da0.png)

**Comment by tannerm** [comment]
awesome!
