### ISSUE TITLE
Link to member details screen from payment history rows

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#343]
Each row in the payment history screen should include a link to the details page for the member the payment is for.

**Comment by tannerm** [comment]
@pippinsplugins are you referring to the list page where all the payments are shown or to the payment details page?

**Comment by pippinsplugins** [comment]
The list page.

**Comment by tannerm** [comment]
Just added a pull request here at #370. Not really crazy about this implementation of the edit link, but wanted to throw something up for us to chew on.

**Comment by michaelbeil** [comment]
Do we want that to display edit or something like view member?

**Comment by tannerm** [comment]
@michaelbeil not sure... totally open to suggestions.

**Comment by pippinsplugins** [comment]
I prefer `View Member`.

**Comment by tannerm** [comment]
Sounds good. What do you guys think of this? I updated the text to "View Member" and made it show on hover (like actions on the posts page). https://www.dropbox.com/s/4donyq6u74bf8p7/Screenshot%202016-03-02%2010.30.32.png?dl=0

**Comment by pippinsplugins** [comment]
I like that :+1:

**Comment by michaelbeil** [comment]
I like that much better.
