### ISSUE TITLE
Integration: Easy Digital Downloads

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#351]
Having tighter EDD integration would be great.

Some areas to consider:
- Purchase link (currently not protected on themes that use it manually - in a sidebar for example)
- Prevent checkouts if someone gets an item in the cart by a direct link
- Download links (prevent inactive subscribers from accessing downloads)
- Login redirect for those without active subscriptions when using [edd_login]
- Revoke EDD API access?

Could be others I'm not thinking about now. We can create a formal list after more consideration. Please add any others you think of.

**Comment by pippinsplugins** [comment]
I'd add: restricting `[downloads]` display and downloads archive to paid subscribers.

**Comment by pippinsplugins** [comment]
Instead of some of the options we included above, let's do this just like the WooCommerce integration we have.

**Comment by mindctrl** [comment]
Started mocking this up in `issue/351`. Will continue building it out.

**Comment by mindctrl** [comment]
I don't remember what I meant here: `Login redirect for those without active subscriptions when using [edd_login]`

**Comment by mindctrl** [comment]
> let's do this just like the WooCommerce integration we have

@pippinsplugins our Woo integration has separate settings for viewing and purchasing, but the UI is totally different. On EDD products we use the standard restriction UI. Adding another set of those same controls for controlling purchasing separate will not look good in my opinion. Right now the code on `issue/351` just ties purchasing ability to the viewing. Do you want us to separate the two and explore UI options?

**Comment by mindctrl** [comment]
I'm ok with doing it like it is now and splitting them later if we get enough requests.

**Comment by pippinsplugins** [comment]
I'm fine with just limiting viewing / purchasing with a single UI.

**Comment by mindctrl** [comment]
Added a PR to make it easier to see. We can continue working on it.

**Comment by mindctrl** [comment]
Checklist of items tested:

* [x] Download links do not work if member is expired (edd_file_download_has_access filter)
* [x] Removing restricted items from the /downloads archive listing, if "Hide Premium Posts" is enabled and the member doesn't have access.
* [x] Removing restricted items from [downloads] shortcode output if "Hide Premium Posts" is enabled and the member doesn't have access.
* [x] Redirecting user if "Hide Premium Posts" is enabled, a redirect page is set, and the user doesn't have access to the single download.
* [x] Remove Add to Cart button if member doesn't have access to product.
* [x] Prevent user from buying a product, or adding it to the cart, if member doesn't have access (edd_can_purchase_download filter).

@pippinsplugins any other thoughts here? anything else you want to see added?

**Comment by pippinsplugins** [comment]
Are file downloads only restricted if the product or category has restrictions?

**Comment by mindctrl** [comment]
Yes.

**Comment by mindctrl** [comment]
Just noticed, need to restrict product description in [downloads] shortcode output if user doesn't have access. Currently EDD uses a different method for displaying it. Will update this in a bit.

**Comment by mindctrl** [comment]
Updated PR for `[downloads]` excerpt filter.

**Comment by pippinsplugins** [comment]
Everything ready for testing?

**Comment by mindctrl** [comment]
@pippinsplugins I think so. Hopefully didn't miss too much. If you have any other ideas for areas we need to cover, we can do that too.

**Comment by pippinsplugins** [comment]
Working great!

Merging and closing. If you think of anything that needs added, re-open.
