### ISSUE TITLE
Wrong Help Page Link

### ISSUE THREAD

**Issue by tannerm** [restrictcontentpro/restrict-content-pro#352]
The flyout menu in the admin for RCP still links to the old help page.

**Comment by pippinsplugins** [comment]
It should do a redirect via JavaScript. Do you see that?

**Comment by tannerm** [comment]
I'm not. Just seeing an empty page. No js errors either. To be clear, if I'm in one of the RCP pages then the help link does work.

**Comment by pippinsplugins** [comment]
Huh. That's clearly wrong 😃
