### ISSUE TITLE
Change password form is not validated 

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#354]
Users are able to leave the password fields blank when updating their password with `rcp_change_password_form()`. Can we include a validation check here to ensure that they're entering something (edit: I can also enter two different passwords, with no validation at all)?

**Comment by michaelbeil** [comment]
Yes, we should work this into a future release.

**Comment by pippinsplugins** [comment]
We'll get that fixed!

**Comment by thomasfw** [comment]
Any reason this keeps getting pushed back? It's a fairly large bug imo?

**Comment by pippinsplugins** [comment]
@thomasfw No reason other than urgency of other issues that had to be included in a release. This will get fixed.

**Comment by pippinsplugins** [comment]
Validation is working fine for me:
![screen shot 2016-05-31 at 1 30 20 pm](https://cloud.githubusercontent.com/assets/1034109/15685989/dcecfe5e-2733-11e6-8ca5-d53c26396c28.png)
![screen shot 2016-05-31 at 1 30 33 pm](https://cloud.githubusercontent.com/assets/1034109/15685999/e46fab22-2733-11e6-830a-80ce83bf4860.png)

**Comment by thomasfw** [comment]
Nope, this doesn't work for me, I'm using the `rcp_login_form_fields()` function in a custom template (and the result is the same if I output the `[login_form]` shortcode).

I visit the reset link as received by email..

`www.site.dev/login/?rcp_action=lostpassword_reset&key=[KEY]&login=[username]`

`rcp_login_form_fields()` function correctly displays `rcp_change_password_form()` (as rcp_action == 'lostpassword_reset'). This contains the fields for resetting the password, and the following hidden input..

`<input type="hidden" name="rcp_action" value="reset-password">`

So I submit the form with an invalid password combination, and rcp_action is changed from 'lostpassword_reset' to 'reset-password', meaning that when I'm redirected back to the login page, all I see is the default login form (and no error messages).

So the conditional in `rcp_login_form_fields()` needs to also check for 'reset-password'...

```
elseif ( isset($_REQUEST['rcp_action']) && ($_REQUEST['rcp_action'] === "lostpassword_reset" || $_REQUEST['rcp_action'] === "reset-password") ) {
		echo rcp_change_password_form();
```

This fixes the issue for me..

**Comment by pippinsplugins** [comment]
Your original issue only mentioned changing the password, not resetting it. I'll test again to see if I can replicate.

**Comment by geoffreybr** [comment]
Still not working for me.
The comment from @thomasfw helps me to sort it out.Thanks!

**Comment by mindctrl** [comment]
Fixed here: https://github.com/restrictcontentpro/restrict-content-pro/pull/740
