### ISSUE TITLE
Stripe Gateway: Zero-decimal Currencies Are Not Calculated Correctly

### ISSUE THREAD

**Issue by michaeluno** [restrictcontentpro/restrict-content-pro#357]
It seems by using the Stripe gateway [zero-decimal currencies](https://support.stripe.com/questions/which-zero-decimal-currencies-does-stripe-support) such as Japanese Yen get multiplied by 100. I guess it is the same problem reported on the EDD support forum [here](https://easydigitaldownloads.com/forums/topic/stripe-amounts-two-digits-off/).

**Comment by mindctrl** [comment]
@michaeluno thanks for reporting this. We'll take a look at it for the next update.

**Comment by pippinsplugins** [comment]
@mindctrl We've fixed this in EDD Stripe: 

https://github.com/easydigitaldownloads/edd-stripe/blob/master/edd-stripe-new.php#L1009

https://github.com/easydigitaldownloads/edd-stripe/blob/master/edd-stripe-new.php#L152

**Comment by tannerm** [comment]
Just submitted a PR for this (#381).
