### ISSUE TITLE
PayPal Express Registration Errors

### ISSUE THREAD

**Issue by tannerm** [restrictcontentpro/restrict-content-pro#358]
When signing up with a negative fee >= the price, PayPal errors saying that the initial payment is invalid.

**Comment by pippinsplugins** [comment]
We should remove the `INITAMT` parameter and instead set the trial amount/period if the initial amount is 0 or less than 0. That should take care of it.

**Comment by tannerm** [comment]
cool, sounds good

**Comment by tannerm** [comment]
Just added a PR for this (#374). I messed around with the trial period a little bit but found that it was much cleaner to just not set the INITAMT if the amount was 0 or less.
