### ISSUE TITLE
Bug in category restrictions with posts in multiple categories

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#365]
When a post is assigned to multiple categories and a member has access via one of those, there's a chance they get blocked due to the way we loop through and check for access. [Reference](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.4.11/includes/content-filters.php#L52-L80).

We could build an array of subscription IDs and check against that after the loop instead, I think.

Existed before, but related: #137 cc: @tannerm

**Comment by tannerm** [comment]
Gotcha. I'll look into it @mindctrl.

**Comment by tannerm** [comment]
@mindctrl I just pushed up a new commit to #355 that adds filters to the handling of restricted taxonomies.

As you noted the current behavior is that when any taxonomy has a restriction then the post is restricted. In the same way if any of the post's taxonomy terms are restricted then that shows the whole taxonomy as restricted.

So the current behavior is that the user must have access ALL the assigned terms for the taxonomy check to clear and the user must have access to ALL of the applicable taxonomies.

So I have introduces two filters ('rcp_restricted_taxonomy_term_match_all' & 'rcp_restricted_taxonomy_match_all') to allow the behavior to be ALL or ANY on the taxonomies and taxonomy terms.

This explanation feels much more complicated than it should be, so feel free to ping me if any of this doesn't make any sense.

**Comment by tnorthcutt** [comment]
@tannerm would this change the default behavior, or just allow filtering that behavior?

**Comment by tannerm** [comment]
@tnorthcutt this just allows filtering the default behavior. Everything should function the same as before.

**Comment by mindctrl** [comment]
Thanks @tannerm.

Pippin and I chatted about this last week and we agreed that a person should only be required to have access to one of the terms.

That's a change from the current behavior it seems, but could be considered a bug. I'm not familiar with the legacy here. @pippinsplugins do you still agree?

**Comment by pippinsplugins** [comment]
I still agree; only access to one term should be required.

**Comment by tannerm** [comment]
Sounds good. I'll make the adjustment.

**Comment by tannerm** [comment]
Adjustment made.

**Comment by mindctrl** [comment]
This is looking good now.

**Comment by pippinsplugins** [comment]
Excellent.

I've merged this into release/2.5.

@mindctrl could you do one more test with EDD category archives just to be sure that's working properly?

**Comment by mindctrl** [comment]
EDD category stuff looks good except https://github.com/restrictcontentpro/restrict-content-pro/issues/137#issuecomment-194377253

**Comment by pippinsplugins** [comment]
Good deal. We'll close this one and leave the other open until that's fixed.
