### ISSUE TITLE
"Last Week" earnings report is incorrect

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#368]
The date range shown is incorrect, and there are some debug notices.

![image](https://cloud.githubusercontent.com/assets/1254870/13415688/c6bcc250-df2a-11e5-83ce-440f0a7c497b.png)

`[29-Feb-2016 21:13:49 America/New_York] PHP Notice:  A non well formed numeric value encountered in /Sites/rcp/wp-includes/functions.php on line 295`

![image](https://cloud.githubusercontent.com/assets/1254870/13415699/ec77afd2-df2a-11e5-8fba-8307548ded62.png)

**Comment by michaelbeil** [comment]
Was just going to share this too and then thought I remembered there being an issue. I have just confirmed here that last week is not working.

**Comment by pippinsplugins** [comment]
@michaelbeil @mindctrl mind testing this?

**Comment by mindctrl** [comment]
@pippinsplugins this line seems to be an issue when `last_week` crosses a month. different bug but related and broken. https://github.com/restrictcontentpro/restrict-content-pro/blob/c26c4ac28d02e6dfbab33c792a85c2a7dd56e08a/includes/admin/reports/reports-page.php#L115

Dump of the `$dates` array:

![image](https://cloud.githubusercontent.com/assets/1254870/15836309/31b5a170-2c02-11e6-86d1-b0568e9657f8.png)

**Comment by michaelbeil** [comment]
Still having an issue here.

**Comment by pippinsplugins** [comment]
The dates array looks correct to me. The beginning of last week is 5/30 and the end of last week is 6/30.

**Comment by pippinsplugins** [comment]
I see what it is. We accounted for this in EDD with this:
```php
} elseif ( $dates['range'] == 'this_week' || $dates['range'] == 'last_week' ) {

		$num_of_days = cal_days_in_month( CAL_GREGORIAN, $dates['m_start'], $dates['year'] );

		$report_dates = array();
		$i = 0;
		while ( $i <= 6 ) {

			if ( ( $dates['day'] + $i ) <= $num_of_days ) {
				$report_dates[ $i ] = array(
					'day'   => (string) $dates['day'] + $i,
					'month' => $dates['m_start'],
					'year'  => $dates['year'],
				);
			} else {
				$report_dates[ $i ] = array(
					'day'   => (string) $i,
					'month' => $dates['m_end'],
					'year'  => $dates['year_end'],
				);
			}

			$i++;
		}

		foreach ( $report_dates as $report_date ) {
			$sales = edd_get_sales_by_date( $report_date['day'], $report_date['month'], $report_date['year'] );
			$sales_totals += $sales;

			$earnings        = edd_get_earnings_by_date( $report_date['day'], $report_date['month'], $report_date['year'] , null, $include_taxes );
			$earnings_totals += $earnings;

			$date            = mktime( 0, 0, 0,  $report_date['month'], $report_date['day'], $report_date['year']  ) * 1000;
			$sales_data[]    = array( $date, $sales );
			$earnings_data[] = array( $date, $earnings );
		}

	}
```

**Comment by pippinsplugins** [comment]
This one is making my head hurt. I'm going to punt it to 2.6.3.

**Comment by mindctrl** [comment]
The `data` array passed to `.plot` is empty:

![image](https://cloud.githubusercontent.com/assets/1254870/15843740/8d83c150-2c32-11e6-991b-aad8e36e7a09.png)

because the `while` loop is only checking the day, not the month and day. `30` is never `<=` to `05`.
