### ISSUE TITLE
Unlimited duration (0) and Stripe interval_count

### ISSUE THREAD

**Issue by thadallender** [restrictcontentpro/restrict-content-pro#373]
Stripe plan creations fail if the RCP subscription level is set to an unlimited duration (0). Stripe returns a 400 status with error response:

type: "invalid_request_error"
message: "Invalid positive integer"
param: "interval_count"

Steps to reproduce:

1. Create a new subscription level and set the duration to 0 and set a price.
2. Try to signup for the plan and you'll receive this Stripe error: Status 400, No such plan.
3. Because the plan doesn't exist, checkout fails.

It appears that Stripe doesn't like interval_count to be 0.

Any possible workarounds here for selling unlimited subscriptions through Stripe?

I've attached a screenshot of the full log.

![screen shot 2016-03-02 at 1 25 30 pm](https://cloud.githubusercontent.com/assets/302884/13470554/bd0e372e-e07a-11e5-9644-98848cb3538d.png)

**Comment by pippinsplugins** [comment]
@thadallender Are you on 2.4.10?

**Comment by thadallender** [comment]
@pippinsplugins 2.4.11

Looking at Stripe's API, I'm not sure it supports an interval_count of 0. Yearly also only supports an interval_count of 1.

I have some UX suggestions that I'll include in a pull request soon if you're interested. The UX changes are extraneous to the Stripe/Unlimited Duration issue.

**Comment by pippinsplugins** [comment]
We'll work on getting this resolved right after 2.5.

I'm happy to hear any UX feedback you have :)

**Comment by pippinsplugins** [comment]
I can't replicate this.

Purchase goes through as expected as a one-time purchase.

**Comment by pippinsplugins** [comment]
Closing as works for me.
