### ISSUE TITLE
Multisite database upgrade notice doesn't go away

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#380]
When visiting a sub-site in a network activated multisite install, I see this notice:

![image](https://cloud.githubusercontent.com/assets/1254870/13620445/c5094ecc-e55d-11e5-8070-71a2b0edb531.png)

Clicking the upgrade link doesn't make the notice go away. At this time I'm not sure if the upgrade routine is successful or not.

**Comment by pippinsplugins** [comment]
Network activated?

**Comment by mindctrl** [comment]
Oops, yes it's network activated. Updated original post to reflect that.

**Comment by mindctrl** [comment]
This appears to be fixed now. I can't reproduce. Probably fixed when introducing upgrader class in 2.6.
