### ISSUE TITLE
Activate license button missing in display

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#383]
**Issue**: When a user first installs and activates RCP, they see the notice: `Please enter and activate your license key for Restrict Content Pro to enable automatic updates.` That is all hunky dory until the user clicks on the `enter and activate` hyperlink, leading to the general settings page ('admin.php?page=rcp-settings'):

![screen shot 2016-03-09 at 11 54 18 am](https://cloud.githubusercontent.com/assets/4752949/13645163/3f67e20a-e5ef-11e5-940f-22b83fe37cc3.png)

If a user enters a license key in the license key field, he/she may not know what to do next, as pressing `enter` opens the "Choose a Logo" media modal. However, when one scrolls down to the bottom and then clicks "Save Options", the page reloads and the "Activate License" button is revealed.  
![screen shot 2016-03-09 at 11 56 27](https://cloud.githubusercontent.com/assets/4752949/13645168/44d91d62-e5ef-11e5-8330-ec5a0ddc66ef.png)

**Proposal**: allow the "Activate License" button to always be on display. 

Code to browse: https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/admin/settings/settings.php#L61-L76

AWP has a good implementation of this: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/settings/class-settings.php#L772-L808

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
While we're here let's update the support link to the new site.

**Comment by michaelbeil** [comment]
Works perfect. 
![screen shot on 2016-06-02 at 15-38-15](https://cloud.githubusercontent.com/assets/4752949/15760286/18ff8132-28d8-11e6-9867-26a605e4badf.png)
