### ISSUE TITLE
Initial payment not being processed or recorded for PayPal Pro 

### ISSUE THREAD

**Issue by tannerm** [restrictcontentpro/restrict-content-pro#390]
PayPal Pro is not using 'INITAMT' for signup and so the initial payment is being ignored. On the webhook side of things PayPal is only listening for "recurring_payment" and is not recording when "recurring_payment_profile_created" happens.

**Comment by tannerm** [comment]
Fixed in #388

**Comment by pippinsplugins** [comment]
Looks good.
