### ISSUE TITLE
PayPal is Not processing Discounts or Proration.

### ISSUE THREAD

**Issue by tannerm** [restrictcontentpro/restrict-content-pro#391]
PayPal Express and Pro transactions do not seem to be acknowledging proration or discounts.

**Comment by pippinsplugins** [comment]
@tannerm Is this only with the new discounts / proration or were you seeing this in `master` too?

**Comment by tannerm** [comment]
@pippinsplugins I haven't tested with master yet, but I didn't see any code that would process discounts. So I'm assuming the issue is on master too.

**Comment by pippinsplugins** [comment]
The discount is set during registration and then passed on to the gateway. As long as the gateway is using the price fed in from the registration handling, the discount is accounted for.
