### ISSUE TITLE
Admin Subscription Levels page is very slow on large sites

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#392]
On sites with large user databases the `Subscription Levels` page becomes incredibly unwieldy, likely due to counting members per level. For example, on [CG Cookie](https://cgcookie.com the page can often take upwards of 1-3 minutes to load on a highly tuned server. On lesser servers, such as our development server, the page times out completely after a few minutes. 

This is also true for the `Members` page, but it's not quite as bad.

**Comment by pippinsplugins** [comment]
We could easily fix this by keeping a static count of the member counts for each subscription level. Anytime a member is added or removed from a level, we can increment / decrement the counts.

**Comment by pippinsplugins** [comment]
@carter2422 Could you give branch `issue/392` a try?

I'm pretty sure there are a few edge cases that will cause member counts to get off, so need to find those and account for them.

I also want to add a tool for recounting member counts.

@mindctrl thoughts and testing too?

**Comment by carter2422** [comment]
Initially this seems to work well @pippinsplugins. I haven't had a chance to compare the counted members, though. 

A **Recalculate Member Counts** tool would be useful.

**Comment by pippinsplugins** [comment]
The main thing that needs tested is whether counts are maintained properly
with account activations, cancellations, explorations, etc

**Comment by pippinsplugins** [comment]
Moving to 2.5.2 for further testing.

**Comment by carter2422** [comment]
How's this looking for 2.5.5?

**Comment by pippinsplugins** [comment]
On my list for Monday.

**Comment by pippinsplugins** [comment]
We should store the counts in subscription meta instead of options #507

**Comment by pippinsplugins** [comment]
This appears to work well on pippinsplugins.com

**Comment by carter2422** [comment]
Whoop! @pippinsplugins this appears to be working great on the `issue/392` branch.

**Comment by carter2422** [comment]
@pippinsplugins what triggers a recount of the subscription level members?

**Comment by pippinsplugins** [comment]
@carter2422 two things:

1. Anytime the status of a member changes
2. Once per day via a cron job

**Comment by carter2422** [comment]
Something is off. 

On the Subscription Levels page the *Monthly Citizen* level reports 1487 members, yet on Members it reports 1970.
![screen shot 2016-06-06 at 3 34 53 pm](https://cloud.githubusercontent.com/assets/1648631/15836823/40bbcdee-2bfc-11e6-9578-007a2f991c25.png)

![screen shot 2016-06-06 at 3 34 45 pm](https://cloud.githubusercontent.com/assets/1648631/15836825/43bcd48e-2bfc-11e6-9f92-7f01c20c8552.png)

**Comment by pippinsplugins** [comment]
Members hasn't been updated to use the new counts yet.

That does then beg the question: which is correct . . .

**Comment by pippinsplugins** [comment]
Can you install `WP Crontrol` plugin and manually run the rcp recount cron job?

**Comment by pippinsplugins** [comment]
Hmmm updating member counts is a bit trickier. Right now the counts are affected by:
- recurring (yes/no)
- subscription level
- status
- search

Our new count method only works with
- subscription level
- status

**Comment by pippinsplugins** [comment]
How about we remove the `Recurring Yes/no` filter. Frankly I don't think it's _that_ valuable and, at least for now, it really blocks our ability to dramatically speed up this page.

**Comment by carter2422** [comment]
Seems to me that *Active* should include all members whom have a subscription and are not yet expired.  

And I have no problem removing the Recurring filter; I never use it.

**Comment by pippinsplugins** [comment]
@carter2422 that's what active already refers to, unless a search term has been entered, then it is the number of active members that match that search term.

I think we can go ahead and do the following:

1. Remove the recurring filter
2. Use the new count method for default status
3. Continue to use the old count method when a search term is entered

**Comment by carter2422** [comment]
👍

**Comment by pippinsplugins** [comment]
@carter2422 Were you able to test this further?

**Comment by pippinsplugins** [comment]
Moved the member counts from wp_options to subscription meta.

**Comment by pippinsplugins** [comment]
@carter2422 @mindctrl this is ready for further testing. Members page now uses static counts if there is no search term.

**Comment by mindctrl** [comment]
@pippinsplugins when filtering, the counts don't match the subscription. Could also do the query counts when filtering like we do with search?

![image](https://cloud.githubusercontent.com/assets/1254870/16386085/5fcd29f0-3c5d-11e6-880f-9c7dfc9052bc.png)

I only have 3 members on that subscription.

**Comment by pippinsplugins** [comment]
Manually run cron. Do they match then?

**Comment by mindctrl** [comment]
No, the code only does the real query if searching, not filtering. Different `$_GET` var.

**Comment by pippinsplugins** [comment]
@mindctrl mine are matching. I'll put this up on my live site to test further.

**Comment by pippinsplugins** [comment]
@mindctrl I just tested this on pippinsplugins.com and it appears to be working properly. I'm fairly certain your counts are incorrectly locally because of test data.

**Comment by pippinsplugins** [comment]
I'm going to merge into release/2.6 so we can continue to test further and get it in beta.

**Comment by mindctrl** [comment]
Working good now with latest commit.

**Comment by pippinsplugins** [comment]
Closing then. We can re-open if any issues are discovered.

**Comment by pippinsplugins** [comment]
There's a bug somewhere in the new sub member count stuff. easiest way to see it is set up a new site, reg a new member and see how the counts are off by one. first user reg'd showed 2 counts. did two more new members, for a total of 3, and ended up with a total count of 5.

**Comment by pippinsplugins** [comment]
Found a second issue while testing this:
![screen shot 2016-07-07 at 10 03 25 am](https://cloud.githubusercontent.com/assets/1034109/16657954/16b2e384-442a-11e6-8c15-2e4f7173b543.png)

That's a brand new site where I just registered a new pending member. The pending count shows as 0.

**Comment by pippinsplugins** [comment]
Another issue. If an active member purchases a second subscription that is the same level as they already have, the count goes up improperly.
