### ISSUE TITLE
Free Subscription : Stripe still being called

### ISSUE THREAD

**Issue by singram26** [restrictcontentpro/restrict-content-pro#394]
When attempting to create a free subscribed account through RCP form, I receive a "The card number is not a valid credit card number." error.

Credit card fields are not showing up because it is free.

Stripe returns: 402 Payment Required - with the following response:

    {
        "error": {
            "message": "The card number is not a valid credit card number.",
            "type": "card_error",
            "param": "number",
            "code": "invalid_number"
        }
    }

Any help towards this would be great.

**Comment by pippinsplugins** [comment]
@singram26 Please go ahead and open a support ticket: http://restrictcontentpro.com/support

GitHub is for development tracking only.
