### ISSUE TITLE
$is_recurring does not get enabled on late, successful payment

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#395]
If a user's subscription temporarily lapses due to a failed payment and then is reactivated a day or more past their normal renewal date when the payment succeeds then they are correctly set to `Active`. However, `is_recurring` does not get set. 

This then becomes a problem because it then appears to the user they no longer have a recurring subscription and they are not able to cancel their account themselves. 

At least in Stripe.

**Comment by pippinsplugins** [comment]
@mindctrl could you dig into this?
