### ISSUE TITLE
Remove restrictions after a set period of time or on a specific date

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#405]
**Proposal**: Make posts restricted for a set period of time only, after which they'd be unrestricted.

**Comment by pippinsplugins** [comment]
I'd like to see this, though it will likely need to be a pro add-on.

**Comment by michaelbeil** [comment]
Sounds like a plan.

**Comment by mindctrl** [comment]
Tracking this here: https://trello.com/c/U73jpIg5/33-remove-restrictions-after-a-set-period-of-time-or-on-a-specific-date

**Comment by michaelbeil** [comment]
beat me to it.
