### ISSUE TITLE
Improve the upgrade routine system

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#406]
We need to improve the upgrade routine code to be similar to what's in AffWP and/or EDD.

While we're doing that, we can remove the duplicate check for `rcp_payments_db_version` here: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.4.11/includes/upgrades.php#L12-L17

**Comment by pippinsplugins** [comment]
Oops, logged a duplicate issue. #511
