### ISSUE TITLE
Link payment transaction IDs to charge page in merchant

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#413]
To help with refund processing, it would be great to have the transaction IDs on the payment details screen be linked to the charge details page in the merchant processor.

**Comment by pippinsplugins** [comment]
@michaelbeil could you give this a test?

**Comment by michaelbeil** [comment]
Yes. It looks we need testing done for all payment gateways, to verify that the charge page is linked to the correlated gateway, right?

**Comment by pippinsplugins** [comment]
Yes please.

**Comment by pippinsplugins** [comment]
I'm going to go ahead and merge this in. If any issues are noticed, we can re-open.
