### ISSUE TITLE
Improve settings descriptions

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#414]
In some places, the settings descriptions can be improved to help customers better understand how something works.

For example, the `Reminder Period` description doesn't make it clear that the Expiring Soon email isn't sent to members with auto-renewing subscriptions. We just had a ticket about this.

There may be others, so I'm generalizing the issue so we can give them all a good look.

Possibly related to #155.

**Comment by pippinsplugins** [comment]
:+1:
