### ISSUE TITLE
Issues with prorates over $1000

### ISSUE THREAD

**Issue by jmarx** [restrictcontentpro/restrict-content-pro#418]
Hey guys,
I don't have time right now to send you a bunch of screengrabs.
But i'll lay it out.

I have two subs.
1 for 1000
1 for 1200

I sign up for the 1000.
Upgrade to 1200
Expected result: I get charged 200
Actual result: I get charged 1200

Lower amounts still work as expected.
Here is a screengrab of my prorate screen. This is on a raw version of wp and your plugin.
Can you guys 
<img width="690" alt="screen shot 2016-03-30 at 6 15 37 pm" src="https://cloud.githubusercontent.com/assets/223919/14159570/8928e144-f6a4-11e5-87da-161b2af307e8.png">
try and replicate this?

**Comment by michaelbeil** [comment]
For any support-related questions, we ask that you send a ticket to https://restrictcontentpro.com/support as we reserve this repository for development purposes.
