### ISSUE TITLE
Issues with prorates over $1000 - Have a PR this time

### ISSUE THREAD

**Issue by jmarx** [restrictcontentpro/restrict-content-pro#421]
Please don't immediately close this. It is a real issue and I have a PR.

Any amount over 1000$ is not getting calculated properly when assigning the prorate credit.

Every time I upgrade from anything over $1000, the prorate credit gets knocked down to  -1.

Because a string "-1,000" is being sent through all your processing functions which ignore everything after the comma.

The "number_format" function seems to be the culprit I have found. And I removed it in this PR. Obviously you guys are way more familiar with this codebase so I'm throwing this out there and I am going to continue to test to see where this could screw other things up. But this should be a high priority things as of now anyone upgrading on sub levels worth more than a grand are going to get charged the full rate(minus a dollar) twice.

Thanks for your attention to this.

Here is the PR I have so far:
https://github.com/restrictcontentpro/restrict-content-pro/pull/420

Thanks for not closing this right away :)
Jeff

**Comment by michaelbeil** [comment]
Thanks for letting us know :smile:. We will test the PR and get back to you.

**Comment by michaelbeil** [comment]
Related: #418

**Comment by jmarx** [comment]
Looks like the purpose of number_format is to make the number look pretty for display. But in the proration credit slot I'm not sure that is a big deal. The final number still gets formatted properly it looks like.

**Comment by pippinsplugins** [comment]
`number_format()` would definitely be problematic here. We'll test further and merge in if it resolves it for us. Thanks!

**Comment by pippinsplugins** [comment]
Merged.
