### ISSUE TITLE
Prorating amounts over 1,000 fails

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#426]
We return amounts through `number_format()` so any amount with three digits breaks because of the `,` added. Instead of formatting the values, we should just typecast them as floats.

**Comment by pippinsplugins** [comment]
Potentially fixed in #420

**Comment by pippinsplugins** [comment]
@mindctrl can you test the PR again?

**Comment by mindctrl** [comment]
@pippinsplugins #420 looks good here.

**Comment by pippinsplugins** [comment]
Good deal :+1:

**Comment by jmarx** [comment]
Thanks!! :+1:
