### ISSUE TITLE
Modify user role when subscription starts/ends

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#427]
It would be nice to change the user role when a user pays for a subscription and when a subscription expires.

**Comment by mindctrl** [comment]
We also need to ensure that changing subscription levels removes the old role given to them by their previous subscription level.

**Comment by mindctrl** [comment]
Added a PR for removing the role when a member expires. https://github.com/restrictcontentpro/restrict-content-pro/pull/834

re: my previous comment about roles during subscription changes, that was handled previously in https://github.com/restrictcontentpro/restrict-content-pro/pull/647

**Comment by pippinsplugins** [comment]
Looks great!

Note: manually changing the subscription level via the admin won't affect the roles.

**Comment by pippinsplugins** [comment]
Merged.
