### ISSUE TITLE
Register with Email (no username)

### ISSUE THREAD

**Issue by JamesGeiger** [restrictcontentpro/restrict-content-pro#431]
Please add the option to register with email and not a username. 

Thanks.

**Comment by pippinsplugins** [comment]
Thanks for the suggestion @JamesGeiger! We'll certainly consider adding it.

Note: you can register with just an email address if you use Stripe Checkout: http://docs.pippinsplugins.com/article/1249-stripe-checkout

**Comment by fasouto** [comment]
+1 I'm also interested in this

**Comment by JamesGeiger** [comment]
@fasouto :)

**Comment by colomet** [comment]
It will be nice to enable email verification for new users.

thanks

**Comment by nosegraze** [comment]
Closing this as we have a code snippet and tutorial for it: https://docs.restrictcontentpro.com/article/1743-email-only-registration I'm not sure we really need to add an extra setting for it.

Reopen if you disagree.
