### ISSUE TITLE
Add Alipay as a supported payment gateway 

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#432]
Alipay was recently added to EDD. Since Alipay is part of Stripe Checkout, let's add support. 

https://stripe.com/docs/alipay

**Comment by carter2422** [comment]
That would be excellent!

**Comment by pippinsplugins** [comment]
For the [register_form_stripe] registration forms, simply adding `data-alipay="1"` to the shortcode should enable it.

**Comment by pippinsplugins** [comment]
:+1:
