### ISSUE TITLE
Refund report missing

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#443]
The refund reports we introduced with #326 has disappeared. Perhaps we forgot to merge it in?

**Comment by mindctrl** [comment]
Looks like it got reverted here: https://github.com/restrictcontentpro/restrict-content-pro/commit/2a8a1c41b0e530d117b26deb55d1442dea4a31c1

**Comment by mindctrl** [comment]
Cherry picked that commit for the PR.

**Comment by michaelbeil** [comment]
good 🍒  picking john. looking forward to having this merged back in.
