### ISSUE TITLE
Revoke Access link doesn't properly revoke access

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#445]
When using the Revoke Access link on the members table, the member is set to Cancelled but access is not revoked. The member still has access until the expiration date passes.

**Comment by mindctrl** [comment]
I asked the customer who reported this how often he uses the link, and his reply was this:

---

I don't know how often they use the "Revoke Access" link, but whenever I'm training them on how to use RCP, it's awkward because I have to explain to them that the "Revoke Access" link doesn't actually revoke access.

I would probably just remove that link altogether to avoid confusion. The only way to actually revoke access is to change their expiration date or delete them from the system which I don't think should be automated with a link like that. Just my two cents because I think some people are probably using the Revoke Access link under the impression they have restricted access for that user.

---

I'm inclined to agree with his suggestion that we remove it, if for different reasons. I don't know if we'd get any pushback on that from existing customers, but it's a somewhat 'dangerous' action to take and having it so easily accessible probably isn't necessary.

Thoughts?

**Comment by pippinsplugins** [comment]
I'm fine with removing it completely.

**Comment by pippinsplugins** [comment]
https://github.com/restrictcontentpro/restrict-content-pro/pull/520

**Comment by mindctrl** [comment]
Works fine.
