### ISSUE TITLE
Stripe coupons aren't created when just Stripe Checkout is enabled

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#446]
If you create a discount code with only Stripe Checkout enabled, it doesn't get created on stripe.com. This isn't apparent when saving the discount in RCP. Then, if you try to use the discount code to make a purchase with Stripe Checkout, you get a 400 error because the coupon doesn't exist on stripe.com.

**Comment by michaelbeil** [comment]
Was this happening when switching from test mode to live mode with only Stripe Checkout enabled? (i.e. test a coupon in test mode and then try to use it in live mode.)

I did not see an issue when remaining on test mode alone or live mode, or perhaps I missed something.

**Comment by carter2422** [comment]
I'm getting this as well while creating discounts in Test Mode in RCP, the discounts do not get created in Stripe when Stripe Checkout is the only enabled gateway.
