### ISSUE TITLE
Subscriptions aren't removed from processor when changing to a one-time payment

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#447]
If you have a recurring subscription and change to another subscription, and in doing so you choose to not make it recurring, the existing subscription is not removed from the user on the processor side. This results in the customer still getting billed for the first subscription while no longer having access to that subscription in RCP.

Steps to reproduce:
- Sign up for a recurring sub
- Change to another sub, uncheck the Auto Renew box, and complete payment.

Check Stripe/PayPal to see that the recurring sub from step one is still active.

**Comment by pippinsplugins** [comment]
Good catch.

**Comment by pippinsplugins** [comment]
For PayPal Standard, it doesn't get cancelled because we cancel the previous subscription during the `subscr_signup` IPN, which only fires for subscriptions:
```php
// Subscriptions
switch ( $posted['txn_type'] ) :

	case "subscr_signup" :
		// when a new user signs up

		// store the recurring payment ID
		update_user_meta( $user_id, 'rcp_paypal_subscriber', $posted['payer_id'] );

		if( rcp_can_member_cancel( $member->ID ) ) {
			$cancelled = rcp_cancel_member_payment_profile( $member->ID, false );
			if( $cancelled ) {
				update_user_meta( $member->ID, '_rcp_just_upgraded', time() );
			}
		}

		$member->set_payment_profile_id( $posted['subscr_id'] );

		do_action( 'rcp_ipn_subscr_signup', $user_id );


		die( 'successful subscr_signup' );

		break;
```

**Comment by pippinsplugins** [comment]
Stripe fails because we handle the cancellation in the recurring signup portion of the gateway processing only. We need to do it in both.

**Comment by pippinsplugins** [comment]
PayPal Express and PayPal Pro also have the cancellation in the `if( $this->auto_renew )` portion only.

Looks like 2Checkout should work as is.

**Comment by pippinsplugins** [comment]
PayPal Standard works now:
![screen shot 2016-04-27 at 11 33 27 am](https://cloud.githubusercontent.com/assets/1034109/14859932/ed2d270e-0c6b-11e6-8d0e-300501ab8ff7.png)
