### ISSUE TITLE
Some strings are missing textdomains

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#448]
We missed some in `templates/register-total-details.php` and `includes/registration-functions.php`. Noticed a couple more in `includes/login-functions.php` too.

**Comment by mindctrl** [comment]
We'll need to regenerate the .pot file after updating this.

**Comment by michaelbeil** [comment]
Solid find for i18n.

**Comment by pippinsplugins** [comment]
@mindctrl regenerate pot and push that then we can call this good.

**Comment by michaelbeil** [comment]
Related: #454. After an update to pot I could refresh the Portuguese translations.

**Comment by mindctrl** [comment]
@m let's regenerate the .pot file and close this last, to make sure we catch everything. #443 will introduce some strings back into the mix.

**Comment by mindctrl** [comment]
@michaelbeil let's regenerate the .pot file and close this last, to make sure we catch everything. #443 will introduce some strings back into the mix.

**Comment by michaelbeil** [comment]
Perfect.
