### ISSUE TITLE
Free Registration not allowed when only Stripe Checkout is Enabled

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#452]
If you're using Stripe Checkout then you cannot signup for a free account without submitting payment details. 

![screen shot 2016-04-14 at 2 11 36 pm](https://cloud.githubusercontent.com/assets/1648631/14540510/fed3472a-024a-11e6-8eb9-612efa6839ba.png)
![screen shot 2016-04-14 at 2 11 41 pm](https://cloud.githubusercontent.com/assets/1648631/14540512/01cdf47a-024b-11e6-8e47-123d30c2d222.png)

If a free membership is chosen then the *Submit Payment* button should be *Register* instead, in the same way that it is when using any other gateway.

**Comment by pippinsplugins** [comment]
@mindctrl could you dig into this tomorrow?

**Comment by mindctrl** [comment]
I was able to replicate this on one site but not another. Will do some digging and see what I can find.

**Comment by carter2422** [comment]
Quick related followup, this is working great now but the registration button still says **Submit Payment** when choosing a free subscription. This just makes it confusing to the user.

**Comment by pippinsplugins** [comment]
See https://github.com/restrictcontentpro/restrict-content-pro/issues/485
