### ISSUE TITLE
Brazilian Real addition breaks currency sign

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#456]
When USD is selected, `R$` shows instead of `$`. Working on a fix locally.

**Comment by pippinsplugins** [comment]
My fault for merging PR without testing.

**Comment by michaelbeil** [comment]
It is ok. Now we discovered that there were some more currency signs that need to be added anyways.

**Comment by michaelbeil** [comment]
I should have a PR in the morning with a working unit test.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by michaelbeil** [comment]
All currencies and currency signs are working well.
