### ISSUE TITLE
Unrestricted WooCommerce products are improperly restricted

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#457]
If an item is unrestricted, it's possible that it gets restricted anyway. This is due to not properly checking `$values` here: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.5.2/includes/integrations/class-rcp-woocommerce.php#L355

`$levels` can return as:
```
Array
(
    [0] => 
)
```

**Comment by pippinsplugins** [comment]
@mindctrl can you do a bit of further testing (unless you already have) to ensure that the first key in the array can't be empty while the second key is not empty?

**Comment by mindctrl** [comment]
Will do.

Note: unit tests failed pending: https://github.com/restrictcontentpro/restrict-content-pro/issues/456

**Comment by michaelbeil** [comment]
Working on a unit test for 456 today.

**Comment by mindctrl** [comment]
@pippinsplugins I don't see any instances where the first key can be empty while second is not.

**Comment by pippinsplugins** [comment]
@mindctrl Good, merging.
