### ISSUE TITLE
Expiring/renewing soon emails

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#460]
The expiring soon email only sends on the first expiration notice. It does that by checking the _rcp_expiring_soon_email_sent user meta and it doesn't get deleted. So if a member has been emailed once, they'll never get emailed again if their subscription is expiring soon later. Note: this is only when auto-renew is not enabled. 
   
We should work out a fix for the user meta to be deleted sometime after the expiration, that way, when someone renews or buys another membership, they can get emailed about it in the future.

So, perhaps we should add a renewing soon email field under the email settings tab, along with adding another cron event for the renewing soon email.

**Comment by pippinsplugins** [comment]
We need to delete it during registration / renewal.

**Comment by mindctrl** [comment]
@pippinsplugins what you think about hooking into rcp_set_status and just doing it any time a member is set to active?

**Comment by michaelbeil** [comment]
That seems like a good approach. Simply check if the member is active and the expiring email can be resent if a member is active.

**Comment by pippinsplugins** [comment]
Yep, works for me.
