### ISSUE TITLE
Stripe Checkout error with unlimited subscription level

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#467]
With Stripe Checkout enabled, let us say that a user creates an unlimited subscription level and add the [register_form_stripe id="3"] to a page. When a customer attempts to register for the subscription, after entering all needed details in the checkout modal, the customer is met with a 400 error page.  
![screen shot 2016-04-18 at 7 37 40 pm](https://cloud.githubusercontent.com/assets/4752949/14693540/6307afea-0725-11e6-9e6b-7a0af92607cf.png)

Here is the JSON response from Stripe:
```` json
{
    error:
    {  
        type: "invalid_request_error"
        message: "No such plan: false"
        param: "plan"
    }
}
````

**Comment by pippinsplugins** [comment]
Ah, that's because you can't have an unlimited plan with Stripe (it's a one time purchase). We setup Stripe Checkout to force automatic renewals. We'll just need to account for that.

**Comment by michaelbeil** [comment]
Got it. This only happens with the [register_form_stripe], so we will need to look there.

**Comment by michaelbeil** [comment]
This is fixed in https://github.com/restrictcontentpro/restrict-content-pro/pull/468/commits/b98ccf81c3e782c8692b8100259b455ae15a9079.
