### ISSUE TITLE
String missing in pot file

### ISSUE THREAD

**Issue by samikeijonen** [restrictcontentpro/restrict-content-pro#469]
There is string `Upgrade or change your subscription` in the plugin but for some reason it's not in the .pot file. Could you regenerate the .pot file or is there something I'm missing?

**Comment by pippinsplugins** [comment]
We will get that fixed!

**Comment by pippinsplugins** [comment]
The string is showing up in the `rcp.pot` file for me. Perhaps the Finnish po/mo file just needs updated?

**Comment by pippinsplugins** [comment]
Ok actually now the POT file is updated. https://github.com/restrictcontentpro/restrict-content-pro/commit/006f672f3499ea387dafcf5c891107e888682d20

**Comment by samikeijonen** [comment]
Thanks!
