### ISSUE TITLE
Stripe checkout modal window has dollar sign

### ISSUE THREAD

**Issue by samikeijonen** [restrictcontentpro/restrict-content-pro#470]
When using Stripe Checkout there is dollar sign ($2.90) even if in the RCP settings we use euros. Is this RCP related issue or Stripe related? I know that Stripe don't offer translations in Finnish at the moment for Stripe Checkout. But dollar sign should still be the same as currency used in RCP settings.

![screenshot 2016-04-23 16 53 00](https://cloud.githubusercontent.com/assets/1820415/14761839/e8695648-0973-11e6-865d-ff50aacae628.png)

**Comment by pippinsplugins** [comment]
Pretty sure this is a bug on our end. We'll get it taken care of!

**Comment by pippinsplugins** [comment]
We're not passing `data-currency` to the window options.

**Comment by mindctrl** [comment]
PR looks good here.

![image](https://cloud.githubusercontent.com/assets/1254870/14762257/23e99366-0944-11e6-827e-6e838aa74450.png)

**Comment by samikeijonen** [comment]
Works for me also, thanks!

Could it also respect the Currency Position setting?

**Comment by michaelbeil** [comment]
Nice find @samikeijonen.

We should be able to pass the currency position option as well.

**Comment by pippinsplugins** [comment]
Doesn't look like there is a currency position setting, unless I've missed it: https://stripe.com/docs/checkout

**Comment by samikeijonen** [comment]
It would be cool if Stripe added that.

**Comment by pippinsplugins** [comment]
Definitely!
