### ISSUE TITLE
Improve list table responsiveness

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#472]
The list table actions currently have their own dedicated `Actions` column. This results in messy displays when on small screens and is also against core WordPress UI.
![screen shot 2016-04-27 at 10 56 23 am](https://cloud.githubusercontent.com/assets/1034109/14858735/d302d9e6-0c66-11e6-8b7b-0651838bdb01.png)
I propose we move them to inline row actions that match WordPress core UI:
![screen shot 2016-04-27 at 10 57 47 am](https://cloud.githubusercontent.com/assets/1034109/14858751/e65a376e-0c66-11e6-886f-236936fb780f.png)

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by mindctrl** [comment]
This works great.

**Comment by pippinsplugins** [comment]
Let's also go ahead and do the other list tables:

![screen shot 2016-06-02 at 4 00 02 pm](https://cloud.githubusercontent.com/assets/1034109/15760909/1b4df466-28db-11e6-861f-77b8d889bdb8.png)

**Comment by pippinsplugins** [comment]
@michaelbeil ready for testing in https://github.com/restrictcontentpro/restrict-content-pro/pull/528

**Comment by mindctrl** [comment]
I see some other adjustments that need to be made at various viewports. Also want to show the payment amount on small screens without having to expand the details.

**Comment by mindctrl** [comment]
I also need to add links to the sub names and discount code names.

**Comment by mindctrl** [comment]
Links are added. Not sure about showing the payment amount for mobile views. Everything inside the row actions is only shown when tapped. The amount would need to be shown in the user column and hidden on larger displays. Thoughts?

**Comment by pippinsplugins** [comment]
How about something like this?
![screen shot 2016-06-06 at 12 07 33 pm](https://cloud.githubusercontent.com/assets/1034109/15830669/49078776-2bdf-11e6-980f-b88cd24ddb58.png)

**Comment by mindctrl** [comment]
@pippinsplugins I like it. Added. Only shows on widths of 782px and smaller, which is when it collapses into the mobile view.

**Comment by pippinsplugins** [comment]
Love it.

Anything else you see or want to add before we merge this in?

**Comment by mindctrl** [comment]
@pippinsplugins looking pretty good here. I think we can merge and tweak further if needed when reworking the CSS in #535

**Comment by michaelbeil** [comment]
Looking good.
