### ISSUE TITLE
Move rcp_can_member_cancel() and rcp_cancel_member_payment_profile() to methods of RCP_Member

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#473]
`rcp_cancel_member_payment_profile()` and `rcp_can_member_cancel()` should be methods of `RCP_Member` instead of global functions.

We'll leave the functions in place but they should become wrappers of the `RCP_Member` methods.

**Comment by nosegraze** [comment]
PR: #937

**Comment by pippinsplugins** [comment]
This looks good at first glance. I haven't had a chance to test it yet though.

**Comment by mindctrl** [comment]
This is working fine for me in Stripe. This was already the case, but noticed we're not checking for Stripe API keys like we do for other gateways before saying a member can cancel.

Can't test PayPal due to sandbox issues.

**Comment by pippinsplugins** [comment]
Looks great, merged.

Note, in the future I would also like to take this further and remove the gateway-specific code into gateway function files, similar to how we handled it in EDD Recurring Payments.
