### ISSUE TITLE
Non-translatable string in templates/paypal-express-confirm.php line 27

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#474]
Currently we are outputting a dynamic string here:

```php
echo sprintf( __( 'Every %d %s(s)', $rcp_checkout_details['subscription']['duration'], 'rcp' ),
    $rcp_checkout_details['subscription']['duration'],
    $rcp_checkout_details['subscription']['duration_unit']
``` 

This could be better:
```php
printf( _n( 'Every %1$d %2$s', 'Every %1$d %2$ss', 'rcp' ),
    esc_html( $rcp_checkout_details['subscription']['duration'] ),
    esc_html( $rcp_checkout_details['subscription']['duration_unit'] )
);
```

Even still, we have an issue with the duration and duration units that are added dynamically to the string based on the RCP settings.

**Comment by pippinsplugins** [comment]
@mindctrl Give this a test please?

**Comment by michaelbeil** [comment]
We are missing the 3rd parameter in `_n(`: `$number`.

`<?php _n( $single, $plural, $number, $domain ) ?>`

We should add it in, but we still need a way to better translate each `duration_unit`.

**Comment by pippinsplugins** [comment]
I'm going to move this to 2.5.4 so that we can get 2.5.3 out the door since there are numerous important issues there.

**Comment by mindctrl** [comment]
@michaelbeil can you test `issue/474-alternate` and see if it works and if I broke anything? :)  I don't know if we need esc_html, but I added it since you already had it in there, and it seems to be fine in my tests.

**Comment by michaelbeil** [comment]
Reviewed and looks good.
