### ISSUE TITLE
Introduce an add-ons page to the Restrict submenu.

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#484]
We should have an add-ons page inside the Restrict admin menu to help increase awareness of the ways to extend RCP, something like we have in Easy Digital Downloads and AffWP.

**Comment by pippinsplugins** [comment]
This is done but waiting for the RSS feed to be live on the site: https://github.com/restrictcontentpro/rcp-site-child/issues/44

**Comment by michaelbeil** [comment]
Looks good here once the feed is live.

**Comment by sumobi** [comment]
@pippinsplugins We're good to go on this. The only thing left is to add excerpts to each download so the buttons don't overlap.

![screen shot 2016-06-03 at 4 17 16 pm](https://cloud.githubusercontent.com/assets/52581/15768641/c0236ffe-29a6-11e6-9516-f0712161478f.png)

Should ideally be 2 lines or less like AffiliateWP and EDD:

![screen shot 2016-06-03 at 4 18 08 pm](https://cloud.githubusercontent.com/assets/52581/15768648/cadfafb6-29a6-11e6-8f9a-345552bfbe77.png)

**Comment by sumobi** [comment]
Some of the official free add-ons also need a new excerpt:

![screen shot 2016-06-03 at 4 19 54 pm](https://cloud.githubusercontent.com/assets/52581/15768682/1a11380c-29a7-11e6-8d7d-16064daf86e3.png)

**Comment by pippinsplugins** [comment]
Done and done!
