### ISSUE TITLE
Restrict comment visibility and commenting ability on restricted posts

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#489]
Currently, if a post is restricted the comments are visible and the comments form is shown. Let's see what we can do to cleanly restrict access to those.

**Comment by mindctrl** [comment]
This looks good to me. Only thing I see is a user that doesn't have access can see comments, but I think that's because it's not merged into all the new `release/2.6` stuff where we're reworking the restriction UI and things underneath.

Let's leave this open until it's merged in with everything for one final test.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@mindctrl merged into `release/2.6` so we can test it further now.

**Comment by mindctrl** [comment]
@pippinsplugins looks good now.
