### ISSUE TITLE
Update [restrict] to use can_access() method of RCP_Member

### ISSUE THREAD

**Issue by ghost1227** [restrictcontentpro/restrict-content-pro#490]
The `[restrict]` shortcode currently doesn't use the `can_access()` method of `RCP_Member`. As a result, content restricted with the shortcode doesn't work with plugins like IP Restriction that override `can_access()`.

**Comment by mindctrl** [comment]
PR attached. Needs thorough testing of the restrictions settings. During my tests, I found issues with restrictions under certain conditions, so went ahead and reworked the logic that handles that so the filter would return more accurate data. Need to make sure I didn't break something else.

**Comment by pippinsplugins** [comment]
No more `extract()` 🎉

**Comment by pippinsplugins** [comment]
@mindctrl This looks to work perfectly for everything except the `WP Approve User` integration. ANnunapproved user can still access restricted content.

**Comment by pippinsplugins** [comment]
@mindctrl Could you test ^?

**Comment by pippinsplugins** [comment]
Looks like subscription level IDs need to be trimmed.

Works: `[restrict subscription="1,2" paid="true"]`

Doesn't work: `[restrict subscription="1, 2 " paid="true"]`

**Comment by pippinsplugins** [comment]
Level ID trimming fixed.

Just finished testing a bunch of configurations and everything seems to work great for me.

**Comment by mindctrl** [comment]
@pippinsplugins WP Approve User integration looks great.

**Comment by pippinsplugins** [comment]
Once unit tests pass, we'll merge.

**Comment by michaelbeil** [comment]
Good deal!
