### ISSUE TITLE
Replace TCPDF with simple HTML / print view

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#493]
The included PDF library is large and accounts for a considerable amount of the total plugin size. We've discussed moving it to a separate plugin, or looking for an alternative library that isn't so large.

**Comment by pippinsplugins** [comment]
Let's look at GiveWP for how they did it.

**Comment by pippinsplugins** [comment]
I think instead of moving it, we should replace it with DOMPDF: https://github.com/dompdf/dompdf

**Comment by pippinsplugins** [comment]
Nvm, DOMPDF is 9+ MBs.

I'm going to go with straight HTML view > print instead.

**Comment by mindctrl** [comment]
Looks good. Just pushed a change to the text on the links for viewing receipts.
