### ISSUE TITLE
Add restriction settings to the Add term screen

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#497]
Right now the term restriction settings are only visible on the `edit term` screen. This results in people not even knowing it's a feature. Let's see about adding them to the `add term` screen.

**Comment by pippinsplugins** [comment]
Moving to 2.7.

**Comment by pippinsplugins** [comment]
Started in #760

**Comment by pippinsplugins** [comment]
@mindctrl I think this is ready to merge, unless you want to play with the UI some more.

**Comment by pippinsplugins** [comment]
Tested this with my Sugar Event Calendar plugin and the category restriction worked perfectly for it's custom taxonomy.

**Comment by mindctrl** [comment]
I'll go ahead and merge it. The UI issue I see is really a core thing, due to the fact that the add term happens via ajax, so if the list is long enough to push it out of view, I don't think there's much we can do without some hacky javascript. If I come up with an idea I'll work it from another issue.
