### ISSUE TITLE
Amounts missing on PDF invoices for certain currencies

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#500]
When using certain currencies, PDF invoices don't show an amount due to an error with `iconv()` [here](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.5.4/includes/invoice-functions.php#L181). It throws the following debug notice:
`PHP Notice:  iconv(): Detected an illegal character in input string in /wp-content/plugins/restrict-content-pro/includes/invoice-functions.php on line 181`

Invoices look like this:
![image](https://cloud.githubusercontent.com/assets/1254870/15332039/11b436fa-1c32-11e6-98ae-9cd61a0b0410.png)

Changing that line to this seems to fix it:
`$amount = iconv('UTF-8', 'ISO-8859-1//TRANSLIT', $amount );`.

Submitting a PR for further testing.

**Comment by mindctrl** [comment]
@michaelbeil mind running some tests on this in different currencies? I noticed a few currencies that show a `?` character. But, before this change, they were blank, so this is an improvement for those for sure. Short of building a map of various character sets, I'm not sure we can do much else with that.

**Comment by pippinsplugins** [comment]
Merged into master.

**Comment by mindctrl** [comment]
I had a customer test this, and the single quotes gave her parse errors. Swapping to double quotes worked for her. Not sure why, but I think we'll swap it here just in case.

**Comment by pippinsplugins** [comment]
Good idea.

**Comment by pippinsplugins** [comment]
Closing as wontfix due to #493

**Comment by pippinsplugins** [comment]
This is now invalid per #493
