### ISSUE TITLE
Rework UI for Restrict this Content metabox

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#516]
I think we should really look into ways to improve the `Restrict this Content` metabox. Customers incorrectly configure it all the time.

How it is currently:
![screen shot 2016-05-31 at 1 43 50 pm](https://cloud.githubusercontent.com/assets/1034109/15686412/c5d66b04-2735-11e6-8fd1-7c1e14b96e9c.png)

A few issues customers encounter:

- Do not know when to check `Paid Only`
- What is an access level?
- Do subscription level boxes need to be checked?

**Comment by pippinsplugins** [comment]
Some thoughts on how we could improve this:

1. Start by showing only a drop down for subscription level
2. Once subscription level(s) is selected, automatically set (in the background) `Paid Only` if the subscription has a price greater than 0.00, else leave unset
3. Move Access Level, User Level, Show Excerpt, and Hide from Feed in to an `Advanced Options` section that is either separate or hidden by default.

**Comment by michaelbeil** [comment]
I like the idea of an advanced options tab in the restrict this content metabox.

**Comment by pippinsplugins** [comment]
@michaelbeil could you give this a try now and let me know what you think?

Note: it is not functional. It's display only (no settings save).

**Comment by pippinsplugins** [comment]
New proposed UI:
![screen shot 2016-05-31 at 5 18 40 pm](https://cloud.githubusercontent.com/assets/1034109/15692402/c0ecb3dc-2753-11e6-9b14-2c87dac37b2b.png)

**Comment by JamesGeiger** [comment]
@pippinsplugins As a user, this new UI looks epic. Hope it get's implemented soon!

**Comment by pippinsplugins** [comment]
@JamesGeiger Thanks!

**Comment by michaelbeil** [comment]
Looks really nice here @pippinsplugins.

**Comment by michaelbeil** [comment]
UI is cleaner, simpler, and more intuitive.

**Comment by pippinsplugins** [comment]
Clicking `Members of specific subscription level` reveals the level options:
![screen shot 2016-06-01 at 5 43 53 pm](https://cloud.githubusercontent.com/assets/1034109/15728163/74e0ddba-2820-11e6-972f-f7bbec7d59d7.png)

UI changes to this if selecting `Members with an access level`:
![screen shot 2016-06-01 at 5 44 19 pm](https://cloud.githubusercontent.com/assets/1034109/15728175/8b01ee36-2820-11e6-8e27-878a0a05c5f1.png)

**Comment by SDavisMedia** [comment]
Super clean and _much_ better than before. 

I don't use RCP often so looking at this was a refresher. In the new design, the default "Members of specific subscription level" section wasn't intuitive for me. I didn't realize that the three radio buttons were displayed conditionally based on the dropdown above them.

Likewise, I didn't realize that the help icon, which I had already read, was related specifically to the select menu below it. I thought it was related to the entire metabox, as the description beside it looks like a description for the entire metabox and not a heading/label for a specific setting.

Here's what I feel would have been a little more intuitive for me personally:

![screen shot 2016-06-01 at 4 05 03 pm](https://cloud.githubusercontent.com/assets/2359131/15728646/aa6ca56c-2812-11e6-8191-dec1b6102d89.png)

**Comment by michaelbeil** [comment]
So adding `Member access options` helped you understand the metabox settings better?

**Comment by SDavisMedia** [comment]
Oh and the reason why I didn't realize that the help text was for the section below it, besides what I've already mentioned, is because its two headings do not match the select menu options they refer to. So made me assume even more that it was general information for the metabox. The descriptions of the settings should be titled with the same text as the options themselves, in my opinion.

**Comment by SDavisMedia** [comment]
@michaelbeil Yes. The regular text displaying just inside the metabox, visually beneath the metabox title immediately made me think it was description text for the metabox itself, not for a specific setting.

**Comment by spencerfinnell** [comment]
Really nice! What about moving the checkboxes for subscription levels to the right a bit for some hierarchy?

**Comment by spencerfinnell** [comment]
Heh I think you all commented as I was admiring! @SDavisMedia yep something like that. Too many lines could get overwhelming but I definitely like the indentation.

**Comment by pippinsplugins** [comment]
Thanks so much for the feedback guys! I'm going to work on those tweaks and then get it functional.

**Comment by michaelbeil** [comment]
I wonder if we should still add some more padding to `rcp-subscription-levels` under the `rcp_subscription_level_specific` label. 

**Current**:
![screen shot 2016-06-02 at 11 20 45 am](https://cloud.githubusercontent.com/assets/4752949/15752519/17f65aa0-28b4-11e6-8dd7-5eefc5c0cfc9.png)

**Extra 10px**:
![screen shot 2016-06-02 at 11 20 22 am](https://cloud.githubusercontent.com/assets/4752949/15752525/1db3f5ce-28b4-11e6-903c-6a8d4f80d04f.png)

**Comment by pippinsplugins** [comment]
Ah yes, I think that's a good idea.

**Comment by michaelbeil** [comment]
Note that the extra 10px was applied on almost every label in my screen for demo.

**Comment by pippinsplugins** [comment]
I've added the first pass at the save routine. @michaelbeil @mindctrl can you guys play with it to see if saving works?

Note: I have not adjusting content restriction yet to work with new UI, so ignore that

**Comment by mindctrl** [comment]
We made some adjustments to the UI. Now we have a default option in the select called "Everyone". We're hiding everything else unless a restriction setting is selected, then we show the appropriate controls.

#### Unrestricted / default
![image](https://cloud.githubusercontent.com/assets/1254870/15758197/6b33626c-28d7-11e6-9ee8-49c718960365.png)

---

#### Any subscription selected
![image](https://cloud.githubusercontent.com/assets/1254870/15758216/8daaf10c-28d7-11e6-9cd8-fb9ae378f0cc.png)

---

#### Specific level option selected
![image](https://cloud.githubusercontent.com/assets/1254870/15758232/9fdb1e2e-28d7-11e6-889f-33d5a6bbacf5.png)

**Comment by michaelbeil** [comment]
Ooh ...

![screen capture on 2016-06-02 at 14-39-03](https://cloud.githubusercontent.com/assets/4752949/15758364/eef4b52c-28cf-11e6-9b0b-4f45c3faae9b.gif)

**Comment by michaelbeil** [comment]
Save is working with no errors.

**Comment by spencerfinnell** [comment]
I think the subscription level checkboxes could be moved in even further to align with the start of the radio label. 

Like: http://cdn3.wpbeginner.com/wp-content/uploads/2013/04/frontpage.png

**Comment by SDavisMedia** [comment]
Sorry for being nitpicky and feel free to ignore it. But the indentation of the subscription levels should place the left edge of the checkboxes inline with the left edge of the label for the parent radio button.

Moving it over will also prevent a visual clash between the parent radio button and the first checkbox, allowing you to reduce the top margin of the subscription level list from 1em to .5em. 

![screen shot 2016-06-02 at 3 42 15 pm](https://cloud.githubusercontent.com/assets/2359131/15763407/9d24d2dc-28d8-11e6-821a-ae3d1653259e.png)

```CSS
.rcp-subscription-levels {
    padding-left: 28px;
    margin-top: .5em;
}
```

**Comment by SDavisMedia** [comment]
Dangit @spencerfinnell lmao sorry... looks like a reverse of what happened yesterday. At least we see the same thing!

**Comment by michaelbeil** [comment]
I agree wholeheartedly. That is what I was going for. Was gonna look further into it soon, but now you already did!

😄

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Done.

**Comment by SDavisMedia** [comment]
@pippinsplugins Looking perfect. :+1:

**Comment by JamesGeiger** [comment]
Looks great guys!!

**Comment by mindctrl** [comment]
We added [TipTip](https://github.com/drewwilson/TipTip) for the help icon tooltip. WordPress core ships with [jQuery Tooltip](https://jqueryui.com/tooltip/). Should we consider using that instead, to avoid adding and possibly maintaining an additional library?

**Comment by mindctrl** [comment]
Quick mockup of the core one

![image](https://cloud.githubusercontent.com/assets/1254870/15800719/13118bf8-2a4f-11e6-91bc-2b214077553f.png)

**Comment by pippinsplugins** [comment]
Yes, let's use core's. I didn't realize core had one.

**Comment by michaelbeil** [comment]
That seems like a much better option.

**Comment by pippinsplugins** [comment]
I'm going to rip out the tool tip stuff from this issue so that we can do it entirely on #518

**Comment by michaelbeil** [comment]
Sounds like a plan.

**Comment by pippinsplugins** [comment]
Oh, John already did :D

**Comment by pippinsplugins** [comment]
@mindctrl @michaelbeil this is ready for testing! I've adjusted the `can_access()` method to account for the new UI.

**Comment by mindctrl** [comment]
@pippinsplugins this seems to be working great.

**Comment by pippinsplugins** [comment]
@mindctrl did you happen to test with content that was configured with the previous UI?

**Comment by mindctrl** [comment]
@pippinsplugins yep, both existing content and new content. Restricted via access level, user level, and subscription level. Tested taxonomy restrictions too.

Just found an issue with the UI not showing properly for content restricted only via user level. The page loads and shows "Everyone" but the restrictions are set to specific user level. Likely just a little javascript. Will look at it in a bit.

**Comment by pippinsplugins** [comment]
Fantastic.

**Comment by mindctrl** [comment]
Sorry, the UI was right, I was a bit confused, but I think we may need to adjust this. Check out this UI pattern.

![image](https://cloud.githubusercontent.com/assets/1254870/16045664/70f6f27e-3217-11e6-8b9d-aa1231974154.png)

The UI says "Everyone" has access, but that's not technically true because the Editor role restriction is in place below. Going to explore this a bit. Have any thoughts?

**Comment by pippinsplugins** [comment]
Well that's confusing. Thinking,

**Comment by pippinsplugins** [comment]
I haven't come up with a good alternative to what we have. I'm okay with leaving it as is. Any objections?

**Comment by michaelbeil** [comment]
I would say leave it for now. If Subscriber is selected then everyone has to be registered. 

Hmm ... yea, this is a bit of a dilemma.

**Comment by spencerfinnell** [comment]
What about having an "Everyone" option (like there is now) that hides the capability select box, and then a "Registered User" option that shows it and allows the cap modification?

It would be moved below the main selection box and indented in.

**Comment by spencerfinnell** [comment]
And if I could have my way I would also say remove the shortcode text in favor of the documentation link only (or nothing at all).

Crazy how much better this looks though! 👍

**Comment by pippinsplugins** [comment]
We could add `Registered User` to the drop down but we'd also need to account for admins that want to restrict content to certain subscription levels or access levels _and_ specific roles.

To do that, I think the role selection needs to be separate.

**Comment by spencerfinnell** [comment]
The role selector would still show when "based on subscription level" or "based on access" level is selected. 

That being said I can't get that pattern to show pulling that branch?

**Comment by pippinsplugins** [comment]
Well that's not quite right either because some admins may want to restrict only by user role and not by sub or access level.

Right now the role drop down is always shown and not controlled at all by the drop down.

**Comment by spencerfinnell** [comment]
Not for me. Cleared cache and script debug on. 

My thoughts:

Everyone: https://cldup.com/JOJbKflnQo.png
Role: https://cloudup.com/cGnDeV8RXDB

The other two would remain the same.

**Comment by pippinsplugins** [comment]
I like that proposal except that is prohibits the ability to set a subscription level _and_ and a user role, which I know for sure some people do.

**Comment by mindctrl** [comment]
We may need to make the top level select control a unrestricted/restricted one, then show the select control for the restriction types along with the additional options stuff. I can tinker with that later tonight if everyone agrees with that idea.

**Comment by spencerfinnell** [comment]
Everyone: https://cloudup.com/c1C9V6YZyY7
Registered: https://cloudup.com/cOzCQBUDNB6 -- I think wording could be better, and the "All" selector does not really make sense if that is selected, as all would allow Guests to see it?
Subs: https://cloudup.com/c0twTbg3Kvc
Access: https://cloudup.com/ckew5Uqazh4

**Comment by pippinsplugins** [comment]
ah! Yes, I like that!

**Comment by spencerfinnell** [comment]
I did the basic toggling in stuff in that same branch. Want me to push it up? Still missing setting the current selections and stuff though.

**Comment by pippinsplugins** [comment]
Yes please!

**Comment by spencerfinnell** [comment]
https://github.com/restrictcontentpro/restrict-content-pro/pull/547/commits/734a854b9f453bf2bd8057c22fe32b37bf1a7c72

**Comment by pippinsplugins** [comment]
Works great @spencerfinnell!

**Comment by mindctrl** [comment]
I want to put some JS triggers in here before we finalize it, so we can do things with add-ons based on these selections. Will push those up to this sometime later today.

**Comment by pippinsplugins** [comment]
I'm working through the save routine a bit. @mindctrl I'll post when done then you can take over.

**Comment by pippinsplugins** [comment]
Okay @mindctrl, all yours!

**Comment by pippinsplugins** [comment]
Everything merged into `release/2.6`.

**Comment by pippinsplugins** [comment]
Found a bug.

`Restrict this Content` on `master`:
![screen shot 2016-06-20 at 1 37 14 pm](https://cloud.githubusercontent.com/assets/1034109/16206023/290f4e64-36ec-11e6-8e50-475e6f8a1c0d.png)
Same post on `release/2.6`:
![screen shot 2016-06-20 at 1 38 01 pm](https://cloud.githubusercontent.com/assets/1034109/16206038/3aa69434-36ec-11e6-990a-82b250dff173.png)

**Comment by pippinsplugins** [comment]
We need to properly handle the redirection for the `Hide Premium Content` option before we close this.

**Comment by pippinsplugins** [comment]
Ok I've just pushed up some significant changes that removes some of the reliance on the old `is_paid` flag.

@michaelbeil @mindctrl can you both give this a test please?

Items that still need addressed:

- How do we handle the `rcp_get_paid_posts()` function? It is used in `rcp_hide_premium_posts()` to remove posts that are "premium". We don't really have "premium" and non "premium" anymore like we used to, so querying on that meta key won't work.

- We need to update the redirect from singular views to check if member has access and then redirect. Right now it only checks if the member is active and if the content is paid only.

**Comment by michaelbeil** [comment]
This is looking good.  

Still thinking on the `rcp_get_paid_posts()` function.

Should we check if a member has access on single views by adding `rcp_user_has_access` to `rcp_redirect_from_premium_post`?

**Comment by mindctrl** [comment]
For `rcp_get_paid_posts()` and `rcp_hide_premium_posts()`:

Last night in Slack we considered the option of saving the `_is_paid` meta behind the scenes, if any subscription level assigned to a post's restriction settings has a price more than $0, to keep things simple for now.

**Comment by pippinsplugins** [comment]
I vote we do the following:

1. Maintain the `_is_paid` meta key and store it anytime the post's configuration uses a paid subscription
2. Keep `rcp_get_paid_posts()` as is but mark as deprecated. In the future we should work out a way to introduce `rcp_get_members_content()` or similar
3. Keep `rcp_hide_premium_posts()` as is but work out a way in the future to make it more robust so as to not rely on `_is_paid`

**Comment by pippinsplugins** [comment]
@michaelbeil could you do another round of testing on this now? `_is_paid` is now kept when saving posts.

**Comment by michaelbeil** [comment]
Things are looking good, except that when selecting "Everyone" and saving the page, the metabox options are changed.

Before updating the page:
 
![screen shot 2016-06-29 at 5 50 05 pm](https://cloud.githubusercontent.com/assets/4752949/16471387/f6204e62-3e21-11e6-90fd-fdd442ba492c.png)

After updating the page:
![screen shot 2016-06-29 at 5 48 22 pm](https://cloud.githubusercontent.com/assets/4752949/16471361/d0e59ae4-3e21-11e6-9a53-981f1a5114f2.png)

**Comment by michaelbeil** [comment]
Paid subscriptions are hiding content appropriately.

**Comment by mindctrl** [comment]
@michaelbeil can you pull down `release/2.6` again and give that dropdown thing another test?

**Comment by pippinsplugins** [comment]
@mindctrl close. We need to delete role setting when changing back to `Everyone`.

Set to and save: 
![screen shot 2016-06-30 at 4 49 28 pm](https://cloud.githubusercontent.com/assets/1034109/16505450/aa0e01ba-3ee2-11e6-80de-349739b6d62b.png)
Now set back to Everyone and it won't save properly. Only saves if the role is changed back to All.

**Comment by mindctrl** [comment]
Good catch. Pushed another update.

**Comment by michaelbeil** [comment]
Looks good.

**Comment by michaelbeil** [comment]
@pippinsplugins should we change this string to `paid` instead of `non-free`?

`Members of any non-free subscription level(s)` 
`Members of any paid subscription level(s)`

Paid sounds better to me.

**Comment by pippinsplugins** [comment]
I'm fine with either.

**Comment by michaelbeil** [comment]
Ok. Changed it to paid.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@mindctrl @michaelbeil can we get one final round of testing on this today / tomorrow so we can close it out for good?

**Comment by pippinsplugins** [comment]
Everything is working great for me. I'm going to close. Let's re-open if anything pops up.
