### ISSUE TITLE
Combine email and user columns

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#527]
No need to have them as separate columns in the Members page.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by mindctrl** [comment]
Pushed some responsive improvements here. Works great on my iPhone. @michaelbeil could you do a quick test of the new Restrict > Members to have one more set of eyes on it?

**Comment by pippinsplugins** [comment]
Ready for testing in https://github.com/restrictcontentpro/restrict-content-pro/pull/528
