### ISSUE TITLE
Remove case sensitivity from discount codes

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#529]
Right now discount codes are case sensitive and can lead to some confusion and a less than ideal end customer experience. Unless there are objections, let's make them work regardless of case.

**Comment by mindctrl** [comment]
Looking at the code for this there's a note:
`// Ensure codes are identical, including case`

Is this something we want to consider doing or just leave it as it is? I'm fine with leaving it. I don't recall why I opened this issue originally.

**Comment by pippinsplugins** [comment]
I agree with making them case insensitive.

**Comment by mindctrl** [comment]
Punting this to 2.7. Note to future selves, test against Stripe.

**Comment by pippinsplugins** [comment]
PR submitted. Includes upgrade routine to changes all existing discount codes to lower case.

**Comment by mindctrl** [comment]
Works great. Merged.
