### ISSUE TITLE
Add payment / subscription level meta table

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#533]
As more and more extensions are created for RCP, it's become clear that we need to offer a way to store metadata about payment records. For this, I propose we add a payment meta table. This could be done just like the Affiliate Meta and Customer Meta tables recently added to AffiliateWP and Easy Digital Downloads.

Related #507

**Comment by pippinsplugins** [comment]
Ready for testing!

Example testing:
```php
global $rcp_payments_db;
$rcp_payments_db->add_meta( 1, 'test_key', 'Test Value' );
var_dump( $rcp_payments_db->get_meta( 1, 'test_key' ) );
```
Result should be `Test Value`.

**Comment by mindctrl** [comment]
The payment and level meta get/add/update/delete methods work fine here.

**Comment by pippinsplugins** [comment]
Time to merge!

**Comment by pippinsplugins** [comment]
Not closing until we have unit tests added.

**Comment by pippinsplugins** [comment]
Tests passing!

**Comment by mindctrl** [comment]
We discussed renaming the table from rcp_subscription_meta to something like `rcp_subscription_level_meta` for more clarity.

**Comment by pippinsplugins** [comment]
@mindctrl please go ahead and change it.

**Comment by pippinsplugins** [comment]
Table name updated.

Note: you will need to deactivate and reactivate RCP in order to create the new table if the beta has already been installed on the site you're testing.
