### ISSUE TITLE
The subscription.php template can show pending registration dates instead of real expiration dates

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#536]
In subscription.php, we do `echo rcp_get_expiration_date()` to show the member's expiration date. [Link](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.5.4/templates/subscription.php#L29). It's a wrapper for `get_expiration_date()` in the `RCP_Member` class. [Link](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.5.4/includes/class-rcp-member.php#L79).

As you can see there, the pending expiration date that gets set during subscription upgrades gets called first. This results in confusion when a customer has a membership, initiates an upgrade, goes to PayPal, but doesn't complete payment. It appears that the expiration date has been adjusted without a payment being completed.

**Comment by mindctrl** [comment]
Note: we've had to work around `get_expiration_date()` behavior in the past here: https://github.com/restrictcontentpro/restrict-content-pro/issues/339

**Comment by pippinsplugins** [comment]
To take care of this, I have decided to add a `$pending` flag to `get_expiration_date()` with a default value of `true`. Only if `$pending` is `true`, do we retrieve the pending date (if there is one). `rcp_get_expiration_date()` passes `false` to `$pending` so that it always retrieves the current date. This function is never used internally for calculations so this is safe.

**Comment by mindctrl** [comment]
This isn't working for me. I still see the pending expiration date if I bail on paying and come back to the site.

**Comment by pippinsplugins** [comment]
@mindctrl Can you tell me where it shows the pending date and where it shows the old date?

**Comment by mindctrl** [comment]
@pippinsplugins the pending date is showing in the [subscription_details] shortcode output, from the call in subscription.php.

The old date correctly shows in the admin.

**Comment by pippinsplugins** [comment]
Thanks.

**Comment by pippinsplugins** [comment]
@mindctrl fixed e902942

**Comment by mindctrl** [comment]
@pippinsplugins looks good now.
