### ISSUE TITLE
Update all calls to wp_remote_* for new response types

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#538]
For WordPRess 4.6, the `wp_remote_post()` and `wp_remote_get()` functions are being updated to return an object instead of an array. The returned object implements array access so the following should still work, but to be safe we need to update all of our code to use the helper functions for retrieving the body, response code, headers, etc.

```php
$request = wp_remote_post( $this->api_endpoint, array( 'timeout' => 45, 'sslverify' => false, 'httpversion' => '1.1', 'body' => $args ) );

if( 200 == $request['response']['code'] ) {  }
```

That should become:

```php
$request = wp_remote_post( $this->api_endpoint, array( 'timeout' => 45, 'sslverify' => false, 'httpversion' => '1.1', 'body' => $args ) );

if( 200 == wp_remote_retrieve_response_code( $request ) ) {  }
```

The return types are changing as part of a bigger project to introduce support for parallel requests (which is really cool): https://core.trac.wordpress.org/ticket/33055

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by mindctrl** [comment]
@pippinsplugins @michaelbeil this looks good to me in Stripe, but I'm having some issues with PayPal that I don't think are related to this. Can someone else verify PayPal works for them and payments show up in RCP?

**Comment by pippinsplugins** [comment]
@mindctrl what's the error message?

**Comment by mindctrl** [comment]
@pippinsplugins no error messages. No debug notices. BTW I was testing Express.

**Comment by pippinsplugins** [comment]
@mindctrl k, I'll test again as soon as I'm on the desktop (laptop cannot connect because of MAMP's SSL).

**Comment by pippinsplugins** [comment]
Payment for PayPal Express one-time worked properly. Will test subscription now.

**Comment by pippinsplugins** [comment]
All good.
