### ISSUE TITLE
Constantly recurring PHP Notices for "Trying to get property of non-object"

### ISSUE THREAD

**Issue by cliffordp** [restrictcontentpro/restrict-content-pro#540]
1)

> PHP Notice: Trying to get property of non-object in /wp-content/plugins/restrict-content-pro/includes/content-filters.php on line 12
> (same for lines 26 and 48)

2)

> PHP Notice: Trying to get property of non-object in /wp-content/plugins/restrict-content-pro/includes/member-functions.php on line 338

**Comment by mindctrl** [comment]
@cliffordp how are you triggering these notices? Can you tell me how to reproduce it?

**Comment by cliffordp** [comment]
I'm not certain. They've been in my debug.log for a long time (months).

I'm on RCP Version 2.5.4 and have the latest version of WP, my theme, and all my plugins.

1)
Looking into the code, I see those 3 lines use these functions:
`rcp_is_paid_content( $post->ID )`
`! rcp_user_can_access( $user_ID, $post->ID )`
`rcp_is_post_taxonomy_restricted( $post->ID, $taxonomy )`

Those seem like pretty basic functions.

2)
```
if( empty( $post_id ) ) {
	global $post;
	$post_id = $post->ID;
}
```

again, pretty straightforward...

===

As such, I wonder if there's an issue when front-end viewing when there isn't a post ID set.

However, when I went to test such an example URL, I am now not seeing either of these 2 errors. Maybe was a plugin conflict (because some plugins recently had new updates and didn't deactivate/reactivate RCP)...

Anyway, thanks for looking into it. I'll update this if I see the issue happening again.

**Comment by pippinsplugins** [comment]
How are you setting up `$user_ID`?

**Comment by cliffordp** [comment]
I didn't customize anything (i.e. setting up `$user_ID`)... I was just copying those functions from the line numbers referenced in the notices.

I really haven't used RCP much but I know it's setup; I'm just not using it regularly (all the more reason I don't have any customizations).

**Comment by pippinsplugins** [comment]
`$user_ID` is not set automatically. Replace that with `get_current_user_id()`. That should fix it.
