### ISSUE TITLE
Stripe: set currency on customer when first creating them

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#549]
When a Stripe purchase alters the initial amount with signup fees, and the store currency is different than that of the stripe account, subscriptions will fail to correctly be made as the balance alteration sets the newly created customer's currency as the Stripe account default, but the subscription is in the store currency, which is now different.

After discussing with Stripe, the method used is to (if a customer does not have a currency) created a 0 amount invoice item with the store currency, then generate an invoice which will then set the customer currency to that of the store currency. Then after altering their balance, and saving, we set that invoice as closed.

Not setting the currency is what occasionally results in a "cannot combine currencies on customer" error during registration.

We did this for EDD Recurring too: https://github.com/easydigitaldownloads/edd-recurring/issues/444

**Comment by pippinsplugins** [comment]
Ready for testing.

To test:

1. Set site currency to a non-USD currency
2. Log out
3. Purchase a subscription that includes a signup fee or discount with a brand new customer (must not exist in Stripe yet)
4. Confirm all amounts are correct

**Comment by mindctrl** [comment]
I'm getting an error when the RCP currency doesn't match the Stripe account.

```
Status: 400

Message: Can't combine currencies on a single customer. This customer has had a subscription, coupon, or invoice item with currency eur
```

This was a new customer that did not exist in Stripe.

**Comment by pippinsplugins** [comment]
Hmm, that's exactly the error that is supposed to be prevented by this. Will look again.

**Comment by pippinsplugins** [comment]
@mindctrl I don't think that's a bug. I just replicated it and it happened because the plan I tried to register for had been created in Stripe prior to me changing the currency to `EUR`.

Once I created a new plan, everything worked as expected.

Can you confirm?

**Comment by mindctrl** [comment]
@pippinsplugins yep, it works fine when I create the plan after switching to EUR, which sounds right to me. I think we're good here.
