### ISSUE TITLE
Make admin notices dismissable

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#553]
Currently the `Please enter and activate your license key for Restrict Content Pro to enable automatic updates.` is not dismissable, nor is the expired notice. 

![screen shot 2016-06-17 at 2 57 13 pm](https://cloud.githubusercontent.com/assets/4752949/16162903/eee346b6-349b-11e6-909f-91a00ec41eaf.png)

We should make these notices dismissable as we did in AffiliateWP: https://github.com/AffiliateWP/AffiliateWP/pull/1167

**Comment by pippinsplugins** [comment]
Yep!

**Comment by pippinsplugins** [comment]
Ready for testing!

**Comment by mindctrl** [comment]
Pushed a small update. Ready to merge when tests finish.
