### ISSUE TITLE
Show "cancel subscription" checkbox when manually changing status from active to cancelled

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#557]
We have had several customers unknowingly fail to cancel a customer's subscription because they went to the edit screen and changed the status from Active to Cancelled.

Right now, payment profiles are only cancelled if the "Cancel" link is clicked on the Members page. We should update the edit screen to show a "Cancel subscription" checkbox when the status is changed to Cancelled and the subscription can be cancelled.

**Comment by nosegraze** [comment]
PR: #983
