### ISSUE TITLE
Subscription renewal reminder email

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#558]
We've had several requests for an option that emails customers prior to their renewals coming up. We have one for expiring soon, but that only works for non-recurring members.

This would be a reminder that says something like "hey, we're billing your subscription renewal on X day" kind of thing. This is particularly useful for subscriptions with longer periods like a year, where people forget, get annoyed, and request refunds.

**Comment by pippinsplugins** [comment]
We built this into Recurring Payments for EDD so could easily take some logic from that.

**Comment by mindctrl** [comment]
Another request for this today.

**Comment by nosegraze** [comment]
Got a request for this.

**Comment by pippinsplugins** [comment]
Another request: https://secure.helpscout.net/conversation/343267794/56596/?folderId=841776

**Comment by nosegraze** [comment]
Got a request for this, but specifically with regards to a trial ending and payment about to be taken for the first time. But I think that could fall under this as well.

**Comment by pippinsplugins** [comment]
Looking good! I've done a first round of testing and everything appears to work well. I have not tested cron functions yet.

There are a few things I'd like adjusted.

The `reminders_enabled()` is a bit odd. It is returning an array of enabled reminders but the description of the method and the name of the method indicate that it should be returning a boolean for whether there are reminders enabled. Let's update that to `get_enabled_reminders()`.

Let's also change `scheduled_reminders()` to `send_reminders()`. The scheduling happens via the `cron-functions.php` file; this method does the actual sending so `send_reminders()` is more appropriate.

In `scheduled_reminders()` there is this logic:
```php
if ( $type == 'expiration' && $member->is_recurring() ) {
	continue;
}
```

That should also check for `$member->is_active()`. If the member is marked as recurring but is no longer active, sending an expiration notice should occur (I think).

When setting up the time periods in the `get_users()` query, we need to pass `current_time( 'timestamp' )` as the context to the `date()` functions to ensure the proper timezone settings are used.
```php
date( 'Y-m-d H:i:s', strtotime( $period . ' midnight' ) ),
date( 'Y-m-d H:i:s', strtotime( $period . ' midnight' ) + ( DAY_IN_SECONDS - 1 ) )
```

That's all I see for now!

**Comment by nosegraze** [comment]
Updated. :)

Also just as a reminder for later, we should add an upgrade routine to automatically set up the old expiration notice as a new reminder.

**Comment by pippinsplugins** [comment]
Updates look good.

Could we please get this set up on a live server and let it run for a few days/weeks to confirm notices are sending properly?

**Comment by mindctrl** [comment]
As with all new things of this size and nature, I think this class should be `final` and filters should be kept to a minimum until this thing is in the real world for some time, at least 2 release cycles.

**Comment by nosegraze** [comment]
Made a few adjustments and I've added this to a live server. I've set up a few different notices that should hit a few different accounts and I'll keep an eye on it.

**Comment by pippinsplugins** [comment]
>>>As with all new things of this size and nature, I think this class should be final and filters should be kept to a minimum until this thing is in the real world for some time, at least 2 release cycles.

I agree 100%.

**Comment by nosegraze** [comment]
I've made two key adjustments:

1. Remove reminder flags when a new payment is made: https://github.com/restrictcontentpro/restrict-content-pro/pull/1157/commits/c303c30bb1f1a6070e6a6943d9075375992a1d15
2. Account for cancelled users: https://github.com/restrictcontentpro/restrict-content-pro/pull/1157/commits/ccf337631797a272578e1d16845e766b81fb2226

Tests have gone well with those changes.

**Comment by mindctrl** [comment]
Left some comments on the PR.

Some other issues.

`get_notice()` returns a default notice when an invalid notice ID is supplied.
`get_notices()` returns two default notices if none are stored in the db.
Both of those makes it harder to use as an API, as it doesn't reflect what's in the database. Managing notices programmatically would be affected by this.

Also deleting all notices doesn't work exactly as you'd expect because it recreates (visually) the default, which then ends up getting stored in the database again after doing some other actions.

There's a mismatch between what's in the database and and what the UI shows and what the API functions return. I think they should reflect what's in the database, and I think it should be possible to delete all notices if you want.

It would be very useful for individual reminders to have a status - enabled/disabled. It would be helpful for things like A/B testing notices, and drafting new notices to get feedback from team members before going live.

**Comment by mindctrl** [comment]
@nosegraze didn't make above comments on PR anywhere, but I think at a minimum we need to address the behavior of `get_notice` and `get_notices`. Individual status can come later, though it seems easy to add.

**Comment by nosegraze** [comment]
I was so sure I replied to this. Now I'm wondering if I randomly replied on the wrong issue or something lol.

My comment was something like: how do you want to handle the default message? Perhaps just add something in the plugin installation?

I do also like the idea of individual statuses.

**Comment by pippinsplugins** [comment]
>>>There's a mismatch between what's in the database and and what the UI shows and what the API functions return. I think they should reflect what's in the database, and I think it should be possible to delete all notices if you want.

I agree, I think, though I'm not really sure if there's a real purpose of doing that. If someone wants to disable all notices, they just uncheck the box. From a functionality perspective, I don't think it's necessary. From a consistency standpoint, definitely

**Comment by nosegraze** [comment]
Added the ability to enable/disable individual reminders https://github.com/restrictcontentpro/restrict-content-pro/commit/0148d90115849265346aa0bf79827622af55351b

**Comment by pippinsplugins** [comment]
Enabling / disabling works well for me!

**Comment by mindctrl** [comment]
Subjects are slashed in the display and in the email.

![image](https://cloud.githubusercontent.com/assets/1254870/26405809/6ed555e2-4064-11e7-816b-0de4a721f26e.png)

![image](https://cloud.githubusercontent.com/assets/1254870/26405814/752320f0-4064-11e7-98c0-d30fb5085e59.png)

**Comment by mindctrl** [comment]
I left two other comments on the PR. After those and the slash issue, I think this will be good to go.
