### ISSUE TITLE
Discount use count gets incremented before payment is completed

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#560]
When processing a registration, we increase the discount code uses before handing the registration off to the payment gateway. This results in counts getting improperly increased if a payment fails or the person fails to complete registration.

**Comment by nosegraze** [comment]
Until we have pending payments, we could do the same thing we did in #999 : hook into `rcp_registration_failed` (though that's only in `release/2.8` right now) and if there was a discount added, decrease the number of uses.

**Comment by pippinsplugins** [comment]
That seems like a good approach. Let's move this to 2.8.

**Comment by nosegraze** [comment]
PR: #1040

**Comment by mindctrl** [comment]
Works great, will merge when unit tests pass.
