### ISSUE TITLE
Auto-fill Stripe Checkout Email with entered email

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#563]
When a user is creating an account and subscribing in one step the entered email should be pre-filled in Stripe Checkout to reduce steps and prevent confusion.

**Comment by pippinsplugins** [comment]
@carter2422 it is pre-filled already.

**Comment by wpmarmite** [comment]
Hey guys,
Actually, it was working for me at first but in some case it didn't work.

**Comment by pippinsplugins** [comment]
Hmm, okay we'll dig into it.

**Comment by carter2422** [comment]
@pippinsplugins for me it's only filled if I'm logged in.

**Comment by pippinsplugins** [comment]
Is this on the main registration form or a Stripe Checkout only form?

**Comment by carter2422** [comment]
Stripe Checkout only.

**Comment by wpmarmite** [comment]
Hey guys,
I managed to load the email from the email field (which is a text input BTW) with this code : 

`jQuery('#rcp_registration_form #rcp_user_email' ).focusout(function() {`
`	 checkoutArgs.email = jQuery('#rcp_registration_form #rcp_user_email' ).val();`
`});`

I guess that the checking occurs only at the loading of the form so the field is always empty...

I'm not a JS expert so I won't do a PR on this issue. Maybe there is a better way to make it work.
What do you think ?

**Comment by mindctrl** [comment]
@wpmarmite that looks about right. Thanks! We'll do some testing.

**Comment by pippinsplugins** [comment]
Taking care of this on https://github.com/restrictcontentpro/restrict-content-pro/pull/604

**Comment by mindctrl** [comment]
Looks good here.
