### ISSUE TITLE
Registration form throws error message when only free subscriptions are activated

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#565]
The following error message shows on the registration form page:

`An error occurred, please refresh the page and try again.`

under the following conditions:

- only subscription levels that are free are activated
- the currently logged in user already has a free subscription

It comes from `rcp_calc_total_ajax()`.

**Comment by mindctrl** [comment]
Just took a closer look at this. It happens because we return false here: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.3/includes/subscription-functions.php#L319-L320

There are no subscription levels to process, and that causes the error.

A couple thoughts. We could allow free forever to show. I can see use cases for that. But if someone only has one free level, the error would still return unless we put in some other check. It's also an edge case that someone would revisit the registration form on a site with only one free level. There's just no need. Thoughts @pippinsplugins?

**Comment by mindctrl** [comment]
I like that!

**Comment by mindctrl** [comment]
This gets rid of the error message, but if someone is on a free trial and tries upgrading to an unlimited free subscription, their subscription doesn't get changed.

**Comment by pippinsplugins** [comment]
@mindctrl why does it not get changed?

**Comment by mindctrl** [comment]
It looks like we don't update the `rcp_subscription_level` meta key in `rcp_process_registration()`. The `rcp_pending_subscription_level` gets created with the new sub value but doesn't update the existing sub level because the user doesn't have an active status. https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.3/includes/registration-functions.php#L146-L166

**Comment by mindctrl** [comment]
When fixing the issue I commented on above, I noticed that the error message `An error occurred, please refresh the page and try again.` shows again because there's no free trial or free forever option to upgrade/change to, so this is only a partial fix.

**Comment by mindctrl** [comment]
@pippinsplugins with the fix in `rcp_show_subscription_level()`, it's still possible to see the error message from the original post.

To reproduce:

- Set up a single free forever subscription level
- Register
- Then visit the registration form again

Another way:
- Set up a free trial and a free forever
- Sub to free trial
- Move to free unlimited
- Visit reg form again

**Comment by mindctrl** [comment]
We could just adjust the error message in `rcp_calc_total_ajax()` to something like you mentioned here: https://github.com/restrictcontentpro/restrict-content-pro/issues/565#issuecomment-232785669 though that feels like cheating. 😛

**Comment by pippinsplugins** [comment]
Let's go ahead and adjust the message.

Frankly that's a super weird scenario (free trial to free unlimited) so I'm not too concerned about it still being possible to trigger.

**Comment by mindctrl** [comment]
Agreed and adjusted.

**Comment by pippinsplugins** [comment]
Let's merge once tests pass.

**Comment by mindctrl** [comment]
Merged

**Comment by mindctrl** [comment]
This introduced a bug where a person can't renew their paid expired subscription because it doesn't show on the registration form. https://github.com/restrictcontentpro/restrict-content-pro/commit/542dcd69d49533cdb06ec2a483570e57337e7dd9

**Comment by mindctrl** [comment]
Going to open a new issue.
