### ISSUE TITLE
Stripe - No such plan: false

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#572]
We've seen numerous reports of `No such plan: false` occurring during signup.

Not yet sure why it happens inconsistently.

https://secure.helpscout.net/conversation/221861615/37232/?folderId=841776
https://secure.helpscout.net/conversation/215291183/36256/?folderId=841782

**Comment by pippinsplugins** [comment]
Looks like this happens when invalid arguments are passed to Stripe.
![screen shot 2016-07-01 at 8 39 52 am](https://cloud.githubusercontent.com/assets/1034109/16523151/7994b062-3f67-11e6-854b-98cde1c5fa56.png)

Let's get some better error handling in here.

**Comment by pippinsplugins** [comment]
I added better error handling that will display the actual API error returned by Stripe. While this does not prevent the error from happening, it does make it much easier to identify the mis-configuration that caused the error.

**Comment by mindctrl** [comment]
Works here. When tested with a duration > 12 months, the following error is shown:

![image](https://cloud.githubusercontent.com/assets/1254870/16523723/d9be42ea-3f72-11e6-8384-b9c366bff85a.png)

Also tested with a new 12 month plan and works as it should.
