### ISSUE TITLE
PHP7 compatibility errors thrown by WPEngine's PHP compatibility plugin

### ISSUE THREAD

**Issue by colinhowells** [restrictcontentpro/restrict-content-pro#580]
The very handy [PHP Compatibility Checker plugin] (https://wordpress.org/plugins/php-compatibility-checker/) from WPEngine has some things to say about RCP 2.6 and PHP 7 - just letting you know as an FYI

file: /foo/wp-content/plugins/restrict-content-pro/includes/class-rcp-export.php
line 49 | ERROR | INI directive 'safe_mode' is deprecated from PHP 5.3 and forbidden from PHP 5.4.

file: /foo/wp-content/plugins/restrict-content-pro/includes/admin/tools/system-info.php
line 173 | ERROR | INI directive 'safe_mode' is deprecated from PHP 5.3 and forbidden from PHP 5.4.

file: /foo/wp-content/plugins/restrict-content-pro/includes/libraries/stripe/lib/Object.php
line 8 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'Object' (since version 7.0)

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll get those taken care of as best we can!

**Comment by pippinsplugins** [comment]
These can be ignored. The safe mode one is a false positive. We similar check if safe_mode is enabled.

The Stripe object may be able to be fixed by updating the Stripe API.

**Comment by pippinsplugins** [comment]
Updated Stripe library in master.

**Comment by colinhowells** [comment]
Ah ok thanks for looking into that!
