### ISSUE TITLE
Add post class to the_content when restricted

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#587]
> Love this plugin, but I was wondering if there's any chance that in your next update you could add a function that adds a class to the body when it's restricted so that it's easier to style the page as needed?

Reference: https://wordpress.org/support/topic/add-body-class-1

**Comment by nosegraze** [comment]
Would it be better to add this to `post_class` rather than `body_class` ? I guess I'm thinking of archive pages.

And maybe two classes:

1. If the content is restricted.
2. If the current user can access the restricted content or not.

**Comment by mindctrl** [comment]
I originally said the same thing about `post_class`. I'm sure people could use either, but I think we should stick with `post_class` since that's what we currently check for restrictions.

We'll want to check what this does to query counts.

**Comment by nosegraze** [comment]
Added a WIP. It doesn't work for taxonomies yet, but I figure we'll wait for when we get that check added to `can_access()` in #795 . Also maybe we should add the taxonomy check to `rcp_is_restricted_content()`

**Comment by pippinsplugins** [comment]
PR looks good so far!

**Comment by pippinsplugins** [comment]
Looks great!

No need to check taxonomy restrictions since we're working on including that in `rcp_user_can_access()` automatically.
