### ISSUE TITLE
Delete member count metadata when a subscription level is deleted

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#590]
Right now the member count meta isn't deleted from the db when a subscription level is deleted. We should remove it just to clean things up.

**Comment by pippinsplugins** [comment]
We could do this in core and have it automatically delete all metadata from add-ons too. Just need to delete all rows that match the level ID.

**Comment by mindctrl** [comment]
@pippinsplugins this what you have in mind?

**Comment by pippinsplugins** [comment]
Yes but let's do a slight tweak. Please fire it via the `rcp_remove_level` action so that someone could remove it or adjust the exact behavior if they chose.

**Comment by mindctrl** [comment]
Per Slack discussion, moved the deletion to the inline processing we do in process-data.php.
