### ISSUE TITLE
Add context parameter to strtotime() to ensure timezone is respected

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#591]
The `is_expired()` method of `RCP_Member` uses `strtotime( 'NOW' )` but does not include the context parameter so it does not always respect the site's timezone configuration.

We need to change it to `current_time( 'timestamp' )` or to `strtotime( 'NOW', current_time( 'timestamp' ) )`.

**Comment by mindctrl** [comment]
Looks good here. Merged.
