### ISSUE TITLE
Stripe Checkout doesn't work with the [register_form] shortcode when an ID is specified

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#596]
When using the standard `[register_form]` shortcode with Stripe Checkout, if you specify an ID, such as `[register_form id="2"]`, you receive the following error:

`Missing Stripe token, please try again or contact support if the issue persists.`

**Comment by pippinsplugins** [comment]
I believe this happens because stripe.js does not get loaded.

**Comment by mindctrl** [comment]
I'm seeing the scripts loading. Not sure what's going on yet.

**Comment by mindctrl** [comment]
This works great.

**Comment by mindctrl** [comment]
Works good with latest commit.

**Comment by mindctrl** [comment]
Merged.
