### ISSUE TITLE
Cancel link not visible 

### ISSUE THREAD

**Issue by sanderdewijs** [restrictcontentpro/restrict-content-pro#598]
I updated the Mollie Payments plugin to support recurring payments. The test user now has a recurring subscription, however the link to cancel the subscription is not visible. The subscription matches the three requirements for the link to show up: 

- The payment gateway supports recurring subscriptions
- The member subscription is checked as recurring
- The member has a payment profile ID in his member profile. 

Can there be another reason the cancel link is not showing up? I also do not see it in the member list when logged in as an admin.

**Comment by mindctrl** [comment]
@sanderdewijs you'll need to use the filter here. We're basically whitelisting the gateways we've created. https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.3/includes/member-functions.php#L1223-L1254
