### ISSUE TITLE
Stripe Checkout: auto-renew does not set is_recurring to true

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#601]
When subscribing via the Stripe Checkout the `is_recurring` flag does not get set to `true`, even when `auto renew = always`. 

It works fine in regular Stripe, though.

Tested in 2.6.3.

**Comment by mindctrl** [comment]
@carter2422 is this on the regular [register_form] or on the standalone [register_form_stripe] form? Just tested on regular [register_form] and it's working. If you're using the regular [register_form], are you using the ID option with it?

**Comment by carter2422** [comment]
The regular `[register_form]` @mindctrl. 

And no, not using the ID option.

**Comment by carter2422** [comment]
I just replicated this again in 2.6.4. 

Using the straight `[register_form], with Stripe Checkout as the only enabled gateway, I signed up first with a Free plan, then went back to `/register` and upgraded to a `Monthly` plan. Upon submitting payment and activating successfully I'm set to non-recurring: https://cl.ly/goGP

The Stripe subscription is active, though.

On a hunch I then did another signup, this time creating an account **and** upgrading at the same time, after which recurring was correctly set to `true`: https://cl.ly/gohs

It seems the problem is in upgrading from Free > Paid.

**Comment by mindctrl** [comment]
@carter2422 thanks for the extra details. I'll try to dig into this later today.

**Comment by carter2422** [comment]
Thanks @mindctrl! I'm looking forward to enabling checkout :)

**Comment by carter2422** [comment]
Oh! One more related thing (perhaps needs to be logged as separate issue).

On that second upgrade (shown here: https://cl.ly/gohs ) notice the `Expiration` date was not updated, it's set to the signup date.

**Comment by mindctrl** [comment]
I tested this earlier today and still was unable to replicate. Only time my user didn't get `is_recurring` set is when I had auto-renew set to `Never`. I'll give it another whirl tomorrow on a fresh test site.

**Comment by mindctrl** [comment]
I just tested this again on a new site and still can't replicate. I went from Free unlimited -> Paid, and the recurring flag was set.

![image](https://cloud.githubusercontent.com/assets/1254870/17297240/d49986bc-57d2-11e6-8336-3ff65d883d8a.png)

@pippinsplugins can you reproduce?

**Comment by mindctrl** [comment]
Just did a free trial -> paid and it worked there too.

**Comment by mindctrl** [comment]
I'm testing on master... so perhaps something we've already done fixed it.

**Comment by pippinsplugins** [comment]
Let's punt to 2.6.6 and then hopefully @carter2422 can replicate (or not) again there.

**Comment by carter2422** [comment]
I'll test again when 2.6.5 is out.

**Comment by carter2422** [comment]
Update. My best guess is this was caused by delayed web hooks as I can no longer replicate it and everything is working fine. 

False alarm.
