### ISSUE TITLE
Discounted total calculation bug when discounted amount >= $1000

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#602]
When a discount is applied on the registration form, if the total amount after the discount is greater than or equal to $1000, the total returned is $1 instead of the correct amount. It applies to both flat rate and percentage discounts.

To replicate:
- Create a subscription level priced at $1030 or higher
- Create a flat rate discount code for $30
- Select the subscription level on the registration form and apply the discount

The total today amount will show $1 instead of $1000. I think it's caused by us doing math on a combination of strings and ints.

We've had a few calculation bugs and subsequent adjustments in RCP_Registration, so any adjustments here will need to be thoroughly tested with that history in mind. https://github.com/restrictcontentpro/restrict-content-pro/commits/master/includes/class-rcp-registration.php

**Comment by pippinsplugins** [comment]
This happens because `calc_discounted_price()` in `RCP_Discounts` returns a formatted amount, which then gets included in raw calculations and and formatted again in RCP_Register.

**Comment by mindctrl** [comment]
This looks good. Tested with various amounts and also with signup fees. All calculated properly.

**Comment by pippinsplugins** [comment]
Added two new unit tests for testing high prices. Let's let those pass before merging.

**Comment by mindctrl** [comment]
Merged.
