### ISSUE TITLE
Trim payment gateway API key fields on save

### ISSUE THREAD

**Issue by DrewAPicture** [restrictcontentpro/restrict-content-pro#610]
Was just testing an improvement the RCP integration for AffiliateWP and when I set up RCP with my Stripe test keys, there was an errant space entered into the key field that persisted on save.

In part, this is a byproduct of Stripe's poor design in allowing extra spaces to be selected for copying, but at the same time I think we could probably make this a little more foolproof for the end user.

**Comment by DrewAPicture** [comment]
Added a PR: #612

**Comment by mindctrl** [comment]
Works great. Merged. Thanks @DrewAPicture!
