### ISSUE TITLE
Checkout hangs when when Stripe API key isn't defined for sandbox mode

### ISSUE THREAD

**Issue by DrewAPicture** [restrictcontentpro/restrict-content-pro#611]
As a side-effect of the issue reported in #610, when I attempted to check out with the faulty API key (faulty due to extra spaces), the checkout process just hung there. Checking the console yielded an `Uncaught Error` returned from Stripe:

```
Uncaught Error: You did not set a valid publishable key. Call Stripe.setPublishableKey() with your publishable key. For more info, see https://stripe.com/docs/stripe.js
```
I haven't looked too deeply into it, but I think it has to do with the sandbox mode not being enabled or the webhook not being defined and thus Stripe attempting to use the live keys that don't exist.

**Comment by mindctrl** [comment]
Added an error message when Stripe keys are missing. This along with #610 should fix it all up.
