### ISSUE TITLE
Improve request body arg handling in PayPal Pro gateway

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#614]
When working on a ticket I found some interesting things in the PayPal Pro gateway.

First, if a site title is empty under Settings > General, PayPal returns the following error:
```
Error message: Illegal characters were removed from the SoftDescriptor field
Error code: 10218
```
We create the SoftDescriptor from the site title and the subscription name here: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.4/includes/gateways/class-rcp-payment-gateway-paypal-pro.php#L74

Adding a site title fixes this. Since the error message from PayPal is a bit vague, I propose we check for an empty site title and fill it with the domain name in cases where it's missing.

Second, there are apparently some PayPal accounts that won't work with our implementation at all if they don't have recurring enabled on their account, even when the site is configured to never auto-renew. This results in the following error:
```
PayPal subscription creation failed.
Error message: The soft descriptor passed in was truncated
Error code: 10215
```

The error message PayPal returns here seems to have nothing to do with the real issue. It's related to the `METHOD` arg we send here: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.4/includes/gateways/class-rcp-payment-gateway-paypal-pro.php#L67

To fix this issue for the customer, I changed it to this instead:
`'METHOD'             => $this->auto_renew ? 'CreateRecurringPaymentsProfile' : 'DoDirectPayment',`

Unless you see an issue with this @pippinsplugins, I propose we implement it to avoid further confusion. It took some time to track down due to the error message PayPal returns being seemingly unrelated to the real problem.

Thoughts?

**Comment by pippinsplugins** [comment]
That makes perfect sense. There is no reason for us to create a recurring profile with a single payment when it's not actually a recurring subscription. :+1:
