### ISSUE TITLE
Fatal error: Class 'RCP_Payment_Gateway' not found 

### ISSUE THREAD

**Issue by sanderdewijs** [restrictcontentpro/restrict-content-pro#624]
Just updated to the latest version of RCP and it threw a fatal error on my Mollie Payment gateway. I initialize the gateway on the 'plugins_loaded' action hook, which should be when the main RCP_Payment class is instantiated. Never had this issue until the latest release.

**Comment by sanderdewijs** [comment]
I fixed the issue by adding a higher priority to my action hook:
add_action('plugins_loaded', 'load_rcp_mollie_classes', 99999);

**Comment by michaelbeil** [comment]
Thanks for letting us know.
