### ISSUE TITLE
Incorrect member expiration date  - [subscription_details] page, and in admin

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#625]
The expiration date shown on the [subscription_details] page is incorrect. For me it is showing the date the user joined. I'm using Stripe as my gateway.. not sure why that would make any difference.

The user's expiration date on the admin member page (in the actual date input) is always displayed correctly (mysite.com/wp-admin/admin.php?page=rcp-members&edit_member=1). But the incorrect date is also displayed in the admin member list (mysite.com/wp-admin/admin.php?page=rcp-members).

**Comment by thomasfw** [comment]
**Admin member list**
<img width="1550" alt="screen shot 2016-08-02 at 23 36 15" src="https://cloud.githubusercontent.com/assets/7723105/17347881/83cf47b0-590a-11e6-8e29-885e8df2a053.png">

**[subscription_details] page**
<img width="832" alt="screen shot 2016-08-02 at 23 37 13" src="https://cloud.githubusercontent.com/assets/7723105/17347886/8d201d58-590a-11e6-90c5-fc1692f1b9d8.png">

**Admin edit member page (exp date input is correct)**
<img width="497" alt="screen shot 2016-08-02 at 23 36 26" src="https://cloud.githubusercontent.com/assets/7723105/17347889/930297be-590a-11e6-8b57-154b1ac53c52.png">

**Comment by thomasfw** [comment]
... my webhook endpoint had been deleted in Stripe, hence the expiration not updating. Closing.

**Comment by pippinsplugins** [comment]
@thomasfw Have you configured the Stripe webhooks? Also, what version of RCP are you using?

**Comment by thomasfw** [comment]
@pippinsplugins see more recent comment, thanks.

**Comment by mindctrl** [comment]
@thomasfw I can't replicate this. Please open a support ticket and include the system info report. https://restrictcontentpro.com/support/
