### ISSUE TITLE
PayPal Pro/Express issue with one-time payments

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#626]
When using PayPal Pro with one-time payments, members remain pending due to our processing in the `process_webhooks()` method in the `RCP_Payment_Gateway_PayPal_Express` class (which is where Pro webhooks get processed).

We partially dealt with one-time payments in https://github.com/restrictcontentpro/restrict-content-pro/issues/614, but it was incomplete.

We need to process `web_accept` payment types for this to work properly.

**Comment by mindctrl** [comment]
Customer confirmed this patch fixes her issue.

**Comment by pippinsplugins** [comment]
Great, merging.
