### ISSUE TITLE
Add email verification

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#632]
Verification of email addresses during registration has been requested countless times. We really should add it.

Example request: https://secure.helpscout.net/conversation/236029190/39562/?folderId=841776

**Comment by pippinsplugins** [comment]
Request: https://secure.helpscout.net/conversation/281754854/47454/?folderId=841781

**Comment by nosegraze** [comment]
WIP: #1049

Just kind of beat it out, but it basically works. Let me know if you have any feedback.

To do:

- [ ] Add "Re-send verification email" link in _Restrict > Members_ interface when hovering over a member pending verification.
- [ ] Maybe add some kind of _"pending verification"_ note when editing the member as well.
- [ ] Allow subject/email to be customized in _Restrict > Settings > Emails_?
- [ ] Maybe filter the restricted content message if they're pending verification. We do this for WP Approve User.

**Comment by pippinsplugins** [comment]
@nosegraze just left one comment on the PR.

Thoughts on putting this in a point release or making it one of the focus features for 2.9? I'm thinking point rrelease.

**Comment by nosegraze** [comment]
Yep I'm happy with a point release!

**Comment by mindctrl** [comment]
It would also make a nice key feature in 2.9. :)

**Comment by nosegraze** [comment]
Ready for a final look and testing, I think!

I also changed the way notices are displayed on the edit profile shortcode.

**Comment by pippinsplugins** [comment]
@nosegraze could we move the email verification settings to the top of the page, or perhaps just under the From name / address options?

**Comment by pippinsplugins** [comment]
This works really well. One thing I think we need to add though, along with the adjustment of the settings placement.

The `Your account is pending email verification. Click here to re-send the verification email.` message should be shown at the top of [subscription_details]`. This is frequently placed on the registration success page and it can be jarring to get there and think your account is fully activated only to discover it's not when navigating elsewhere on the site.

**Comment by nosegraze** [comment]
I moved the settings to the top, right above template tags. That work?

I'll work on moving the message to the other shortcode! 👍

**Comment by pippinsplugins** [comment]
I think the message should be on both shortcodes, though it should also detect if both shortcodes are on the same page and only display once.

**Comment by mindctrl** [comment]
This is looking good! Something I think we should clarify in the setting dropdown. `On for free registrations` could be mistaken for a registration that is free due to a 100% discount code. It might be clearer to say `On for free subscription levels` just to remove any doubts.

**Comment by mindctrl** [comment]
We might want a tooltip to explain that it doesn't apply to discounted ones?

**Comment by nosegraze** [comment]
Good idea!

**Comment by mindctrl** [comment]
I left a comment on the PR re: WP Approve User. In either case, I think it would be good to ship this as is and update it later if we agree that needs to happen.
