### ISSUE TITLE
[restrict] shortcode improperly restricts content for Free members

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#637]
When using the shortcode as follows, free members are unable to see content:

`[restrict subscription="18"]You should be able to see this, but you can't.[/restrict]`

**Comment by pippinsplugins** [comment]
PR looks good to me.

**Comment by mindctrl** [comment]
@pippinsplugins good to merge this?

**Comment by pippinsplugins** [comment]
Yes.
