### ISSUE TITLE
Content improperly restricted for Free members when using Access Level restrictions

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#639]
Free members are unable to view content when content is restricted like via access levels in the _Restrict this content_ meta box.

![image](https://cloud.githubusercontent.com/assets/1254870/17570973/78b98e4a-5f1c-11e6-8589-4590615ec3d3.png)

This is because we set the `_is_paid` post meta flag when saving posts if there are any paid subscription levels on the site at all. [Reference 1](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.6/includes/admin/metabox.php#L146-L154) and [Reference 2](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.6/includes/admin/metabox.php#L193)

We discussed getting away from the metadata at some point in the future. A possible workaround until then is to adjust the `can_access()` method in `RCP_Member` to check for expired instead of not is active. Changing [this](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.6/includes/class-rcp-member.php#L736):

from:

`if ( rcp_is_paid_content( $post_id ) && ! $this->is_active() ) {`

to this:

`if ( rcp_is_paid_content( $post_id ) && $this->is_expired() ) {`

**Comment by mindctrl** [comment]
That appears to work in my local testing. This doesn't appear to break anything because the paid level checks happen below that line. Going to push up a change and see what the unit tests think. My local phpunit is broken at the moment.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
@michaelbeil do you have a few minutes you can spare to test this?

**Comment by mindctrl** [comment]
@pippinsplugins I think we're good here, but can you give it a whirl to make sure?

**Comment by pippinsplugins** [comment]
Works properly for me.
