### ISSUE TITLE
Improve Stripe error message when things fail

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#642]
We've seen a few instances where customer creation fails. When that happens, we `wp_die` with this message: `'Stripe customer could not be created, please try again or contact support if the issue persists.'`

It would be great to include the error message from the caught exception to get a better idea of why it failed. There may be other error messages we can improve error messaging.

This would help us with customer support issues and possibly help customers figure it out on their own.

**Comment by mindctrl** [comment]
Some additional info:

If a customer is moving from a free trial to a paid plan and the credit card is declined, the "Stripe customer could not be created" message is shown. This message is thrown in the logic that checks for a payment profile ID, and if one doesn't exist and the card is declined, it throws the wrong message.

If a customer has a payment profile ID already, but then attempts to make another payment that is declined, the error message is spectacular:
```
Fatal error: Uncaught exception 'Stripe\Error\Card' with message 'Your card was declined.' in /wp-content/plugins/edd-stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php:107 from API request 'req_93PdahM5L35Nws'

Stack trace:
#0 /wp-content/plugins/edd-stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php(222): Stripe\ApiRequestor->handleApiError('{? "error": {?...', 402, Array, Array)

#1 /wp-content/plugins/edd-stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php(60): Stripe\ApiRequestor->_interpretResponse('{? "error": {?...', 402, Array)

#2 /wp-content/plugins/edd-stripe/vendor/stripe/stripe-php/lib/ApiResource.php(108): Stripe\ApiRequestor->request('post', '/v1/customers/c...', Array, Array)

#3 /wp-content/plugins/edd-stripe/vendor/stripe/stripe-php/lib/ApiResource.php(99): Stripe\ApiResource::_staticRequest('post', '/v1/customers/c...', Array, Object(Stripe\Util\RequestOptions))

#4 /wp-content/plugins/edd-stripe/vendor/st in /wp-content/plugins/edd-stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php on line 107
```

Note the above references `edd-stripe`, which I also have active on this site.

We should try to catch payment declines and show them on the registration form inline with the existing error processing notices to make for a better flow.

**Comment by pippinsplugins** [comment]
Good find. We can definitely catch that!
