### ISSUE TITLE
User's role does not change on upgrade/downgrade

### ISSUE THREAD

**Issue by tannerm** [restrictcontentpro/restrict-content-pro#645]
When a user switches (upgrades/downgrades) between levels with different roles, the new role is added to the user but the old role is not removed. (https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/registration-functions.php#L178)

This should mimic the behavior seen when an admin manually changes a users behavior: https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/process-data.php#L240.

**Comment by pippinsplugins** [comment]
PR looks good to me though will need further testing.

**Comment by mindctrl** [comment]
Working fine here.
