### ISSUE TITLE
Invalid integer error in Stripe when using discounts

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#649]
It's possible to trigger the following error when using discounts with Stripe:

```
An error occurred
Status: 400
Message: Invalid integer: 1999.2
```

To reproduce:
- Create a subscription level priced at $24.99
- Create a discount code for 20% off
- Apply the discount during registration and attempt to purchase.

**Comment by mindctrl** [comment]
@pippinsplugins this fixes that case, but presents another issue.

First, I ran the test listed above, and it worked fine. Totals:

![image](https://cloud.githubusercontent.com/assets/1254870/18055592/7d858050-6dd6-11e6-91b7-48f7084f4ef4.png)

---

Next, I went through again, got a prorated amount and applied a 35% discount. Totals:

![image](https://cloud.githubusercontent.com/assets/1254870/18055610/9600c860-6dd6-11e6-8247-b142f9f3fcd4.png)

This resulted in an error 400, invalid positive integer:

![image](https://cloud.githubusercontent.com/assets/1254870/18055624/a2ea4d4e-6dd6-11e6-95da-8dca721d4b40.png)

--- 

In the error log on stripe.com, I see a 0 for the amount passed:
![image](https://cloud.githubusercontent.com/assets/1254870/18055651/b537c01c-6dd6-11e6-932c-6c13f0e23c5d.png)

**Comment by pippinsplugins** [comment]
@mindctrl recurring or non recurring?

**Comment by mindctrl** [comment]
@pippinsplugins non recurring

**Comment by pippinsplugins** [comment]
@mindctrl look in your Stripe logs please. Did it fail when creating the 0.00 invoice or when creating the charge?

**Comment by mindctrl** [comment]
@pippinsplugins it's the charge.

**Comment by pippinsplugins** [comment]
Can you print out the args sent to `rcp_stripe_charge_create_args` and exit then post them?

**Comment by mindctrl** [comment]
```
Array
(
    [amount] => 0
    [currency] => usd
    [customer] => cus_9639nD1YRj7ywW
    [description] => User ID: 106 - User Email: issue649-2@localhost Subscription: 24.99
    [receipt_email] => issue649-2@localhost
    [metadata] => Array
        (
            [email] => issue649-2@localhost
            [user_id] => 106
            [level_id] => 44
            [level] => 24.99
            [key] => f852f654688e5451b22e1dce694d644a
        )

)
```

**Comment by mindctrl** [comment]
@pippinsplugins I just tested this second scenario on 2.6.6, and the amount shows 0 there too for some reason. This seems like a separate issue, and I'm not even sure why it's showing 0 there when the registration totals page shows 3.25.

**Comment by mindctrl** [comment]
RCP Gateway Object passed into `rcp_stripe_charge_create_args`

```
RCP_Payment_Gateway_Stripe Object
(
    [secret_key:protected] => xxx
    [publishable_key:protected] => xxx
    [supports] => Array
        (
            [0] => one-time
            [1] => recurring
            [2] => fees
        )

    [email] => issue649-2@localhost
    [user_id] => 106
    [user_name] => issue649-2
    [currency] => USD
    [amount] => 16.2435
    [discount] => 8.7465
    [length] => 1
    [length_unit] => month
    [signup_fee] => -16.2435
    [subscription_key] => 55d76454fd8304384aff6316219946a0
    [subscription_id] => 44
    [subscription_name] => 24.99
    [auto_renew] => 
    [return_url] => http://dev.rcp:8888/register/welcome/
    [test_mode] => 1
    [initial_amount] => 0
    [discount_code] => bbbbbbbbbb
)
```

**Comment by mindctrl** [comment]
Level config:
![image](https://cloud.githubusercontent.com/assets/1254870/18059457/05b61894-6de7-11e6-9660-cdf7332c8aa5.png)

**Comment by mindctrl** [comment]
Must be a miscalculation of the prorate.

**Comment by mindctrl** [comment]
When looking at the [subscription_details] output for this member, after the initial payment:

![image](https://cloud.githubusercontent.com/assets/1254870/18059520/4921a742-6de7-11e6-9eb1-02ccefe1dd26.png)

The amount has the 3 decimal places.

**Comment by pippinsplugins** [comment]
Ok so that's a separate bug. Let's log that separately and then close this as fixed, agree?>

**Comment by mindctrl** [comment]
Agreed. Merged. Will open a new issue for this other bug.
