### ISSUE TITLE
Search by first/last name on Members page

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#650]
The current username/email lookup isn't all that useful when i'm looking for a particular member by name. Any chance of implementing a more comprehensive search here?

**Comment by pippinsplugins** [comment]
I don't see any reason we can't add support for that.

**Comment by nosegraze** [comment]
PR: #995

Thoughts on this approach?

**Comment by mindctrl** [comment]
Haven't tested but looks good.

**Comment by mindctrl** [comment]
This works pretty well. One thing it requires is a full match. I think we could enable partial matching (like when a user has two words in the last name) by adding `'compare' => 'LIKE'` to the query args for `first_name` and `last_name`.

**Comment by nosegraze** [comment]
Good idea! Added that in.

**Comment by mindctrl** [comment]
Works great. This is milestoned for 2.8. We can merge this into master and ship it with 2.7.3 or redo it for `release/2.8` (which doesn't yet exist). I'm good with either.

**Comment by nosegraze** [comment]
I don't mind. Since it's done and fairly simple, maybe we should just go for `2.7.3`.

**Comment by mindctrl** [comment]
Good with me. Merged and updated milestone.

**Comment by pippinsplugins** [comment]
:+1:
