### ISSUE TITLE
Add 'View User Account' link to records on Payments page

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#651]
This is fairly minor, but when viewing payments there's no easy way to get to the user's profile without navigating to the Users page and doing a manual name search.

I can click through to the Edit Member page with 'View Member', but a 'View User Account' link alongside this which goes to the standard user profile would be really useful.

A 'View User Account' link on the Edit Member page would also be nice (I often need to get to the user's account/profile to see their email address for example).

**Comment by pippinsplugins** [comment]
Great idea.

**Comment by pippinsplugins** [comment]
Ready for testing

**Comment by pippinsplugins** [comment]
![screen shot 2016-10-14 at 11 39 20 am](https://cloud.githubusercontent.com/assets/1034109/19395362/de0fb6d4-9202-11e6-9761-7c043404a233.png)

**Comment by mindctrl** [comment]
Works great. Will merge when tests pass.
