### ISSUE TITLE
rcp_generate_invoice() requires 'manage_options' cap

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#655]
Editors are unable to download invoices even thought they can carry out most other member related tasks.

Other actions seem to use the 'rcp_manage_members' or 'rcp_manage_payments' cap which might be more appropriate here?

**Comment by mindctrl** [comment]
@thomasfw Editors are unable to manage members on the default installation. Have you made customizations to your roles, or am I misunderstanding what you mean?

**Comment by thomasfw** [comment]
@mindctrl In that case it's likely i've updated the editor role to include the rcp caps (we give clients the editor role rather than admin). 

Regardless, I think the `rcp_manage_payments` capability should still be used here (If a user with the `rcp_manage_payments` cap can edit a payment, it seems illogical that they're unable to download a payment invoice).

**Comment by pippinsplugins** [comment]
I agree that `rcp_manage_payments` makes more sense.

**Comment by mindctrl** [comment]
@thomasfw thanks for clarifying. I agree that `rcp_manage_payments` should be the cap check.
