### ISSUE TITLE
Change payment method interface to radio buttons

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#658]
We've had numerous requests about changing the payment method selector from a dropdown to a radio, like we have in EDD. I agree with these requests. The radio is easier to use and gives instant visibility to all options available.

**Comment by pippinsplugins** [comment]
Ready for testing!
![screen shot 2016-11-03 at 8 51 39 pm](https://cloud.githubusercontent.com/assets/1034109/19991873/59575630-a207-11e6-8586-44e2f9b579ff.png)

**Comment by mindctrl** [comment]
This breaks Stripe, with Stripe missing token error.

**Comment by mindctrl** [comment]
Updated. Tested with:
* [x] Stripe
* [x] Manual
* [ ] PayPal Standard
* [ ] PayPal Express
* [ ] PayPal Pro
* [x] Braintree (works but when other gateway is selected, its fields still show. Will open issue there.

**Comment by mindctrl** [comment]
@pippinsplugins can you test all the PayPal gateways? I still have a broken sandbox.

**Comment by mindctrl** [comment]
Visually, I'd like to consider displaying the radio buttons side by side like we do in EDD, instead of vertically.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by mindctrl** [comment]
@pippinsplugins I think we're good here. Just need to confirm no unintended issues with PayPal gateways. I've reached out to PayPal again about my sandbox being hosed, but nothing yet. Can you do a test on those 3 above?

**Comment by pippinsplugins** [comment]
All three work properly! Merging.

**Comment by pippinsplugins** [comment]
Looks like the gateway isn't pre-selected:
![screen shot 2017-01-17 at 3 34 26 pm](https://cloud.githubusercontent.com/assets/1034109/22040928/72ef63fa-dcca-11e6-8ad3-7943d5f80517.png)

**Comment by mindctrl** [comment]
I'll address this after #893 is merged.

**Comment by mindctrl** [comment]
@pippinsplugins updated

**Comment by pippinsplugins** [comment]
Works fine for me!

**Comment by mindctrl** [comment]
Merged.
