### ISSUE TITLE
Tables aren't accessible on network activated installations

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#669]
If you network activate, go to the first site, and then try to create a level, you'll get an error that it wasn't created. PHP error is:

`WordPress database error Table 'pressmatic.restrict_content_pro' doesn't exist for query SELECT * FROM restrict_content_pro  ORDER BY list_order; made by do_action('restrict_page_rcp-member-levels'), rcp_member_levels_page, rcp_get_subscription_levels, RCP_Levels->get_levels`

If you go to a second site, it works. If you go back to the first site, you see the level you created on the second site, and then it now works on the first site.

We set an empty prefix on network activated installs here: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.6/restrict-content-pro.php#L41

Not sure why it works if you go to the second site and back. Haven't looked at it yet. Logging for 2.7 unless you want to fix it up sooner @pippinsplugins.

**Comment by pippinsplugins** [comment]
Let's do it in 2.7 unless we start to see more tickets about it.

**Comment by pippinsplugins** [comment]
This works properly for me now. I think our introduction of `rcp_register_databases()` may have fixed this.

Closed as resolved!

**Comment by mindctrl** [comment]
@pippinsplugins I saw this happen again about 2 days ago on a new customer site. It only happens when network activated, and I think it's due to us setting an empty string for the db prefix in all the `rcp_get_*_name()` functions.

I'm going to open this back up and run another test since I just saw it happen and will close it again if I can't reproduce.

**Comment by pippinsplugins** [comment]
Hmmm, I tested network activation and adding sub levels to multiple sites.

**Comment by mindctrl** [comment]
This happens because when clicking `Network Activate`, the `is_plugin_active_for_network` checks inside `rcp_get_*_db_name` return false. This results in the table names being prefixed with `$wpdb->prefix` during activation, so those are the tables that get created.

But after the plugin is fully activated, `is_plugin_active_for_network` returns true, and `rcp_get_*_db_name` functions return the unprefixed name.

We should probably check for `$network_wide` in `rcp_options_install()` and get the values accordingly.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
https://github.com/restrictcontentpro/restrict-content-pro/commit/9b5b83050dd8f340748845d9a4875956c0cb7eaf is one idea for handling this. Works in local tests for both network activated and site-level activated.

While looking at this I noticed debug messages in the upgrade routines due to the same prefix issue, so I adjusted that too.

**Comment by mindctrl** [comment]
Related: https://github.com/restrictcontentpro/restrict-content-pro/issues/220

**Comment by pippinsplugins** [comment]
Ah! I like that approach

**Comment by mindctrl** [comment]
Cool! I'll phpdoc that function, make another quick pass to make sure I didn't miss anything, and will PR it.

**Comment by mindctrl** [comment]
PR submitted.

**Comment by pippinsplugins** [comment]
This works well but causes one major issue:

1. Activate the plugin on a site within the network
2. Create some subscription levels and/or discount codes
3. Activate the plugin network wide
4. Go to a different sub site
5. Create levels and/or discount codes
6. Return to the site in 1-2.
7. The existing levels that were created are now gone and replaced by the ones created in step 5.

This is happening because all sites are sharing the same database tables, so that's expected, but this could really cause some major issues with existing sites. Imagine the fallout if a network was previously running RCP on individual sites in the network and then chose to network activate it instead. All of their levels, discounts, and payments would be gone.

I think we need to change this approach a little:

1. Keep database tables site independent, even when network activated
2. Profile a `RCP_NETWORK_WIDE` constant, just like AffiliateWP does that can enable shared tables across the network.

**Comment by mindctrl** [comment]
@pippinsplugins I originally had that thought, and I like the idea, but introducing the constant would break existing multisites that have it network activated. Here's why. If you network activated the plugin before, the prefixed tables were created and you couldn't use the plugin. But, once you visited another site on the network, the unprefixed tables were created and the shared tables started working. That's because the rcp_is_installed option was missing on the site, the is_plugin_active_for_network check returned true at that point, and things worked the way the code seemingly intended.

I know of at least a few site that discovered this. And since they'd need to add the constant to continue working the way they do now, they'd break when upgrading.

I'm not opposed to breaking a few things to move it in the right direction, but wanted to get your thoughts on that before adding the constant setup to this PR.

If we move forward with that, we can announce it early through a blog post and the mailing list, and maybe do some kind of upgrade notice on the plugin row through the EDD SL API.

**Comment by pippinsplugins** [comment]
Ok so we have break points in either direction. I _think_ I'd prefer to go with the constant approach. Not 100% sure yet.

**Comment by mindctrl** [comment]
An idea to avoid any breakage is to do what the PR does now (network wide), and make the constant work to allow site-level dbs instead of network wide.

**Comment by pippinsplugins** [comment]
Yeah I like that idea. Could you update the PR accordingly?

**Comment by mindctrl** [comment]
Updated PR. Looks good to me locally, but need another set of eyes and tests on this.

**Comment by pippinsplugins** [comment]
Merged into 2.7!

**Comment by pippinsplugins** [comment]
@mindctrl could you please draft up a doc on this? Re-opening and then can close once that's done.

**Comment by mindctrl** [comment]
@pippinsplugins draft here: http://restrict-content-pro.helpscoutdocs.com/article/1584-using-restrict-content-pro-with-wordpress-multisite?preview=58508291c697912ffd6be74b&auth=true

Closing this now. Ping me on Slack if you have any edits.

**Comment by pippinsplugins** [comment]
Doc looks great!
