### ISSUE TITLE
Improve rcp_process_registration() processing

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#670]
`rcp_process_registration()` makes a number of calls to helper functions, which themselves call the `RCP_Levels` and `RCP_Member` classes. The results in those classes being instantiated several times over the course of processing a registration. We can streamline this a bit and reduce the number of class instantiations and maybe a few database queries.

I started noticing performance issues locally due to the number of test levels I have on my sites. Normally I'd be all for the helper functions, but until we make some other changes to make the process leaner, I think streamlining `rcp_process_registration()` is a good enhancement in the meantime. Note: we've done a little of this in the admin-side processing already.

**Comment by pippinsplugins** [comment]
PR looks good. Merged.

**Comment by mindctrl** [comment]
I think we're good here. @pippinsplugins if you want to do another test to be sure, that would be great. Otherwise we can close.

**Comment by pippinsplugins** [comment]
Worked perfectly.
