### ISSUE TITLE
Show notice when saving Login Redirect without a log in form on the redirect page

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#672]
In order to prevent admins from locking themselves out of their site, we automatically uncheck the login redirect option if the selected page does not contain a log in form.

There's not currently a notice of any kind that explains why the option is not saved so admins come to us and ask why it failed. The answer is simply that they need to add `[login_form]` to the redirect page.

Let's show a notice that explains this.

**Comment by pippinsplugins** [comment]
See https://secure.helpscout.net/conversation/245835732/41269/?folderId=841776 for an example.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by mindctrl** [comment]
Works great. Merged.
