### ISSUE TITLE
Ambiguity on the Edit Member page

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#674]
The 'cancel' button should be removed from the top of the edit_member page. It's not clear at all that this means 'go back to member list' rather than 'cancel this user's membership'.

Maybe change to  **<a href="#back-to-member-list">Members</a> > Edit Member: John Doe**

<img width="779" alt="screen shot 2016-09-06 at 15 28 44" src="https://cloud.githubusercontent.com/assets/7723105/18277537/b8ad1d98-7446-11e6-8610-6949ade0eb46.png">

It would also be useful if we could cancel from this page using a button (and with a js confirmation dialog). It seems more deliberate than a dropdown select..

<img width="433" alt="screen shot 2016-09-06 at 15 35 59" src="https://cloud.githubusercontent.com/assets/7723105/18277869/e4f54334-7447-11e6-98d8-8d4d7072c71c.png">

Also, a quick query - If I change a member's status to 'canceled' in the **Status** dropdown, will their subscription be canceled in the payment gateway, or just their status meta changed?

**Comment by mindctrl** [comment]
Right now setting a member's status to cancelled does not cancel their subscription. We have an issue for that here: https://github.com/restrictcontentpro/restrict-content-pro/issues/557

**Comment by mindctrl** [comment]
Re: removing "cancel" button at top, agreed. We should either change it to "Go back" or remove it entirely.

**Comment by thomasfw** [comment]
This is actually a pretty large issue for me, I'm currently documenting the Membership processes for a client and the lack of consistency will be very confusing. 

I don't see why somebody would want to flag an account as 'canceled' without actually canceling the gateway subscription, so @pippinsplugins suggestion in #557 of an additional checkbox next to the dropdown doesn't make sense to me - 'Cancel' should always mean cancel, especially when customer payments are concerned?

**Comment by mindctrl** [comment]
@thomasfw people do all sorts of things you can't imagine in membership sites. Every single site we see is different, and many do things we think makes no sense, but for their use case it does. In another project of ours, we added a checkbox to refund the payment in the processor, which is where his suggestion came from. We're always open to suggestions. The point being we have an issue for clarifying and improving the process.

**Comment by thomasfw** [comment]
@mindctrl No problem, if this is something that you don't see making it into a release, is there a cancelation hook you might suggest I use to cancel the subscription in our gateway any time the status is changed?

**Comment by pippinsplugins** [comment]
We're going to add a real cancellation option in 2.7.

In the mean time, you could hook into `rcp_set_status`.

**Comment by thomasfw** [comment]
Thanks :)

**Comment by mindctrl** [comment]
PR removing cancel button submitted. We'll deal with the cancellation issue in #557.
