### ISSUE TITLE
Improve "upgrade" phrasing on registration form

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#677]
We've had several tickets about this now. When there's only one subscription level on a site and a member visits the registration form, the form says "Upgrade Your Subscription". The main complaint they have is that there's only one sub level, so "upgrade" is confusing. Let's look at improving this to avoid confusion, reduce tickets, and make it so customers aren't having to edit their templates to change it.

**Comment by pippinsplugins** [comment]
Maybe we should just add shortcode parameter to allow it to be changed.

**Comment by mindctrl** [comment]
I'm moving this to 2.7.2. We've had several tickets about it over the last couple weeks. The biggest complaint lately is that it says "Upgrade" when a logged in user doesn't have a subscription already. The template just does a simple `is_user_logged_in()` check.

I think we should add a shortcode parameter as you said, and also adjust the default so that it only says Upgrade if the person already has a subscription and there is more than one subscription on the site.

**Comment by pippinsplugins** [comment]
Sounds good to me.

**Comment by nosegraze** [comment]
PR: #1169

Any ideas for the default header if someone is logged in but doesn't have a subscription? It's currently `Register New Account`, but I don't feel that makes sense, as they already have an account. Other options might be `Register for a Subscription` or `Sign Up for a Subscription`.

**Comment by mindctrl** [comment]
Maybe `Join Now`? Doesn't imply a payment necessarily, and doesn't imply a subscription in cases where auto-renew is off or optional.

**Comment by mindctrl** [comment]
Though I suppose it could sounds subscription-y.

**Comment by nosegraze** [comment]
I like `Join Now`.
