### ISSUE TITLE
document / officially support the rcp_user_has_access function as part of the API?

### ISSUE THREAD

**Issue by derickbailey** [restrictcontentpro/restrict-content-pro#679]
I'm doing some custom work in my theme and plugin where I want to show the complete content of the page to anyone that views it. 

This page also has a video that I am loading from a URL in custom field. Only members with access level > 0 are allowed to watch the video. Everyone else is shown the title image from the video with a message about how they can subscribe.

To make this work, I can't use the "Restrict this content" option in the post settings - that ends up hiding part of the content and still showing the video... the opposite of what I want.

What I need, is to check if the current user access level is high enough to watch the video. 

After digging through the source code, I found the `rcp_user_has_access` function and it's exactly what I need.

However, this function is not documented in the official API list on the website, so I'm assuming it's something I should not call because it may change in the future, etc.

I would like to see this function exposed as a well-known API function that I can call. Or, alternatively, the equivalent function on the `RCP_Member` object. 

Note that I can't use the `RCP_Member->can_access` method, because that requires me setting the post access level, which causes problems as I noted above.

If the `RCP_Member->can_access` method allowed a second parameter to specify which access level is required, that would work fine. 

Either way works for me, really: either documenting `rcp_user_has_access` or adding the "required access level" parameter to `RCP_Member->can_access` ...

Would either of these be possible in the next release? I'm planning to use `rcp_user_has_access`, for now, knowing that it may break, as an undocumented API.

Thanks!

**Comment by mindctrl** [comment]
@derickbailey our code documentation is lacking. You can use `rcp_user_has_access()`. We're not changing it in the immediate future, and if we do it would either be backwards compatible or we'd safely deprecate it in favor of something new.

**Comment by derickbailey** [comment]
@mindctrl totally understandable - docs can be ridiculously time consuming to maintain, and low priority. I'll keep using `rcp_user_has_access()`, as I planned. Thanks! :)
