### ISSUE TITLE
Add override hook to webhook listener callback

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#681]
Is it possible to add an override hook at the top of the Stripe webhook listener callback.

Adding a hook at the top of the Stripe webhook listener means we can completely override the webhook process, so it's possible to prevent a charge from being processed by RCP when required (i'll get to that in a minute)...

**do_action( 'rcp_stripe_webhook_listener_override', $payment_event );**

```
class RCP_Payment_Gateway_Stripe extends RCP_Payment_Gateway {

    ...

    public function process_webhooks() {

          ...

          $event_id = $event_json_id->id;

			try {

				$event         = \Stripe\Event::retrieve( $event_id );
				$payment_event = $event->data->object;

                // Add override hook
				do_action( 'rcp_stripe_webhook_listener_override', $payment_event );

```

I'm currently running a modified plugin with this hook hardcoded, if it could make it into the core for the next release i'd really appreciate it - I can create a pull request if necessary.

Thanks

**Comment by thomasfw** [comment]
And the reason why this is useful - We've just set up a feature which allows us to charge a Stripe customer that was set by RCP when they joined. 

The issue is that every Stripe charge we make gets processed by the RCP webhook listener, and the user's membership gets updated as a result (the payment is processed as a membership payment, even though we've billed them for something unrelated).

**Comment by mindctrl** [comment]
@thomasfw if the member's membership is being updated when a webhook event comes in, and that webhook is unrelated to an RCP charge, that's probably an RCP bug we need to fix.

**Comment by thomasfw** [comment]
@mindctrl you might be right - as far as I can see the webhook receiver just gets the $member from the charge data, checks they have a subscription_id, and inserts/processes that payment only on the condition that it doesn't already exist. 

This only happens when i'm using the customer object set up by RCP to make the charge, and not when i'm making one off charges for a user using another method.

Is it possible to add the override hook anyway - it's still useful to be able to hook into the webhook processor.

Thanks

**Comment by thomasfw** [comment]
For a more permanent fix, something like this..?

1. When a user joins/renews and the charge is requested, add the transaction_id received from the gateway (e.g. Stripe) to an array of rcp_membership_payments `[ch_f8tiE9fe9UyUhi0x0f5OjIf0, ch_D854E9fe9UyUhi0x0f5OjI03]` (stored in site options).

2. When a charge is processed by the webhook listener, before doing anything else check that the transaction_id is in the array of rcp_membership_payments. 

This way no payments other than those directly requested by RCP will be processed.

**Comment by pippinsplugins** [comment]
@thomasfw You could hook into `init` earlier than we do to intercept the webhook. That would do it.

**Comment by thomasfw** [comment]
@pippinsplugins I considered that.. I'm just concerned that if the rcp webhook hook priority was changed for any reason we might not pick up on that right away, and obviously that would immediately cause problems. I seem to remember the priority is already set to something like -999999 so it just feels a bit unsafe to rely on always hooking in before rcp!

Thanks

**Comment by pippinsplugins** [comment]
It's highly unlikely we will change the priority we use. As long as you use a really, really low one, it should never be an issue.
