### ISSUE TITLE
Stripe: send plugin name and info to Stripe's SetAppInfo()

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#686]
Stripe has a new `setAppInfo()` that we can use to tell Stripe the requests come from RCP. This will help with debugging and backtracking through history.

See https://github.com/easydigitaldownloads/edd-stripe/issues/141

**Comment by mindctrl** [comment]
Updated Stripe library. Screenshot of app info:

![image](https://cloud.githubusercontent.com/assets/1254870/18754708/9c72495a-80b7-11e6-8892-61a88748e7d3.png)

**Comment by pippinsplugins** [comment]
Nice!

I wonder if it makes more sense to include the URL of the site running RCP instead of our own site URL, that way there's no question what site sent the API request. Thoughts?

**Comment by mindctrl** [comment]
Hmm that's probably a good idea.

**Comment by mindctrl** [comment]
Updated.

![image](https://cloud.githubusercontent.com/assets/1254870/18755091/d1faa062-80b8-11e6-87ff-80e374753d54.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Let's merge once tests pass.
