### ISSUE TITLE
Cancellation emails get sent twice

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#688]
When a member cancels a subscription, the emails to the site admin and to the member both get sent twice.

**Comment by pippinsplugins** [comment]
@mindctrl are there two status changes shown in user notes section?

**Comment by mindctrl** [comment]
@pippinsplugins no, only seeing one.

This was a daily sub, renewing until I cancelled it from the front end.
![image](https://cloud.githubusercontent.com/assets/1254870/18845126/69ad2316-83ee-11e6-99d8-7a3e5e77d514.png)

**Comment by mindctrl** [comment]
BTW a customer reported this, and I did a quick test to confirm it. Just haven't dug into why it happens yet.

**Comment by pippinsplugins** [comment]
I bet we have the email hooked twice.

**Comment by mindctrl** [comment]
It looks like we cancel the member in the webhooks, as we should. But, when processing a user-initiated cancellation in `[subscription_details]` we also cancel the member by calling `rcp_process_member_cancellation()`, which calls `rcp_cancel_member_payment_profile()`, which then runs `$member->cancel()`.

**Comment by pippinsplugins** [comment]
@mindctrl @michaelbeil ready for testing.

**Comment by mindctrl** [comment]
Works great! Merged.
