### ISSUE TITLE
Use rcp_get_currency() throughout the plugin in place of direct options call

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#690]
`rcp_currency_filter()` should be calling `rcp_get_currency()` [here](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.7/includes/misc-functions.php#L73
), instead of getting it directly from the options. This will allow the filter in `rcp_get_currency()` to work with `rcp_currency_filter()`.

**Comment by mindctrl** [comment]
I see a couple other places we could probably do this.

**Comment by mindctrl** [comment]
@pippinsplugins I updated this PR since you approved it. Mind giving it another look?

**Comment by pippinsplugins** [comment]
PR looks good still.
