### ISSUE TITLE
Add option to disable WP dashboard access and hide admin bar

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#693]
We get asked about this a lot. People want to disable backend access and they want to hide the admin bar. Every week I'm recommending people install one or two other plugins to do these simple tasks. I think we should consider adding it.

**Comment by pippinsplugins** [comment]
I vote we add a checkbox for both.

**Comment by pippinsplugins** [comment]
PR submitted to disable toolbar.

**Comment by mindctrl** [comment]
Merged.

**Comment by pippinsplugins** [comment]
This only hid the toolbar so updated issue title to reflect that change.

I vote we send people to `Remove Dashboard Access` if they want to remove the whole admin too.
