### ISSUE TITLE
Existing Stripe subscriptions not cancelled when a member does a single payment

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#694]
If someone has an existing auto-renewing subscription in Stripe, and they come back to the site to manually renew or buy another subscription, we don't cancel their existing subscription on Stripe. This results in the customer continuing to get billed for the recurring subscription.

We should cancel any existing subscriptions during single payments too.

**Comment by pippinsplugins** [comment]
@mindctrl @michaelbeil ready for testing!

**Comment by mindctrl** [comment]
Hmm this doesn't work. I get this error after making a single payment:

```
An error occurred

Status: 404

Message: Customer cus_9J7q6liOWPH9fh does not have a subscription with ID sub_9J7qNc9GLFRmCk
```

The existing subscription gets cancelled, and the single payment gets billed, but that error is thrown.

**Comment by mindctrl** [comment]
After looking at this closer, I see the logic that cancels the subscription down below. https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.7/includes/gateways/class-rcp-payment-gateway-stripe.php#L317-L322

That explains the error I got above.

The existing code should be working fine, and I just tested it again without this patch and it DID work fine. I'm not sure what was happening on the customer site and on my test site when I reported this. I definitely saw it not working.

**Comment by pippinsplugins** [comment]
That seems to imply either the customer ID is changing or the subscription ID is being changed before the cancellation is called.

**Comment by mindctrl** [comment]
I thought that, but can't replicate it now.

**Comment by pippinsplugins** [comment]
Can't replicate now as in it is working properly now?

**Comment by mindctrl** [comment]
Working for me now. I'm closing this out. We can reopen if we run into it again. Blaming it on a glitch in the matrix for now.
