### ISSUE TITLE
Can't complete registration with 100% discount with Stripe Checkout

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#695]
With Stripe Checkout enabled, if someone goes to the registration form and applies a 100% discount, the registration won't complete. It just sits there.

[Customer reported](https://secure.helpscout.net/conversation/257672347/43554/?folderId=841781) and confirmed locally.

**Comment by pippinsplugins** [comment]
I just tested this and it worked properly for me.

**Comment by mindctrl** [comment]
Hmm doesn't work for me on two different sites.

**Comment by pippinsplugins** [comment]
MaIn registration form with all levels shown or just a single level?

**Comment by mindctrl** [comment]
Main reg form with all levels shown.

**Comment by mindctrl** [comment]
@pippinsplugins try that.

**Comment by pippinsplugins** [comment]
@mindctrl works for me!
