### ISSUE TITLE
StripeCheckout.configure: Unrecognized options

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#696]
I'm seeing the following errors in the console when using Stripe Checkout. Confirmed on my site and a customer site.

```
StripeCheckout.configure: Unrecognized option 'allow-remember-me'.
You can learn about the available configuration options in the Checkout docs:
https://stripe.com/docs/checkout
```

Seems like it's now named `data-allow-remember-meallowRememberMe`????

https://stripe.com/docs/checkout

**Comment by pippinsplugins** [comment]
![screen shot 2016-09-30 at 11 32 32 am](https://cloud.githubusercontent.com/assets/1034109/18999118/9ac7b018-8701-11e6-8399-0230a6ec63f4.png)

**Comment by mindctrl** [comment]
Weird. I saw `data-allow-remember-meallowRememberMe` from 2 different computers, but just now refreshed and only see `data-allow-remember-me`. Me thinks they're having some docs issues, or I'm caught in a vortex.

**Comment by pippinsplugins** [comment]
@mindctrl This is working fine for me.

`[register_form_stripe id="2" data-allow-remember-me="false"]`

**Comment by pippinsplugins** [comment]
Ah, I see. Error shows on main registration form.

**Comment by pippinsplugins** [comment]
Renamed issue as there are actually several unrecognized options.

StripeCheckout.open: Unrecognized option 'label'. Did you mean 'name'?
You can learn about the available configuration options in the Checkout docs:

StripeCheckout.open: Type mismatch for option 'amount':
Looking for type 'number', but instead we found 'string'.

**Comment by pippinsplugins** [comment]
@mindctrl @michaelbeil ready for testing.

**Comment by mindctrl** [comment]
Works great. Merged.
