### ISSUE TITLE
Configure Admin Emails with Template Tags

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#7]
The admin emails should be significantly improved to allow modification.

**Comment by tnorthcutt** [comment]
@pippinsplugins To clarify, are you talking about emails that are sent to admins (e.g. when a user signs up, cancels, etc.)?

If so, would you be in favor of keeping those on the existing `Emails` tab, or splitting off into separate tabs (e.g. `User Emails` and `Admin Emails`)?

**Comment by pippinsplugins** [comment]
This is referring to the ones sent to the admin.

I'd like to rework this whole tab to be a lot more user friendly. The settings will probably still be under one tab, but they need cleaned up a lot.

**Comment by nosegraze** [comment]
Kind of similar, I think we should rework the "Disable New User Notifications" setting. Right now it's actually pretty misleading. It implies it only affects new user notifications, but the same setting is also used for all admin notifications, including:

* New user activation
* User cancellation
* User expiration
* New free subscription
* New trial subscription

Two things that I think would be good:

1. Text box for configuring the admin emails (which address they get sent to). This could be in the "General" section.
2. Have a separate checkbox to disable each type of admin email. These could be moved into each email section. Example:

![rcp-admin-email](https://cloud.githubusercontent.com/assets/6324272/21809799/177cf958-d741-11e6-9b20-59f837690b98.png)

**Comment by pippinsplugins** [comment]
@nosegraze I really like that proposal.

**Comment by donnfelker** [comment]
Definitely looking forward to some customization. I've provided a PR #911 as a simple fix for what I need, but full customization would be great too.

**Comment by nosegraze** [comment]
WIP PR: #965

Added separate checkboxes for disabling admin emails (as pictured above) and added a new box for specifying the email to send notices to.

**Comment by pippinsplugins** [comment]
Looking food!

**Comment by nosegraze** [comment]
Do we literally want to duplicate the subject/message fields like this?

![rcp-admin-emails](https://cloud.githubusercontent.com/assets/6324272/23128966/cf57c52e-f778-11e6-92dc-5a9862f1d0e0.png)

It's going to be a long ass page. :P

**Comment by mindctrl** [comment]
I think we have to do that to make this fully customizable. At some point, after we revamp all the settings, they could go into a nested tab or something.

Hmm what if you move the checkbox above the admin subject/body, and hide them if the checkbox is checked? That would at least help hide them if they're not being used.

**Comment by nosegraze** [comment]
I like that idea!

**Comment by nosegraze** [comment]
Ready for testing!

**Comment by pippinsplugins** [comment]
UI works great for me!

**Comment by donnfelker** [comment]
Awesome stuff folks. Kudos to developing in the open too. Nice work.
