### ISSUE TITLE
Bad expiration date format when editing member

### ISSUE THREAD

**Issue by boluda** [restrictcontentpro/restrict-content-pro#704]
When editing a member, the prepopulated expiration date format is not the proper one

![screen shot 2016-10-05 at 16 59 20](https://cloud.githubusercontent.com/assets/4599915/19118599/2c983228-8b1d-11e6-8195-e8e310b43867.png)

The main problem, is that if you don't see it, when updating any other field, the date is automatically changed to January 1, 1970, and the membership status change to expired.

**Comment by pippinsplugins** [comment]
@boluda what is your WordPress date format set to?

**Comment by boluda** [comment]
That one!
![screen shot 2016-10-05 at 23 37 05](https://cloud.githubusercontent.com/assets/4599915/19132599/ae92b4ec-8b54-11e6-9c17-5ef0426891c7.png)

**Comment by pippinsplugins** [comment]
This happens because we pass the expiration date straight to the `set_expiration_date()` method of `RCP_Member` without converting it to the expected date format.

**Comment by pippinsplugins** [comment]
@mindctrl could you give this a test?

**Comment by pippinsplugins** [comment]
See https://github.com/restrictcontentpro/restrict-content-pro/pull/715 for additional changes.

**Comment by mindctrl** [comment]
@geoffreybr your fix works great. Merged. Thanks. Thanks @boluda for reporting this.
