### ISSUE TITLE
Link payment ID to payment Gateway on member details page

### ISSUE THREAD

**Issue by boluda** [restrictcontentpro/restrict-content-pro#705]
I'm not sure if this is a bug, in case it's not, just close it.

In EDD payment IDs are linked to the gateway's payment transaction details page. At least if they pay with Stripe and Paypal, so when I click on them, I go to the merchant's payment page.

But in RCP there is no link to the merchant's payment page, right?

Again, sorry if it's not a bug, but it's so convenient! :)

Thanks!

**Comment by pippinsplugins** [comment]
Where are you clicking on them from? The transaction IDs show in Restrict > Payments are linked.

**Comment by boluda** [comment]
Oh, cool! I was clicking on the "payments section" on "rcp-members&edit_member". That brings me to "rcp-"payments&payment_id", where there is no link. Thanks!

**Comment by pippinsplugins** [comment]
We should add a link there.

**Comment by boluda** [comment]
Cool, thanks, that would be useful :)

**Comment by pippinsplugins** [comment]
I've added a link to the edit payment screen and also adjusted the table on the member page to include the payment ID and link the transaction ID to the merchant:
![screen shot 2016-11-21 at 5 24 45 pm](https://cloud.githubusercontent.com/assets/1034109/20504893/7e424624-b00f-11e6-8b17-fd8de62e5702.png)
![screen shot 2016-11-21 at 5 25 29 pm](https://cloud.githubusercontent.com/assets/1034109/20504902/88077972-b00f-11e6-8b52-ec4cb2895edd.png)
