### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by boluda** [restrictcontentpro/restrict-content-pro#706]
There is a misspelling in a Spanish translation of "Active". It says "Acitvado" instead of "Activado".

I modified my po and mo file, how should I send you the right version? Is Github the proper way, or I should do it somewhere else?

Thanks.

**Comment by mindctrl** [comment]
@boluda you can open a PR here, or you can email them to us via the support form here: https://restrictcontentpro.com/support/

**Comment by boluda** [comment]
OK, thanks John!
