### ISSUE TITLE
Stripe Checkout: data-panel-label adds price even if changed

### ISSUE THREAD

**Issue by boluda** [restrictcontentpro/restrict-content-pro#712]
Hi there!

I noticed than in [register_form_stripe], the data-panel-label adds the {price} no matter what, even if a different value is defined in that parameter.

So if i go for data-panel-label="$10 month", the output is "**$10 month 10,00€**", which is weird. Since we are dealing with subscriptions, something like this would make sense:

![image](https://cloud.githubusercontent.com/assets/4599915/19297670/698eba4c-9047-11e6-8ac3-c59a10d1da15.png)

Thanks, guys :)

**Comment by pippinsplugins** [comment]
Thanks for the headsup! We'll get that resoolved.

**Comment by boluda** [comment]
Great! :)

**Comment by mindctrl** [comment]
Stripe says this:

>The label of the payment button in the Checkout form (e.g. Subscribe, Pay {{amount}}, etc.). If you include {{amount}} in the label value, it will be replaced by a localized version of data-amount. Otherwise, a localized data-amount will be appended to the end of your label. Checkout does not translate custom labels to the user's preferred language.

I read that to mean we can't remove the price from the button.

**Comment by mindctrl** [comment]
Re-open if you disagree.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by dobesv** [comment]
By the way, the workaround is to set the amount to `0`, then it won't be added to the button label.  You can still use the payment method for your subscription afterwards.
