### ISSUE TITLE
Add helper function for creating a member

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#713]
When a member is created several things need to be handled, such as subscription level, join date, status, etc. It would be nice to have a helper function that handles all these things, so it's easier for us to handle in RCP core, in add-ons, and for customers looking to programmatically create members themselves.

Something like: `rcp_set_as_member( $user_id, $args = array() )`

**Comment by helsinglee** [comment]
cool!

**Comment by mindctrl** [comment]
#1127 has been merged.
