### ISSUE TITLE
WordPress database error on installation

### ISSUE THREAD

**Issue by sumobi** [restrictcontentpro/restrict-content-pro#716]
With latest master I'm getting this message on a fresh WP MS installation:

> WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`)' at line 1 for query ALTER TABLE wp_rcp_payments ADD` (``) made by activate_plugin, do_action('activate_restrict-content-pro/restrict-content-pro.php'), rcp_options_install, dbDelta

**Comment by mindctrl** [comment]
Related: https://github.com/restrictcontentpro/restrict-content-pro/issues/669, https://github.com/restrictcontentpro/restrict-content-pro/issues/380

**Comment by mindctrl** [comment]
#380 mentioned above is fixed. Closing this in favor of #669, which has more info.
