### ISSUE TITLE
Add a per-category restricted message

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#718]
It could be neat to add the option to change the restricted (Premium Content Message) message on a per-category basis.

Ref: https://secure.helpscout.net/conversation/266897596/45094/?folderId=841776

**Comment by pippinsplugins** [comment]
Agreed.

**Comment by mindctrl** [comment]
What happens if a post is in multiple categories?

**Comment by pippinsplugins** [comment]
Two things we could do:

1. Default to the first term
2. If WP SEO is active, default to the one set as Primary (this will be most sites)

**Comment by nosegraze** [comment]
I'm closing this in favour of https://github.com/restrictcontentpro/restrict-content-pro/issues/1701 and moving towards just a single restriction message.

Reopen if you disagree.
