### ISSUE TITLE
Incorrect expiration date when upgrading with manual gateway

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#721]
When upgrading a subscription using the manual gateway, the expiration date is incorrectly set for the member.

Steps to reproduce:
- buy a subscription 1 month expiration date and note your expiration date
- immediately upgrade to another 1 month subscription

At this point, the expiration date is 2 months out. The user has only paid for 1 month, as he was prorated when buying the second subscription. The expiration date should have remained 1 month out.

**Comment by pippinsplugins** [comment]
Was the member `pending` or `active` before upgrading?

**Comment by mindctrl** [comment]
@pippinsplugins `active`.

**Comment by pippinsplugins** [comment]
@mindctrl Thinking on this more. Wouldn't it be correct to extend from the current expiration if we are renewing the same subscription level? So we should only use the current time (I think) if we're buying a different level.

**Comment by pippinsplugins** [comment]
@mindctrl looks good to me!
