### ISSUE TITLE
Checkbox to Hide/Show Payment Gateway Settings

### ISSUE THREAD

**Issue by renatonascalves** [restrictcontentpro/restrict-content-pro#736]
The default behavior in this tab is to show the 3 most used gateway.

Gateway Options
![screenshot_1](https://cloud.githubusercontent.com/assets/19148962/19810584/d1216ade-9d0c-11e6-885a-4b1d8175108a.png)

Gateway Settings
![screenshot_2](https://cloud.githubusercontent.com/assets/19148962/19810645/0c7a05aa-9d0d-11e6-9536-ee25495de7eb.png)

I'd suggest to show the settings for the ones only checked. In this way, the plugin would only show settings the site is using, instead of showing Stripe settings when the site is using only the PayPal one.

**Comment by mindctrl** [comment]
@renatonascalves That's a good idea. We're planning to redo the whole settings panel at some point. https://github.com/restrictcontentpro/restrict-content-pro/issues/155

At that point the whole layout may be different, but this is something we'll consider. I'm going to close this and link to it from the original issue. Thanks for the suggestion!

**Comment by renatonascalves** [comment]
Ok!
