### ISSUE TITLE
Improve User Notes

### ISSUE THREAD

**Issue by renatonascalves** [restrictcontentpro/restrict-content-pro#737]
I'd suggest to improve the user notes area. Could use WooCommerce as a inspiration. Not necessarily to add notes, but the presentation of it, also allow hooking (this part I'm not sure if already exists.).

https://12407-presscdn-0-33-pagely.netdna-ssl.com/wp-content/uploads/2016/02/Screen-Shot-2016-02-26-at-5.10.56-PM.png

**Comment by mindctrl** [comment]
@renatonascalves we have an issue to improve notes here: https://github.com/restrictcontentpro/restrict-content-pro/issues/384

**Comment by renatonascalves** [comment]
Thanks! =)
