### ISSUE TITLE
Improve system info report

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#738]
We're missing some things that would help with support. Some are:

- [ ] whether or not API keys are set for payment processors (we'd not send the keys themselves, just that they're set or not. also need to check if the secret/publishable keys at least start with the right characters. people swap them sometimes.)
- [x] a list of subscription levels and their price (helpful for determining the behavior differences between free and paid levels)
- [x] email settings (status, subject set or not, body set or not, and all related settings)
- [x] WordPress date format, time format, and timezone from Settings > General.
- [x] WordPress membership setting under Settings > General.
- [x] New User Default Role from Settings > General.
- [x] action hooks so add-ons can add information to the report
- [x] Content excerpts
- [x] Opt into beta
- [x] Disable WordPress Toolbar
- [x] Email verification
- [x] One time discounts
- [x] Whether or not proration is disabled
- [ ] Whether or not upgrading is disabled
- [x] Debug mode

**Comment by mindctrl** [comment]
We also need to add the new settings we've added, like Content Excerpts, Opt into beta, and Disable WordPress Toolbar.

**Comment by mindctrl** [comment]
We also need to add any new settings that have been added since this was introduced.

**Comment by nosegraze** [comment]
Updated the issue with what I think is a full list. Feel free to add anything else.

**Comment by nosegraze** [comment]
Not done yet, but some progress: #1283

However, I realized the proration/upgrade status may not be accurate or reliable since those filters pass in the user ID so could be manipulated depending on the current user's status.

**Comment by nosegraze** [comment]
> also need to check if the secret/publishable keys at least start with the right characters.

Wasn't really sure what to look for here so I just checked if they were set.

**Comment by mindctrl** [comment]
For Stripe I was just thinking about checking that the keys start with the right characters, since it has a predictable prefix, but we can skip part for now if we want.
