### ISSUE TITLE
Validate inputs on price fields on subscription level add/edit screen

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#744]
Just had a customer getting Stripe token errors. Turns out she had input a bunch of text in the price field, like this: `22.00 ($21.00 monthly + $1.00 Processing fee for credit card payments)`

We should prevent that from happening. We should also ensure the other fields are validated for proper input.

**Comment by mindctrl** [comment]
PR submitted. I adjusted what we use on the payment screen for pattern. My regex-fu is not good, so would like another set of eyeballs on this for sure.

**Comment by pippinsplugins** [comment]
My regex-fu is also not good. Which patters do you intend to allow?

**Comment by mindctrl** [comment]
Basically these:
1.00
1
1,00

no negative amounts.

**Comment by mindctrl** [comment]
Didn't catch the comma I see. Do we need to?

**Comment by pippinsplugins** [comment]
Commas should be supported.

**Comment by mindctrl** [comment]
@pippinsplugins updated pattern. found that one here: http://www.regexlib.com/DisplayPatterns.aspx?cattabindex=2&categoryId=3&AspxAutoDetectCookieSupport=1

**Comment by pippinsplugins** [comment]
:+1:

Can we sanitize at DB level too please?

**Comment by mindctrl** [comment]
@pippinsplugins updated PR.

**Comment by mindctrl** [comment]
A note for reference: full form validation is something I've been working on in the evenings, which is bigger in scope than just level data validation. It will work with any form data we have in front end or back end. For now I marked this valid_amount method as private, because it'll likely go away in the future in preference of the newer form validation stuff.

**Comment by pippinsplugins** [comment]
PR looks good at first glance. I still need to test it.

**Comment by pippinsplugins** [comment]
This is causing subscription levels to not be updated:

Level:
![screen shot 2016-11-23 at 9 47 02 am](https://cloud.githubusercontent.com/assets/1034109/20568336/d2c7e322-b161-11e6-9c37-514687499e1f.png)

Error:
![screen shot 2016-11-23 at 9 47 20 am](https://cloud.githubusercontent.com/assets/1034109/20568346/db58798e-b161-11e6-9776-891ec371464d.png)

No changes are saved.

I've tried with free and non-free levels.

**Comment by mindctrl** [comment]
Ugh. Good catch. This happens because posting an empty value overrides the default 0 when passed through `wp_parse_args`. We should probably add a default placeholder to those fields anyway, and then also check for empty values inside the `RCP_Levels` class.

**Comment by pippinsplugins** [comment]
Works well now.

We need to strip `,` from the amounts. For example, you can enter `1,999` and it will save properly but it will come in as `1` on registration.

**Comment by mindctrl** [comment]
@pippinsplugins ugh, we said we wanted to keep commas for currencies that use it. https://github.com/restrictcontentpro/restrict-content-pro/issues/744#issuecomment-257990411

So I guess we need to convert it from `,` to `.` before storing, since we don't have a currency separator option. Or display it properly coming out... which would require a bunch more tests with the gateways.

**Comment by mindctrl** [comment]
We just need to strip commas. We're not really set up for converting them... 

Ideally down the road we'd move to storing amounts in cents and use a multiplier like Stripe does.

**Comment by pippinsplugins** [comment]
Let's strip them for now.

**Comment by mindctrl** [comment]
@pippinsplugins updated, give this one a whirl.

**Comment by pippinsplugins** [comment]
Works great.

**Comment by pippinsplugins** [comment]
Merge once tests pass.
