### ISSUE TITLE
Enable rich editor on email settings

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#749]
Once #748 is completed, we should update the email settings to use rich editors.

**Comment by pippinsplugins** [comment]
This is included in the PR for #748 https://github.com/restrictcontentpro/restrict-content-pro/pull/750

**Comment by mindctrl** [comment]
We need to run these through `wp_kses_post` or similar. It's possible to save anything right now. Will update #750 shortly.

**Comment by mindctrl** [comment]
Updated: https://github.com/restrictcontentpro/restrict-content-pro/pull/750/commits/65a52843bc8fa3a86d839c82406e9b07cc2bf9fb

**Comment by pippinsplugins** [comment]
Looks good!
