### ISSUE TITLE
Fix fatal error on unsupported PHP versions

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#756]
If someone's PHP version is lower than 5.3, none of the plugin files get loaded, but the `rcp_register_databases` action still triggers. This causes a fatal error when trying to use classes (like `RCP_Payments`) that don't exist.

Moving the action into the `else` block for the version check fixes the problem.

See #755

**Comment by mindctrl** [comment]
Works great. Merged.

**Comment by pippinsplugins** [comment]
We have several other actions that tie in at `plugins_loaded` so each of those pieces of functionality need thoroughly tested:

- integration classes
- gateway loading

Could I get confirmation both of those are still working? They should but just to be safe.

**Comment by nosegraze** [comment]
Well the only one I moved was:

`add_action( 'plugins_loaded', 'rcp_register_databases', 11 );`

which looks to only be setting up global variables:

```php
/**
 * Register / set up our databases classes
 *
 * @return  void
 *
 * @access  private
 * @since   2.6
 */
function rcp_register_databases() {

	global $wpdb, $rcp_payments_db, $rcp_levels_db, $rcp_discounts_db;

	$rcp_payments_db   = new RCP_Payments;
	$rcp_levels_db     = new RCP_Levels;
	$rcp_discounts_db  = new RCP_Discounts;
	$wpdb->levelmeta   = $rcp_levels_db->meta_db_name;
	$wpdb->paymentmeta = $rcp_payments_db->meta_db_name;

}
```

This is the one function that was being loaded *outside* of the PHP check.

The gateway and integration classes are hooked in separate files, which are only conditionally loaded in the `else` portion of the PHP version check anyway. For example, the gateway hook is separate in includes/gateways/gateway-functions.php:

`add_action( 'plugins_loaded', 'rcp_load_gateway_files', 9999 );`

But includes/gateways/gateway-functions.php is only loaded if PHP is >= 5.3.

**Comment by pippinsplugins** [comment]
All good then!

**Comment by mindctrl** [comment]
Both payments and integrations working for me. We only moved `add_action( 'plugins_loaded', 'rcp_register_databases', 11 );` from outside the PHP version check to inside it... we didn't wrap it in another `add_action`.
