### ISSUE TITLE
Not preventing account sharing if the first user connected never connects again

### ISSUE THREAD

**Issue by geoffreybr** [restrictcontentpro/restrict-content-pro#761]
My use case is with three users : **A**, **B** and **C** using the same account, with prevent account sharing enabled.
1. User **A** logs in and get connected. He closes his web browser without logging out.
2. User **B** logs in and get connected.
3. User **C** logs in and get connected.
4. Unless user **A** connects again using the connection cookie set up during step 1, user **B** is never logged out by RCP. So users **B**, **C** and the next users connected with this account can share it easily.

*Note: the pull request for this issue is coming in few minutes*

**Comment by mindctrl** [comment]
Works great. Thanks @geoffreybr.
