### ISSUE TITLE
Make it easier to customize the jQuery blockUI overlay

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#767]
A number of people have asked about customizing it, mainly because they don't like it or they want to change the color of it. I'd like to look into ways to make it easier for customers to customize.

**Comment by pippinsplugins** [comment]
Perhaps we could write up a quick doc on how to style it with CSS.

**Comment by mindctrl** [comment]
BlockUI takes the options we pass to it in register.js and adds the styles to the blocking element itself. While that's not ideal, we can just do a tutorial on how to use `!important` to override it.

Closing this out.
