### ISSUE TITLE
Can't use another payment gateway if Stripe Checkout has been selected

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#768]
To reproduce:

* Enable Stripe Checkout and another gateway (I tested with PayPal).
* On register form, choose Credit / Debit Card (Stripe Checkout).
* Then change to PayPal after the ajax finishes.
* Press submit.

The Stripe Checkout modal pops up instead of taking you to PayPal.

**Comment by pippinsplugins** [comment]
Replicated.

**Comment by mindctrl** [comment]
PR submitted. Needs testing.

**Comment by mindctrl** [comment]
Just had a thought that this may need to be updated for the radio buttons in 2.7.

**Comment by pippinsplugins** [comment]
PR looks good at first glance.

@michaelbeil or @nosegraze could one of you test it?

**Comment by nosegraze** [comment]
Works good for me!
