### ISSUE TITLE
Add filters and actions in rcp_process_profile_editor_updates

### ISSUE THREAD

**Issue by geoffreybr** [restrictcontentpro/restrict-content-pro#769]
I added few fields in the profile editor ('Edit your profile' page) : URL of the user's Facebook page, a small description of the user, etc. ; the goal was to show these contents in the comments of the registered users without giving them access to the WP back-office.
In `rcp_process_profile_editor_updates`, there is no filters and actions equivalent to `rcp_form_errors` and `rcp_form_processing` that are used in the registration form. So I had the choice between modifying the code of restrict content pro (which is not a good idea for updates) and replacing the `rcp_process_profile_editor_updates` action by mine (which I did).
Moreover, it could be great to add the old user data in the `rcp_user_profile_updated` action. For example, I use the old email address to check if it has changed and, if so, I send a verification link (#632).

It would be great to add these kind of actions and filters to allow the plug-ins to really plug in the profile editor :slightly_smiling_face:. I will also use them to improve the Mailchimp plug-in.

*Note: As usual, the pull request is coming*

**Comment by pippinsplugins** [comment]
This looks good to me!

**Comment by mindctrl** [comment]
Merged. Thanks @geoffreybr

**Comment by geoffreybr** [comment]
@mindctrl Do you know when the v2.7 will be released ? I will need this soon (so will probably have to integrate the feature in my version) but it could be good to have an approximative date :wink:. Thanks!

**Comment by mindctrl** [comment]
@geoffreybr we don't have a set date yet. My guess would be within the next 2 months, but that depends largely on how things go during the holiday season.
