### ISSUE TITLE
Add option to remove all data when uninstalling plugin

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#771]
When uninstalling RCP, we should have an option that allows for removing all plugin data, tables, etc. It should default to off, so that people don't accidentally remove all data. EDD has an option like this.

**Comment by nosegraze** [comment]
PR: #1009

**Comment by pippinsplugins** [comment]
@nosegraze Could you update the `release/2.8` branch with `master` show the PR is clean and limited to just the relevant changes?

**Comment by nosegraze** [comment]
I'm off my game today.

Should be fixed now.

**Comment by mindctrl** [comment]
I updated this PR to use get_option directly instead of calling the `$rcp_options` global. The global wasn't accessible on my site during uninstall for some reason.

I also updated the `DROP TABLE` stuff to use the table name helper functions. Since those helper functions have filters and the names aren't predictable, I ran them through `esc_sql` to at least ensure they don't have funky data - it appears you can't pass table names through `prepare()`, as it quotes the names and results in invalid SQL. This is the first time I've needed to use this approach, so if anyone knows of a better way I'd love to know about it.

**Comment by nosegraze** [comment]
Makes sense. It's the same for why you can't use `prepare()` for order/orderby values.

I'm good with it!
