### ISSUE TITLE
Restrict entire post type

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#782]
It would be nice to be able to restrict an entire custom post type with one setting. I've seen this request pop up a few times now.

Examples:
https://secure.helpscout.net/conversation/280575299/0/
https://secure.helpscout.net/conversation/278540313/46900/?folderId=841781

**Comment by mindctrl** [comment]
I've seen a few requests for this too. The main thing that comes to mind is how it works with the existing restrictions UI at the post level. What about existing posts? What about ability to override at post level? When creating a new post, we'd need to read the default values for the post type and automatically set them on the post restriction settings... or introduce a new default option that flows back to the global post type setting. Also need to consider interaction with taxonomies.

**Comment by nosegraze** [comment]
So we don't forget..

In the meeting we talked about the possibility of auto adding a new submenu page under each public post type that contains restriction settings for that post type.

**Comment by nosegraze** [comment]
WIP PR: #1118

Certainly not done but I've started playing with some ideas. I haven't thought about overriding at a post level or anything right that. Honestly, I started cringing at how that would basically double the size of `RCP_Member::can_access()`. :P Right now it's basically:

- Whole post type is restricted
- Or, restrict individual posts

**Comment by mindctrl** [comment]
> I haven't thought about overriding at a post level or anything right that. Honestly, I started cringing at how that would basically double the size of RCP_Member::can_access().

I agree with you. Anything that adds anything significant to `can_access()` gets a 👎 from me too.

**Comment by nosegraze** [comment]
Maybe we should do something similar to what we did with content excerpts. If a post type is restricted then show all the settings in the restrict meta box but disable them, with a note about post type restriction.

**Comment by nosegraze** [comment]
![rcp-restricted-post-type](https://cloud.githubusercontent.com/assets/6324272/24298265/5e421d7e-109d-11e7-9821-bd577d8daefc.png)

**Comment by pippinsplugins** [comment]
Oh I love that.

**Comment by nosegraze** [comment]
Ready for a look/testing!

**Comment by pippinsplugins** [comment]
How about changing the `Restrict` submenu to `Restrictions` or `Restrict Access` or `Restrict Options`. Just `Restrict` doesn't seem clear enough to me.

**Comment by pippinsplugins** [comment]
@nosegraze This is looking great! The restriction settings, however, aren't quite working for me.

I've set a post type to be restricted to `any` level but my active subscriber still gets redirected away from it. I've also tried specifying specific levels and the redirection still happens.

**Comment by pippinsplugins** [comment]
If I remove the restrictions, I can view the post type fine.

**Comment by nosegraze** [comment]
@pippinsplugins Hm I'm not sure I'm able to reproduce the issues with restrictions. Did these posts have any post-level restrictions before you added the global post type ones? Or are they in a restricted category?

**Comment by pippinsplugins** [comment]
This is working beautifully now.

I just realized it wasn't working before because my member's account was expired. Oops.

**Comment by CaptainN** [comment]
Any idea when this will ship? I could use this feature pretty soon. :-)

I'll try the issue #782 branch for now, and see how it goes.

**Comment by pippinsplugins** [comment]
@CaptainN it's getting included in version 2.9, which we will ship (probably) sometime in May.

**Comment by CaptainN** [comment]
Great thanks! I actually applied the branch to master and uploaded that. Seems to work :-)

**Comment by mindctrl** [comment]
Looking at the flow of our access checks reveals something we need to address. Just for kicks I wanted to know how many times these new post type restriction functions run. Specifically I tested `rcp_get_post_type_restrictions()`.

When logged out on a single post view, `rcp_get_post_type_restrictions()` runs a total of 7 times just on `the_content` filter. Here's a trace of those:

```
apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_is_restricted_post_type,
rcp_get_post_type_restrictions


apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions


apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_get_post_type_restrictions


apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions


apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
apply_filters('rcp_member_can_access'),
WP_Hook->apply_filters,
rcp_disallow_access_pending_verification,
rcp_is_restricted_content,
rcp_is_restricted_post_type,
rcp_get_post_type_restrictions


apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
apply_filters('rcp_member_can_access'),
WP_Hook->apply_filters,
rcp_disallow_access_pending_verification,
rcp_is_restricted_content,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions

apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
rcp_is_paid_content,
rcp_get_post_type_restrictions
```

It also runs a number of times for post_class and for the comments template. We have a good amount of inefficiency and this only adds to it. Ideally we would address these issues before adding complexity, adding code we have to maintain, along with the new filters we'd have to keep around while working to fix the issues.

Admittedly some of this existing already, but I don't like adding to it.

It looks like we could eliminate 2 of these calls by moving the check that happens in `rcp_disallow_access_pending_verification()` to `RCP_Member::can_access()` instead of using the `rcp_member_can_access` filter.

Curious what you all think of this issue in general.

**Comment by pippinsplugins** [comment]
That's a good catch, John. Let's go ahead and move what we can to `can_access()` and then reassess.

**Comment by mindctrl** [comment]
Moving the pending verification removed 2 runs.

Current status

`post_class` filter:
```
apply_filters('post_class'),
WP_Hook->apply_filters,
rcp_post_classes,
rcp_is_restricted_content,
rcp_is_restricted_post_type,
rcp_get_post_type_restrictions



apply_filters('post_class'),
WP_Hook->apply_filters,
rcp_post_classes,
rcp_is_restricted_content,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions



apply_filters('post_class'),
WP_Hook->apply_filters,
rcp_post_classes,
rcp_user_can_access,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_is_restricted_post_type,
rcp_get_post_type_restrictions



apply_filters('post_class'),
WP_Hook->apply_filters,
rcp_post_classes,
rcp_user_can_access,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions



apply_filters('post_class'),
WP_Hook->apply_filters,
rcp_post_classes,
rcp_user_can_access,
RCP_Member->can_access,
rcp_get_post_type_restrictions



apply_filters('post_class'),
WP_Hook->apply_filters,
rcp_post_classes,
rcp_user_can_access,
RCP_Member->can_access,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions
```

`the_content` filter:
```
the_content,
apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_is_restricted_post_type,
rcp_get_post_type_restrictions


the_content,
apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions


the_content,
apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_get_post_type_restrictions


the_content,
apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
RCP_Member->can_access,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions


the_content,
apply_filters('the_content'),
WP_Hook->apply_filters,
rcp_filter_restricted_content,
rcp_is_paid_content,
rcp_get_post_type_restrictions
```

`comments_template` filter:
```
apply_filters('comments_template'),
WP_Hook->apply_filters,
rcp_hide_comments,
rcp_user_can_access,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_is_restricted_post_type,
rcp_get_post_type_restrictions


apply_filters('comments_template'),
WP_Hook->apply_filters,
rcp_hide_comments,
rcp_user_can_access,
RCP_Member->can_access,
rcp_is_restricted_content,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions


apply_filters('comments_template'),
WP_Hook->apply_filters,
rcp_hide_comments,
rcp_user_can_access,
RCP_Member->can_access,
rcp_get_post_type_restrictions


apply_filters('comments_template'),
WP_Hook->apply_filters,
rcp_hide_comments,
rcp_user_can_access,
RCP_Member->can_access,
rcp_has_post_restrictions,
rcp_is_paid_content,
rcp_get_post_type_restrictions
```

**Comment by pippinsplugins** [comment]
This might be a terrible idea, but what if we setup a global that held an array of all post IDs checked on a page along with the access status for the current member and each post ID? That would allow us to run a check for each post ID on a page and then never need to run it again since we could easily read the access status for the ID from the global.

**Comment by nosegraze** [comment]
I feel like @mindctrl had a similar-ish idea that he voiced in one of our first meetings.

**Comment by mindctrl** [comment]
I should have an update for this today.

**Comment by mindctrl** [comment]
I pushed a commit that introduces the in memory cache we discussed during the meeting. It also more efficiently applies the filters we use in post_class, the_content, and comments_template.

The net result is the 17 runs above are down to 1.

This needs heavy testing. Also probably need some adjustments in general and feedback on the concept.

**Comment by mindctrl** [comment]
Forgot to mention that's on a new branch, `issue/782-cache` - which is branched off of `issue/782` here.

**Comment by mindctrl** [comment]
Getting the `_is_paid` meta directly helps. It brings us down to 8 duplicate runs. We can get it down to 2 runs, before we do #1250, by doing this:
- comment out the `add_filter` lines for `rcp_filter_restricted_content`, `rcp_hide_comments`, and `rcp_post_classes`
- adding the following in its place

```
function rcp_member_access_post_filters( $post ) {

	if ( ! rcp_user_can_access( get_current_user_id(), $post->ID ) ) {
		add_filter( 'post_class', 'rcp_cannot_access_post_class_filter' );
		add_filter( 'the_content', 'rcp_cannot_access_the_content_filter', 100 );
		add_filter( 'comments_template', 'rcp_cannot_access_comments_template_filter', 1000 );
	} else {
		remove_filter( 'post_class', 'rcp_cannot_access_post_class_filter' );
		add_filter( 'post_class', 'rcp_can_access_post_class_filter' );
		remove_filter( 'the_content', 'rcp_cannot_access_the_content_filter', 100 );
		remove_filter( 'comments_template', 'rcp_cannot_access_comments_template_filter', 1000 );
	}

}
add_action( 'the_post', 'rcp_member_access_post_filters' );

function rcp_cannot_access_post_class_filter( $classes ) {

	$classes[] = 'rcp-is-restricted rcp-no-access';

	return $classes;
}

function rcp_can_access_post_class_filter( $classes ) {
	$classes[] = 'rcp-can-access';
	return $classes;
}

function rcp_cannot_access_the_content_filter( $content ) {

	global $post, $rcp_options;

	$message = ! empty( $rcp_options['free_message'] ) ? $rcp_options['free_message'] : false; // message shown for free content

	if ( get_post_meta( $post->ID, '_is_paid', true ) || in_array( $post->ID, rcp_get_post_ids_assigned_to_restricted_terms() ) ) {
		$message = ! empty( $rcp_options['paid_message'] ) ? $rcp_options['paid_message'] : false; // message shown for premium content
	}

	$message = ! empty( $message ) ? $message : __( 'This content is restricted to subscribers', 'rcp' );

	return rcp_format_teaser( $message );

}

function rcp_cannot_access_comments_template_filter() {
	return rcp_get_template_part( 'comments', 'no-access', false );
}
```

This is a nice improvement and 2 is better than 8 in this case. If we remove the filter in `rcp_get_post_type_restrictions`, and I think maybe we should, it further improves the efficiency and prevents additional runs of hooked functions.

**Comment by pippinsplugins** [comment]
@nosegraze this is all working great for me. I did notice two small, easy to fix issues and one formatting item, which I've noted in my review on the PR>

**Comment by nosegraze** [comment]
Thanks for testing! Added changes here https://github.com/restrictcontentpro/restrict-content-pro/commit/153c7c67ff685cc01b5754816ef9f626e9e74a61

**Comment by pippinsplugins** [comment]
Looks good, merging!

**Comment by nosegraze** [comment]
🎉
