### ISSUE TITLE
Add support for user-defined locales

### ISSUE THREAD

**Issue by ramiabraham** [restrictcontentpro/restrict-content-pro#783]
WordPress 4.7 introduces `get_user_locale()` ([changeset](https://core.trac.wordpress.org/changeset/38705)), which falls back to the standard `get_locale()`.

This changes the RCP `load_textdomain()` loader method ([line link](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/restrict-content-pro.php#L131)) to support user locales.

**Comment by ramiabraham** [comment]
Added a PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/784

**Comment by mindctrl** [comment]
Was going to test this, but don't see an option in the profile editor to change user language on the latest trunk. Will swing back around.

**Comment by pippinsplugins** [comment]
Works perfectly!
