### ISSUE TITLE
Could U add user center page which merge all essential information all in one by using tabs?

### ISSUE THREAD

**Issue by helsinglee** [restrictcontentpro/restrict-content-pro#786]
User need a front end page focus their information.
Feature request
1 [restrict] where I used, I hope there are link user can purchase membership or 1 time access this project.
2 user can create groups and sell the seats to others.
3 Provide a tool in editor bar restrict the post paid content.
4 hope bring more features in other membership plugin... s2me...  just a suggestion.
it a long way to go, about addons, if possible move all the addons build-in #RCP 's addon page, we can download/ install / active addons in this page, and dont need goto wordpress plugin page manage the addons. I think that all the addons just a feature can be use a switcher turn on/ off, maybe dont need an extra addon to relize it. We need lots of time to install the addons, build in or a switcher more great. I look EDD had lots of addons, I know U can earn more money but hope RCP can run an other way. It isnt just a membeship plugin.
thanks!

**Comment by mindctrl** [comment]
@helsinglee please open a support ticket at https://restrictcontentpro.com/support/. We only use Github for development tracking.
