### ISSUE TITLE
Restrict any element? such as ads can be display for different level members?

### ISSUE THREAD

**Issue by helsinglee** [restrictcontentpro/restrict-content-pro#787]
I want to display ads to the different level members, or any other content. if possible create ads addon for the RCP.  and how to integrate other e-commerce plugins? for example wooecommerce, EDD. I found that when use more than one these plugins, there are two or more checkout/ store / account pages, it's not easy to use.  as the previous post, hope RCP can provide a user center page, and auto-create these pages.

**Comment by mindctrl** [comment]
@helsinglee please open a support ticket at https://restrictcontentpro.com/support/. We only use Github for development tracking.

**Comment by helsinglee** [comment]
OK, thanks!
