### ISSUE TITLE
Error when adding discount code with no Stripe credentials

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#788]
To reproduce:

1. Enable the Stripe gateway.
2. Leave API credentials blank.
3. Create discount code.

The result:

![rcp-discount-error](https://cloud.githubusercontent.com/assets/6324272/20669912/7e338e18-b56e-11e6-80db-b67c250a35df.png)

If API creds are required for creating the discount then at the very least the error message should be improved!

**Comment by pippinsplugins** [comment]
@mindctrl let's put this in 2.7 instead. It's pretty low priority and would be nice to get 2.6.11 out sooner than later.

**Comment by helsinglee** [comment]
Maybe need more developers for RCP.

**Comment by mindctrl** [comment]
@helsinglee this issue is on track to be fixed. If you're having this issue, turn off Stripe or enter your Stripe API keys. If you continue to have issues, feel free to email us!

**Comment by helsinglee** [comment]
@mindctrl Yep, thanks. Ashley Gibson solved lots of my doubts. and can post feature request to the support team? RCP now had many bugs, need more  big things.

> I'm so sorry, I realized I forgot to address this:

"when I used stripe checkout, then submit it, canceled and switch to the paypal, then submit payment, but it is still the stripe payment..."

This is an issue we're aware of and we're releasing a fix for it in the next update. :)

{#HS:282967609-47833#}  

Ashley Gibson
support@restrictcontentpro.com

**Comment by mindctrl** [comment]
@helsinglee yes, you can send feature requests to support. We only add an issue here for a feature when we've decided that it needs to be developed. We use Github for development tracking only.

**Comment by mindctrl** [comment]
PR works great. Merged.
