### ISSUE TITLE
Registration - auto select first level, or hide price table until level is selected

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#792]
On the registration page, a level isn't chosen by default (assuming `$_GET['level']` isn't set), but the total price table is displayed. This can be a bit confusing since it's showing price details for a plan that isn't selected. It would be better if either the first subscription plan is selected by default to match the price table, or hide the price table completely until a plan is actually chosen.

![rcp-total-price](https://cloud.githubusercontent.com/assets/6324272/20709237/f7d2be52-b62b-11e6-98a5-8d95ca735ca3.png)

**Comment by pippinsplugins** [comment]
It's supposed to auto select the first one, or the one provided in the URL.

**Comment by mindctrl** [comment]
Maybe introduced here: https://github.com/restrictcontentpro/restrict-content-pro/commit/4dff9be67302d1042f6917ff812b541ef8639d3e

**Comment by pippinsplugins** [comment]
Yep that looks like it.
