### ISSUE TITLE
Redirect premium posts when restricted only via taxonomy

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#795]
If a post is restricted only via taxonomy, the redirect doesn't happen. It would be nice to support this, as it would make the taxonomy restrictions much more useful and viable with the redirect option. There are some performance concerns with querying the taxonomies and terms connected to a post, but I'd like to dig into it and see if we can come up with a decently performant way to do this.

**Comment by mindctrl** [comment]
@pippinsplugins took a stab at this in `issue/795`. Needs some testing and probably a little bit of error checking. Thoughts on this approach?

**Comment by pippinsplugins** [comment]
See comment on PR regarding using the WP query classes.

**Comment by mindctrl** [comment]
After looking through `WP_Term_Query`, I don't see a way to specify post ID to narrow down the query into one step. I think the approach here is the most performant, but happy to go another route with a WP core method if we can identify one.

**Comment by pippinsplugins** [comment]
Ok this approach seems fine then.

In testing I've found a few things.

1. Terms were coming back as having restrictions even when no restrictions were set. This was due to `None` getting saved in the access level. Fixed in b529dc899ccec3ca76be832684b5088e025d45ff.

2. The `Hide Premium Posts` feature was originally built only to redirect away from _premium_ posts, so content restricted to free members was never affected. In the current implementation, however, this is not the case with taxonomy terms. For example, adding a restriction to a free subscription level will result in the redirect occurring. Basically it's not respecting the `rcp_is_paid_content()` check for terms. This is a bit tricky to fix and, frankly, I'm not sure we should fix it. I actually think we should work on moving towards supporting redirects for _all_ cases where a member does not have access to the content.

3. The current implementation does not properly check if a member has access to terms the content is assigned to before redirecting away from it.

There are two things I think we should do here:

1. Implement a usage of `RCP_Member->can_access( $post_id )` in the redirect function
2. Update `can_access()` to check the taxonomy term restrictions. Right now it doesn't even acknowledge they exist, this is done separately in `rcp_filter_restricted_category_content()`, which is tied to `the_content`. 

Moving the restriction checks on terms to `can_access()` provides several major benefits:

1. Allows us to do redirects for any kind of content, not just paid content.
2. Makes it _significantly_ easier to programmatically check if a member has access to a post.
3. Further reduces confusion in our own code base.

**Comment by mindctrl** [comment]
I agree.

1. We save `None` on post restrictions. It would be great to move away from that too.

2. I'd love to move this direction too. The existing setup is confusing to a lot of our customers.

3. It runs `! rcp_is_active()` first, which helps with that, but doesn't cover free cases - which hopefully are going away as per #2.

Will work on moving the taxonomy checks to `can_access()` soon.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
WIP submitted. Needs to be updated to account for someone having access via one taxonomy term instead of all, like we do in `rcp_is_post_taxonomy_restricted()`. Will wrap this up this afternoon.

FYI: the unit test failed due to Travis funk, so restarted it.

**Comment by pippinsplugins** [comment]
Looking good!

**Comment by mindctrl** [comment]
Right now the `free_message` is shown for content restricted only via taxonomy. We need to account for that and show the `paid_message` if the term is restricted to paid levels.

**Comment by mindctrl** [comment]
Just a note: still got some things I want to do here.

**Comment by mindctrl** [comment]
re: this comment: https://github.com/restrictcontentpro/restrict-content-pro/issues/795#issuecomment-266489858

In the current release version, we just assume paid message in `rcp_filter_restricted_category_content()` unless paid message is empty, then we use a generic fallback message.

Because we moved term checks to `can_access()` in `RCP_Member`, we no longer need to run `rcp_filter_restricted_category_content()`. It gets handled in `rcp_filter_restricted_content()` now when it runs `rcp_user_can_access()`.

However, inside `rcp_filter_restricted_content()`, `rcp_is_paid_content()` only does the post-level checks specifically for the `_is_paid` meta value. That leaves us not having a proper paid/free check for taxonomy term restrictions, and therefore we don't necessarily show the proper free/paid restricted content message.

We can introduce a new function like `rcp_post_has_paid_taxonomy_term_restrictions()` - which could also maybe be useful outside of this context - and add that to `rcp_filter_restricted_content()`.

I have some code that does the check for paid level restrictions and shows the proper message. It can add a couple queries to the mix on index/archive pages if multiple terms are assigned to posts, particularly if "paid only" isn't checked and it has to loop through the subscription levels assigned to the term.

I'll push that up shortly so we can look at it and decide if we want that, or maybe come up with a better way. We're bound to increase queries to some degree just by properly checking taxonomy term restrictions now, but I'm looking for the most efficient way to check all the data we need to check to determine if content is restricted, and how it's restricted, so we can deal with it the way we need to.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
@pippinsplugins I was able to avoid additional queries inside `rcp_filter_restricted_content()` for taxonomy term restrictions by using the cached values we already have in the newly-introduced `rcp_get_post_ids_assigned_to_restricted_terms()` function and checking to see if the current post ID is in the array. Also was able to reduce the number of times `rcp_is_paid_content()` runs by only running it if the user doesn't have access.

Things achieved here:
- moved taxonony term restriction checks to `can_access()`
- changed "Hide Premium Posts" to "Hide Restricted Posts", which now hides all restricted content from queries. Customers will love us for this.
- Redirects now work for all restricted content - not just paid.
- Did away with the need to use `rcp_filter_restricted_category_content()` (commented out the filter line, leaving the function in case someone is using it directly), as it's all now handled in `rcp_filter_restricted_content()`.
- Removed the match all filter on term restrictions. This removed some complexity (yay) and was thankfully an undocumented feature.
- Introduced some new helper functions to make restricted content queries more efficient: `rcp_get_post_ids_assigned_to_restricted_terms()` and `rcp_get_restricted_post_ids()`, as well as some functions for clearing the transients used by these functions.
- Checks for `$query->is_main_query()` inside `rcp_hide_premium_posts()` so that it only runs when we mean for it to run.

Lots of changes in this PR to get where we needed to be, and it definitely needs more eyeballs. Unit tests are passing, so yay for that! Let me know if you find anything. I've been looking at this on and off for days, so I'll likely circle back around again with fresh eyes before we merge.

**Comment by mindctrl** [comment]
Need to update the new EDD integration, where we filter `edd_downloads_query`, to use the way we now handle restricted post IDs in `rcp_hide_premium_posts()`.

**Comment by pippinsplugins** [comment]
Frickin fantastic. Will try and thoroughly test soon.

**Comment by pippinsplugins** [comment]
@mindctrl Am I reading your changes right and understanding that we can now remove this monstrosity?
```php
function rcp_user_level_checks() {
	if ( current_user_can( 'read' ) ) {
		if ( current_user_can( 'edit_posts' ) ) {
			if ( current_user_can( 'upload_files' ) ) {
				if ( current_user_can( 'moderate_comments' ) ) {
					if ( current_user_can( 'switch_themes' ) ) {
						//do nothing here for admin
					} else {
						add_filter( 'the_content', 'rcp_display_message_to_editors' );
					}
				} else {
					add_filter( 'the_content', 'rcp_display_message_authors' );
				}
			} else {
				add_filter( 'the_content', 'rcp_display_message_to_contributors' );
			}
		} else {
			add_filter( 'the_content', 'rcp_display_message_to_subscribers' );
		}
	} else {
		add_filter( 'the_content', 'rcp_display_message_to_non_loggged_in_users' );
	}
}
add_action( 'loop_start', 'rcp_user_level_checks' );
```

Looks like all the necessary checks now happen inside of `rcp_filter_restricted_content()`, yes?

**Comment by pippinsplugins** [comment]
Let's change `Hide Restricted Posts` to `Hide Restricted Content`, unless you disagree.

**Comment by pippinsplugins** [comment]
Hmm, redirect isn't happening to me on pages when viewing a restricted page while logged out.

**Comment by pippinsplugins** [comment]
Ok I've found a small issue. If there are _zero_ blog posts available to the viewer (due to them being restricted), the `Posts` page set in Settings > Reading doesn't work. It loads a different page instead (in my case it loaded the Affiliate Area page from AffiliateWP). I believe this is due to there not being any posts returned by the WP_Query.

This may not be an issue but is something to be aware of.

**Comment by mindctrl** [comment]
@pippinsplugins re: the rcp_user_level_checks monstrosity, yep that can go!

**Comment by mindctrl** [comment]
I can't reproduce the `Posts` page issue. When no posts are available due to restrictions, I get the default theme display for when no posts are found.

![image](https://cloud.githubusercontent.com/assets/1254870/21338513/d177db56-c644-11e6-965e-ac209c4d7558.png)

I even activated AffWP to see if it was something there, but still couldn't reproduce.

**Comment by mindctrl** [comment]
I'm going to add some additional unit tests for content that is only restricted via taxonomy terms.

**Comment by pippinsplugins** [comment]
:+1: 💯

**Comment by mindctrl** [comment]
@pippinsplugins made several updates here. Can you give this another look?

**Comment by mindctrl** [comment]
After lunch I'm going to add at least one more test to check access when a post is restricted one way and an assigned term has different restrictions to make sure things work as expected.

**Comment by mindctrl** [comment]
Found an edge case where this improperly restricts people when they should have access.

**Comment by mindctrl** [comment]
WIP: still needs work after latest commit.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
Need to write a workaround for the fact that `WP_Term_Query` is only available on WP 4.6+. Unit tests failed because we also test 4.4 and 4.5.

**Comment by pippinsplugins** [comment]
@mindctrl finished here and ready for more testing?

**Comment by mindctrl** [comment]
@pippinsplugins I should probably give it another look for my own sanity, but I'd love it if you can go ahead and test and give it an eye to see if you catch anything I've overlooked.

**Comment by pippinsplugins** [comment]
@mindctrl I have a page restricted to any member but am still able to view it when logged out: 

![screen shot 2017-01-03 at 4 07 26 pm](https://cloud.githubusercontent.com/assets/1034109/21624928/d00a78ce-d1ce-11e6-8ff6-9af078555620.png)

I can view it _and_ I'm not redirected.

**Comment by pippinsplugins** [comment]
Sorry, that's a filthy lie. I just suck at testing.

This seems to work beautifully!

**Comment by pippinsplugins** [comment]
@mindctrl good to merge?

**Comment by mindctrl** [comment]
@pippinsplugins I think so!

**Comment by mindctrl** [comment]
For some reason the build got stuck on the very last one, `trunk`. It hasn't started yet. That's been almost 3 hours ago. All other ones passed.

**Comment by pippinsplugins** [comment]
Merging.
