### ISSUE TITLE
Incorrect payment status when using manual payments

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#798]
When using the Manual Payments gateway, we set the member to pending until someone manually approves the member. But, the payment status is set to complete, which you can see in the admin, and the invoice the customer accesses from the [subscription_details] shortcode shows complete. 

We should probably set the payment status as pending (which we don't currently use), and mark it as complete when the member is manually approved. Otherwise a member can have an invoice that shows they completed payment when they really didn't.

**Comment by nosegraze** [comment]
I believe #1000 fixed this and it's no longer an issue.

**Comment by mindctrl** [comment]
Confirmed that this was fixed.
