### ISSUE TITLE
How should extensions filter RCP settings on save?

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#799]
The [`rcp_save_settings`](https://github.com/restrictcontentpro/restrict-content-pro/blob/b3366fe0b0132873d7b85b99479937c3dcf59ca5/includes/admin/settings/settings.php#L1124) action exists, but unless I'm mistaken since it's a `do_action()` instead of an `apply_filters()`, it doesn't allow for modifying the passed `$data` array of existing settings.

My use case: I'm writing an extension (actually forking [RCP Group Accounts](https://github.com/restrictcontentpro/rcp-group-accounts )where I want to be able to set "tier names" (e.g. bronze/silver/gold). My initial thought is to have a textarea settings field, with one tier name entered per line. I'd hoped to then hook in and `explode()` those to convert from one string with newlines into an array of tier names.

If I'm missing something obvious, feel free to say so, or if this is a stupid approach, I'm open to that too 😄.

My hunch is that having `rcp_sanitize_settings()` `return apply_filters( 'rcp_save_settings', $data );` instead of the current `return $data;` would solve this – if that's the case give me a thumbs up and I'll file a PR.

**Comment by pippinsplugins** [comment]
@tnorthcutt Yep, pretty sure that would resolve it!

**Comment by tnorthcutt** [comment]
@pippinsplugins Thanks. I'll see if I can get this in next week.

**Comment by nosegraze** [comment]
PR: #1002

**Comment by mindctrl** [comment]
Thinking about this a little... will having this filter affect our ability to totally rewrite the settings in #155?

If so, is `pre_update_option_{$option}` a viable solution for @tnorthcutt and others in the interim? https://github.com/WordPress/WordPress/blob/4.7.2/wp-includes/option.php#L285-L296

**Comment by nosegraze** [comment]
I don't think it would affect it. If we'll be rewriting the settings like EDD then those settings are still sanitized and can still be run through a filter before being saved.

Anyone who uses the filter would just want to update their code to hook into the new settings panel properly and stop using the filter.

Either way, it would require a code update.

**Comment by pippinsplugins** [comment]
I'm good with this, Merged.
