### ISSUE TITLE
Add a filter to allow metadata to be attached to subscriptions

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#800]
Being able to add metadata to a subscription would be nice. For example, attaching a group name from the Group Accounts add-on. For one-time payments, we have something similar: the `rcp_stripe_charge_create_args` filter.

**Comment by nosegraze** [comment]
PR: #1008

While editing, I noticed that the args were an array being passed into an another array, like this: `$customer->subscriptions->create( array( $sub_args ) )`

Is that right, or can we safely update that to `$customer->subscriptions->create( $sub_args )` ? 

`$sub_args` is already an array.

**Comment by pippinsplugins** [comment]
That doesn't look right to me. I'm certain it should be `$customer->subscriptions->create( $sub_args )`.

**Comment by nosegraze** [comment]
Yeah that's what I thought as well. At least it still works LOL.

I'll update it.
