### ISSUE TITLE
Show email and username on edit member screen

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#802]
We should display the email and username of the member on the member edit screen.

The email address should be editable; the username should be set to read-only.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by nosegraze** [comment]
Works well for me.

Maybe it would be nice to add an "Edit User Account" link on the page too. I know there's a link when hovering over it in the members list, but it might be nice to add it directly to the edit page too.

**Comment by mindctrl** [comment]
+1 for Edit User Account link on member edit page. What about something simple like this?

![image](https://cloud.githubusercontent.com/assets/1254870/21239571/60839c04-c2d5-11e6-8895-833f1eaf40e5.png)

**Comment by pippinsplugins** [comment]
I like that. @mindctrl go ahead and add it please.

**Comment by mindctrl** [comment]
Added
