### ISSUE TITLE
Prevent Account Sharing option causes user-based REST auth failure in other plugins

### ISSUE THREAD

**Issue by ramiabraham** [restrictcontentpro/restrict-content-pro#805]
Having the _Prevent Account Sharing_ feature active in _Restrict &rarr; Settings &rarr; Misc_ disables any plugin from accessing data remotely if it depends on user-based authentication, via any standard protocol.

This issue occurs when the user is already logged in. Since the most common way to authenticate with a third-party is to log in to the host and generate auth keys, it becomes a blocker for auth entirely. 

In the case of AffiliateWP, the Zapier add-on auth (http basic) is affected with an authentication error on the Zapier server side, which displays as an anonymous `3xx` redirect process that eventually times out.

- I think a good idea would be a _whitelisting filter_ in RCP, to define specific TLD's that are permitted to authenticate (or perhaps restrict via connection types instead)

- The filter could be `rcp_whitelist_account_sharing_urls` which would return either an array of urls, or a bool `false` by default/if none are defined.

- User-facing control of this feature are I think worth considering, since any non-developer with RCP + AffWP + AffWP Zapier will effectively need third-party help to implement this. Though that could certainly be a revision provided later on.

---

Affected functions will be:

- `rcp_set_user_logged_in_status()`
- `rcp_clear_auth_cookie()`
- `rcp_can_user_be_logged_in()`

**Comment by ramiabraham** [comment]
_(PR in progress)_

**Comment by pippinsplugins** [comment]
@mindctrl good with this?

**Comment by mindctrl** [comment]
Looks good to me. @ramiabraham anything else you want to do here before merging?

**Comment by ramiabraham** [comment]
@mindctrl Sorry for the delay! Nope that should be it!

**Comment by pippinsplugins** [comment]
Merged!
