### ISSUE TITLE
Invalid markup in profile editor output

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#809]
There are two `<legend>` elements in the `<fieldset>`, and there should only be one.

**Comment by nosegraze** [comment]
Added PR: #815 

Split it up into two `<fieldset>` tags so each only has one `<legend>`

**Comment by pippinsplugins** [comment]
I think the submit button should be in its own fieldset instead of grouped with password.

**Comment by nosegraze** [comment]
Updated the PR with that change.

**Comment by pippinsplugins** [comment]
Perfect.
