### ISSUE TITLE
Manual renewals improperly given both proration and full expiration date extension

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#812]
When a non-recurring member manually renews early, a proration credit is given and the expiration date is extended a full period from the current expiration date instead of current date. This results in the person getting free time on their subscription.

For simplicity sake, I think if someone is manually renewing the same subscription early, we should not give proration credits and simply handle the expiration date like we already do.

**Comment by pippinsplugins** [comment]
>>>For simplicity sake, I think if someone is manually renewing the same subscription early, we should not give proration credits and simply handle the expiration date like we already do.

I agree.

**Comment by nosegraze** [comment]
PR: #1039

**Comment by pippinsplugins** [comment]
PR looks right to me.
