### ISSUE TITLE
Some notes are not stored when a member is updated (bug in process-data.php)

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#816]
Notes set within member hooks are overridden by $_POST['notes'] value in process-data.php.

Say I want to add an extra note every time a member's expiry is updated in the backend. I'd hook into the member action `rcp_set_expiration_date` to store an additional note using `$member->add_note()` like so..

```php
add_action( 'rcp_set_expiration_date', function( $uid ){
    $member = new RCP_Member( $uid );
    $member->add_note( "Adding another note when the expiration is changed." );
});
```
The new note will NOT be stored because the value of $_POST['notes'] sets the notes meta back to it's original value in `includes/process-data.php`..

```php
271: if( isset( $_POST['notes'] ) ) {
272: 	update_user_meta( $user_id, 'rcp_notes', wp_kses( $_POST['notes'], array() ) );
273: }
```

**FIX: Move the notes meta update (lines 271 - 273 in process-data.php) above ALL the other** `$member->set_...` **calls**.

It looks like this is affecting the core code too, changing the expiration in _Members -> Edit Member_ doesn't store a message in the log as it should.

Hope this makes sense :/

**Comment by mindctrl** [comment]
Related: https://github.com/restrictcontentpro/restrict-content-pro/issues/384
