### ISSUE TITLE
Add rcp_payments_page_table_column action

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#825]
In `includes/admin/payments/payments-page.php`

We have actions there for `rcp_payments_page_table_header` and `rcp_payments_page_table_footer` but nothing in the actual columns like we do for `rcp_members_page_table_column`.

**Comment by pippinsplugins** [comment]
Oops.

**Comment by mindctrl** [comment]
A customer just reported this. We used to have a `rcp_payments_page_table_column` action here, but at some point in 2.6 dev it got removed.

**Comment by mindctrl** [comment]
That's on me. Got lost here: https://github.com/restrictcontentpro/restrict-content-pro/commit/fdad073c1bc8307dc6f066753c4e71680d4c3718

**Comment by mindctrl** [comment]
PR submitted so we can get this in 2.7. Tested with this code:

```
function jp_rcp_payments_page_table_header_footer() {
	?>
	<th scope="col" class="rcp-payments-moo-col"><?php _e( 'Moo', 'rcp' ); ?></th>
	<?php
}
add_action( 'rcp_payments_page_table_footer', 'jp_rcp_payments_page_table_header_footer' );
add_action( 'rcp_payments_page_table_header', 'jp_rcp_payments_page_table_header_footer' );

add_action( 'rcp_payments_page_table_column', function( $payment_id  ) {
	?>
	<td data-colname="<?php _e( 'Moo', 'rcp' ); ?>"><?php echo 'moo'; ?></td>
	<?php
});
```

**Comment by pippinsplugins** [comment]
Looks good.
