### ISSUE TITLE
Incorrect renewal date for 1 year

### ISSUE THREAD

**Issue by curbb** [restrictcontentpro/restrict-content-pro#829]
When a user purchases a subscription that has a duration of 1 year, their renewal date is set to the purchase date. Then it gets updated to 1-month duration instead of 1 year.

Example: Purchased 1-year subscription on 12/17/2016. The renewal date is suppose to be 12/17/2017. Instead, it's set to 12/17/2016. The next day, it's updated to 1/17/2017

This is during sandbox mode using PayPal and Stripe.

**Comment by mindctrl** [comment]
@curbb we have no other reports of this. Could you please go ahead and open a support ticket at https://restrictcontentpro.com/support/, include your system info report, and screenshots of your subscription level configurations?

I'm closing this issue out. We only add issues here when we've confirmed a bug. We'll open it back up if we can confirm.

**Comment by curbb** [comment]
The issue disappeared after updating the IPN on paypal and hook stripe.

Confirming that its fixed.
