### ISSUE TITLE
Existing users can't subscribe using Stripe Checkout

### ISSUE THREAD

**Issue by boluda** [restrictcontentpro/restrict-content-pro#830]
Hi there!

When an existing WordPress user tries to subscribe using the Stripe Checkout he can't. The user has to be deleted, then he can subscribe.

**Comment by mindctrl** [comment]
Followed up in the support ticket you opened. I'll close this for now and reopen when we have more info.

**Comment by mindctrl** [comment]
Confirmed this bug. When an existing user tries to pay for a subscription **while logged out**, Stripe Checkout appears to process the payment, then the registration page reloads with the following errors:
```
Username already taken
Email already registered
```

No charge appears to hit Stripe. We may need to introduce a user/email lookup here. Other gateways show the error before attempting payment and without reloading the page.

**Comment by pippinsplugins** [comment]
Related https://github.com/restrictcontentpro/restrict-content-pro/issues/562

**Comment by mindctrl** [comment]
Let's hold off on testing/merging this just yet. I want to explore another idea.

**Comment by mindctrl** [comment]
@pippinsplugins submitted an alternate idea to `issue-380-alternate`. Doesn't do the inline auto-validation like the first proposal, but uses the existing ajax validation we have and reduces the duplication.

Tested this with Manual, Stripe, PayPal Standard/Pro/Express and it seems ok. Will need to make another pass and also look at Braintree.

Needs another set of eyes too.

**Comment by mindctrl** [comment]
Will have an update here later today for #830, #562, and #855 as they're all connected.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
All good here!

**Comment by nosegraze** [comment]
Works perfectly with `[register_form]`. I'm not sure if it was meant to be addressed, but this is still an issue with `[register_form_stripe]` though. The modal makes it look like it's been paid but it hasn't been.

**Comment by mindctrl** [comment]
Merged.

Note: we found no event to tie into when someone enters an email in the modal when using just the shortcode version, so we can't do any JS validation before the form submits at this time.
