### ISSUE TITLE
Member remain pending but no records on paypal.

### ISSUE THREAD

**Issue by curbb** [restrictcontentpro/restrict-content-pro#835]
A couple of members are marked as paid subscribers and they're set as pending. I checked Paypal and I don't see any transactions made or payment manual reviews.

I ran a sandbox and its working as expected. The problem only happens when I run it live. I tried emailing them to see if they registered but they haven't replied yet.

- IPN sending is enabled
- Non-standard currency is accepted.

**Comment by mindctrl** [comment]
@curbb please open a support ticket at https://restrictcontentpro.com/support. We use Github for development tracking only.
