### ISSUE TITLE
Two subscription levels with the same name results in incorrect payment/duration

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#836]
I haven't had a chance to dig into the "why" yet, I just got it reproduced. I've also only tested it with Stripe so far so I haven't had a chance to check if it's gateway related or something we're passing to gateways.

How I reproduced it:

- Create a subscription level with a price like $10.
- Register and make a Stripe payment. (not sure if this step is actually required, but in my test I happened to start with a subscription level I'd used before)
- Create a new subscription level with the same name but a different price, like $15.
- Register and make a Stripe payment. The registration form shows the correct price of $15, but Stripe actually takes the amount (and duration settings) from the *first* level ($10) instead.

Editing the member in RCP also shows an expiration date as if I'd subscribed for that first level rather than the second one.

It seems like kind of a weird situation to have two levels with the same name. The guy who discovered it seemed to be wanting to change the subscription level price, so he deactivated the first level, then created a new one with a new price. He was able to "fix" the problem by renaming the first level to add "(old)" at the end.

**Comment by nosegraze** [comment]
Also both levels are marked as `selected` when editing the user due to using names instead of IDs here in `includes/admin/members/edit-member.php`:

`selected( $level->name, $member->get_subscription_name(), false )`

**Comment by nosegraze** [comment]
WIP PR: #964

Just fixed the second issue I mentioned where both levels are marked as `selected`. Still need to dig into the deeper issue.

**Comment by pippinsplugins** [comment]
@nosegraze this looks right to me. Ready for testing?

**Comment by nosegraze** [comment]
I think so. I was going to test it myself first, but haven't gotten to it yet. But I think it's ready in theory. :P

**Comment by nosegraze** [comment]
Confirmed it fixed the problem, so ready for testing!

**Comment by pippinsplugins** [comment]
I'm good with this changeset once @mindctrl has tested it as well.
