### ISSUE TITLE
Push API Payment Update

### ISSUE THREAD

**Issue by Basilakis** [restrictcontentpro/restrict-content-pro#838]
I do not know what tag ( and if it is possible ) belongs to that, but it would be also nice, to have an API update, when a subscription fails to take over. Paypal returns 5 days after, to retry, but the subscription stays as " active " ( I did checked that ).
Also - if possible an option to " Try Charge again " through RCP admin panel, to try renew the client purchase manually?

**Comment by pippinsplugins** [comment]
@Basilakis this is something we're beginning to work on. See #360 for the first part.

**Comment by mindctrl** [comment]
See also https://github.com/restrictcontentpro/restrict-content-pro/issues/657

**Comment by Basilakis** [comment]
Thank u for your hard work.
