### ISSUE TITLE
Add setting to opt into beta releases

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#840]
With EDD Software Licensing 3.5 now running on the site, it's possible for us to release beta versions.

We should add a new setting so customers can opt into beta versions.

**Comment by mindctrl** [comment]
@pippinsplugins PR submitted. Can you double check all this?

**Comment by pippinsplugins** [comment]
@mindctrl PR looks good! Merge and deploy at will!
