### ISSUE TITLE
jQuery Migrate warning on registration page

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#842]
On the registration page, jQuery Migrate complains about our use of `.attr` in `register.js` with the following notice in the console: `jQuery.fn.attr('checked') might use property instead of attribute`

It comes from this [line](https://github.com/restrictcontentpro/restrict-content-pro/blob/2.6.13/includes/js/register.js#L274): `$('#rcp_auto_renew_wrap input').attr('checked', false);`

We have several instances of this in register.js. I think we need to move to `.prop` instead.

**Comment by nosegraze** [comment]
PR: #945
