### ISSUE TITLE
Add status filters to Subscription Levels, Discount Codes, and Payments tables

### ISSUE THREAD

**Issue by ramiy** [restrictcontentpro/restrict-content-pro#847]
Sites with many subscription levels have a very messy subscription screen.

It would be nice to have some kind of indication whether the subscription levels are active or inactive.

We can add a new column with Red/Green color to the table.

Another approach is to add a navigation filter above the table:

![nav](https://cloud.githubusercontent.com/assets/576623/21747324/22aebe14-d56c-11e6-82e9-379f95c4fe38.png)

**Comment by ramiy** [comment]
By the way, the discounts table has a "**status**" column. The same column can be added to the subscription levels table.

**Comment by ramiy** [comment]
Status filter are available only on **Members** page:

![rsc-members](https://cloud.githubusercontent.com/assets/576623/22011406/99713e64-dc97-11e6-8c2d-87fd3cc768a7.png)

It would be nice to have status filters on:
* **Subscription Levels** Screen
* **Discount Codes** Screen
* **Payments** Screen

**Comment by nosegraze** [comment]
PR: #1170

I added status filters to the Subscription Levels, Discount Codes, and Payments tables.

I also ended up tweaking some of the formatting of the payments DB queries, mostly to ensure everything is properly escaped and running through `$wpdb->prepare()` whenever possible. That probably ended up being a bit out of the scope of this issue, but I got carried away!

**Comment by pippinsplugins** [comment]
@nosegraze Looking good!

Seems that payment counts aren't quite working:
<img width="762" alt="screen shot 2017-04-12 at 11 58 59 am" src="https://cloud.githubusercontent.com/assets/1034109/24969763/7a1f85de-1f77-11e7-89f0-1d2fe6cc527c.png">
I refunded a payment and it shows in refunded but the count is still 0.

**Comment by nosegraze** [comment]
Maybe the transient didn't clear properly. I'll take a look!

**Comment by mindctrl** [comment]
This is a minor thing, but if you view a status with 0 discount codes, the table says "No discount codes added yet".

![image](https://cloud.githubusercontent.com/assets/1254870/25345270/a189c8f4-28e2-11e7-95f0-9dd0e1857a4c.png)

**Comment by mindctrl** [comment]
We could not show the link if the count = 0. This is what WP core does.

**Comment by mindctrl** [comment]
Updated a payment from refunded to complete and the refunded count didn't update.

![image](https://cloud.githubusercontent.com/assets/1254870/25346652/29f48fe6-28e6-11e7-83f2-f9e6559ee7c1.png)

**Comment by nosegraze** [comment]
I like that idea. Updated the PR!

**Comment by nosegraze** [comment]
I kind of want to redo how the caching works because it's absolute shit for trying to get it cleared when stuff updates.

**Comment by mindctrl** [comment]
Much better! Just a trailing `|` that shouldn't be there.

![image](https://cloud.githubusercontent.com/assets/1254870/25346864/f564067a-28e6-11e7-97dd-f93d0dd088ff.png)

**Comment by nosegraze** [comment]
Pushed a commit that should fix both problems. The cache one should work for now but maybe we should consider something less annoying when we do https://github.com/restrictcontentpro/restrict-content-pro/issues/790 or something.

**Comment by mindctrl** [comment]
Searching within a status doesn't work right. It goes to the All filter and returns all the matching results. In other words, you can't search refunded payments without getting all payments.

**Comment by nosegraze** [comment]
Update should fix searching, and I think I covered all your other comments on the PR.

**Comment by mindctrl** [comment]
I think this PR is mostly good now. 

One thing I think we need to do is run `prepare()` at the point of the query instead of running it numerous times throughout. Makes it more obvious that it's being prepared, easier to review, and probably pleasing any code analysis tools that look for it.

Foresee any issues doing it that way?

**Comment by nosegraze** [comment]
To clarify, instead of doing this (super rough example):

```php
$where .= $wpdb->prepare( "AND `status` = %s", $args['status'] );

$payments = $wpdb->get_results( "SELECT {$fields} FROM " . $this->db_name . " {$where}" );
```

You want to do something like this?

```php
$placeholders = array();

$where .= "AND `status` = %s";
$placeholders[] = $args['status'];

$query    = $wpdb->prepare( "SELECT {$fields} FROM " . $this->db_name . " {$where}", $placeholders );
$payments = $wpdb->get_results( $query );
```

**Comment by mindctrl** [comment]
Right, just running prepare at the end instead of on each statement as we flow through the method.

`$wpdb->get_results( $wpdb->prepare( the query ) );`

Like what's in `get_payments()`

**Comment by nosegraze** [comment]
I actually find the first method easier to digest, but I'm happy with either way.

**Comment by mindctrl** [comment]
I'm fine with running prepare on the line above the query.

**Comment by nosegraze** [comment]
Updated the PR.

The main change is here: https://github.com/restrictcontentpro/restrict-content-pro/pull/1170/commits/e37f37374f9088a628f9e2c2d52d3dfacfa46756
Then I just renamed the variable since I realized `$placeholders` actually isn't an accurate description at all. :P https://github.com/restrictcontentpro/restrict-content-pro/pull/1170/commits/cd699aa3e912cc6c73fd0b6bb0839d1c5276d102

**Comment by mindctrl** [comment]
Using an array for `status` in `get_payments` isn't working with the latest commit.

**Comment by mindctrl** [comment]
Merged!

**Comment by pippinsplugins** [comment]
🎉
