### ISSUE TITLE
Set display name to username if first & last name aren't filled out

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#849]
When creating user accounts we set the display name as follows:

`'display_name'    => $user_data['first_name'] . ' ' . $user_data['last_name'],`

But neither first name nor last name are actually required in the form, so if neither one is filled out then the display name is just totally blank, which is a bit weird. I'm thinking we should make that fall back to the username if both fields are empty.

Had someone with this problem here: https://secure.helpscout.net/conversation/299269629/50084/?folderId=1100052

**Comment by pippinsplugins** [comment]
:+1:

**Comment by nosegraze** [comment]
PR: #938
