### ISSUE TITLE
Login failure if username is an email address but different from the actual email

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#854]
Kind of a weird situation..

This guy has people registering with an email address as the username, but then entering a *different* email address for the email field. Example:

Username: ashley@rcp.com
Email: support@rcp.com

Then the login fails because of this in `rcp_process_login_form()`:

```
if( is_email( $_POST['rcp_user_login'] ) ) {

	$user = get_user_by( 'email', $_POST['rcp_user_login'] );

} else {

	// this returns the user ID and other info from the user name
	$user = get_user_by( 'login', $_POST['rcp_user_login'] );

}
```

The username is entered as `ashley@rcp.com`, which is a valid username in this case, but then it's being matched against the email and an account may not exist with that email.

We have this from #306 to allow logins via email, which makes sense. Maybe first we should do a quick `username_exists()` check on the email and if it does exist treat it as a username instead.

**Comment by pippinsplugins** [comment]
Interesting . . . should be easy to fix though.

**Comment by mindctrl** [comment]
Just got another report of this.

**Comment by nosegraze** [comment]
PR: #931
