### ISSUE TITLE
Invalid integer error when using Alipay

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#855]
We need to pass the `data-amount` to the Checkout window for Alipay to work. From Stripe support:
> If you're using Alipay with Checkout you absolutely must include a 'data-amount' parameter as part of your Checkout window. This is because Alipay needs to know beforehand how much to allow the user to be charged for. This isn't required for card payments and thus why a card payment works but not Alipay.

**Comment by pippinsplugins** [comment]
:+1:
