### ISSUE TITLE
Issues with rcp_get_current_url() when using reverse proxies

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#860]
`rcp_get_current_url()` doesn't work well when using a reverse proxy behind another reverse proxy (i.e. PHP behind NGINX behind Varnish). The usage of `$_SERVER["SERVER_PORT"]` has caused some quirks for me when doing things like cancelling subscriptions.

I want to play around with this a bit and see if I can come up with a better way of doing it.

**Comment by nosegraze** [comment]
PR: #940

Any issues with this? For `rcp_get_current_url()` I copied chunks from EDD's version and it seems to work well for me. The main thing that was causing issues was processing cancellations since that runs on `init`, when none of the conditional statements work yet. Changing that to `template_redirect` solves it.

**Comment by mindctrl** [comment]
This works well. It fixed an issue for me while testing https://github.com/restrictcontentpro/restrict-content-pro/pull/937.
