### ISSUE TITLE
Add filter for metabox post types

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#861]
Just thinking about updates for the Download Monitor add-on and a filter for the supported post types would help us get our restriction metabox on there if we want it. (DLM's CPT is private so it wouldn't show up right now).

**Comment by nosegraze** [comment]
Now that I think about it, this might be a bit weird because we're getting post type objects. I'll think about this but might end up closing this.

**Comment by nosegraze** [comment]
PR: #863

**Comment by mindctrl** [comment]
@nosegraze this looks good. Left a note on the PR.

Also think we need to document the hook change in case someone is unhooking the meta box in their own code for some reason. Maybe we can mention that in the beta blog post.

**Comment by nosegraze** [comment]
Just updated the PR, thanks @mindctrl !

And yes, good point on documenting this.

**Comment by nosegraze** [comment]
Updated PR to allow for controlling the display of the "Additional Options" section.

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by mindctrl** [comment]
Works great. Merged.
