### ISSUE TITLE
Issues updating RCP using composer

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#864]
I'm managing plugins using composer on a Bedrock installation and i've noticed that `rcp_version` (and possibly other rcp settings) aren't being updated with each release. On a couple of occasions i've actually lost the entire `rcp_settings` after an update, but not sure if that's related.

I've tested this on a fresh WP install and had the same issue. Could be something to do with the plugin's update procedure - maybe not firing correctly?

**Comment by pippinsplugins** [comment]
@thomasfw do you mean the DB value or the constnat?

**Comment by thomasfw** [comment]
@pippinsplugins the actual database values

**Comment by pippinsplugins** [comment]
I see the problem.

Our `RCP_Upgrades` class is only setting the new version in the DB if an upgrade routine was run, meaning it won't set it if no upgrade routine (such as on most point releases) was run.

```php

	private $upgraded = false;

	public function __construct() {

		add_action( 'admin_init', array( $this, 'init' ), -9999 );

	}

	public function init() {

		$version = get_option( 'rcp_version' );

		$this->v26_upgrades();
		$this->v27_upgrades();

		// If upgrades have occurred
		if ( $this->upgraded ) {
			update_option( 'rcp_version_upgraded_from', $version );
			update_option( 'rcp_version', RCP_PLUGIN_VERSION );
		}

	}
```

We need to update it to update the version numbers anytime the `RCP_VERSION` (constant) and `rcp_version` (db) don't match.

**Comment by pippinsplugins** [comment]
Reay for testing.
