### ISSUE TITLE
Taxonomy term restrictions issue when Paid Only not selected

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#868]
It's possible for expired members to access content that's restricted only via taxonomy term, if the term doesn't have the Paid Only checkbox selected. This has already been addressed in `release/2.7`, but I think we should do a point release to fix this in 2.6.x.

**Comment by nosegraze** [comment]
Gave this a quick before/after test and it works properly now.

**Comment by mindctrl** [comment]
Woot! Thanks @nosegraze. @pippinsplugins look good to you? I'd like to deploy this update today if possible.

**Comment by nosegraze** [comment]
Should we also add an expiry check for access level and roles like we talked about last night? That's a very similar issue with `_is_paid` not being set except that happens automatically while saving the meta. But it's possible for it to not get saved if there are no paid subscription levels.

**Comment by mindctrl** [comment]
@nosegraze forgot about that. You looked deeper at this than I did. I think we can fix that by changing this in `can_access()`:

```
// Assume the user can until proven false
$ret = true;
```

to:

```
$ret = ! in_array( rcp_get_status(), array( 'active', 'free', 'cancelled' ) );
```

I did a quick change locally and it still passes unit tests, but we clearly have a missing test in this branch since we've missed this without the change. (`release/2.7` adds more tests and might help).

Do you want to test that change locally since you have this setup already?

**Comment by nosegraze** [comment]
Gave it a test with:

```
// Assume the user can if they have a valid membership status, until proven false
$ret = in_array( rcp_get_status(), array( 'active', 'free', 'cancelled' ) );
```

And that fixes it. :) I checked with access levels, roles, and specific level restriction.

**Comment by mindctrl** [comment]
Thanks @nosegraze. Updated PR.

**Comment by nosegraze** [comment]
Just updated the PR. I found another instance where access is always given regardless of expiration dates if there are no paid plans on the site.

**Comment by pippinsplugins** [comment]
I'm happy with the PR if you both are.

**Comment by nosegraze** [comment]
Yep I think I'm happy with it!

**Comment by pippinsplugins** [comment]
@mindctrl go ahead and merge and deploy at will.

**Comment by mindctrl** [comment]
Merged. Will deploy after unit tests finish.
