### ISSUE TITLE
Update Spanish .mo file

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#871]
Looks like the .po file was updated but not the .mo file so not all strings are being translated.

**Comment by nosegraze** [comment]
PR: #872 

It looked good in my testing, but I sent the files off to one of the people who submitted a ticket about this to confirm. Haven't heard back yet.

**Comment by mindctrl** [comment]
This looks good to me. Good to merge once you get confirmation from customer.

**Comment by pippinsplugins** [comment]
I'm good with this too.

**Comment by nosegraze** [comment]
Got confirmation from him that it works, and merged!
