### ISSUE TITLE
Possible for incorrect ID to be returned when inserting level, payments, and discounts

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#873]
In the `insert()` methods of `RCP_Levels`, `RCP_Payments`, and `RCP_Discounts`, it's possible that the returned ID of the inserted data is wrong. This happens because the global `$wpdb->insert_id` may get overwritten by other code, which is easy to do since we have action hooks in each of those right before returning.

Taking `RCP_Levels` for example, we have this:
```
do_action( 'rcp_add_subscription', $wpdb->insert_id, $args );

return $wpdb->insert_id;
```

If something hooks into `rcp_add_subscription`, adds an entry to the database, the `$wpdb->insert_id` gets overwritten and that results in the wrong ID getting returned.

We need to save the `$wpdb->insert_id` to another variable before firing the action hook and return it instead.

**Comment by pippinsplugins** [comment]
PR looks good.
