### ISSUE TITLE
Fix missing/broken PHPDocs

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#879]
We have a lot that are missing or not formatted correctly and fixing them will make me super happy. :D

**Comment by mindctrl** [comment]
Yesssssssss.

**Comment by nosegraze** [comment]
WIP: #883

Got up to `misc-functions.php`

**Comment by mindctrl** [comment]
Woohoo! Can't wait to see this completed!

This will cause a ton of merge conflicts if we go much further before merging release/2.7, particularly in all the gateway stuff we have pending for trials and one-time discounts.

**Comment by nosegraze** [comment]
@mindctrl  Want me to hold off for a bit?

**Comment by mindctrl** [comment]
@nosegraze I think so, if you don't mind. Probably save you and me both some grief.

**Comment by pippinsplugins** [comment]
I'd say keep going but let's just plan on not merging until the very last thing. Easier to fix conflicts in docs than functionality.

**Comment by pippinsplugins** [comment]
But pausing won't hurt either :D

**Comment by nosegraze** [comment]
Did another round of updates and it should be up to date with `release/2.7`.

There's a spacing quirk I just noticed I need to fix, then I'd like to add headers to all the template files.. then that should be it!

**Comment by pippinsplugins** [comment]
Looking good! This makes me happy :)

**Comment by nosegraze** [comment]
This should be ready for a final look over.

**Comment by mindctrl** [comment]
Merged! 🎉
