### ISSUE TITLE
Include first/last name and full billing address for PayPal Pro

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#895]
The docs indicate they're required, but we don't include any of them (though the docs also say that _sometimes_ the billing address is not required, though I don't think it says when lol). It works absolutely fine without them in Sandbox but I had a customer getting a bunch of "missing billing address" errors when making live payments.

I basically have this coded up already and the customer verified it works. I just want to look over it again and I need to add some checks in the `validate_fields()` method.

**Comment by nosegraze** [comment]
PR: #896

Need to give it another test first though.

**Comment by pippinsplugins** [comment]
@nosegraze merged in. Could you do a second PR for adding the `validate_fields()` logic?

**Comment by nosegraze** [comment]
Those should all be in there now I think. I snuck them in.

**Comment by pippinsplugins** [comment]
Perfect, closing then.
