### ISSUE TITLE
Update EDD_SL_Plugin_Updater to 1.6.10

### ISSUE THREAD

**Issue by cklosowski** [restrictcontentpro/restrict-content-pro#901]
https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/master/samples/edd-sample-plugin/EDD_SL_Plugin_Updater.php

**Comment by nosegraze** [comment]
@pippinsplugins Can I get access to that repo?

**Comment by cklosowski** [comment]
@nosegraze got you

**Comment by nosegraze** [comment]
Thank you, awesome person. :D

**Comment by nosegraze** [comment]
PR: #903
