### ISSUE TITLE
Incorrect expiration date calculation if payment is late

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#905]
Here's a sample log from someone signing up for a 14 day subscription:

```
January 11, 2017 22:24:00 - Member's status changed from  to pending

January 22, 2017 09:23:29 - Member's expiration changed from  to 2017-01-25 23:59:59

January 22, 2017 09:23:30 - Member's status changed from pending to active

January 28, 2017 05:35:26 - Member's status changed from active to expired
```

The payment is 11 days late somehow (going to ask how this guy paid, maybe it was a super late eCheque or something), but when it finally comes through the expiration date is set based on the original signup date. It should be adjusted to account for the late payment.

**Comment by mindctrl** [comment]
@nosegraze did you hear back from the customer? Which gateway was this?

**Comment by nosegraze** [comment]
Never heard back and haven't gotten any other complaints either.

**Comment by nosegraze** [comment]
Wait. I did hear back. It was PayPal. What I didn't hear back about was whether or not it actually was an eCheque, which would explain the delay.

**Comment by nosegraze** [comment]
I'm inclined to say we postpone this until https://github.com/restrictcontentpro/restrict-content-pro/issues/1000 Presumably when that happens we could ditch pending expiration dates all together and just calculate it when payment is completed? (assuming we store enough data)

**Comment by nosegraze** [comment]
Damnit: https://secure.helpscout.net/conversation/324615299/53878/?folderId=841776

**Comment by pippinsplugins** [comment]
Looks like deleting the pending details right before registration would resolve it.

**Comment by nosegraze** [comment]
PR: #1032

**Comment by pippinsplugins** [comment]
Merged.
