### ISSUE TITLE
Improve detection of levels with free trials

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#907]
In #335 we introduced free trials. Detecting a free trial during registration currently relies on some markup changes made in the `register.php` and `register-single.php` templates (data-has-trial attribute).

To improve the experience and help avoid support requests related to this, I think we should pass an array of trial-enabled levels to `rcp_script_options` that we can use instead of relying on the template having the proper data attribute.

**Comment by pippinsplugins** [comment]
I haven't tested it yet but this looks like it should work fine.

**Comment by nosegraze** [comment]
Works perfectly!

**Comment by mindctrl** [comment]
Thanks! Merged.
