### ISSUE TITLE
Users with 'rcp_manage_discounts' can't add discounts

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#909]
Users with the `rcp_manage_discounts` cap aren't able to add discount codes.

The wrong capability (`rcp_manage_levels`) is being checked before loading the form in `includes/admin/discounts/discount-codes.php`

**Comment by thomasfw** [comment]
@mindctrl is there a time frame on the 2.7.2 release? Any chance of getting it into 2.7 seeing as it's just a one line fix?

**Comment by pippinsplugins** [comment]
Let's go ahead and get this in 2.7. Super minor change.

**Comment by thomasfw** [comment]
@pippinsplugins thanks, much appreciated

**Comment by nosegraze** [comment]
PR: #913

**Comment by mindctrl** [comment]
Merged!
