### ISSUE TITLE
PayPal: Add filter for valid currency check

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#912]
I have someone wanting a filter for this currency check in the PayPal Standard webhook:

`if( strtolower( $currency_code ) != strtolower( rcp_get_currency() ) )`

This person is adding some customizations to allow for multiple currencies and I guess this check is making things difficult for them. They'd like a filter here so they can check the currency against an array rather than the single selected currency.

Maybe we should make an `rcp_is_valid_currency( $currency )` function and have the filter there.

**Comment by pippinsplugins** [comment]
>>>Maybe we should make an rcp_is_valid_currency( $currency ) function and have the filter there.

I like this approach.

**Comment by mindctrl** [comment]
I think we can do this without introducing a new function and filter by changing it to this:

`if ( ! array_key_exists( strtoupper( $currency_code ), rcp_get_currencies() ) ) {`

and he can use the existing filter in `rcp_get_currencies`, if needed, to add/remove currencies.

**Comment by nosegraze** [comment]
Yeah changing it to check against `rcp_get_currencies()` would make the check less 'secure' for people who are just using RCP as-is, I guess.

**Comment by lordspace** [comment]
Thanks for discussing my feature request :)
Just want to add some context. I am launching apps and want to have USD as default currency but for European customers to switch to EUR. There's a filter to change the currency in paypal params, but when the Paypal IPN comes back I'd like to accept both as valid currencies.

**Comment by nosegraze** [comment]
PR: #960
