### ISSUE TITLE
Content with category restrictions always using "premium content message", even if it's free content

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#914]
Regardless of whether the content is free or paid, the "Premium Content Message" is always used.

**Comment by mindctrl** [comment]
@nosegraze on `release/2.7`?

**Comment by nosegraze** [comment]
Yep, `master` and `release/2.7`. In 2.7 it's because of this:

```php
$message = ! empty( $rcp_options['free_message'] ) ? $rcp_options['free_message'] : false; // message shown for free content

if ( rcp_is_paid_content( $post->ID ) || in_array( $post->ID, rcp_get_post_ids_assigned_to_restricted_terms() ) ) {
	$message = ! empty( $rcp_options['paid_message'] ) ? $rcp_options['paid_message'] : false; // message shown for premium content
}
```

Basically, "if it's a paid post or has any term restriction, use the paid message."

The logic is similar in `master`, just in a different function.

**Comment by tnorthcutt** [comment]
Thinking about how to refactor this... possibly by adding a `paid_only` or `free_only` parameter to `rcp_get_post_ids_assigned_to_restricted_terms()`. If we do that, we'll need to keep in mind other places that function is called:
`RCP_Member->can_access()`
`rcp_filter_restricted_content()`
`rcp_is_restricted_content()`
`rcp_hide_premium_posts()`
`RCP_EDD->edd_downloads_query()`

Some of those may not be impacted by the same problem this issue points out, but worth checking on.

**Comment by tnorthcutt** [comment]
Not sure what should happen in the case where a term is restricted, and both a free and paid subscription level are checked for that term. Which message should be shown then?

**Comment by tnorthcutt** [comment]
I started working on this, and allowing e.g. `$paid_only` within the existing function got pretty messy, so I switched to a new, similar function called `rcp_get_post_ids_assigned_to_paid_restricted_terms()` which gets all post IDs that are assigned to terms which are restricted, but ONLY restricted to paid subscription levels. In other words, if a post is assigned to a term which has a free subscription level checked, it won't be included.

However, I now see that this still doesn't solve every problem with this issue: if a post is both assigned to a paid term, AND that same post's restriction settings allow a member with a free subscription access, a non logged in user will still see the premium content message.

One way to solve this would be to introduce a new `rcp_is_free_content()` helper function. This function would return true if a post's restriction settings allow a member with a free subscription access.

That function could then be checked in `rcp_filter_restricted_content()`, and if true, the free message used.

**Comment by mindctrl** [comment]
Everything related to restrictions is already pretty complicated, at every place where we deal with it all. Rather than make it more complicated, I'd prefer to work towards a future where we don't have separate messages for free and paid content. Is that crazy?

**Comment by nosegraze** [comment]
@mindctrl I'm totally on board with that. With the huge number of ways we have to restrict content (and with content possibly being restricted to both a free and paid level, not to mention complicated access levels), differentiating between `free` and `paid` is just a massive PITA. It seems way more complicated than any possible benefit.

**Comment by tnorthcutt** [comment]
I think moving away from free vs. paid messages is a great idea. Site owners can customize the restricted content message to fit their particular situation ("this is restricted content, but you can get a free account, click here!") regardless.

How do we move toward no longer differentiating between free and paid, while preserving backwards compatibility? How has RCP approached other breaking-ish changes in the past?

**Comment by mindctrl** [comment]
Back compat is a good question. Will think about it. Share any ideas you have!

**Comment by tnorthcutt** [comment]
Opened a new issue to discuss the bigger issue of moving away from free vs. paid in https://github.com/restrictcontentpro/restrict-content-pro/issues/1701

**Comment by tnorthcutt** [comment]
Closing this since we're doing #1701. @nosegraze @mindctrl feel free to reopen if you think we should still track this for now.
