### ISSUE TITLE
Invoices: Add hook to allow for customisation after 'Additional Info'

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#917]
It would be really useful if we could have a hook at the bottom of the invoice template to allow us to generate and insert some custom data (e.g that which is required for tax purposes) - 

```php
<?php do_action( 'rcp_after_invoice_additional_info' ); ?>
```

**Comment by nosegraze** [comment]
PR: #936

I added a few others in spots I thought might be useful for inserting tax information, other line items, etc.

**Comment by thomasfw** [comment]
@nosegraze perfect, thanks!

**Comment by pippinsplugins** [comment]
Looks good, merged.
