### ISSUE TITLE
rcp_process_gateway_webooks() runs when not needed

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#918]
`rcp_process_gateway_webooks()` runs on the `init` hook. This results in it running when it shouldn't, like during ajax requests and when the cron runs. It also doesn't need to run when `is_admin()` is true.

To see it in action, you can add `error_log('rcp_process_gateway_webooks() is running');` inside `rcp_process_gateway_webooks()` and just load the WP admin dashboard. It fires for the normal `init`, and again for any ajax requests that run (like the EDD sales dashboard widget).

I think we can check for ajax, cron, and is_admin so that it only runs when needed, with something like this:
```
	if ( ( defined( 'DOING_AJAX' ) && DOING_AJAX ) || ( defined( 'DOING_CRON' ) && DOING_CRON ) || is_admin() ) {
		return;
	}
```

**Comment by pippinsplugins** [comment]
Looks great!
