### ISSUE TITLE
Registration total details table broken on mobile

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#919]
![rcp-responsive-form](https://cloud.githubusercontent.com/assets/6324272/22649760/54cf3094-ec74-11e6-86e6-fdcdfdf45597.png)

Caused by #492

Probably just need to add the `data-th` attributes to the table.

**Comment by nosegraze** [comment]
PR: #920

**Comment by pippinsplugins** [comment]
Merged!
