### ISSUE TITLE
Add report for active counts over time

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#92]
This will allow site admins to see how their active subscribers count is changing over time.

It will require that a new option get stored in the database (not autoloaded) that stores the counts over time. The counts will be populated via a daily cron job that runs and records the number of active subscribers for each subscription level.

**Comment by nosegraze** [comment]
Closing this in favour of https://github.com/restrictcontentpro/restrict-content-pro/issues/289
