### ISSUE TITLE
Add "Payment Status" column to [subscription_details] shortcode

### ISSUE THREAD

**Issue by ramiy** [restrictcontentpro/restrict-content-pro#923]
Ok, so I have a client that payed twice accidentally. I've refunded his account. But he doesn't see the refund in his account details page which uses the `[subscription_details]` shortcode.

Screenshot:

![screenshot 2017-02-07 02 04 25](https://cloud.githubusercontent.com/assets/576623/22672129/a9872f54-ecda-11e6-89c6-47df1416dfbc.png)

First I was thinking to create an addon to add a new "**Payment Status**" column, but the [subscription template](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/templates/subscription.php) is not very friendly for developer.

I think that it would be easier to add this column to plugin core.

**Comment by pippinsplugins** [comment]
I agree, we should show the status.

**Comment by pippinsplugins** [comment]
PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/924#issuecomment-277980383
