### ISSUE TITLE
"Total today" and "total recurring" rows not visible on mobile

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#930]
Due to #492

This is because they are in `th` tags and we're hiding those on mobile.

These not being visible can be confusing particularly when discounts and fees come into play.

**Comment by nosegraze** [comment]
Is there a better way to do this than just `display: block;` on the headings? Which would result in them being kind of awkwardly stacked like this:

![rcp-table](https://cloud.githubusercontent.com/assets/6324272/22789481/f6a0e698-eeda-11e6-87ad-89af85e1cce3.png)

**Comment by mindctrl** [comment]
These are being shown in `<th>` elements instead of `<td>` elements like the others. I think we need some consistency with the markup in this whole table.

**Comment by mindctrl** [comment]
### Twenty Fifteen mobile:
![image](https://cloud.githubusercontent.com/assets/1254870/22905928/37c48f0c-f210-11e6-8796-4abc3f10af3a.png)

---

### Twenty Fifteen desktop:
![image](https://cloud.githubusercontent.com/assets/1254870/22905940/43bd4114-f210-11e6-8c54-a35bc1dbb971.png)

**Comment by pippinsplugins** [comment]
Looks great!
