### ISSUE TITLE
New free trial members aren't getting an activation email

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#935]
Neither the 'active' or 'trial' emails are being sent to members who sign up for a paid level with a free trial. (This refers to the new integrated free trials introduced in 2.7.)

**Comment by nosegraze** [comment]
Thoughts on which email we should send here?

**Comment by mindctrl** [comment]
Yep, that's a bit confusing. It's paid and it's a trial. I think we send the trial one. Gives people more control over the messaging.

**Comment by pippinsplugins** [comment]
>>>It's paid and it's a trial. I think we send the trial one.

I agree.

**Comment by nosegraze** [comment]
PR: #956
