### ISSUE TITLE
HTML emails sent through Mandrill have extra spacing

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#943]
![image](https://cloud.githubusercontent.com/assets/1254870/22795965/9eae6e10-eec6-11e6-8fef-c19c111c7467.png)

The WP Mandrill plugin has a filter we can use to fix this up.

See: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/1810#issuecomment-54078817

We need `add_filter( 'mandrill_nl2br', '__return_false' );`

**Comment by nosegraze** [comment]
PR: #946
