### ISSUE TITLE
Quick editing WooCommerce product wipes restriction settings

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#944]
- Fully edit product.
- Add restriction settings of some kind.
- Return to product list.
- "Quick edit" that same product and save.
- Restriction settings are wiped.

**Comment by nosegraze** [comment]
Related, as adding this would probably fix the problem: #826

**Comment by pippinsplugins** [comment]
I'm bumping the priority on this.

We can fix it by detecting if a quick edit action is being performed and then bailing on our update method.

**Comment by mindctrl** [comment]
Went ahead and pushed a PR for this. Initially went with this to detect:
```
if ( ! empty( $_GET['bulk_edit'] ) || ( ! empty( $_POST['action'] ) && 'inline-save' === $_POST['action'] ) ) {
	return $post_id;
}
```
But decided to just use a nonce like we do with other posts, and that will work if/when we add bulk/quick edit support.

**Comment by pippinsplugins** [comment]
PR looks good to me, though I haven't tested it yet.

**Comment by nosegraze** [comment]
Works great for me!
