### ISSUE TITLE
Incomplete subject for admin notification on free trials

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#948]
When an admin is notified of a new free trial, the subject is missing the site name.

Reference: https://github.com/restrictcontentpro/restrict-content-pro/blob/2.7.1/includes/email-functions.php#L146

**Comment by nosegraze** [comment]
Lol I think I noticed this when I was testing earlier and I was trying to figure out why the email didn't look right... :D
