### ISSUE TITLE
Allow discount code to be pre-filled by a query arg

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#95]
An option to prefill a discount code via a URL should be added. If a code is present, the field will be prefilled and the code will be validated.

Perhaps a URL should be displayed in the admin to make it easy for site admins to copy and paste a URL for specific codes.

**Comment by derickbailey** [comment]
any chance this will get bumped down into the 2.x series? 2+ years seems a long time to wait for a feature of this much benefit. 

and i really need this in combination with the one time discounts in #483

**Comment by mindctrl** [comment]
@derickbailey I'll move this to 2.7 and we'll see if it's something that can make the cut.

**Comment by pippinsplugins** [comment]
Ready for testing!

**Comment by mindctrl** [comment]
Works great. Merged.
