### ISSUE TITLE
Join form 'Register' button reverts to unfiltered default text after loading state

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#954]
A minor one - I've changed the default text for the 'Register' button using the `rcp_registration_register_button` filter. It works fine initially, but when the form validation fails the text reverts back to 'Register' after the button's 'Loading...' state.

```php
// Works, but reverts to original text after button load state..
add_filter( 'rcp_registration_register_button', 'my_rcp_register_button', 10 );
function my_rcp_register_button()
{
    return 'Continue';
}
```

**Comment by pippinsplugins** [comment]
We'll need to pass the text to the localized script variables in order for it to retain the custom text.

**Comment by nosegraze** [comment]
PR: #982

**Comment by meadows19** [comment]
I've changed the text of the Register button on register-single by modifying the template file, and not using any filters.

When there is an error during payment (for example, select a card expiry date in the past for Stripe checkout), the error message shows (in this case "`Your card's expiration month is invalid.`") and **the button changes back to the default text**.

This is using RCP 2.8.2

**Comment by pippinsplugins** [comment]
@meadows19 You will need to use the `rcp_registration_register_button` filter in order to prevent that.

**Comment by meadows19** [comment]
@pippinsplugins Thank you. I couldn't find any mention of this filter on the Docs site [http://docs.restrictcontentpro.com/category/1513-filters](url) but the code above by @thomasfw works fine.

**Comment by nosegraze** [comment]
I'll add an article for it, thanks @meadows19  :)
