### ISSUE TITLE
Email tags are NOT being parsed for "plain text only" template

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#955]
Here is an example of a member email sent out after updating to the latest version.. luckily picked up on this just before pushing the update out to live. I'm on 2.7.1.

```
Dear %displayname%,

Welcome to ..... Your %subscription_name% is now active.

Regards,
...
```

I'm using [WP HTML Mail](https://wordpress.org/plugins/wp-html-mail/) to handle mail templating rather than the now built-in option which might be related, but this needs to be investigated as i'm sure many users were/are already using a separate plugin to handle HTML emails/templates prior to 2.7.

Could be an issue with a hook priority somewhere (e.g. one of the email plugins hooking into `wp_mail()` before rcp does it's stuff)? Although as I said, no issues prior to the update.

**Comment by thomasfw** [comment]
(we're also using [WP Mail SMTP](https://wordpress.org/plugins/wp-mail-smtp/))

**Comment by nosegraze** [comment]
Do you have your template set to "plain text only" ?

**Comment by thomasfw** [comment]
Yep I forgot to mention we have the "plain text only" setting enabled, we're still using the other plugin for the HTML templates

**Comment by nosegraze** [comment]
I believe that's the problem. Email tags aren't being parsed just for that specific template and we need to work on a fix there. I'm going to tweak your issue title slightly to reflect that.

**Comment by thomasfw** [comment]
No problem, thanks

**Comment by nosegraze** [comment]
PR: #957
