### ISSUE TITLE
Add dynamic rcp_set_status_{$status} hook

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#958]
In `RCP_Member::set_status()` we fire this:
`do_action( 'rcp_set_status', $new_status, $this->ID, $old_status, $this );`

It would be great to fire one with the status attached, so we can avoid having to check the status every time we use it and keep some functions from running unnecessarily. Something like this:

`do_action( "rcp_set_status_{$new_status}", $this->ID, $old_status, $this );`

**Comment by nosegraze** [comment]
PR: #998

**Comment by mindctrl** [comment]
Love this. Merged and changed milestone to 2.7.3.

**Comment by pippinsplugins** [comment]
🎉
