### ISSUE TITLE
Stop using our own deprecated functions

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#959]
Every time I'm working on another issue I come across a case where we're using our own deprecated function and I keep forgetting to make an issue to fix it. So here we are!

I know there are at least a few instances so I'd like to go through and update them all.

Deprecated functions currently in use:

- [x] `rcp_check_for_existing_payment()`
- [x] `rcp_get_pdf_download_url()`
- [x] `rcp_calc_member_expiration()`

**Comment by nosegraze** [comment]
Is there actually an alternative to `rcp_calc_member_expiration()` ? I mean, I know we have `$member->calculate_expiration()` but the place this function is being used is in `rcp_calculate_subscription_expiration()`, which is then being used in an ajax callback. It calculates the expiration date based on a subscription level rather than a member. This is being used when adding a new subscription for an existing user. When you select the subscription level from the dropdown, it auto populates the expiration date based on that selection. So we can't really use `$member->calculate_expiration()` here since the user doesn't yet have a subscription level.

**Comment by pippinsplugins** [comment]
I don't think we need to stop using that one.

**Comment by nosegraze** [comment]
Maybe we should un-deprecate it then but we can add a comment to direct people to `$member->calculate_expiration()` if they're wanting to do it for a member.

**Comment by pippinsplugins** [comment]
I agree with that.

**Comment by nosegraze** [comment]
PR: #967

`rcp_calc_member_expiration()` used to be in `member-functions.php` but I put it in `subscription-functions.php` since it really doesn't deal with members at all and maybe that will discourage people from using it. :P 

I also updated some of the variable names in the function for clarity.

**Comment by nosegraze** [comment]
Now that I'm thinking about it, we could also just leave `rcp_calc_member_expiration()` deprecated and copy the code over into `rcp_calculate_subscription_expiration()` and have that stand on its own.

**Comment by mindctrl** [comment]
@nosegraze I like that idea. `rcp_calculate_subscription_expiration()` is a more accurate name.

Just had a thought after typing that sentence.

In a few places, we're on the edge of confusing a subscription with a level... by that I mean a subscription could be confused for a payment processor subscription and not a subscription level. We're consistent in that regard. With that in mind, I like `rcp_calculate_subscription_level_expiration()` or `rcp_calculate_level_expiration()`.

**Comment by nosegraze** [comment]
Well `rcp_calculate_subscription_expiration()` already exists, it's just very very small:

```php
function rcp_calculate_subscription_expiration( $id ) {
	$length = rcp_get_subscription_length( $id );
	return rcp_calc_member_expiration( $length );
}
```

So I was thinking that we ditch this line:

```php
return rcp_calc_member_expiration( $length );
```

And basically insert the contents of `rcp_calc_member_expiration()` in there instead.

I do definitely see what you mean about subscription/subscription level, though I just want to point out the `rcp_calculate_subscription_expiration()` function already exists in case that wasn't clear.

**Comment by pippinsplugins** [comment]
>>>And basically insert the contents of rcp_calc_member_expiration() in there instead.

I like this approach.

**Comment by mindctrl** [comment]
This seems to be working well. Confirmed PayPal purchase worked as expected. Left a note on the PR about a small alignment issues left over from the past, otherwise ready to merge I think.

**Comment by nosegraze** [comment]
Merged.
