### ISSUE TITLE
Upgrading from a unlimited duration plan to one with a duration does not disable Never Expires?

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#961]
When a user upgrades from a free plan with, unlimited duration, to a plan with a duration, the `Never Expires?` flag is not being disabled. 

This results in an active member with an expiration, yet who's `$expiration` is always returned as `none` when using `rcp_get_expiration_date`.

**Comment by nosegraze** [comment]
Not sure I'm able to reproduce this. Steps I took:

- Registered for an unlimited free plan. Verified that "never expires" was checked on.
- Upgraded to paid plan with 1 month duration.
- Verified that "never expires" was unchecked.

**Comment by pippinsplugins** [comment]
@carter2422 Did the customer go through Stripe Checkout? If so, was it the standard registration form or the `[register_form_stripe]` one?

**Comment by carter2422** [comment]
@pippinsplugins yep, Stripe Checkout through the standard registration form. I'll test again and get better steps to replicate.

**Comment by mindctrl** [comment]
That would happen if the webhook didn't get delivered.

**Comment by mindctrl** [comment]
@carter2422 you have a chance to reproduce this? If not we can punt. Also, do you know if the webhook was delivered during your test?

**Comment by mindctrl** [comment]
I think this was fixed in https://github.com/restrictcontentpro/restrict-content-pro/pull/1079/files. If not, we can open this again.
