### ISSUE TITLE
Authorize.net: Payment records inserted without a valid date

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#968]
A customer reported that all the payment records (from silent post) had the date `1970-01-01 00:00:00`. I don't think `$_POST['timestamp']` actually exists [here](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/gateways/class-rcp-payment-gateway-authorizenet.php#L217) which would cause the problem. I assume we can just set that to the current time.

**Comment by mindctrl** [comment]
Hmm, would be best to get it from the webhook data instead of current time, in case of a delayed webhook delivery.

**Comment by nosegraze** [comment]
That would definitely be ideal, but based on the examples I'm looking at I don't think they actually send a date at all.

**Comment by pippinsplugins** [comment]
I've just looked at a couple of other plugins that integrate with Authorize.net and they do not grab a date from Authorize.net either.

**Comment by nosegraze** [comment]
I found this to be very useful if anyone else wants to bookmark it. :D http://www.johnconde.net/blog/all-about-authorize-nets-silent-post/

**Comment by mindctrl** [comment]
Wow, that's amazing. :1st_place_medal: 

I bet we could fetch the date from the API when the webhook comes in, but that feels crazy.

Given that, I think I'm ok with current time unless someone has another idea, or someone complains loud enough. :p

**Comment by pippinsplugins** [comment]
Super handy!

**Comment by pippinsplugins** [comment]
I vote for current time.

**Comment by nosegraze** [comment]
PR: #972
