### ISSUE TITLE
Stripe Checkout spinner icon shows if modal closed

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/restrict-content-pro#969]
If the Stripe Checkout modal is closed without making a payment, the spinner icon still shows. This seems to be new behavior in the modal - perhaps a change in their API, not sure - since this never came up during development and testing of the changes in 2.7.

As a quick test I tried running `rcpStripeCheckout.close()` in the `checkoutArgs.closed` function, but that didn't tear down the iframe and remove the spinner. However a quick test using `$('.stripe_checkout_app').hide();` seemed to fix it.

Need to do some further investigation before submitting a fix.

**Comment by nosegraze** [comment]
Works well!
