### ISSUE TITLE
Unrestricted posts incorrectly being removed from queries when using "hide restricted posts"

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#971]
If "Hide Restricted Posts" is turned on, it removes restricted posts from the main query. But entire categories are being hidden even if they don't have any restrictions. This is because of this query in `rcp_get_post_ids_assigned_to_restricted_terms()` : 

```php
$terms = get_terms(
	array_values( get_taxonomies( array( 'public' => true ) ) ),
	array(
		'hide_empty' => false,
		'meta_query' => array(
			array(
				'key' => 'rcp_restricted_meta'
			)
		)
	)
);
```

It's looking for terms that have the key `rcp_restricted_meta`, but even completely unrestricted categories would have that key - it would just be saved as an empty array.

We can solve this by actually fully deleting that meta key in `rcp_save_term_meta()` if there are no restriction settings.

Note: The actual posts can be viewed just fine if people have the full URL. The problem is only with them being removed from queries.

**Comment by nosegraze** [comment]
PR: #973

**Comment by pippinsplugins** [comment]
Good catch! I saw a customer run into this last week.
