### ISSUE TITLE
rcp_check_for_expired_users cron should also expire cancelled users?

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#974]
Seem to me like the `rcp_check_for_expired_users` cron should also expire 'cancelled' users.

```php
67. AND  (mt2.meta_key = 'rcp_status'
68. 	AND CAST(mt2.meta_value AS CHAR) = 'active') ) // OR 'cancelled' ???
69. ORDER BY user_login ASC LIMIT 9999";
```

**Comment by pippinsplugins** [comment]
Cancelled users are designed to not be marked as expired. An expired user is one who paid one-time or whose payment failed, resulting in them being marked as expired.

**Comment by thomasfw** [comment]
I see from #1013, #1041 that there's no clear reason not to expire cancelled members. Just in case you're still pondering over it here are some related issues we've picked up on. 

Expiring cancelled users who've met their expiry date should fix points **1** and **2** below. Point **3** concerns a larger issue regarding the confusion between cancelation of membership and cancelation of auto-renewing payments.

---

### 1. How do we know which of the cancelled members still have access?
`cancelled` **non-expired** members are currently indistinguishable from `cancelled` **expired** members, meaning keeping tabs on actual member counts involves counting 'active' members and also manually counting 'cancelled' members who've not yet reached their expiry.

Even more confusion ensues when we are carrying out member correspondence outside of RCP. We have to have a sql query to pull out all `active` members, and all `cancelled` members who's expiry date < NOW.

---

### 2. No expiry emails for cancelled members
This would be the expected behaviour for a member who'd cancelled indefinitely or had their access revoked, but those users who just wished to cancel their auto renewal will not receive an expiry notification email when the time comes, which most likely equals another member lost. 

---

**Both of these points lead onto a bigger issue...**

### 3. The 'Cancelled' status has multiple meanings
Are we cancelling a membership, or cancelling an auto-renewal? It seems like the concepts of cancelling an auto-renewal and cancelling a membership have been merged into one. And the result is actually really quite confusing for both members and administrators (based on the feedback we've had). 

On the `Subscription Details` page we tell members to that they can 'cancel' their membership when in reality they're cancelling their auto-renewal. When a member cancels their auto-renewal with 6 months left of their membership, they wouldn't expect to not be classed as a current member (which is currently the case, users see their membership labeled as 'cancelled'). To get around member confusion for now, we've updated the member details template to never show the cancelled status, and changed the 'cancel' button to 'cancel your auto-renewal'.

<img width="849" alt="screen shot 2017-03-01 at 20 05 05" src="https://cloud.githubusercontent.com/assets/7723105/23478854/891dddb6-feba-11e6-867f-84434862a01b.png">

Related to #1043 - to revoke a membership the suggestion is to set a member's status to 'cancelled' and change then change expiry date to a past date. Again, it's impossible to distinguish between 'cancelled' members as those who should NOT be considered a member, and those members who have just cancelled their auto renewal but technically remain a member until their expiry.


### Solution?

When a user cancels from their profile, they should remain `active`, their `auto-renewal` flag set to `0`, and their subscription disabled in the payment gateway. I'd have thought this would be the logical process as it would put them in the same category as a member who'd signed up without the auto-renewal.

The `cancelled` status should be reserved for members who have actually cancelled their memberships or had access revoked. Cancelled members should not have access to content?

---

Apologies that this is so long. We are heavily invested in the RCP member infrastructure and the issues surrounding the ambiguity of cancelled members is causing issues for both staff and members.

Thanks

**Comment by nosegraze** [comment]
Thanks so much for posting that @thomasfw. Those are all excellent points!

**Comment by mindctrl** [comment]
Thanks for the feedback @thomasfw.

I'm not sure I agree that `cancelled` status should mean "no access to content". Cancelled should mean the member or the admin cancelled the subscription, but the person still has time left that they've paid for already. Revoking access because someone cancels is wrong unless you refund them the money for the time left.

To give an example of that, if your Spotify membership is paid through the end of March and you cancel today, you retain access until the end of the March because you already paid for it. You wouldn't expect them to revoke access before your paid term is up, and I don't think members would expect that with their memberships on a site powered by RCP.

Revoked and cancelled are two very different things in my mind, and we should not mix them up.

**Comment by pippinsplugins** [comment]
>>>Revoked and cancelled are two very different things in my mind, and we should not mix them up.

Agreed. That's why we used to have a `Revoke` option on members. The feature was correct in theory, just wrong in how we implemented it, which led us to remove it.

**Comment by thomasfw** [comment]
@mindctrl completely agree, and that is actually my point.

There is confusion over whether members are cancelling their memberships full stop, or just cancelling their auto-renewing payments.

We've had exasperated emails from members asking us why their membership has been cancelled when all they wanted to do is cancel their auto-renewing payments. That is default RCP behaviour, the membership is marked as cancelled, and the member receives an email telling them so.

In my opinion, the emphasis should be on the cancellation of the auto-renewing payments, and the member's status should remain `active`. Actually, as far as I can tell the 'cancelled' status is not entirely necessary and only leads to confusion. When a user cancels their auto-renewal why not just do the following...

> "When a user cancels from their profile, they should remain active, their auto-renewal flag set to 0, and their subscription disabled in the payment gateway. I'd have thought this would be the logical process as it would put them in the same category as a member who'd signed up without the auto-renewal."

Along with removing any ambiguity, this also means that we wouldn't have to combine 'cancelled' and 'active' membership numbers in order to  get our actual member count!

**Comment by thomasfw** [comment]
No other thoughts?

**Comment by pippinsplugins** [comment]
Re-opening for further consideration.

>>>The cancelled status should be reserved for members who have actually cancelled their memberships or had access revoked. Cancelled members should not have access to content?

I don't agree with this.

As a customer, if I have a subscription on a site, I want it to show `active`. If I then cancel my subscription, I would expect my account to properly reflect that with a `cancelled` or `stopped` status.

We could perhaps consider changing the exact message displayed to customers, but changing the access level that customers have when their account status is `cancelled` is not something we can do. With over 5 years of `cancelled` being treated the way it is, changing it could have severely drastic consequences on existing sites.

If we make a change here, I vote only for changing the message shown to customers, perhaps something like `Cancelled` with a tooltip (or similar) for `You will retain access until YYY-NN-DD`.

**Comment by thomasfw** [comment]
I can see why changing the `cancelled` status is not an option. I think the main issue here is the wording - if it was immediately obvious that membership is retained after cancellation until the expiry date then that would prevent a lot of member confusion.

I also think that `expiring` cancelled members when their expiry is met is pretty important (unless there are reasons why this can't be done). This way we know that everyone listed under 'cancelled' is technically still a member, which is really useful for tracking member numbers. And it would prevent the need to keep manually checking the expiry dates of cancelled members to see if they still have access.

**Comment by mindctrl** [comment]
> if it was immediately obvious that membership is retained after cancellation until the expiry date then that would prevent a lot of member confusion.

Currently the `[subscription_details]` shortcode shows the status and expiration date. If a membership is cancelled, the expiration date will still show the correct future expiration date. This communicates the state of the membership. Do you have a suggestion for making it clearer?

**Comment by thomasfw** [comment]
@mindctrl the user is given the option to `Cancel your subscription`, and nowhere does it state that their membership/access will be retained until it's expiry date if they do so. So maybe a tooltip next to the cancel button to clear this up?

Changing the text to something like `Cancel your membership renewal` would better describe it in my opinion. The cancel button (regardless of the actual text) would also really benefit from a confirmation dialog to prevent any accidental cancellations. And there's another opportunity to make things clearer for the user...

<img width="532" alt="screen shot 2017-03-12 at 21 46 49" src="https://cloud.githubusercontent.com/assets/7723105/23836261/784780c6-076d-11e7-9626-fa1129bb8041.png">

The cancellation success message could also be improved. e.g..
 
```
"Your profile has been successfully cancelled."
```
```
"Your auto renewal has been cancelled. Your membership will expire on March 12, 2017."
```

**Comment by pippinsplugins** [comment]
I like the idea of a message showing when access will be disabled.

**Comment by nosegraze** [comment]
Related: #654

**Comment by mindctrl** [comment]
See https://github.com/restrictcontentpro/restrict-content-pro/issues/654 for PR related to cancellation confirmation.

**Comment by pippinsplugins** [comment]
Looks good to me!

**Comment by mindctrl** [comment]
I think we've agreed to mark `cancelled` members as `expired` in the cron job. We'll also need to adjust the logic in `RCP_Member::get_status()` that sets a member to expired if they haven't yet been set that way with the cron job.

Before we do it, can anyone think of anything else this could affect?

**Comment by nosegraze** [comment]
The only thing I can think of is that the `Revoke Access Now` option may not really be necessary anymore, since that could just be done by marking them as expired. Or maybe we could just change the way it works slightly to make more sense and have it just be a convenient way to have RCP back-date the expiration date for you.

**Comment by thomasfw** [comment]
Any idea when this might make it into a release? As our list of cancelled members grows larger, it's increasingly difficult to see how many of those users are still technically active members, and how many have expired since cancelling. It makes it difficult for us to track specific membership numbers, as we just have to ignore the whole 'cancelled' list.

**Comment by mindctrl** [comment]
This is currently slated for 3.0, which probably won't be ready until January. I'm fine with us bumping this up into a 2.9.x point release if we have a PR for it before then.

**Comment by nosegraze** [comment]
PR: #1602

- Updated cron job to check `active` and `cancelled` users.
- Updated `RCP_Member::get_status()` to also check for `cancelled` users.
- Updated `Revoke Access` description, and it now changes the user's status to `expired` when revoking.
