### ISSUE TITLE
Unrestricted posts incorrectly in rcp_get_restricted_post_ids()

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#978]
Related-ish to this issue: #971

Some unrestricted posts are incorrectly being caught up in this meta query in `rcp_get_restricted_post_ids()`:

```
array(
	'key' => 'rcp_access_level'
)
```

The customer I spoke to had a bunch of old posts that had `rcp_access_level` set to an empty string, but because the key existed at all, the posts were caught up in this query incorrectly. I suspect this is from a while ago when the key wasn't being deleted, as re-saving the posts fixed the problem by deleting the keys.

Still might be worth fixing in case other people have the same problem. We could amend it like this:

```
array(
	'key'     => 'rcp_access_level',
	'value'   => 0,
	'compare' => '>='
)
```

That fixed the problem for me in my quick test.

**Comment by nosegraze** [comment]
PR: #980

**Comment by pippinsplugins** [comment]
We should probably add `'type' => 'NUMERIC'` there as well.

**Comment by nosegraze** [comment]
I actually had that in at first and it broke it. Maybe because that was converting an empty string into `0`.

**Comment by nosegraze** [comment]
I actually think I got my wires crossed here with another piece of meta and it was actually being saved as `None` rather than an empty string. So I might have to rethink this PR.

**Comment by nosegraze** [comment]
If `0` access level (which is in the dropdown) means no restriction then this would work:

```
array(
	'key'     => 'rcp_access_level',
	'value'   => 1,
	'compare' => '>=',
	'type'    => 'numeric'
)
```

or:

```
array(
	'key'     => 'rcp_access_level',
	'value'   => 'None',
	'compare' => '!='
)
```

**Comment by pippinsplugins** [comment]
That looks good.

**Comment by nosegraze** [comment]
Updated PR.

**Comment by pippinsplugins** [comment]
@mindctrl could you please test this?

**Comment by mindctrl** [comment]
Works great. Merged.
