### ISSUE TITLE
Feature Request: Multiple Reminder Emails

### ISSUE THREAD

**Issue by psorensen** [restrictcontentpro/restrict-content-pro#984]
Getting requests from clients to include multiple expiration reminder emails. e.g send expiration warning at 1 week, 3 days,  and 1 day before expiration.

**Comment by mindctrl** [comment]
Related: https://github.com/restrictcontentpro/restrict-content-pro/issues/558

**Comment by mindctrl** [comment]
Got another request for this.

**Comment by pippinsplugins** [comment]
Closing this as a duplicate of https://github.com/restrictcontentpro/restrict-content-pro/issues/558
