### ISSUE TITLE
Free trials not working in PayPal Express

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#987]
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/gateways/class-rcp-payment-gateway-paypal-express.php#L209

It's using `$this->is_trial()`, which uses `$this->subscription_data`. That would be totally fine in the `process_signup()` method, but in `process_confirmation()` that's a totally different page where `$this->subscription_date` is just `null`.

The subscription data should be accessible from the `$details` variable a bit further up:

```
$details = $this->get_checkout_details( $_POST['token'] );
```

**Comment by nosegraze** [comment]
Annoyingly we can't check this during `process_confirmation()` : 

```
$this->subscription_data['trial_eligible']
```

The trialling meta data flags get set before being passed to the gateway, so we can't just look up the member again and check for `has_trialed()`.

Is there a safe way to pass information from `process_signup()` to `process_confirmation()` other than like.. in the URL?

**Comment by pippinsplugins** [comment]
Subscription details supplied to the confirmation screen like this:
```php
$body['subscription'] = (array) rcp_get_subscription_details( $subscription_id );
```

So you can set any additional parameters needed inside of `get_checkout_details()` and then reference them via `$details = $this->get_checkout_details( $_POST['token'] );` in `process_confirmation()`.

**Comment by nosegraze** [comment]
Yeah that works for duration and unit, but not for whether the member is
eligible for a trial to begin with. Those meta keys are set before going to
the gateway at all, so the records will be outdated anyway by the time we
re-check in the gateway. ( has_trialed would be true at this point, making
it look like they're ineligible)

**Comment by pippinsplugins** [comment]
How about adding `trial_eligible` to the `subscription` array?

**Comment by nosegraze** [comment]
We flag them as starting a trial before we get to that point. See
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/registration-functions.php#L298

So it would go like this:

1. Customer is eligible for trial, and that's reflected on register form
and passed to gateway class.
2. We update the meta to make them ineligible for trial.
3. Customer goes to gateway to make payment.
4. Page refreshes to do PayPal confirmation thing and we lose all our
variables (including the one that says they're eligible).
5. Getting their trial eligibility again at this point would incorrectly
come back ineligible since we already set their meta in step 2 before
processing payment.

I actually did exactly what you suggested at first and it didn't work
because of the above. I got it working by passing the trial eligibility in
the return URL like we do with whether or not it's recurring but that's not
ideal.

**Comment by mindctrl** [comment]
Processing the new style free trials goes through the block above that: https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/registration-functions.php#L219

**Comment by nosegraze** [comment]
Just linked to the wrong line.
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/registration-functions.php#L246

**Comment by nosegraze** [comment]
For example, this is the code I was working on: #991

It would work, except `$member->has_trialed()`  returns `true` here due to when we set it before going to the gateway: https://github.com/restrictcontentpro/restrict-content-pro/blob/97ba75d46a824e4f9c5215ce2920e8cfab29477b/includes/gateways/class-rcp-payment-gateway-paypal-express.php#L641

**Comment by pippinsplugins** [comment]
@nosegraze is this ready to test then?

**Comment by nosegraze** [comment]
Not yet. The trial eligibility check doesn't work since we set those flags before going to the gateway. We might need to rethink that process in general because I think it'll also cause issues if payment fails and the user goes back to try again (they'd be ineligible for a trial).

Will do some more testing on Monday.
