### ISSUE TITLE
Developer request: .editorconfig file

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#988]
An [`.editorconfig`](editorconfig.org) file would be nice to have, and would reduce instances of asking outside developers to modify their pull requests to fit (undocumented) coding standards for RCP.

I'm assuming this should be similar to or the same as WordPress core; I'll open a PR with that in case that's an accurate assumption.

**Comment by pippinsplugins** [comment]
:+1:
