### ISSUE TITLE
No information added to user when stripe charge fails

### ISSUE THREAD

**Issue by tnorthcutt** [restrictcontentpro/restrict-content-pro#990]
Currently, if a charge in Stripe fails, the `rcp_stripe_charge_failed` action fires, but nothing is hooked to it, and no record is made of the failed charge in RCP.
```php
// failed payment
if ( $event->type == 'charge.failed' ) {
	do_action( 'rcp_stripe_charge_failed', $invoice );
	die( 'rcp_stripe_charge_failed action fired successfully' );
}
```

I propose that a note should be added that a charge failed. Here's a rough implementation:
```php
// failed payment
if ( $event->type == 'charge.failed' ) {
	do_action( 'rcp_stripe_charge_failed', $invoice );
        rcp_add_member_note( $member->ID, sprintf( __( 'Charge failed in Stripe. Event ID: %s', 'rcp' ), $event->id ) );
	die( 'rcp_stripe_charge_failed action fired successfully' );
}
```

**Comment by mindctrl** [comment]
Good idea

**Comment by nosegraze** [comment]
Maybe we should add them to all gateways via `rcp_recurring_payment_failed`.

Though then we wouldn't be able to include the `$event->id`

**Comment by tnorthcutt** [comment]
@nosegraze yeah, would be really nice to have that event ID to make it easy to find the corresponding event in the Stripe admin interface.

**Comment by nosegraze** [comment]
PR: #1022

I tried to do both. :P

**Comment by tnorthcutt** [comment]
@nosegraze very nice! Leaves the option to add custom notes for other gateways in the future as well.
