### ISSUE TITLE
If payment fails during free trial signup, user becomes ineligible to try again

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/restrict-content-pro#999]
- User is eligible for trial and let's say they register via Stripe.
- Submit registration form.
- Their account is updated like so: `update_user_meta( $user_data['id'], 'rcp_has_trialed', 'yes' );`
- *Then* they're sent to the gateway class via `rcp_send_to_gateway()`
- Let's say the card is declined so they get an error screen.
- Go back to registration form to try again... but they can no longer sign up for a free trial since their account has already been flagged. So instead they're prompted to pay immediately.

The same would happen with PayPal if they get taken to PayPal but don't complete payment for whatever reason, then try again later.

Perhaps we should set some kind of `rcp_pending_trial_activation` meta instead, and only update to `rcp_has_trialed` and `rcp_is_trialing` after the account is activated? This would also fix a problem I'm having in #987

**Comment by mindctrl** [comment]
A new pending meta key would work, but it highlights an issue with our payment flow. We really should not set the rcp_has_trialed flag until the member has truly initiated the trial with a successful payment.

**Comment by nosegraze** [comment]
I feel like a lot of things would feel a bit cleaner if we perhaps created "pending" payment records immediately and then marked them as completed after payment is received, and with a bit more data in them (discount code used, etc.).

**Comment by mindctrl** [comment]
That's definitely the direction we need to be moving. We have a need for pending payments in https://github.com/restrictcontentpro/restrict-content-pro/issues/798 and maybe https://github.com/restrictcontentpro/restrict-content-pro/issues/560.

**Comment by pippinsplugins** [comment]
Pending payments would definitely help solve a _lot_ of issues with the registration flow.

**Comment by pippinsplugins** [comment]
For now, how about just clearing out the meta on failure. Perhaps we could introduce a standard `rcp_registration_failed` hook that can be used to reset data?

**Comment by nosegraze** [comment]
Is a failed registration something we can reliably check for in PayPal? If they're taken to the PayPal screen and then just close the window or something.

**Comment by pippinsplugins** [comment]
If they click `Cancel and return to X`, we can control that URL.

**Comment by nosegraze** [comment]
PR: #1016

Haven't done PayPal Standard yet.

We only want to delete the meta if the current signup was for a trial (to avoid deleting a flag that was possibly set like 2 signups ago or something). We could a query arg for the trial status in the `cancel_return` URL I guess, and delete the meta if that is present.

**Comment by pippinsplugins** [comment]
This is looking good to me.

**Comment by mindctrl** [comment]
This works great with Stripe. Should work with Braintree once that gets merged.

PayPal is tricky because the `cancel_return` param could be faked to allow anyone to get a new trial period if all we do is check that it's set. I don't think they fire a webhook when someone cancels and returns. We need another way to validate it.

**Comment by nosegraze** [comment]
Our options are probably to set some kind of meta flag or just leave PayPal as-is for now and fix it when we add pending payments.

**Comment by nosegraze** [comment]
You guys happy to merge without PayPal for now?

**Comment by pippinsplugins** [comment]
Yes, I'm fine with that.
